govuk-one-login/authentication-frontend

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/further-information/_account-creation-further-information.njk
src/components/contact-us/questions/_sign_in_phone_number_issue.njk
src/components/contact-us/questions/index.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

For reviewer - wanted to check whether updating the form value field had any implications.
* Updates the text on the radio button on the "A problem creating a GOV.UK One Login" page from ‘You do not have a UK mobile number’ radio button to ‘You had another problem with a phone number’
* Reorders these radio buttons so that this makes sense in the context
* Updates the title of the subsequent page when a user selects this radio button so that this page makes sense
* Updates the tag assigned to this when sent through to zendesk
Users can now create a GOV.UK One Login with a non-UK mobile number, so the lack of a UK number should not, in itself, be a problem. However, users are still selecting this option, so users could still be experiencing problems that are not covered by the other radio …

AUT-1338: update phone number issue contact form pages

---

.github/CODEOWNERS
CODEOWNERS

Update CODEOWNERS for new org.
Team names are different in the govuk-one-login org.

BAU: Update CODEOWNERS for new org

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Updates the privacy notice.
Reflects launch of the contact centre
[Bump to T&Cs version](https://github.com/govuk-one-login/authentication-api/pull/3470)

AUT-1721: Update privacy notice for 1.10

---

ci/terraform/production.tfvars

Sets the URL for support links to go to the triage page.
We have been given the go-ahead from the Contact Centre team to set support links to go to the new triage page.

AUT-1907: Enable triage page in production

---

package.json
yarn.lock

Bump jsdom from 19.0.0 to 22.1.0
Auth IT Health Check found several dependency vulnerabilities and this PR is for jsdom.
[https://govukverify.atlassian.net/browse/AUT-1825](url)

BAU: Bump jsdom from 19.0.0 to 22.1.0

---

ci/terraform/sandpit.tfvars

Add additional config for sandpit deployment:
- orch_to_auth_client_id
- orch_to_auth_audience
To fix error messages in the frontend on authorize when this config is missing

BAU: Add additional config for sandpit deployment

---

ci/terraform/sandpit.tfvars
ci/terraform/variables.tf
src/app.ts
src/config.ts
src/config/helmet.ts

Add a functionality to add the frame-ancestors and form-actions CSP headers if the FRAME_ANCESTORS_FORM_ACTIONS_CSP_HEADERS terraform variable is set to true.
The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined: frame-ancestors, form-action The directive(s): frame-ancestors, form-action are among the directives that do not fallback to default-src, missing/excluding them is the same as allowing anything.

AUT-1706: review and fix CSP issues identified by ZAP

---

ci/terraform/auto-scaling.tf
ci/terraform/build.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf
deploy-sandpit.sh

Test standard ECS auto scaling configuration in sandpit, build and staging.
Switch off the current auto scaling configuration and switch on the standard one in these environments. Have applied the standard configuration using Terraform: 
https://github.com/govuk-one-login/architecture/blob/4b985350c63b000343bccc76027101139b0e5e35/adr/01XX-fargate-scaling.md
The current configuration did not scale appropriately during performance test.

AUT-1624: Test standard ECS auto scaling configuration in sandpit, build and staging

---

ci/terraform/integration.tfvars
ci/terraform/staging.tfvars

AUT-1706: Turn on the frame_ancestors_form_actions_csp_headers flag in integration and staging
Add a functionality to add the frame-ancestors and form-actions CSP headers if the FRAME_ANCESTORS_FORM_ACTIONS_CSP_HEADERS terraform variable is set to true.
We need to turn on this flag in integration and testing in order to test if the CSP headers don't break any existing configurations.

AUT-1706: Turn on the frame_ancestors_form_actions_csp_headers flag

---

ci/terraform/ecs.tf

Add csp switch env var to ecs config.
So that the switch value gets passed to the application via the ecs task config.  Without this change the switch does not apply.
#1208

AUT-1706: Add csp switch env var to ecs config

---

.github/workflows/build-and-push-frontend.yml
.github/workflows/deploy-frontend.yml

AUT-1946 --Mask the AWS credentials in GitHub workflow on repo authentication-frontend
The GitHub Action have unmasked AWS credentials in GitHub workflow , This is security concern to have them unmasked credentials on GIT hub public repo authentication-frontend
N/A as this change in CI/CD not application

Moving AWS credentials to Secrets

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/contact-us-service.ts
src/components/contact-us/questions/_security_send_method.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Modified radio buttons to reflect changes described in ticket 1356
**Before:**
**After**
Kim Clayden has been informed of the changes and the screenshots necessary have been posted above

Adding radio buttons and conditional fields

---

ci/terraform/build.tfvars
ci/terraform/sandpit.tfvars

Reset build and sandpit ecs task count to the previous defaults.
After switching to the v2 scaling policy there was an issue with the application not restarting due to the minimumHealthyPercent threshold not being met during a deployment, as the minimum count had gone down to 1.
#1202

BAU: Reset build and sandpit ecs task count to the defaults

---

ci/terraform/waf.tf

Amend WAF query param limit
The authorize request from orchestration exceeds the limit imposed by this WAF rule. Maintain for all other endpoints, but extend to 4096 for the authorize endpoint.
https://github.com/govuk-one-login/authentication-api/pull/3563

ATO:195 Amend WAF query param limit

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/index-public-contact-us.njk
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts

Fixes Contact Forms "Back" links issues that have emerged since the Triage Page was introduced.
The changes to make "Back" links work are quite involved (much less straightforward than I'd anticipated), so I've tried to set out all the relevant context. Let me know if you'd like me to talk you through it - I'd be very happy to. 
The programme introducing a Triage Page that sits outside the `di-authentication-frontend` repository has introduced some complexity for determining the correct destination for "Back" links presented to users presented to users in the Contact Forms. Significant contributors to this are that:
1. there are Triage Pages for most, but not all, our environments 
2. the Triage Page includes a single link to the Contact Forms that **does** include a `fromURL` parameter …

CN-754: Fix issue with Contact Form back links

---

src/components/authorize/authorize-controller.ts
src/components/common/cookies/cookies-controller.ts
src/components/landing/landing-controller.ts

What?
HttpOnly has been applied to cookies_preferences_set cookie as per description in AUT-1985

AUT-1985/Cookies-not-set-with-HttpOnly-and-Secure-Flag

---

.github/workflows/build-and-push-frontend.yml
Dockerfile

Adds Dynatrace integration to auth-frontend dockerfile.
Instrumenting the nodejs frontend with Dynatrace OneAgent.
<https://github.com/govuk-one-login/authentication-frontend/pull/1226>

Add Dynatrace integration to Dockerfile

---

src/utils/smartAgent.ts
src/utils/zendesk.ts

Extends logging in response to a failed support form submission to include additional information that will support investigation of issues. This includes:
- Which service could not be submitted to (SmartAgent or Zendesk)
- The status code and status text
- The ticket identifier
A recent incident revealed the need to make it easier to identify failed contact form submissions in the logs.

AUT-2048: Improve support form submission error logging

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/auth-code/tests/auth-code-service.test.ts
src/config.ts

AUT-1993: Create SUPPORT_2FA_B4_PASSWORD_RESET feature flag

---

src/app.constants.ts
src/app.ts
src/components/account-intervention/temporarily-blocked/index.njk
src/components/account-intervention/temporarily-blocked/temporarily-blocked-controller.ts
src/components/account-intervention/temporarily-blocked/temporarily-blocked-router.ts
src/components/account-intervention/temporarily-blocked/tests/temporarily-blocked-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Added template, route, unit test and translations for the Temporary Suspended page.
The changes are necessary to be implemented as part of the account interventions user journey.
| English Translation | Welsh Translation | 
| --------------- | --------------- | 
| <img width="1440" alt="English Translation" src="https://github.com/govuk-one-login/authentication-frontend/assets/65968889/73a619b6-be6d-4304-a05f-fafe3bb6fe67">  | <img width="1440" alt="welsh-temporary-blocked-screenshot" src="https://github.com/govuk-one-login/authentication-frontend/assets/65968889/4c910c1a-839b-4402-b016-ff2262fc0975">  |

AUT-1862: Created Page and Route for Temporary Suspended Page

---

ci/terraform/authdev1.hcl
ci/terraform/authdev1.tfvars
ci/terraform/authdev2.hcl
ci/terraform/authdev2.tfvars
ci/terraform/dns.tf
deploy-authdevs.sh

Adding Authdev1 and  Authdev2 env  based on sandpit Env for locally deployment in new development aws account 
(https://github.com/govuk-one-login/authentication-api/pull/3638)

AddingAuthdev1 and  Authdev2 Env

---

src/components/prove-identity/prove-identity-controller.ts
src/components/prove-identity/tests/prove-identity-controller.test.ts

Invoke the auth code logic in provide identity when the auth-orch split is enabled
When the auth orch split is enabled, we should return to orchestration rather than redirecting to IPV.

ATO-224: Return to orchestration on ID journeys

---

ci/terraform/integration.tfvars

Turn on frame ancestors feature switch on in integration.
Before adding the Frame Ancestors Content Security Policy to production, we should first add them to integration, in order to make sure the security headers don't break any other implementations.

AUT-2029: turn on frame ancestors feature switch on in integration

---

ci/terraform/production.tfvars

Production environment variable changes to enable SmartAgent and Welsh language.
The new Contact Centre expects submissions to SmartAgent (rather than Zendesk) and will support Welsh language.

AUT-1884: Enable SmartAgent and Welsh in production Contact Forms

---

src/components/sign-in-or-create/index.njk

This PR simply left aligns the "Sign in" button on larger screens without impacting the presentation on smaller screens. This button is presented to users during the "Create / Sign in" journey. I've also formatted the related Nunjucks template to fix indentation issues etc. You can view the diff without whitespace changes [here](https://github.com/govuk-one-login/authentication-frontend/pull/1250/files?diff=split&w=1)
<details>
<summary>Button presentation on larger screens (details component expanded)</summary>
</details>
<details>
<summary>Button presentation on smaller screens (details component expanded)</summary>
</details>
I've simply wrapped it in a block-level element. This seemed the simplest way to achieve consistent results. 
This change has been tested in the following …

AUT-1934: Move 'Sign in' button on 'Create/sign in' screen

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/check-reauth-users/tests/check-reauth-user-service.test.ts
src/config.ts

Create a new frontend feature switch SUPPORT_REAUTHENTICATION
- Write unit tests to verify the feature flag is configured correctly
Feature flag to support re-authentication until it's fully implemented and integrated

AUT-2118: Create a new frontend feature switch SUPPORT_REAUTHENTICATION

---

src/components/check-your-email/check-your-email-validation.ts
src/components/common/verify-code/tests/verify-code-validation.test.ts
src/components/common/verify-code/verify-code-validation.ts

Introduces a custom sanitizer to remove whitespace from OTP fields before they are passed to validation functions. This validator captures the all instances of the following types of whitespace: 
* Whitespace and line terminator characters 
* Horizontal and vertical tabs
* New lines
* Carriage returns
* Form feeds
Recent advice from Accessibility Specialists has revealed that users of some assistive technologies may find their input mechanism injects whitespace into fields. Prior to this PR, user entries that included whitespace would have failed validation.

AUT-1895: Remove whitespace from OTP field entires

---

.github/workflows/pre-merge-checks.yml

Add coverage report task to pre-merge checks.
Task was removed because it was only reporting on integration test coverage as running tests removes all previous coverage tracking. Adding the task back in a different place so it reports on unit test coverage only.

BAU: Add coverage report task to pre-merge checks

---

src/components/contact-us/questions/_security_send_method.njk

Removes the "Email" option from forms under "A problem signing in" while retaining it for the "A problem creating a GOV.UK One Login" forms.
<details>
<summary>You’ve changed your phone number or lost your phone (under "A problem signing in") - 'Email' option removed</summary>
</details>
<details>
<summary>The security code does not work (under "A problem signing in") - 'Email' option removed</summary>
</details>
<details>
<summary>You did not get a security code (under "A problem signing in") - 'Email' radio option removed</summary>
</details>
To demonstrate that the changes are limited to the relevant forms, I've included screenshots of their counterparts in the account creation journey to demonstrate that they are not changed.
<details>
<summary>The security code does not work (under …

AUT-2104: Remove "Email" radio button from "A problem signing in" forms

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/jwt-service.test.ts
src/components/authorize/types.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/types.ts
src/utils/http.ts

In order to implement re-authentication, we need to respond to a claim sent to us by orchestration which signals that reauthentication should occur.
This PR:
* checks for the existence of the `reauthenticate` claim
* If it's present, and if the user is currently logged in, then upon the call to /authorize we will redirect the user to the sign in page
This claim will contain the user's RP pairwise ID. In this PR, we don't do anything with this beyond check for the existence of the claim. Work to check this pairwise ID against what we hold for the user will be implemented in [this ticket](https://govukverify.atlassian.net/browse/AUT-2127).
For the moment, we redirect to the existing sign in page screen. It's possible that we will amend this in future to point to a new page, this is still …

Aut 2113/handle auth params

---

src/app.constants.ts
src/app.ts
src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/reset-password-2fa-sms/index.njk
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-routes.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-integration.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Change the screenflow to include the SMS 2FA step in password reset when the switch is on.
In the existing journey where a user’s password can be reset without entering an mfa, once a user has reset their password they would then have to enter their mfa to login (for a 2fa service).  In the new journey this is not required so should be removed if the switch is off.

AUT-1995: Set up Password Reset ‘Check your phone’ flow

---

src/components/auth-code/auth-code-controller.ts
src/components/auth-code/auth-code-service.ts
src/components/auth-code/tests/auth-code-service.test.ts
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/types.ts

Call the "old" auth code endpoint after prove identity callback
To minimise the number of changes applied at the same time, the split will initially use the authentication identity callback page. To enable this, the auth code endpoint has been modified to generate an orch->rp authcode after identity proving instead of an auth-orch authcode.

ATO-260: generate an orch->rp authcode after identity callback

---

src/app.constants.ts
src/components/account-intervention/account-intervention-service.ts
src/components/account-intervention/types.ts
src/components/auth-code/auth-code-routes.ts
src/components/common/state-machine/state-machine.ts
src/middleware/account-interventions-middleware.ts
test/unit/middleware/account-interventions-middleware.test.ts

Created Front End Middleware for Account Interventions and associated tests. Also updated state machine to allow for account interventions user journey AUTH_CODE path.
Currently changes are a WIP but are turned off by the SUPPORT_ACCOUNT_INTERVENTIONS feature flag.
Password Reset required journey also needs linking to the following check your email page via post request as is shown on the figma:
https://www.figma.com/file/aVqNC4pKaebZchIU691f31/DI-Authentication?type=design&node-id=22785-87951&mode=design
Middleware and state machine needed to be implemented to allow for account interventions user journeys.
https://github.com/govuk-one-login/authentication-frontend/pull/1244

AUT-1841: Create Frontend Middleware For Account Interventions

---

src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/reset-password/reset-password-controller.ts

Functionality to skip subsequent paths from the reset password screen has been removed and instead MFA is instead disabled if MFA has previously been completed as part of the new journey.
Current MFA PW reset functionality skipped login MFA after password reset as expected but it also skipped

AUT-2213: Rework login MFA skip functionality for MFA PW reset journey

---

src/components/account-recovery/check-your-email-security-codes/send-email-otp-middleware.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts

Applies '15-min block' error screens consistently when user exits journey and restarts across scenarios:
So that the error screens are consistent across all scenarios when a user:
1. triggers a 15-min block error, and
2. then exits the journey and restarts it before the 15-min block has passed
The user first encounters this screen at the point they submit an incorrect SMS OTP for the 5th time.
Restarting a journey while the block is still in place will result in this screen being shown when they submit their password.
The user first encounters this screen at the point they request the 5th SMS OTP code
Restarting a journey while the block is still in place will result in this screen being shown at the point they submit their password
The user first encounters this screen at the point they …

AUT-1553: Change error screens for new journeys with block in place

---

src/app.constants.ts
src/components/check-reauth-users/check-reauth-users-service.ts
src/components/check-reauth-users/types.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-routes.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts

Temporarily redirect the user to /enter-password during the re-authenticate journey only when feature flag is on
- Update state machine
- Update enter-password GET controller method
- Call new CheckReauthUsers API endpoint
Temporarily redirect to /enter-password page whilst discussions are ongoing with HMRC regarding the new reauth screen

AUT-2116: Integrate 'Enter password' into the frontend re-authentication flow

---

ci/terraform/staging.tfvars

Scale ECS staging up and out.
Doubling both cpu and memory, more than doubling max number of tasks to 30.  IPV has max of 60 but will retest with 30 first to see.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size
Applies to staging only.
Performance test achieved 8 tps vs target of 30 tps. Could not scale beyond 12 tasks.
#1288

AUT-2241: Scale ECS staging up and out

---

src/app.constants.ts
src/app.ts
src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/types.ts
src/components/reset-password-2fa-auth-app/index.njk
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-routes.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-controller.test.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-integration.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-auth-app-2fa-integration.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/types.ts

Change the screen-flow to include the Enter Authenticator App Code 2FA step in password reset when the switch is on.
The BAU flow for the password reset is: 1.Check-email 2.Reset-Password 3.MFA. The order needs to be changed as mentioned above.

AUT-1997: Setup Password Reset Enter Authenticator App Code flow

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-service.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/enter-password/types.ts

Send the user journey to the backend API when they log in during a reauthentication journey.
We need to increment a relevant counter on the backend when the user logs in during reauthentication.
- https://github.com/govuk-one-login/authentication-frontend/pull/1290

AUT-2244: Send user journey to backend API when logging in during reauthentication

---

.github/CODEOWNERS

Restrict the codeowners file to just the leads groups
To avoid incompatible changes during the release of phase 1 of the auth orch split

ATO-255: Restrict codeowners for the duration of the deployment

---

ci/terraform/production.tfvars
ci/terraform/waf.tf

Increase WAF rate limits for frontend, and cpu and memory for ECS.
Provide an uplift in capacity.

BAU: Increase frontend capacity

---

src/components/authorize/authorize-controller.ts
src/components/authorize/claims-config.ts
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/types.ts

During the release of the phase 1 split, an increase in errors was seen on the orchestration redirect endpoint. This was caused by incorrect behaviour in the authentication frontend. When a user clicks the browser back button to return to auth from IPV, they land on the processing identity page and receive a NO_ENTRY response from the processing identity lambda, as no data has been sent to SPOT. In this case, the auth frontend should return the user to the RP with an error, but was incorrectly returning the user to the orchestration redirect.

ATO-331: Redirect to RP on identity error, not orchestration

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars

Switch off autoscaling v1 in integration and prod.
Precursor to switching on autoscaling v2 as a single deployment switching v1 off and v2 on does not work. Default task counts will apply while scaling is switched off. To be followed by a PR switching on v2.

AUT-2287: Switch off autoscaling v1 in integration and prod

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars

Switch on autoscaling v2 in int and prod
Increase max task count to 60 in prod.
Applies step scaling rules as used in performance testing.

Aut 2287: Switch on autoscaling v2 in int and prod

---

.github/CODEOWNERS

This reverts commit 871be2690d6679904f2793d54462fd0174141d23.
Phase 1 deployment is complete; restore original codeowners

Revert "ATO-255: Restrict codeowners for the duration of the deployment"

---

src/components/account-intervention/password-reset-required/index.njk
src/components/account-intervention/permanently-blocked/index.njk
src/components/account-intervention/temporarily-blocked/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Account Interventions - Page titles for suspended/blocked/pw reset not displayed in the tab heading like it is for other screens.
Acceptance tests use the name in the tab to determine if correct page is displayed.

AUT-2229: Fixed Page Titles Not Displaying In Tab Heading

---

ci/terraform/alb.tf

AUT-2261
This change is to Enable ALB access logging for frontend load balncer & pushing access logs to S3 
Only on prod 
Have tested the TF on AUthdev1 to enable logging  however this  Changes is for Prod only

Adding ALB Access logging

---

src/components/auth-code/auth-code-controller.ts
src/components/auth-code/tests/auth-code-controller.test.ts

When the auth controller is hit, this removes the `reauthenticate` property from the users session.
This is to ensure we don’t use it incorrectly in later journeys. Reauthenticate here indicates the RP requested that the user reauthenticate before performing an action on the RP.
- https://github.com/govuk-one-login/authentication-frontend/pull/1290
- https://github.com/govuk-one-login/authentication-frontend/pull/1297

AUT-2253: Remove `reauthenticate` property from user session once auth journey finishes

---

src/components/common/state-machine/state-machine.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/components/reset-password/tests/reset-password-forced-2fa-before-integration.test.ts

Due to the way we have completed the MFA password update journey and the way forced password reset routing works, only the password update controller required updating to handle a forced password reset journey.
We needed to add MFA to the forced password reset journey caused by the user using a weak password during login.
At some point we used routes to route the user to existing password reset functionality despite there being a state machine flow for the forced password reset journey, this made the MFA journey change a lot more simple once the difference from normal flow was understood.
related links:
[SMS journey](https://govukverify.atlassian.net/browse/AUT-2032)
[Auth App journey](https://govukverify.atlassian.net/browse/AUT-2033)

mfa password reset required journey

---

ci/terraform/production.tfvars

Switch off autoscaling v2 in on prod.
Precursor to switching on autoscaling v1 back  as a single deployment switching v2 off and v1 on does not work.

AUT-2297-Switching off V2 scaling in Prod

---

pre-commit.sh
shutdown.sh

Add shutdown script for local application.
Shutsdown both local node servers started with the '-l' option and node servers running under Docker.
If using the '-l' startup option just calling docker-compose down on its own will not terminate the local node instance, so another command is needed to do this.

BAU: Add shutdown script for local application.

---

src/middleware/account-interventions-middleware.ts
test/unit/middleware/account-interventions-middleware.test.ts

Removing temporary suspension handling from auth frontend
Temporary suspension account interventions are handled by orchestration

AUT-2296: Change Temporary Suspension Behaviour

---

ci/terraform/waf.tf

Add the supplied IPs to frontend staging WAF allowlist
So our pentesters can access the staging environment

AUT-2360: Add pentester IPs to staging WAF allowlist

---

src/components/account-recovery/check-your-email-security-codes/check-your-email-security-codes-controller.ts
src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-controller.test.ts
src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-integration.test.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/tests/check-your-email-controller.test.ts
src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts

Added to the verify code controller to handle a user requesting a change in MFA method while having account interventions against their account.
How AIS had been implemented thus far had not met the acceptance criteria for the scenarios outlined in AUT-2331
https://github.com/govuk-one-login/authentication-frontend/pull/1249

AUT-2231: Fixed Account Interventions/Change MFA Method Journeys

---

ci/terraform/staging.tfvars

Enable 2FA before password reset in staging.
To enable testing in staging (with account interventions)

BAU: Enable 2FA before password reset in staging

---

src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-routes.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts

- This PR is the first part of creating a new screen for the reauthentication journey
- Previously, it was decided for the user to be redirected to the /enter-password when reauthentication is required
- It has now been decided that the user to be redirected to a new re-auth screen
New re-auth screen is now available, user will be redirected to this screen instead
Revert some of the Initial PR to redirect user to /enter-password when re-authentication is required
(https://github.com/govuk-one-login/authentication-frontend/pull/1262)

AUT-2093-part-1: Remove previous implementation of reauth landing screen

---

src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/components/prove-identity-callback/types.ts

Some account interventions need to be applied post SPoT. To do this, the backend will return an intervention response with a redirect URL. This change actions that.
https://github.com/govuk-one-login/authentication-api/pull/3928

ATO-364: Pass through intervention from processing identity API call

---

ci/terraform/sandpit.tfvars

We now have the correct variable set in secrets to point to the stub in sandpit, so we can turn this on.

BAU: Turn on support for account interventions in sandpit

---

src/components/landing/landing-controller.ts

Log landing route referer.
The landing route is no longer in use but is seeing some traffic.  When users land on '/' they are no longer able to log in, even though it looks like the journey is working correctly, and effectively their session is broken.
Would like to see where users are coming from before removing it completely.
The standard logger logs the referer pathname so logging the entire referer to see if it yields any more information.

BAU: log landing referer

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-email/index-re-enter-email-account.njk
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- Create new re-enter email screen
- When reauth flag is on and reauthication is required, render re-enter email screen
- Integrate CheckReauth API in enter email post request
- When reauth flag is on and reauth is required, and user enter's a valid email, call the CheckReauth API
Revalidate user email when re-authentication is required
Part 1: https://github.com/govuk-one-login/authentication-frontend/pull/1354

AUT-2093-part-2: Create Re-enter your sign in details screen

---

ci/terraform/build.tfvars
src/components/reset-password-2fa-auth-app/index.njk
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add New 2FA content missing from 'Enter security code from your auth app' page.
New UI/UX design is required

AUT-2389: New 2FA content missing from 'Enter security code from your auth app' page

---

ci/terraform/build.tfvars

Switch of 2FA B4 password reset in build.
Further testing is required to make compatible with the acceptance tests.

BAU: Switch of 2FA B4 password reset in build

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/auth-code/tests/auth-code-service.test.ts
src/config.ts

Added a feature flag for the lockout duration increase.
Require a frontend flag for the new copy updates to mirror the existing flag in the backend PR as the new copy specifies the new 2hr lockout period

feature flag for 2hr lockout duration increase

---

src/components/common/layout/base.njk

Enables Tudor Crown in header and favicons across pages.
To reflect use of new crown across Digital Identity.
- https://github.com/govuk-one-login/authentication-frontend/pull/1360
- https://github.com/alphagov/di-infrastructure/pull/574

AUT-2363: Enable Tudor Crown

---

src/components/auth-code/auth-code-routes.ts
src/components/common/state-machine/state-machine.ts
src/components/prove-identity/prove-identity-routes.ts
src/components/prove-identity/tests/prove-identity-integration.test.ts
src/components/reset-password/reset-password-routes.ts
src/components/reset-password/tests/reset-password-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-forced-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-integration.test.ts
src/middleware/account-interventions-middleware.ts
test/helpers/account-interventions-helpers.ts
test/unit/middleware/account-interventions-middleware.test.ts

This ensures that, when a user goes through the "forgotten password" flow, they are sent to the account suspended or blocked screen instead of being able to re-set their password.
We should not allow users to re-set their passwords who have account interventions set on them.

Aut 2396/call account interventions on password reset

---

package.json
src/components/common/layout/base.njk
yarn.lock

Updates the govuk-frontend NPM package to version 4.8 so that we can use the Tudor Crown. Also introduces `useTudorCrown` to the `govukHeader` component so the swtich will simply be changing the value passed.
I've also applied IntelliJ auto-formatting to `base.njk` because the formatting was off. Most of these will changes can be hidden by choosing the 'hide whitespace'. 
To prepare for the move to the Tudor Crown.
This PR makes does not change the user interface.
- https://github.com/govuk-one-login/authentication-frontend/pull/1361
- https://github.com/alphagov/di-infrastructure/pull/574

AUT-2358: Update GOV.UK Frontend to use Tudor Crown

---

sonar-project.properties

Indicate test files for sonarqube.
Sonarqube is including test code when calculating coverage which is reducing coverage.
#1389 
#1388

AUT-2238: Indicate test files for sonarqube

---

src/locales/cy/translation.json

Add Welsh text required for page title on 'Enter_a_security_code_from_your_authenticator_app' page.
This [AUT-2389](https://github.com/govuk-one-login/authentication-frontend/pull/1364) was merged without welsh translations for all sections, to speed up the testing process. This PR was made to include the translations, as they were recently provided. 
[AUT-2389]: https://govukverify.atlassian.net/browse/AUT-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-2409: Add Welsh text required for page title on 'Enter_a_security_code_from_your_authenticator_app' page

---

src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-integration.test.ts

Add lockout logic for reset-password-2fa-sms controller
Reset password journey - 6 incorrect sms codes - switches between screens when new code then requested

AUT-2415: fix switching between screens when new code then requested

---

src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-controller.test.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-integration.test.ts

add lockout logic for reset-password-2fa-auth-app-controller.ts
Enter a security code from your auth app - 6 incorrect codes - user can immediately navigate back to auth app screen without waiting for lockout period to expire

AUT-2417: add lockout logic for reset passwd 2fa auth app controller

---

src/app.constants.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/check-reauth-users/check-reauth-users-service.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts

Amend typo in the endpoint for checking validity of user when re-authentication is required.
- from `/check-reauth-users` to `/check-reauth-user`
- Refactor state machine to redirect to `/enter-email` re-auth screen when no session exists

bau: Amend check reauth user endpoint

---

ci/terraform/alb.tf

What?
AUT-2270 --Ensure that Drop Invalid Header Fields feature is enabled for your Amazon Application Load Balancers (ALBs)
Why?
If Drop Invalid Header Fields security feature is enabled, HTTP headers with header fields that are not valid are removed by the Application Load Balancer instead of being routed to the associated targets

AUT-2270 conditionally enabling http drop invalid  header  on lower env

---

ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/check-reauth-users/check-reauth-users-service.ts
src/components/enter-email/index-re-enter-email-account.njk
src/components/enter-email/index-sign-in-details-entered-too-many-times.njk

- The reauth check lambda returns a 404 when no user matched or found
- The axios interceptor seems to validate only http status codes between 200 to 400
- For any other http status it rejects the promise and returns the screen "Sorry, there is a problem" which is not the requirement for reauth
- Refactor the axios create to validate status code up until 500 internal server error
- Reduce the email entered wrong blocked minutes to 30 secons in build
- Remove back button for reauth screens
To return the appropriate screens for reauth journey when user enter's invalid email

BAU/reauth-fix: Refactor axios handling of 404 http status code

---

src/components/common/state-machine/state-machine.ts
src/components/reset-password-2fa-sms/index.njk
src/components/reset-password-check-email/index.njk

remove Back button from /reset-password-2fa-sms, add it to the /reset-password-check-email screen
Changes required in new UI/UX design.
- Back button removed from /reset-password-2fa-sms page
-Back button added to reset-password-check-email page: 
-User can transition to /enter-password, from /reset-password-check email, via the new back button:

AUT-2356: remove Back button from /reset-password-2fa-sms, add it to the /reset-password-check-email screen

---

ci/terraform/alb.tf

AUT-2270 -Enabling Drop invalid  HTTP Header on Frontend ALB
We need to enable HTTP drop Invalid Header as per CPC finding CPC-225 
Valid Header : Elastic Load Balancing requires that message header names conform to the regular expression [-A-Za-z0-9]+ 
Invalid Header  are which contains "-" (underscore) 
NO change to Demonstrated , however this has be tested in Lower env Acceptance Test are passed

AUT-2270 -Enabling Drop invalid  HTTP Header on Frontend ALB

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/index-account-locked.njk
src/components/enter-password/index-sign-in-retry-blocked.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Copy update for enter password lockout error screens using feature flag.
When feature flag is enabled lockout is increased to 2 hours so we need to display updated error messages.
Lockout
Later Attempt
Lockout
Later attempt

AUT-2362/enter password error update

---

src/components/enter-password/enter-password-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Copy update for enter password inline error message using feature flag.
When feature flag is enabled we want to display the new content update.

copy update for inline incorrect password error

---

ci/terraform/production.tfvars

turn on support_2fa_b4_password_reset feature switch in production
Only to be merged with: https://github.com/govuk-one-login/authentication-api/pull/4033

BAU: turn on support_2fa_b4_password_reset feature swtich in production

---

deploy-authdevs.sh
deploy-sandpit.sh
scripts/dev_deploy_common.sh
scripts/export_aws_creds.sh

- Use well-known AWS profile names
- Pull out common code from deploy-authdevs.sh and deploy-sandpit.sh
into a common script
- Pull out AWS credential export into a separate script
Local profile names were different for each person's laptop. This standardises them.
Also, it makes the deploy scripts easier to maintain.
- use python script implemented in govuk-one-login/authentication-api#4042 to create the correct AWS accounts
- deploy something to sandpit - check there are no errors
- deploy something to an authdev - check there are no errors
govuk-one-login/authentication-api#4042
alphagov/di-infrastructure#576

[AUT-2485] Improve Dev deployment scripts

---

src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/locales/cy/translation.json

Fixed AIS password reset required journey to allow for password reset journey rather than redirecting to temporarily suspended screen.
After password reset required screen, entering OTP and MFA a user with passwordResetRequired and temporarilySuspended statuses was incorrectly being shown the temporarily suspended screen instead of being taken through the password reset journey.

AUT-2446: Fixed AIS Password Reset Required Journey to Allow for Password Reset Instead of Showing Temporarily Suspended Screen

---

.env.build

Sample .env config file to run di-authentication-frontend locally pointing to build.
The local stub has recently been updated and additional environment variables are required to make it run against build
#1411

BAU: Sample .env config file to run di-authentication-frontend locally pointing to build

---

src/components/common/footer/accessibility-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Several changes for the accessibility-statement page.
**Update 1**
ADD
- the header sign-out link causes a horizontal scrollbar at very large magnifications on mobile devices
- it’s not always possible to use your browser's autocomplete options to enter information
- the links in the footer are not the same on every page
- there is an empty link in the header for a short section of the journey
- some pages do not correctly identify the language they are published in
- some page titles do not start with ‘error’ if you have not entered the information that’s needed in the correct format`
- some links in the header and footer that you may expect to open in a new tab open in the same tab
- some form fields limit how many characters can be entered in them, which can make it difficult to enter …

AUT-2462: modify content for the accessibility-statement page

---

.env.build
startup.sh

Use `export_aws_creds.sh` to set AWS credential envars for local docker deploy.
This standardises credential access within this repo.
https://github.com/govuk-one-login/authentication-frontend/pull/1420

AUT-2485: Use CLI profiles for local docker deployment

---

src/components/check-reauth-users/check-reauth-users-service.ts
src/components/check-reauth-users/types.ts
src/components/enter-email/enter-email-controller.ts

- Include reauthenticate claim in the request of the CheckReauthUser lambda
The value would be used to compared against a calculated rpPairwiseID

bau: Refactor CheckReauthUser service to include the user sub in request

---

startup.sh

The previous grep/xargs approach is a bit brittle and can break
on syntax errors in the .env file.
Instead, use `set -o allexport` to export all variables set in the file
and `source` it directly.
https://github.com/govuk-one-login/authentication-frontend/pull/1424

AUT-2485: Fix loading the .env file

---

ci/terraform/production.tfvars

AUT-2487 switching off the current scaling policy on prod to enable new scaling policy in next PR 
The new scaling policy for NFR has been tested and passed in Staging environment so push the new scaling policy on prod  

AUT-2487-Switch off current scaling policy on Prod

---

src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts

It does not make sense in this case to redirect through the password reset journey.
An additional change will be required to make this journey work fully - PR to follow.

Bugfix: Do not redirect to password reset intervention when on password reset journey in verfiy code controller

---

src/middleware/account-interventions-middleware.ts
test/unit/middleware/account-interventions-middleware.test.ts

This fixes the case where, when resetting a password due to an account intervention of password reset required, we are taken to the temporarily blocked screen, since in the reset password routes we still care about the suspension status as we don't want to allow password resets on suspended users. However, when someone has an account intervention of 'password_reset_required', they will always have a suspension also until they have reset their password. Therefore, in the password reset routes and in the middleware, we want to differentiate between the case where a user only has a suspension status (in which case they should not be allowed to reset their password) from the case where they have a suspension status because they need to reset their password.

Bugfix: Do not direct to suspensions screen when password reset intervention also applies

---

.github/PULL_REQUEST_TEMPLATE.md

This is a space for developers to list specific steps needed for the PR to be
fully reviewed. 'Code review' is always implied, but can be stated here.
This seems completely unnecessary - it makes it really difficult to write
the PR in a logical way: 'what?' and 'why?' are intrinsicly linked, and the description
is easier to understand if these are together, rather than split apart.
This emphasises their 'differentness', and means that they are not rendered if
left in after submitting the PR. Some people find it easier to write with the prompt
visible at the time, and this means they don't need to worry about removing the prompt
after finishing writing the description.
1. Ensure no important sections have been removed
2. Ensure no unnecessary sections have been added
3. Ensure the …

[AUT-2484] Add 'How to review' section in PR template

---

src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts

A user going through the forced password reset flow has already entered a 2FA code when going through the regular login journey. A user should not have to enter their MFA twice.

Bugfix: removed the 2FA step from the password reset intervention flow

---

ci/terraform/auto-scaling.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/variables.tf

AUT-2487-Removing old ecs scaling policy  post switched to step scaling
We have moved our ECS policy to step scaling after passing the Performance testing , so removing old scaling policy code for clean-up

AUT-2487-Removing old ecs scaling policy  post switched to step scaling

---

src/components/account-creation/resend-mfa-code/index.njk
src/components/account-creation/resend-mfa-code/resend-mfa-code-controller.ts
src/components/resend-email-code/index.njk
src/components/resend-email-code/resend-email-code-controller.ts
src/components/resend-mfa-code/index.njk
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/security-code-error/index-too-many-requests.njk
src/components/security-code-error/index-wait.njk
src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Update the content of the error screens that appear when a user is locked out due to requesting an SMS + email OTP too many times.
We are increasing the lockout time to 2 hours, so the lockout time needs to be accurately reflected.
This is longer than the idle session time out, so the user journey changes.
[email ticket](https://govukverify.atlassian.net/browse/AUT-2367)
[SMS ticket](https://govukverify.atlassian.net/browse/AUT-2366)
**_You asked to resend the security code too many times_**
-----
**_You cannot get a new security code at the moment_**
-----
**_Get security code_**
-----
-----
**_You asked to resend the security code too many times_**
-----
**_You cannot get a new security code at the moment_**
-----
**_Get security code_**

content updates for too many code request error screens

---

src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/config/nunchucks.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/phone-number.ts
test/unit/utils/phone-number.test.ts

Updates the content on SMS and Authenticator App uplift screens, including introducing the last three characters of the user's telephone number (for which I've introduced a Nunjucks filter, utility function and associated tests). 
<details>
<summary>Enter a security code to continue (SMS version in English)</summary>
</details>
<details>
<summary>Enter a security code to continue (SMS version in Welsh)</summary>
</details>
<details>
<summary>Enter a security code to continue (Authenticator App version in English</summary>
</details>
<details>
<summary>Enter a security code to continue (Authenticator App version in Welsh)</summary>
</details>
1. Look at the [SonarCloud report](https://sonarcloud.io/summary/new_code?id=govuk-one-login_authentication-frontend&pullRequest=1438) to see if …

AUT-1540: Update content on uplift screens

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-controller.test.ts

Previously the journey of a blocked user was inconsistent with other account interventions when the user has a common password. This fixes that, by ensuring they are prompted to check their email before 2FA

AUT-2439: Ensure that a blocked user with a common password goes through the correct flow

---

src/components/reset-password/reset-password-controller.ts
src/components/reset-password/types.ts

Created isForcedPasswordReset parameter in updatePassword method to accept req.session.user.withinForcedPasswordResetJourney as an argument in the reset password controller. This is so that in the backend we can distinguish between password reset journey types for auditing.
Another PR is to follow for the backend.
Code should be reviewed alongside backend PR (https://github.com/govuk-one-login/authentication-api/pull/4087) ensuring that the argument for isForcedPasswordReset is accessible in the ResetPasswordHandler
https://github.com/govuk-one-login/authentication-api/pull/4087

AUT-2543: Created isForcedPasswordReset parameter in updatePassword method

---

src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-controller.test.ts
src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/middleware/account-interventions-middleware.ts
src/types.ts
test/helpers/account-interventions-helpers.ts
test/unit/middleware/account-interventions-middleware.test.ts

This fixes a problem whereby when someone resets their password, we redirect them to /auth-code and immediately call the interventions middleware again, at which point we will prompt them to reset their password again, since this does not give enough time for the account interventions service to be updated.
Instead here, we:
* set the timestamp of the time when a user reset their password on the session
* read from this value in the middleware when we have the `resetPassword` intervention set. If a) there is a resetPasswordTime in the session, and b) it is later than the `appliedAt` time on the intervention, we ignore the intervention and continue the journey.
This also contains some refactoring commits to make tests easier to read.
Note that this alone will not be enough to ensure that a …

AUT-2552: ignore reset password intervention within middleware when password has been more recently reset than intervention applied

---

src/components/account-recovery/check-your-email-security-codes/send-email-otp-middleware.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-password/enter-password-controller.ts
src/components/resend-email-code/resend-email-code-controller.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/security-code-error/index-security-code-entered-exceeded.njk
src/components/security-code-error/index-too-many-requests.njk
src/components/security-code-error/index-wait.njk
src/components/security-code-error/index.njk
src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts
src/components/select-mfa-options/select-mfa-options-controller.ts
src/components/sign-in-or-create/sign-in-or-create-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/types.ts

Update the content of the error screens that appear when a user is locked out due to entering and incorrect SMS OTP too many times
We are increasing the lockout time to 2 hours, so the lockout time needs to be accurately reflected.
This is longer than the idle session time out, so the user journey changes.
Journeys this needs to be done in:
* Create a  One Login account- will need different content to the rest of the journeys
* Sign in to One Login
* Reset password
* 2fa account recovery - when user is setting up their new 2fa method
The changes for this were demonstrated to Kim and to Craig, Kim and other colleagues in a demo.

AUT-2356: Update error screens when a user has entered an incorrect SMS code more than 5 times

---

src/components/auth-code/auth-code-service.ts
src/components/auth-code/tests/auth-code-service.test.ts
src/components/prove-identity/tests/prove-identity-controller.test.ts

Created the password reset time parameter in the auth code service in to be passed to the backend with the argument being stored in the access token store and then sent in the user info response to the backend. This argument is to be used by orchestration to compare the time a password has been successfully reset with the time a password reset account intervention status has been applied to an account.
Change in backend to accept this as a parameter: https://github.com/govuk-one-login/authentication-api/pull/4104
This PR not to be merged until that one merged first.

AUT-2553: Pass PW Reset Timestamp to Orch via Auth Code

---

shutdown.sh
startup.sh

It was pointed out that the `*_PORT` variables were missing defaults, meaning that the script blew up ungracefully if they were not set.
As they're not likely going to be deliberately changed by many users, we can set defaults within the script without it being '_unexpected behaviour_'.
Both `s{tartup,hutdown}.sh` scripts now have `set -euo pipefail` set, to better handle errors / missing values.
I've updated the `ACTION_*` variables to not have the default values pre-set at the top. Instead, they're set with defaults when the variable is accessed (`${VAR:-default}`). Happy to drop this if people think this'd be confusing. For me it's nice to have the defaults in the `if` statements, so 'default' behaviour can be more easily visualised (bash intellisense isn't a thing!)
1. with a valid …

BAU: Update defaults in `startup.sh`

---

.env.authdev1
.env.build
dev-check-environment.js

Having pulled the latest `main` I've found that frontend isn't running locally. In trying to understand what's happened, I've found that one issue is tests that require environment variables relating to Zendesk. Because all code relating to Zendesk was [removed in January](https://github.com/govuk-one-login/authentication-frontend/pull/1316), I've replaced these with to those that relate to SmartAgent and included these in `.env.authdev1`. Doing so has fixed the ability to run frontend locally. 
1. Code Review
1. Follow the setup instructions in `README.md` (ensuring you have the all the `requiredEnvVars` stipulated in `dev-check-environment.js`)
1. Run the frontend with `./startup.sh -l`
The PR that removed Zendesk was https://github.com/govuk-one-login/authentication-frontend/pull/1316

BAU: Replace Zendesk with new Contact Centre env vars

---

src/components/common/state-machine/state-machine.ts

Added the PROVE_IDENTITY path as an option from PASSWORD_CREATED given that isIdentityRequired is true. This is to resolve the IPV + AIS password reset required and suspended journey looping on the “You have already proved your identity” page.
This change needs to be merged and tested in staging as currently there is no way to test this locally.
Changes need to be tested in the staging environment with prod promotion paused in the pipeline.

AUT-2549: Bug fix for looping IPV page in AIS journey

---

src/components/common/state-machine/state-machine.ts

Reverts govuk-one-login/authentication-frontend#1457
Changes did not work when testing in staging

Revert "AUT-2549: Bug fix for looping IPV page in AIS journey"

---

src/components/common/state-machine/state-machine.ts
src/components/reset-password/reset-password-controller.ts

Added the PROVE_IDENTITY path as an option from PASSWORD_CREATED given that isIdentityRequired is true. This is to resolve the IPV + AIS password reset required and suspended journey looping on the “You have already proved your identity” page.
This change needs to be merged and tested in staging as currently there is no way to test this locally.
Changes need to be tested in the staging environment with prod promotion paused in the pipeline.

AUT-2549: Added ipv callback journey from auth code

---

src/components/account-intervention/types.ts
src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-controller.test.ts
src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/prove-identity/tests/prove-identity-integration.test.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password/tests/reset-password-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-integration.test.ts
test/helpers/account-interventions-helpers.ts
test/unit/middleware/account-interventions-middleware.test.ts

This is a preparatory commit to allow us to implement logic to allow users who are suspended with reprove identity to reset their passwords (and not hit a suspended page as they currently do). The field is unused for the moment.
1. Code Review
[PR](https://github.com/govuk-one-login/authentication-api/compare/AUT-2623/add-reprove-identity?expand=1) that sends this type on the backend - plan is to merge this backend PR after the PR here

AUT-2623: Add reprove identity to account interventions response

---

src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/middleware/account-interventions-middleware.ts
src/utils/interventions.ts
test/unit/middleware/account-interventions-middleware.test.ts

Have made changes that allow for a user to either reset their password or change their security codes if they have an AIS suspension status placed against their account while also requiring that they reprove identity. Now they are allowed to to reset their password or change their MFA method before being taken on to the reprove identity process where they will continue their journey.
1. Code Review
2. Run the front end against build with reprove identity and suspension statuses against your account
3. Go through the normal (non-forced) password reset journey successfully
4. Go through the change MFA journey successfully

Aut 2623/allow actions for reprove identity

---

src/components/account-creation/resend-mfa-code/resend-mfa-code-controller.ts
src/components/account-creation/resend-mfa-code/tests/resend-mfa-code-controller.test.ts
src/components/enter-phone-number/enter-phone-number-controller.ts
src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts

To implement the correct locking for code requests, we need to send the correct journey type to the backend API. Because the resend-mfa-code-controller.ts is used in the creation, account-part-created and account recovery journeys, we need to make sure that we send the current journey type, not JOURNEY_TYPE.REGISTRATION. Backend implements locking on the 6th requests. The enter-phone-controller sent the correct journey type, while the resend-mfa-code-controller.ts sent the wrong one, reason why we were blocked on the 6th, not 5th request. Obs: part-created and creation are using JOURNEY_TYPE.REGISTRATION, while account recovery has its own journey type.
Update resend-mfa-code-controller.ts to send correct journey type
1. Deploy to sandpit with ./deploy-sandpit.sh -l or test locally by …

AUT-2617: add the correct journey type to resend-mfa-code-controller.ts

---

src/components/create-password/create-password-validation.ts

UCD identified a bug today relating to the order of validation messages when a user leaves both password fields blank during an account creation journey. The problem is that "Re-type your password" appears before "Enter your password" (whereas the fields are in the opposite order). This PR changes the order of these messages. 
I have also checked that the page retains existing validation behaviour, including:
1. Start frontend running locally against this branch
2. Begin an account creation journey
3. On the "Create your password", leave both fields blank and submit the form
4. Confirm that the error message order matches what's in the screenshots below
5. Try different validation error permutations to confirm all is working as expected
6. Code review
<details> …

AUT-2612: Reorder validation messages on create password screen

---

src/components/reset-password-check-email/reset-password-check-email-service.ts

Currently, the api response for a reset password request returns a 204 (no content). We want to start returning some content, so we'll need to support it returning a 200. This adds 200 as a possible API response code, as a preparatory step before we start returning a 200 from the API.
When we have switched the API response over, we can remove 204 as a possible response code from here.
1. Code Review
[PR](https://github.com/govuk-one-login/authentication-api/pull/4162) that updates this response on the backend.
We'll need to first merge this PR in frontend, and then the above backend PR.

AUT-2598: Update success status code for reset password check email service

---

src/components/enter-password/enter-password-controller.ts

Support 2hr lockout flag was not passed to index-security-code-entered-exceeded.njk from enter-password-controller when a user is locked out due to too many failed sms mfa attempts.
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -a`
3. Follow steps in [ticket](https://govukverify.atlassian.net/browse/AUT-2600)

AUT-2600: update lockout error screen after entering correct password with too many incorrect mfa codes

---

src/config/nunchucks.ts

Enable nunjucks caching in deployed environments
This has been shown to improve performance by some Identity teams
See https://github.com/govuk-one-login/ipv-core-front/pull/1206/commits/b08319e95d055ac8437a24c45f5d6fab093a09d8

ATO-459: Performance: cache nunjucks templates

---

src/components/authorize/authorize-controller.ts
src/components/authorize/claims-config.ts
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/types.ts

Accept RP state from Orchestration and use this when redirecting to RP for identity errors. Not to be merged until Orch changes are in.
API change to pass state in https://github.com/govuk-one-login/authentication-api/pull/4139

ATO-449: use the correct state when returning to RP

---

README.md
package.json
scripts/render-user-journey-documentation.ts
src/components/common/state-machine/state-machine.ts

Create a dev only command `yarn dev:render-user-journey-documentation` that generates temporary local documentation derived from the user journey state machine.
A HTML table is created that has had the headers "Current Path", "Input Event", "Next Path & "Optional Paths" and can be used to understand how a user can navigate through their journey.
Definitions of the conditions to get to the next paths are added inline with the `title` attribute and the fall through nature of next paths are visualised.
Understanding how the user journey is implemented can take a while when looking at `src/components/common/state-machine/state-machine.ts`. This documentation should reduce the time to understand it.
https://github.com/govuk-one-login/authentication-frontend/assets/723372/c7822553-54a4-4a06-940e …

BAU: Add `dev:render-user-journey-documentation` command

---

src/components/check-your-phone/check-your-phone-controller.ts
src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts

Redirect to correct resend-mfa page when user is locked out due to too many incorrect codes entered in the account creation journey, and requests a new code.
1. Code Review
2. Ensure environment variables 'SUPPORT_2HR_LOCKOUT' and 'SUPPORT_2FA_B4_PASSWORD_RESET' are set to 1
3. Deploy to sandpit with `./deploy-sandpit.sh -l` (or run local)
4. Create a new account with an unregistered email address 
5. Enter correct email OTP
6. Enter 5 wrong SMS OTPS, check that you are redirected to the 15 min error screen 
7. Click on "get a new code" and verify that you are redirected to /resend-code-create-account?isResendCodeRequest=true
Changes to the user interface or content should be demonstrated to Content Design and Interaction Design before being merged. This is to ensure they can make any …

AUT-2633: Fix the resend code link for the check-your-phone page

---

src/utils/logger.ts

We should avoid stuffing our logging capacity with HTTP request logs for asset files in order to reduce the cost of logging (as these are requested very often and often not useful in debugging issues).
The following files are ignored: `/public/scripts/showPassword.js` and `/assets/images/govuk-crest.png`.
1. Run the service locally.
2. Open http://localhost:2000
3. See the logs in console do not include a 200 success response for `govuk-crest.png`.
Noticed after updating the pino dependencies in https://github.com/govuk-one-login/authentication-frontend/pull/1367

BAU: Ignore additional assets in pino-http logging

---

src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/reset-password-check-email-service.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/reset-password-check-email/types.ts

Currently, if a user:
* locks themselves out of their account due to too many passwords and then;
* attempts to access the service again in a new session and;
* chooses to reset their password when they hit the blocked screen
They will not be prompted to enter their 2fa during the password reset journey. This is because we determine whether someone needs to enter 2fa depending on whether the enterEmailMfaType is set in the session. This is normally set by the response from the "CheckUserExists" api endpoint, but when someone is locked out, this response returns an error and we do not get the mfa detail.
This commit forms part of a fix for this. We've updated the resetPasswordRequest response to contain the user's mfa details. Therefore, in this commit we:
* Add a new response interface …

Aut 2598/add mfa method when resetting password

---

.eslintrc.js
.github/workflows/pre-merge-checks.yml
README.md
package.json
pre-commit.sh
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-integration.test.ts
yarn.lock

Unit and integration test execution improvements
- Add eslint plugin and rule to prevent commiting 'it.only' tests
- Remove an 'it.only' that has been commited.
- Change and document the redis port used to run integration tests.
1. Code Review.
1. Change a test to 'it.only' and run 'yarn lint'.  You should see a linting error. 
1. If you commit this change and create a PR then the 'lint' action will fail, making the PR impossible to merge.
1. Follow the instructions in the readme to run integration tests.  They run cleanly in GHA, but there should only be the same 3 or 4 failures locally.

BAU: Unit and integration test execution improvements

---

ci/terraform/alb.tf
ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/variables.tf

We are deploying cloudfront in front of all frontends and performing some reconnaissance to ensure that the front end times out before we do. Currently auth ALB timeout is at default 60 seconds.  We would like to drop your timeout to 30 seconds to align with other frontends using api gateway.

adding idle_timeout to ALB

---

.env.authdev1

Update STUB_HOSTNAME for authdev1
The previous value is no longer in the client registry so is causing an error on authorisation to orchestration.
1. Shutdown your local frontend using 'shutdown.sh'
2. Delete your docker images for the local stub.
3. Make sure your .env file is configured to point to authdev1.
4. Update  STUB_HOSTNAME to the value in this PR.
5. Run 'startup.sh -lc'
6. Navigate to 'localhost:2000'.  You should be redirect to the 'Sign in or create' page.
<!-- 
This is to avoid failures occurring after a merge. The types of changes that may impact acceptance tests might be:
- changes to user journeys
- changes to the text of page titles
- changes to the text of interactive elements (such as links).
The Test Engineers on the Authentication Team will be happy to discuss any …

BAU: Update STUB_HOSTNAME for authdev1

---

ci/terraform/waf.tf

As part of ATO-449, we started passing through the state param in authorize JARs, which increased the length of the query params to this endpoint. We're seeing requests just over the 4096 limit, so this should give us a bit of headroom.
Not to be merged until approval given by security

INCIDEN-723: increase query param length limit

---

src/components/reset-password-check-email/index.njk
src/components/reset-password-check-email/reset-password-check-email-controller.ts

Removed "We need to make sure this is your GOV.UK One Login before you can reset your password" paragraph from reset password check email screen if req.session.user.withinForcedPasswordResetJourney is true. This content should not have been being shown during a forced password reset journey.
1. Code Review
2. Run through journey with AIS statuses temporarilySuspended == true && resetPasswordRequired == true
After change with AIS statuses applied going through forced password reset …

AUT-2654: Fix forced pw reset check email content

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Corrects text on the sign in or create screen. In a previous PR, I removed the feature flag to support international numbers but missed this bit of the view where it is used.
| English | Welsh |
|----|---|
|<img width="476" alt="Screenshot 2024-04-05 at 09 58 52" src="https://github.com/govuk-one-login/authentication-frontend/assets/25515510/b07d54d5-dfa9-4354-b153-203bff76596d">|<img width="521" alt="Screenshot 2024-04-05 at 09 59 12" src="https://github.com/govuk-one-login/authentication-frontend/assets/25515510/dcbcc3b0-a970-43b8-b607-09409af3c0d6">|
1. Code Review
1. Review screenshots
Changes to the user interface or content should be demonstrated to Content Design and Interaction Design before being merged. This is to ensure they are aware of changes and behaviours (for example, how …

Aut 2680/fix text on sign in screen

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-email/types.ts

Refactor the API interface variables to coincide with what BE is sending. 
1. Code Review
2. Ensure environment variables 'SUPPORT_2HR_LOCKOUT' and 'SUPPORT_2FA_B4_PASSWORD_RESET' are set to 1
3. Deploy to sandpit with `./deploy-sandpit.sh -l` (or run local)
4. Proceed through PW reset journey and enter the correct OTP email
5. Enter 5 wrong AUTH_APP OTPS, check that you are redirected to the screen corresponding to the first Screenshot below
6. Restart the journey by going to localhost:2000, or going through the stub again, go to the reset-password journey and verify that you're redirected to the 2nd screenshot below, after entering the correct email OTP. 
7. Proceed through the SIGN_IN journey
8. Enter 5 wrong AUTH_APP OTPS, check that you are redirected to the screen corresponding to …

AUT-2602:refactor naming of variables

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars

Fix the orch to auth signing public key for the authdev environments. This was previously set as the sandpit value, and has never worked.

BAU: fix orch to auth signing public key

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/utils/lock-helper.ts
test/unit/utils/lock-helper.test.ts

On the backend, we handle locks in seconds. On the frontend, we largely treat them as minutes. In a recent change, we started reading locks from the backend in a small number of cases, in order to ensure they were locked in the session. However, there was a mismatch - we were assuming the backend time to live was also in seconds.
This corrects this mismatch.
1. Code Review

Aut 2602/fix lockout units

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update the content of the 'Create or sign in' screen
1. Code Review
2. Run locally
3. Validate create or sign in page

AUT-2575: copy update to sign in or create page

---

.github/PULL_REQUEST_TEMPLATE.md

Created a single checklist of pre-submission items and added one to ensure a design review is performed if necessary.
Removed unnecessary headers and used comments to hide item guidance.
Read the PR template and check the changes make sense.
[Same work in the API repo](https://github.com/govuk-one-login/authentication-api/pull/4245)

Chore: Update PR template to ensure design review performed and restructure checklist

---

dev-check-environment.js

Adds `STUB_HOSTNAME` to the array of environment variables that should be both defined and not empty. It is already included in `.env.authdev1` and `.env.build` 
1. Code Review

BAU: Add STUB_HOSTNAME as a required env var

---

src/components/account-not-found/index-mandatory.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Remove references to Personal Tax Account and introduce additional changes identified in recent user research. 
While working on this change I've identified an additional page not covered by the Jira ticket that will be presented if the `req.session.client.serviceType` is "OPTIONAL". I am working with Tech Lead and UCD to determine if a new ticket is needed to update that page.
<details>
<summary>Coming from a government service (English)</summary>
</details>
<details>
<summary>Coming from a government service (Welsh)</summary>
</details>
<details>
<summary>Coming from One Login sign in (English)</summary>
</details>
<details>
<summary>Coming from One Login sign in (Welsh)</summary>
</details>
1. Code Review
2. Run frontend from this branch
1. Try to sign in with a non-existent email
2. …

AUT-2021: Change content on 'No GOV.UK One Login found' screens

---

ci/terraform/.terraform.lock.hcl
ci/terraform/site.tf
ci/terraform/variables.tf
ci/terraform/waf.tf

Endpoints can be rate limited based on the number of requests in a given
time period (number and time period are configurable via tfvars).
There are two buckets for rate limiting:
- Per-IP: A single IP address can only make the configured number of
requests in the configured time period.
- Per-Session: A single session (as defined by the `aps` cookie) can
only make the configured number of requests in the configured time
period.
By default, the limits are very generous. These should be set via tighter tfvars
Additionally, update AWS provider to `5.53.0` to make `evaluation_window_sec` available for use.
- Code review

AUT-2697: Enable rate limiting of frontend urls

---

ci/terraform/variables.tf

The `or` statement needs at least two endpoints to work.
- Update the default to a list of two uuids (non-existant routes)
- Add a validation rule to catch this problem before running the terraform
- Code Review

AUT-2697: Need two endpoints for the or statement here

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Fixes an issue raised by UCD where the word "in" had been appearing on a line alone following a recent content change. This has been fixed by introducing non-breaking space HTML entities to ensure the words in 'sign in' and 'One Login' do not split across lines as text wraps across different screen sizes. 
By default, Nunjucks escapes HTML entities so I've introduced the 'safe' filter in conjunction with 'striptags' for this element.
<details>
<summary>"in" appears alone on second line</summary>
</details>
<details>
<summary>Initial wrap (largest screen) - "sign in" appears on second line</summary>
</details>
<details>
<summary>Second wrap point - "or" joins "sign in" on second line</summary>
</details>
<details>
<summary>Third wrap point - "One Login" joins "or sign in" on second …

BAU: Fix issue with landing page heading text wrap

---

ci/terraform/cloudfront.tf
ci/terraform/dns.tf
ci/terraform/route53.tf
ci/terraform/sandpit.tfvars
ci/terraform/site.tf
ci/terraform/sns.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf
ci/terraform/waf-cf.tf
scripts/dev_deploy_common.sh
scripts/read_secrets__main.sh

AUTH-2655 Initial cloud-front resource creation
Initial cloud-front resource creation for AUTH
This PR is to create a Cloud front resource for each Env with `cloudfront_auth_frontend_enabled = true flag`
Most of the resource for cloud front get created in region` us-east-1`
TLS certificate , DNS records for CF origin, SNS for Notification , WAF for Cloud front & Cloud-front distribution & monitoring
##This PR Will not do the Traffic Switch will only create parallel resource for Cloud Front 
Code Review
Deploy to sandpit with ./deploy-sandpit.sh -t -p 
See if Cloud-front is deployed by checking on AWS console

AUTH-2655 -initial cloud front resource creation

---

package.json
src/app.ts
src/assets/scss/application.scss
src/components/common/layout/base.njk
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/middleware/set-local-vars-middleware.ts
yarn.lock

Add language toggle into all pages.
1/ Add a new env variable: LANGUAGE_TOGGLE_ENABLED (and set the value to 1)
2/ Run the app, and open it in the browser. 
3/ You will see new texts (just after the phase banner): English and Cymraeg.
Current language of the page is a text, the other language is a link. If you click on it, active language will change.
4/ Navigate into the app and check if language is still the same.

DFC-427: add language toggle feature

---

package.json
src/utils/error.ts
src/utils/http.ts
yarn.lock

Bumps [axios](https://github.com/axios/axios) from 0.25.0 to 1.6.8.
**Bug Fixes**
- AxiosHeaders: fix AxiosHeaders conversion to an object during config merging (https://github.com/axios/axios/issues/6243) ([2656612](https://github.com/axios/axios/commit/2656612bc10fe2757e9832b708ed773ab340b5cb))
- import: use named export for EventEmitter; ([7320430](https://github.com/axios/axios/commit/7320430aef2e1ba2b89488a0eaf42681165498b1))
- vulnerability: update follow-redirects to 1.15.6 (https://github.com/axios/axios/issues/6300) ([8786e0f](https://github.com/axios/axios/commit/8786e0ff55a8c68d4ca989801ad26df924042e27))

AUT-2393: Axios upgrade from 0.25.0 to 0.1.6.8

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/sandpit.tfvars

increase cpu Size from (.25 cpu , 512Mb ) to (.5cpu & 1Gb)   as healths checks failing on load balancer -Authdev's & sandpit 
And Setting desired count to 1 so no impact on Cost 
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -t -p

increase cpu Size as healths checks failing on load balancer

---

ci/terraform/build.tfvars
ci/terraform/variables.tf

Auth-2656 deploy Cloud front in Build no DNS switch
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -t -p

Auth-2656 deploy Cloud front in Build

---

ci/terraform/cloudfront.tf

fixing Template version & ignoring the changes to header parameter
1 ) Fixing the cloud-front Monitoring version making sure no changes to cloud front distribution or cloud front Monitoring is applied without testing 
2)  Ignoring parameter changes as these parameter are been read via secret manager and terraform continually detects changes to stack even though there aren't
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -t -p `

fixing Template version & ignoring the changes to header parameter

---

docker-compose.frontend.yml
docker-compose.yml
local.Dockerfile
scripts/_create_env_file.py
startup.sh

- Check if the token plain doesn't exist (ie. the user has never run
`aws sso login`), and give a more helpful error message.
- Check if the environment exists in the remote state when setting up
the state getter, to fail fast if the environment doesn't exist. Also
add a more helpful error message if the environment doesn't exist.
- Code review
Functional tests, but this will kinda involve blatting your AWS config, so unsure if people will want to do this.

[AUT-2759] Better error handling for _create_env_file

---

src/components/authorize/authorize-controller.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/common/cookie-consent/cookie-consent-service.ts
src/components/common/cookie-consent/tests/cookie-consent-service.test.ts
src/components/common/cookie-consent/types.ts
src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/tests/cookies-controller.test.ts
test/helpers/mock-cookie-consent-service-helper.ts

* Removes `HttpOnly` flag from `cookie_preferences_set` cookie included in HTTP responses. The [commit message](https://github.com/govuk-one-login/authentication-frontend/commit/b9e295d24fd67acfbd6d844fbd3030fba0334ee2) provides more context on the reasons for this change
* Removes duplicated `createConsentCookie` function that served only to wrap the `res.cookie` function provided by Express
* Applies `String` encoding to the cookie for consistency with encoding when the cookie is set on the client.
* Updates associated tests to ensure calls to `res.cookie` include the expected arguments and flags that will set the `HttpOnly` and `Secure` attributes. The [commit message](https://github.com/govuk-one-login/authentication-frontend/pull/1588/commits/939071fb1ceeaaa7c51132f76b1fdb7532d06e48) …

AUT-2733: Fix server sent consent cookie

---

scripts/set-password-by-email.sh

We need a script to set be able to set a password by email. This way, we can set ourselves a faulty password for development purposes.
Add a script to set a password by email.
For example:
1. Code Review
2. Populate the fields in the script with values for a desired environment. 
3. Run the script
4. Try to log on the environment with the new password

BAU: add set-password-by-email.sh script

---

src/components/auth-code/auth-code-controller.ts
src/components/auth-code/auth-code-service.ts
src/components/auth-code/tests/auth-code-service.test.ts
src/components/auth-code/types.ts
src/utils/http.ts
test/unit/utils/http.test.ts

Converts the auth code service to use the new getInternalRequestConfigWithSecurityHeaders function, which adds common security headers via the govuk-one-login/frontend-passthrough-headers library.
This needed a change to the way we construct the url that we pass through to the library, since in the auth code service sometimes we call a different base url, depending on the context. So this PR also updates that function to respect an optional base path that gets passed through to the config function.
1. Code Review
[Original PR](https://github.com/govuk-one-login/authentication-frontend/pull/1609) that converted one of the existing services

Aut 2578/convert more services common headers

---

src/app.constants.ts
src/components/check-email-fraud-block/checkEmailFraudBlockService.ts
src/components/check-email-fraud-block/types.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts

Create a new service to check fraudulent emails. The scope of this PR is just to receive and log information from the BE. This provides the infrastructure on which further functionalities can be built upon. 
1. Code Review
The screenshot below shows how the FE correctly receives information from the BE.

AUT-2164: Create new service to check for fraudulent emails

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf

Adds several environment variables used by the Frontend Capability Team `@govuk-one-login/frontend-analytics` NPM package to support GA4 and Universal Analytics.
1. Code Review
- https://github.com/govuk-one-login/authentication-frontend/pull/1522 introduced the `@govuk-one-login/frontend-analytics` NPM package.

BAU: Set environment vars for GA4 and Universal Analytics

---

src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
src/components/setup-authenticator-app/setup-authenticator-app-validation.ts
src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts

Fixes a bug reported by QA where authenticator app secret keys were not displayed following a validation error.
The fix ensures the secret will display both:
- where the **code format is invalid** and therefore fails the validation rules as set in `setup-authenticator-app-validation.ts`
- where the **code is incorrect**, as demonstrated by the `verifyMfaCode` service not returning a success
The related integration tests have also been updated to prevent assertions passing where the code is not included (the previous non-empty test would always pass because the text included whitespace and line break characters)
1. Code Review
1. Run this branch locally
1. Go through an account creation journey choosing authenticator app when asked to choose a method for second factor. 
1. On the "Set up …

AUT-1432: Fix secret key display in error state and tests

---

src/components/reset-password/reset-password-service.ts
src/components/reset-password/tests/reset-password-service.test.ts

We had [previously](https://github.com/govuk-one-login/authentication-frontend/commit/d9e8001c238ff3c6a299eccf562e8103f8c489df) added this parameter to the interface, but not used it. In the backend, this [controls](https://github.com/govuk-one-login/authentication-api/blob/0a1a1d414d24fa7cd8e51962e2b57706023a165c/frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java#L190-L207) whether we send the `PASSWORD_RESET_INTERVENTION_COMPLETE` audit event through, so this change should mean these events are being sent.
Detailed rationale for this change:
[Here](https://github.com/govuk-one-login/authentication-api/blob/0a1a1d414d24fa7cd8e51962e2b57706023a165c/frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java) …

BAU: send isForcedPasswordReset in request to backend

---

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/questions/_proving-identity-problem-with-national-insurance-number.njk
src/components/contact-us/questions/index.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Create new form “A problem with your national insurance number” (with English / Welsh variants and appropriate error states) and link to previous user selection
Go to http://localhost:3000/contact-us-questions?theme=proving_identity&subtheme=proving_identity_problem_with_national_insurance_number&lng=en&referer=
And play with the new form.

Aut-2844 : add new contact form problem with national insurance number

---

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/further-information/_proving-identity-further-information.njk
src/components/contact-us/questions/_proving-identity-problem-with-bank-building-society-details.njk
src/components/contact-us/questions/index.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Create new form “A problem with your bank or building society details” (with English / Welsh variants and appropriate error states) and link to previous user selection
Go to http://localhost:3000/contact-us-questions?theme=proving_identity&subtheme=proving_identity_problem_with_bank_building_society_details&referer=yourreferrer
And play with the new form

Aut-2843 add new contact form problem with bank or building society details

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/dev.tfvars
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf
scripts/_create_env_file.py
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/further-information/_proving-identity-further-information.njk
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Add two new radio options (one of which includes hint text and a hyperlink) into "A problem proving your identity" contact form.
in the contact form page, choose the option "A problem proving your identity" and submit the form.
"A problem proving your identity" form will appears and you will be able to see the 2 new options:
- "You had a problem with your bank or building society details"
- You had a problem with your National insurance number
You can read more about getting or finding your National Insurance number at [www.gov.uk/find-national-insurance-number](https://www.gov.uk/find-national-insurance-number)
Welsh version:
In the same page, add a new query parameter to your url: &lng=cy.
The text will appears in welsh.

AUT-2841 - add new radio button options into "A problem proving your identity" contact form

---

ci/terraform/waf.tf

The cloudfront cloudformation stack creates a WAF ACL that we can use for our ALB.
This PR makes the ALB use that stack.
Code review

INCIDENT-814: use waf acl created by cloudfront stack

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Add a non-breaking space between the words "sign" and "in".  This pr is a 1 to 1 copy of [this PR](https://github.com/govuk-one-login/authentication-frontend/pull/1564), that was reverted.
##Why
Fixes an issue raised by UCD where the word "in" had been appearing on a line alone following a recent content change. This has been fixed by introducing non-breaking space HTML entities to ensure the words in 'sign in' and 'One Login' do not split across lines as text wraps across different screen sizes.
1. Code Review

AUT-2729: Fix text wrapping issue on home page

---

ci/terraform/staging.tfvars
ci/terraform/variables.tf

Switch off the pre auth page in all environments
The change is already enabled in staging and has been tested there.
1. Code Review
https://github.com/govuk-one-login/authentication-smoke-tests/pull/559
https://github.com/govuk-one-login/authentication-frontend/pull/1657
https://github.com/govuk-one-login/authentication-frontend/pull/1643

AUT-2760: Switch off the pre auth page in all environments

---

src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/types.ts

Reverts govuk-one-login/authentication-frontend#1656
After a meeting (14/06/24 - 11.30am) with Christopher Sly (HGS - Digital Solutions), it seems his request was not the solution.
So now we have to revert this change.

Revert "AUT-2881: change identity document attribute"

---

.git-blame-ignore-revs
src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/setup-authenticator-app/index.njk
src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/locales/tests/locale.test.ts

A bug in Safari on iOS causes users to be prompted to 'Scan card' when specific input fields receive focus. Device testing has revealed this impacts only those fields containing the term 'security code'. It seems this is causing browser autocomplete heuristics to interpret the field purpose as being for a CVV code.
This PR:
* removes the term 'security code' from all form labels and introduces tests to ensure it is not reintroduced
* updates error messages to be consistent with the new labels
* introduces a change requested by UCD to combine an instruction with the associated form label (avoiding redundant messaging). 
The term "security code" has been removed from field labels and error messages in:
* The **set up an authenticator app** page
* The **check your phone** page presented …

AUT-2797: Remove terms that trigger iOS bug from labels

---

src/components/resend-mfa-code/index.njk
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
src/utils/phone-number.ts
test/unit/utils/phone-number.test.ts

Updates the "Get security code" screen to include the last 3 digits of the users mobile phone number when the user has reached this page having clicked "send the code again" during a sign in journey. 
<details>
<summary>Get security code (English)</summary>
</details>
<details>
<summary>Get security code (Welsh)</summary>
</details>
1. Code Review
1. Running frontend against this branch, confirm the page appears as expected (steps to reproduce are outlined in the Jira ticket)

AUT-1466: Show end of telephone number on MFA resend screen

---

src/components/resend-mfa-code/index.njk
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
src/utils/phone-number.ts
test/unit/utils/phone-number.test.ts

Reverts govuk-one-login/authentication-frontend#1672 to see if it may be related to the acceptance test failure 
> Expected condition failed: waiting for title to contain "You asked to resend the security code too many times". Current title: "Check your phone - GOV.UK One Login"

Revert "AUT-1466: Show end of telephone number on MFA resend screen"

---

.github/workflows/analyse-on-merge.yml
.github/workflows/pre-merge-checks.yml

Updates sonarcloud to point to latest version.
This resolves an issue where sonarcloud can update their image and run on our pipelines when we have not bumped the version.

BAU: Update sonarcloud version to point to latest version

---

package.json
src/components/contact-us/contact-us-questions-validation.ts

Into Contact forms, Sanitize free text value and add contact form submission rate limit.
- Add an xss filter on free text value from contact forms.
1/ Go to any contact form page, fill a free text field with some js code inside (ex: `<script>alert("test")</script>`) and be sure the form is not submitted and error message is here.

AUT-2776 contact us page spamming - Sanitize free text value into contact us forms

---

src/app.constants.ts
src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/index.njk
src/components/common/cookies/tests/cookies-controller.test.ts
src/config.ts

Restores the ability for users to change their previously selected cookie preferences via the cookies page.
This has been achieved by:
1. Removing the hidden attribute from the form
2. Updating the controller to remove those analytics cookies with known keys and the dynamic analytics cookies (while the prefix shown on the cookies page shows the prefix as `_gat_UA-[number]` I've found that a `_ga_[alphanumeric code]` cookie is set when GA4 is enabled, so I have extended the test to remove all dynamic cookies that start with `_ga`)
3. Introducing a function in `config.ts` to ensure the correct domain is used when we call `res.clearCookie`. This is to accommodate the difference between domains used for GA cookies between localhost (which uses "localhost") and all other environments (which …

INCIDEN-827 Restore cookie preferences form

---

.git-blame-ignore-revs
src/components/common/footer/accessibility-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

This PR updates the GOV.UK One Login Accessibility Statement (in 5f87297f30070f45fab4421e5010a97df90c83f0) to:
- describe issues related to the introduction of a third-party webchat tool
- separate these issues from those related to the broader GOV.UK One Login service
- introduce three new anchors, two of which are linked to from the statement itself and a third is for incoming links from
the webchat tool itself 
The PR also:
1. reformats the accessibility statement template (in https://github.com/govuk-one-login/authentication-frontend/pull/1679/commits/55fcf27b9b0df344e23cabfb10f297149e84498d) and excludes the commit from `git blame` (in https://github.com/govuk-one-login/authentication-frontend/pull/1679/commits/4e19bf50658b026fb9262606e7d7840eae369c58)
2. replaces positional section …

[Do not merge before go-live date] AUT-2682: Update Accessibility Statement for webchat

---

src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-email/tests/check-your-email-controller.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts

Prior to this commit, the call to the check email fraud block was imlemented in the enter-email-controller. This commit moves it over to the check-your-email-controller where it should be.
1. Code Review

AUT-2931: Move check email fraud block logic

---

ci/terraform/production.tfvars

Enables GA4 in production
1. Code Review
* https://github.com/govuk-one-login/authentication-frontend/pull/1671 - updated the environment variables
* https://github.com/govuk-one-login/authentication-frontend/pull/1633 set the GA4 and UA environment variables as initially requested
* https://github.com/govuk-one-login/authentication-frontend/pull/1522 introduced GA4

AUT-1784: Enable GA4 in production environment

---

src/locales/cy/translation.json
src/locales/en/translation.json

Updates the title presented to users on the Create password screen to specify that it is the GOV.UK One Login Terms of use that are being agreed to.
<details>
</details>
<details>
</details>

AUT-1484: Change "Terms of use" agreement title

---

.github/workflows/pre-merge-checks.yml

We have GitHub PR checks toat wait for SonarCloud reports, but they are not triggered for dependabot PRs.
- See the removal of the dependabot condition

BAU: Allow dependabot to trigger SonarCloud analysis

---

ci/terraform/ecs.tf

Removes duplication of `ANALYTICS_COOKIE_DOMAIN` within the ECS Task Definition, retaining the variant that makes use of the `var.analytics_cookie_domain` that exists specifically for the purpose of setting a common cookie domain (regardless of the specific subdomain that might be used).
SRE colleagues have explained that the duplicated name is forcing new deployments and reduced capacity as a consequence. 
1. Code Review
The newer variant was introduced in https://github.com/govuk-one-login/authentication-frontend/pull/1633

BAU: Remove duplicated name in ECS task definition

---

ci/terraform/production.tfvars

AUT-2924 Prod enable Service down page
Note : This PR Just deploy the Service Down Page  as Dormant for use , It **DOES NOT**  actually switch on the page
To Switch the Page We need to Follow a Manual Step to Temporarily shutter the Service documented on Team manual 
We have migrated service down page from concur pipeline to AWS code pipeline 
1. Code Review

AUT-2924: Prod enable Service down page

---

.github/workflows/test-sidecar.yml
ci/terraform/core.tf
ci/terraform/ecs.tf
ci/terraform/nonprod-common.tfvars
ci/terraform/sandpit.tfvars
scripts/dev_deploy_common.sh
test/basic-auth-sidecar/basic-auth-sidecar.test.ts

As we now have a cloudfront distribution in front of the ALB, we need to add the cloudfront node CIDRs to the list of trusted proxies in the sidecar container. This will allow the sidecar to correctly identify the client IP address via X-Forwarded-For headers.
With cloudfront, the sidecar sees the following header:
`X-Forwarded-For: client_ip, cloudfront_ip`, eg:
```
X-Forwarded-For: 1.2.3.4, 15.158.48.119
```
As 15.158.48.119 was previously not in the list of trusted proxies, nginx treated it as the client IP address (as it is the rightmost IP that's not a trusted proxy). This resulted in the sidecar requesting basic auth. Now these IPs are marked correctly, it will work as expected again.
This behaviour is as-per `real_ip_recursive on;`:
> If recursive search is enabled, the original …

AUT-1723: trust cloudfront cidrs in sidecar

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/deploy-frontend.yml
.gitignore

As-per https://ordinaryexperts.com/blog/2019/04/27/better-codepipeline-metadata
This extra metadata is shown in the codepipeline UI and will allow better identification of where the artifact has come from.
- Code review
- Deploy to dev from this branch (`./scripts/trigger-gha-current-branch.sh`) and confirm that the resulting pipeline run has the sensible metadata
Unfortunately the pr merge one is untestable without merging a pr. I guess 'trust me'?
- govuk-one-login/authentication-api#4851

BAU: add metadata that codepipeline understands

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/deploy-frontend.yml

AWS can't handle non-ascii characters in S3 metadata, so strip them out
- Code review

BAU: strip non-ascii characters from metadata

---

src/components/contact-us/questions/_sign_in_phone_number_issue.njk

- Add the field "What service were you trying to use?" to the ‘Another problem with a phone number screen’ to allow users to tell us what service they were trying to use when they are loading the contact form signin phone number issue
- Go to /contact-us-questions?theme=account_creation&subtheme=sign_in_phone_number_issue&referer=
- Check if new field is here
-  Valid the form and be sure you're landing on the good page

Aut-2325: Add "What service were you trying to use?" question into signin phone number issue contact form

---

basic-auth-sidecar/default.conf

Apparently, the order of the realip config is important. It seems that the trusted proxy config must come before the other directives.
Code review 👀

AUT-1723: Fix the order of the realip config

---

.github/dependabot.yml
.github/workflows/deploy-frontend.yml

Bit of a kitchen sink PR.
deploy-frontend had a `push` trigger. This made no sense because nothing happened on push, only when it was triggered by the completion of the build workflow.
I've removed this trigger
Also, we hadn't updated the actions for a while - node16 is deprecated, so i've bumped actions relating to it.
Also, dependabot will now inform us of action upgrades.
Code review

BAU: Improve deploy-frontend + upgrade action versions

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

Rather than managing dependencies twice, just use the local node_modules for pre-commit depdencies. This will require a `yarn install` before running it for the first time - This has been added to the `pre-commit.yml` workflow
Additionally, don't run pre-commit for dependabot PRs.
- Code review

BAU: Use eslint and prettier from node_modules

---

src/components/common/footer/privacy-statement.njk
src/components/create-password/index.njk
src/components/enter-email/index-create-account.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Updating the privacy notice (see AUT-3022)
- Moving the “Agree to the [GOV.UK](http://gov.uk/) One Login terms of use” message from the Create Password screen to the Enter your email address screen (see AUT-3023)
- 
- Start the create account journey and check if you have the  “Agree to the [GOV.UK](http://gov.uk/) One Login terms of use” message when you have to enter your email address.
- Continue the create journey until you have to enter a new password. Check if you don't have the  “Agree to the [GOV.UK](http://gov.uk/) One Login terms of use” message.
- Go to /privacy-notice and check if the paragraph is correctly updated (see AUT-3022)
**### AUT-3022 screenshots:**
**### AUT-3023 screenshots:**

AUT-3057: move privacy links into create your account journey step 1 and update Privacy notice paragraph

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Updates the privacy notice for updates to Dynatrace
To capture these screenshots within a single image it was necessary to remove the CSS that sets normal page and column widths. This was done in browser developer tools only. 
<details>
<summary>Privacy notice - English</summary>
</details>
<details>
<summary>Privacy notice - Welsh</summary>
</details>
Code Review
- https://github.com/govuk-one-login/authentication-frontend/pull/1784 Updates the cookies policy

AUT-2904: Privacy notice updates for Dynatrace

---

.git-blame-ignore-revs
src/app.constants.ts
src/assets/javascript/application.js
src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/index.njk
src/components/common/cookies/tests/cookies-controller-integration.test.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

This PR does three things:
1. Updates the GOV.UK One Login cookie policy to list cookies set by Dynatrace RUM
2. Adds these cookies to the array of cookie names to be cleared if a user opts out of cookies using the form shown on the cookie policy page
3. Introduces additional tests to reduce risk that measurement cookies are added to the privacy policy without being included in the list of cookies to be cleared when a user opts out using the form on the policy page.
<details>
<summary>Cookie policy - English</summary>
</details>
<details>
<summary>Cookie policy - Welsh</summary>
</details>
Code Review commit by commit.
- https://github.com/govuk-one-login/authentication-frontend/pull/1704 Updates the privacy policy

AUT-2997: Update cookie policy and functionality for Dynatrace RUM

---

yarn.lock

A clone of [a change Dependabot made but is failing to rebase](https://github.com/govuk-one-login/authentication-frontend/pull/1693). This deals with a ["ws affected by a DoS when handling a request with many HTTP headers"](https://github.com/govuk-one-login/authentication-frontend/security/dependabot/35) security vulnerability.
Bumps [ws](https://github.com/websockets/ws) from 8.14.2 to 8.17.1.
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](websockets/ws@8.14.2...8.17.1)
---
updated-dependencies:
- dependency-name: ws dependency-type: indirect ...
1. See changes match the Dependabot change https://github.com/govuk-one-login/authentication-frontend/pull/1693
https://github.com/govuk-one-login/authentication-frontend/pull/1693

Bump ws from 8.14.2 to 8.17.1

---

basic-auth-sidecar/default.conf
ci/terraform/core.tf
ci/terraform/ecs.tf
test/basic-auth-sidecar/basic-auth-sidecar.test.ts

Rather than trying to parse the X-Forwarded-For header, instead use the CloudFront-Viewer-Address header. This header is set by CloudFront and contains the IP address and source port of the viewer request, e.g. `203.0.113.1:12345`.
We will only trust this header if the request is coming from the ALB.
In theory, this would be injectable / bypassable if someone manages to make a request directly through the ALB, but as Cloudfront is applied to integration and the ALB's WAF requires cloudfront be the caller, so that's an unlikely occurrence. Plus, we're using Basic Auth with no real rate limit / brute force protection, so this whole sidecar is more of a polite 'please go away' anyway.
If my tests are correct, then this should be a case of "if the tests pass, we're good". Therefore, reviewing …

AUT-1723: use CloudFront-Viewer-Address header

---

.github/dependabot.yml
.github/workflows/dependabot-validate.yml
.pre-commit-config.yaml

- dependabot for docker in sidecar as well
- workflow to validate dependabot config file
- pre-commit hook to ensure that actions are pinned to SHAs, not tags
Code Review

BAU: Dependabot should also check sidecar docker

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars

Switch reauth off in build and integration.
- Off in build so that the configuration matches production.
- Off in integration as communicated to HMRC that reauth will not be available while changes are being made.
1. Code Review
https://github.com/govuk-one-login/authentication-acceptance-tests/pull/393

BAU: Switch reauth off in build and integration

---

src/app.ts
src/config.ts
src/utils/redis.ts
test/unit/utils/redis.test.ts

- Moved logic associated with getting redis config to redis.ts
- When getting redis config, we first look for environment variables, then look for parameters in SSM
- If environment variables are not found in DEV environment, default values for 'host' and 'port' are returned
- If environment variables are not found in PROD, we try to get parameters from SSM
The frontend currently uses SSM to retrieve the parameters for establishing a connection to elasticache (redis).  The frontend should be modified to look for these values in environment variables instead.  The environment variables will be obfuscated when viewed in the console so there is no security issue using them.
The change should be written is such a way that the frontend will fallback to using SSM if the environment variables …

AUT-3374: Use env vars and SSM to get redis config

---

ci/terraform/ecs.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf
scripts/_create_env_file.py
src/config.ts
src/utils/http.ts
test/unit/utils/http.test.ts

Add switch to enable http keepalive on axios.
There are potential performance gains from using http keepalive.  This needs to go through performance test to see if it makes a difference, so has been added behind a feature switch.
Feature to be proven as part of a performance test run in staging, so will only be enabled in the staging environment.
1. Code Review
2. Local running with the switch on and off to prove that axios calls are working.

AUT-3090: Add switch to enable http keepalive on axios, switch on in staging

---

src/components/prove-identity-callback/index-new-spinner.njk
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/prove-identity-callback-routes.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

This fixes the accessibility issue arising from automatic page refreshes by introducing a form that will instead allow the user to refresh the page when they are ready to do so. Bear in mind that this HTML-only version of the page will <mark>only be presented to those users who do not have access to client-side JavaScript</mark>: users with access to JavaScript will see the page as enhanced by the spinner.
For the time-being, this new form is behind a feature flag. 
Rather than creating a new controller method, it seemed sensible to repurpose the existing method to handle both `GET` and `POST` requests, but I'd be happy to introduce a new handler if the reviewer feels that would be best. 
<details>
</details>
<details>
</details>
1. Code …

AUT-3401: Replace auto refresh with HTML form

---

ci/terraform/integration.tfvars

The feature flag introduced in AUT-3390 should not have been enabled in the integration environment (see #1844 for the original PR). This PR turns off the feature flag.
Code review
* https://github.com/govuk-one-login/authentication-frontend/pull/1844 - Added the feature flag
* https://github.com/govuk-one-login/authentication-frontend/pull/1869 - Linked the feature flag to the presentation of the new page

BAU: Turn off new IPV spinner in integration

---

src/locales/cy/translation.json

Change button text on Welsh version of 'Create your GOV.UK One Login or sign in' page from 'Fewngofnodi' to 'Mewngofnodi'. 
For context, these both translate to 'log in'. 'Fewngofnodi' is appropriate for use in sentences but 'Mewngofnodi' must be used when it is used as a stand-alone label.
<details>
</details>
The smallest code review possible - one character has been changed.

AUT-3519: Fix translation issue on 'Create your GOV.UK One Login or sign in' page

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/build-deploy-frontend.yml
.github/workflows/call_build-push-docker-image.yml
.github/workflows/call_get_pr_data.yml
.pre-commit-config.yaml
Dockerfile
basic-auth-sidecar/Dockerfile
scripts/trigger-gha-current-branch.sh

- Move pr-data into reusable workflow
- pr-data now returns the output of `JSON.stringify`, not an object,
meaning that quotes will be automatically escaped in the output
- pull pr-data into the push job via `env`, meaning that single quotes
inside of the string will not allow shell escaping.
- Build docker image with `docker/build-push-action`. This means we get
a nice build summary on the action run. It also makes caching easier.
- Enable build caching, using a separate MUTABLE ecr repository. This
dramatically speeds up the build process, as we can avoid rebuilding
identical image layers, such as the initial `yarn install` in the
case that no dependencies have changed.
- Rework the Dockerfiles to be more cacheable: things that are less
likely to change should be above things that do …

BAU: improve frontend build and deployment

---

src/components/prove-identity-callback/index-new-spinner.njk

While reviewing the code, the Orchestration Tech lead asked how the JavaScript button would work in the completed state. This question revealed an issue with the existing static HTML structure because the button will rely on a containing form to perform the submit action.
This commit simply amends the HTML structure to move the spinner container into the form. There are no changes to the user interface. 
Code review. If it looks like there are a lot of changes, this is because the indentation has changed - a lot of this noise can be removed by switching to the "Hide whitespace" view. 
- https://github.com/govuk-one-login/authentication-frontend/pull/1869 introduced this form

AUT-3401: Move spinner container into form

---

src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts

Introduces a new condition into the `proveIdentityStatusCallbackGet` handler to reflect the `IdentityProcessingStatus.INTERVENTION` status having been returned. 
This is being introduced in response to feedback from the Orchestration Tech Lead following their review of the code earlier today.
Code review.
- https://github.com/govuk-one-login/authentication-frontend/pull/1867 introduced the route and handler this PR amends

AUT-3402: Add condition to reflect INTERVENTION status

---

src/locales/cy/translation.json
src/locales/en/translation.json

Adds scheme and subdomain to a link in translation files. This link is presented to users who encounter an error on the new spinner page. 
This has been made in response to feedback from the Orchestration Tech lead that "translations seem to be incorrect or missing in some places", linking to this line in the translation file (See comment in Jira ticket for AUT-3408). While making this change, I have checked that all translations referenced in `data-` attributes are present. The only issue I could see is this one.
Code Review
- https://github.com/govuk-one-login/authentication-frontend/pull/1869 - introduced these translation file entries along with the HTML-only version of the page
- https://github.com/govuk-one-login/authentication-frontend/pull/1925 -amended the structure of the HTML …

AUT-3401: Add scheme and subdomain to link href

---

src/components/reset-password/reset-password-routes.ts

Without this, a user was allowed to manually transition to these pages from an invalid state (e.g. their account was not found). This meant that they would end up hitting a backend error at some point, rather than this not being allowed in the first place.
Also added session middleware as it seems correct to be doing both of these checks
1. Code Review
1. Run the app locally
1. When signing in, enter an email that doesn't have an account associated with it, and see that you hit the account not found error
1. Manually change the url to /reset-password-request, or /reset-password-required
1. See that you are redirected back to /account not found, and do not hit any unexpected errors
1. Compare this behaviour against staging
1. Also try a normal reset password journey locally, and verify …

AUT-1555: Add journey to reset password routes

---

.github/workflows/deploy-frontend-sp.yml

- Use latest refactored devplatform-upload-action-ecr
- Pass in `oneagent_codemodules` build context
- Build sidecar and service-down page in parallel to speed up the
workflow
Run manually - ensure it runs!
🚨  https://github.com/govuk-one-login/devplatform-upload-action-ecr/pull/19 must be merged first, and the SHA updated to the new tag 🚨

BAU: Use refactored devplatform-upload-action-ecr

---

src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk

Previously, when either sms mfa or an auth app code were submitted incorrectly, the link to reset mfa would disappear - see screenshots below for visual example.
This is because when the template was first rendered (before an incorrect code was submitted), its value is a boolean. However, when we store the cached version (which gets used when the page reloads e.g. for a validation error) the value is a string.
This meant that on page relaod, the equality check (=== true) would return false, and the account recovery content would disappear.
I tried storing the cached value as a boolean rather than a string - e.g. changing
`<input type="hidden" name="isAccountRecoveryPermitted" value="{{isAccountRecoveryPermitted}}"/>`
to
`<input type="hidden" name="isAccountRecoveryPermitted" …

AUT-3052: Fix disappearing links

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/index.njk

This PR removes the back button when the session journey type == REAUTHENTICATION. 
1. Code Review
2. Deploy to sandpit and run through a sign in journey. See that the back button **_IS_** present on enter password screen when going through this step. Copy and paste ID token at end of journey.
3. Go through reauthentication journey, following the guidance [here](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4317446229/How+to+trigger+reauthentication).  See that back button **_IS NOT_** present on enter password screen when going through this journey.
The following screenshot is the enter password screen on the initial SIGN IN part of the journey:
The following screenshot is the enter password screen in the REAUTHENTICATION journey:

AUT-3499: Remove back button from reauth password screen

---

.git-blame-ignore-revs
package.json
src/assets/scss/application.scss
src/assets/scss/prove-identity-callback/spinner.scss
src/components/prove-identity-callback/index-new-spinner.njk
yarn.lock

Adds JavaScript and Sass to enable the new spinner. This includes: 
Once merged the spinner page will be enabled in environments where the feature flag is enabled, allowing for testing in `staging`.
Code Review commit-by-commit. Two commits are prefixed with "BAU" because they relate to a formatting change.
* https://github.com/govuk-one-login/authentication-frontend/pull/1904
* https://github.com/govuk-one-login/authentication-frontend/pull/1869
* https://github.com/govuk-one-login/authentication-frontend/pull/1844

AUT-3407: Add spinner dependency

---

shutdown.sh

Changed 'docker-compose' to 'docker compose' in the shutdown.sh script as 'docker-compose' has been depracated:
"GitHub deprecated v1, and you need to change the command from, e.g., docker-compose build to docker compose build (remove the dash)" - mentioned [here](https://github.com/orgs/community/discussions/116610)
1. Code Review

BAU: Fix shutdown script

---

src/components/prove-identity-callback/index-new-spinner.njk
src/components/prove-identity-callback/prove-identity-callback-controller.ts

Testing in staging environment has revealed that the service name is shown as 'undefined'. This PR:
1. updates the controller to pass the `serviceName` variable through to the template
2. creates a separate block for `serviceName` to be rendered (rather than relying on Nunjucks to do the concatenation).
Code Review

FIX: Pass serviceName to spinner template

---

src/components/authorize/kms-decryption-service.ts
yarn.lock

Bumps the aws sdk client kms library from 3.370.0 to 3.635.0. 
Recreates [this dependabot PR](https://github.com/govuk-one-login/authentication-frontend/pull/1973) which was getting a bit faffy to rebase
This required using a typed EncryptionAlgorithmSpec, rather than a string, since on a previous version of the library it accepted a union type of EncryptionAlgorithmSpec or string, but now we need an EncryptionAlgorithmSpec
Code review

BAU: bump aws sdk client kms library

---

src/config/helmet.ts

We've been notified of a CSP violation in production that's causing the browser to refuse to connect to a domain for Google Analytics - the blocked domain is https://region1.google-analytics.com
The [Google Developers site](https://developers.google.com/tag-platform/security/guides/csp) lists directives required for GA4 and Universal Analytics (both GA and UA are currently in use in the authentication frontend).
These directives are required to use GA4
```
script-src:  https://*.googletagmanager.com
img-src:     https://*.google-analytics.com https://*.googletagmanager.com
connect-src: https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com
```
Additional directives are required for Universal Analytics:
```
script-src: …
```

AUT-3617: Fix CSP violation related to analytics

---

package.json
src/app.ts
src/config/helmet.ts
yarn.lock

* Upgrades `helmet` to version 7.1.0 proposed by dependabot in #1716 
* Upgrades `typescript` and `ts-node` to version required by this version of Helmet
* Updates `package.json` to reflect Node version required for this version of TypeScript
* Removes deprecated Certificate Transparency from Helmet config
* Refactors Helmet config with a view to making it a bit clearer
I've popped some context in the relevant [commit message](a07abe46006f02273576bf7f9f46371809bdc4a1) about this change.
A more detailed description is that [Certificate Transparency (CT)](https://developer.mozilla.org/en-US/docs/Web/Security/Certificate_Transparency) is a
> ... protocol for publicly logging the existence of Transport Layer Security (TLS) server certificates as they are issued or observed, in a manner that …

BAU: Helmet dependency upgrade

---

src/app.ts
src/components/account-creation/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
src/components/account-recovery/check-your-email-security-codes/tests/check-your-email-security-codes-integration.test.ts
src/components/check-your-email/tests/check-your-email-integration.test.ts
src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/create-password/tests/create-password-integration.test.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts
src/components/enter-email/tests/enter-email-create-account-integration.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/enter-password/tests/enter-password-reauth-integration.test.ts
src/components/enter-password/tests/enter-password-support-2fa-before-password-reset-integration.test.ts
src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts
src/components/resend-email-code/tests/resend-email-code-integration.test.ts
src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
src/components/reset-password/tests/reset-password-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-forced-2fa-before-integration.test.ts
src/components/reset-password/tests/reset-password-integration.test.ts
src/components/select-mfa-options/tests/select-mfa-options-integration.test.ts
src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts
src/components/updated-terms-conditions/tests/updated-terms-conditions-integration.test.ts
src/handlers/csrf-missing-handler.ts
src/handlers/tests/csrf-missing-handler.test.ts
test/unit/error-handler.test.ts

Currently, we return a server error in the case of a missing csrf token, as we do not have any specific handling for this case. When we get spam requests, this means we end up return 5xxs and flagging errors.
Adding middleware to handle this case means that we will return 403s, rather than 500s. This solution is in line with the suggestion from csurf: https://www.expressjs.com.cn/resources/middleware/csurf.html
1. Code Review
1. Run the app locally, and make a random POST request to it. See that you get a 4xx, not a 5xx.

AUT-2914: Add middleware for handling missing or invalid csrf tokens

---

src/components/common/cookies/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Add browser session id cookie on cookie policy page. 
We have created a new cookie to track the browser session of users. The new cookie implemented is due to needing a way of making sure users are logged out when the browser is closed.

ATO-965: update cookie page with browser session id

---

src/components/authorize/authorize-controller.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/authorize/types.ts

This ensures that a user who has exceeded the max tries for credential entry on reauth cannot start a new reauth journey - if the start response indicates that a user has any blocks, they will be logged out rather than allowed to proceed with a reauth journey
1. Code Review
1. Deploy to authdev1 with the relevant backend (main) deployed
1. Open two different browsers. Log in in both
1. Start a reauth journey in one. Enter the wrong email or the wrong password to the point where you're logged out
1. Start a reauth journey in your other browser. Note that you are immediately logged out
## Related PRs:
Backend PR that started returning this information from the start response: https://github.com/govuk-one-login/authentication-api/pull/5152

AUT-3613: Log a reauth user out if they are blocked for reauth

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-reauth-integration.test.ts

If, on entering a password in a reauth journey, the backend responds with an error code indicating that any reauth count (enter email, enter password or enter mfa) has been exceeded, we want to log someone out. 
Previously, we would have only logged someone out if they had exceeded the password count at this point. However, we want to cover off a case where users are doing multiple concurrent reauthentication journeys. If they get logged out for whatever reason in one reauth journey, they should be logged out at the next possible point in the other.
This change means responding to a new error code in the enter password controller.
Also contains a small bit of refactoring.
1. Code Review
[This PR](https://github.com/govuk-one-login/authentication-api/pull/5180) in the backend starts doing …

Aut 3613/logout on max credentials enter password

---

src/components/account-creation/resend-mfa-code/index.njk
src/components/resend-email-code/index.njk
src/components/reset-password-check-email/index-reset-password-resend-code.njk

399095bbce10ab1421621e31ce76b79659b60b70 introduced a split in the string that warns the user if they request more than 5 security codes they will be locked out for 2 hours. There are certain other template pages that warn of the same, but the split string was not concatenated, meaning the pages would only show the first half of the sentence.
This adds the last half of the sentence back where it is missing.
1. Code Review, compare to the string before the split in 399095bbce10ab1421621e31ce76b79659b60b70
https://github.com/govuk-one-login/authentication-frontend/pull/1860

AUT-3686: Fix broken sentence for 2hr lockout warning

---

package.json
src/app.ts
src/config/helmet.ts
yarn.lock

This PR does three things, all of which are required to meet a dependency bump for `helmet` that was initially proposed by dependabot (see https://github.com/govuk-one-login/authentication-frontend/pull/1716):
1. Updates the TypeScript version to that required by Helmet, and updates Node engine to that required by this TypeScript version (See commit message for f4e495d362293231ae02a4d5fefe95a18214e5a2)
2. Updates the Helmet dependency, refactors the Helmet config and removes a deprecated option (See commit  message for c4f16b820983a1c4af1b53861b0ec7889952fc4d)
3. Overrides one of the new default CSP directives set by Helmet because this was causing our acceptance tests to fail (See commit message for ab4e31d982938d9a58aa689a3b483cd755c0edb3)
The upgrade to `helmet` will add these new …

BAU: Helmet dependency upgrade with default override

---

src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts

On mfa entry (auth app or sms) in the reauth journey, we want to log someone out if the response from the backend indicates that they have exceeded any reauth credential entry counts. This is to handle edge cases around multiple reauth journeys taking place for a single user at once.
This won't currently affect behaviour, as we'll need to make a change to the backend to start sending these error responses at these points.
Also contains some test refactors.
1. Code Review commit by commit

Aut 3530/logout on failed counts mfa

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/types.ts
src/utils/http.ts

`previousSessionId` will be added as a claim in authorize request to Authentication (see 3 below).
This is required in order to break session dependencies between Authentication and Orchestration. When Auth has its own session store (see 2 below), the hash key for the session will be `sessionId`. When `sessionId` gets updated, the record will need to be recreated, and in order to do this, Auth need `previousSessionId` in order to map the previous session ID to the new one (which will be extracted from the gs cookie).
Originally `previousSessionId` was added as a header in the GET request to /start. This has since been changed due to [this comment](https://github.com/govuk-one-login/authentication-api/pull/5154#discussion_r1738887805), but is still present in the commit history.
Request to …

ATO-984 (2/5): Pass `previousSessionId` to StartHandler in POST request

---

src/locales/cy/translation.json
src/locales/en/translation.json

Content updates to re-auth email address screen. 
<details>
</details>
<details>
</details>
1. Code review
https://github.com/govuk-one-login/authentication-acceptance-tests/pull/419 updates the acceptance tests to reflect this change

AUT-3685: Update re-auth email address screen

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/types.ts

Adds two extra reauth fields to the request body sent to the start handler:
* rp pairwise id for reauthentication
* previous govuk signin journey id
This is so that the start handler can use this information when it emits the "AUTH_REAUTH_REQUESTED" audit event, in the case of a reauth journey.
The previous govuk signin journey id has recently been added to the claims orchestration send through to us, to facilitate this.
1. Code Review
[PR](https://github.com/govuk-one-login/authentication-api/pull/5228) that introduced reading these request params in and using them in the audit event in the start handler
[Orchestration PR](https://github.com/govuk-one-login/authentication-api/pull/5223) that started passing the previous signin journey id through to us as a claim

Aut 3596/add extra info to start call

---

package.json
yarn.lock

Upgrade express to 4.20.0.
In order to keep our express version current.
Tested locally.
1. Code Review
1. Deploy to a sandpit with `./deploy-sandpit.sh -a` for testing or run locally.

BAU: Upgrade express to 4.20.0

---

package.json
yarn.lock

Upgrade dompurify to 2.5.4.
To keep dompurify current.
Tested in a local environment.
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -a` or test locally.

BAU: Upgrade dompurify to 2.5.4

---

src/components/auth-code/auth-code-service.ts
src/components/auth-code/tests/auth-code-service.test.ts

This will control whether or not the auth code handler emits the "reauth success" event is emitted in the backend when a user reaches the point of the authentication auth code handler.
1. Code Review
[Backend PR](https://github.com/govuk-one-login/authentication-api/pull/5242) that adds this extra param to the auth code request and responds to it by emitting the relevant audit event.
Plan is to merge that PR first, and then this one.

AUT-3601: Add is reauth journey to auth code request

---

src/components/account-intervention/password-reset-required/index.njk
src/components/account-intervention/permanently-blocked/index.njk
src/components/account-intervention/temporarily-blocked/index.njk
src/components/common/cookies/index.njk
src/components/contact-us/questions/index.njk

Adds the OPL script to the pages:
- Temporarily Blocked
- Contact Us/Questions
- Cookies
This will need to be tested using the Google Tag Assistant extension

[DFC-653] - Add missing OPL script to required pages

---

src/assets/scss/application.scss

The CSS Working Group has changed the way CSS handles declarations mixed with nested rules. Sass has been updated to reflect this change and any declarations that appear after nested rules are deprecated in Dart Sass distributions > 1.77.7 (See [Sass documentation](https://sass-lang.com/documentation/breaking-changes/mixed-decls/))
As a result of this we have been seeing multiple deprecation warnings when compiling our Sass. 
> _Deprecation Warning: Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version_
This commit simply changes the code in a block that is specific to the password entry component so that a nested rule appears after declarations in the same block.
<details>
<summary>Screenshot after …

BAU: Prevent Sass mixed declaration warnings

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
scripts/_create_env_file.py
src/app.constants.ts
src/components/authorize/authorize-controller.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-controller.test.ts
src/config.ts
src/types.ts

Read 'channel' claim if SUPPORT_MULTI_CHANNEL is switched-on and assign to session variable.
- Adds a feature switch SUPPORT_MULTI_CHANNEL
- Adds a configurable default channel DEFAULT_CHANNEL, which defaults to 'web'.
This is to support rendering the UI differently per channel.  The Strategic App will run the authentication sign-in flow in a webview, which needs to be rendered differently.  The session variable can be used to determine how to render the UI.
There are two config values because the orchestration and orchestration stub changes are not yet available to supply the new claim to authentication, but the code is there to support this when it arrives.  In the meantime developers can vary the DEFAULT_CHANNEL in order to test rendering for both channels.  
1. Code Review
1. Set …

DFC-663: Read 'channel' claim if SUPPORT_MULTI_CHANNEL is switched-on

---

src/app.ts
src/middleware/channel-middleware.ts
src/middleware/tests/channel-middleware.test.ts

Adds a new middleware to expose the active channel to nunjucks components. This is a continuation of the work found in https://github.com/govuk-one-login/authentication-frontend/pull/2080
1. Code Review
2. Confirm the middleware correctly exposes the channel value to nunjucks templates

feat(DFC-663): Add Channel Middleware

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/authorize/authorize-controller.ts
src/components/authorize/claims-config.ts
src/components/authorize/jwt-service.ts
src/components/authorize/tests/jwt-service.test.ts
src/config.ts

In the build environment we want to be able to invoke the frontend using either real orchestration or the orchestration stub. To achieve this, this change allows the frontend to accept authorise requests from two different sources.

AUT-3763: Add support for Orch stub in addition to real Orch

---

.pre-commit-config.yaml

On some systems the correct node version to use for pre-commit work is not automatically selected, even when it is apparently the default on the developer terminal.
Here we explicitly pin the correct version.
1. Code Review

BAU: Pin node version in pre-commit config

---

src/components/account-creation/resend-mfa-code/tests/__snapshots__/resend-mfa-code-integration.test.ts.snap
src/components/authorize/tests/__snapshots__/authorize-integration.test.ts.snap
src/components/check-your-email/tests/__snapshots__/check-your-email-integration.test.ts.snap
src/components/check-your-phone/tests/__snapshots__/check-your-phone-integration.test.ts.snap
src/components/create-password/tests/__snapshots__/create-password-integration.test.ts.snap
src/components/enter-authenticator-app-code/tests/__snapshots__/enter-authenticator-app-code-integration.test.ts.snap
src/components/enter-email/tests/__snapshots__/enter-email-integration.test.ts.snap
src/components/enter-mfa/tests/__snapshots__/enter-mfa-integration.test.ts.snap
src/components/enter-password/tests/__snapshots__/enter-password-integration.test.ts.snap
src/components/enter-password/tests/__snapshots__/enter-password-reauth-integration.test.ts.snap
src/components/enter-phone-number/tests/__snapshots__/enter-phone-number-integration.test.ts.snap
src/components/prove-identity/tests/__snapshots__/prove-identity-integration.test.ts.snap
src/components/resend-email-code/tests/__snapshots__/resend-email-code-integration.test.ts.snap
src/components/resend-mfa-code/tests/__snapshots__/resend-mfa-code-integration.test.ts.snap
src/components/reset-password-2fa-auth-app/tests/__snapshots__/reset-password-2fa-auth-app-integration.test.ts.snap
src/components/reset-password-check-email/tests/__snapshots__/reset-password-check-email-auth-app-2fa-integration.test.ts.snap
src/components/reset-password-check-email/tests/__snapshots__/reset-password-check-email-integration.test.ts.snap
src/components/reset-password/tests/__snapshots__/reset-password-integration.test.ts.snap
src/components/reset-password/tests/__snapshots__/reset-password-required-integration.test.ts.snap
src/components/select-mfa-options/tests/__snapshots__/select-mfa-options-integration.test.ts.snap
src/components/setup-authenticator-app/tests/__snapshots__/setup-authenticator-app-integration.test.ts.snap
test/helpers/expect-taxonomy-helpers.ts

fe8dba081ad1f14a6eabb1b81a2559c1132a3fd7 introduced a regex that finds GA4 taxonomy levels values in our integration test generated HTML.
This was too restrictive and missed out values with spaces in them. So this adds `\s` as an expected regex character class inside the quotes. Also add `\d` to capture digits for good measure.
1. Code Review
- The important change is in `test/helpers/expect-taxonomy-helpers.ts`. 
- The rest of the commit fixes the snapshots.
https://github.com/govuk-one-login/authentication-frontend/pull/2121

AUT-3760: Broaden taxonomy match regex

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/dev.tfvars
ci/terraform/security-groups.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf

security group rules added: allow connection from new auth to frontend Redis 
Issue: [AUT-3768]
[AUT-3768]: https://govukverify.atlassian.net/browse/AUT-3768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 AUT-3768 - Redis security group allow connection from new auth frontend

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/authorize/tests/authorize-integration.test.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/jwt-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

- As [part of previous work](https://github.com/govuk-one-login/authentication-api/pull/5310/files), Orchestration now pass the `authenticated` claim to Auth as part of the `/authorize` request. We now need to pass this further to the backend so it can be stored in the new session store
- This PR pulls this claim out of the JAR and adds it to the body of the of the POST request to the start handler
- There are also some BAU commits which do some light refactoring in places:
- Renames a test helper to use camel case
- Updates the test helper return type to reflect more accurately the claims passed from Orchestration to Auth
- Updates the authorize service interface for start to cut down on the number of method arguments, moving these into 
an object.  
- Code review commit-by-commit
- …

ATO-980: Send `authenticated` claim to backend

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/dev.tfvars
ci/terraform/kms.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf

The auth encryption key policy allows cross account decrypt permission.
- Default implict kms key policy is overwritten with an explicit policy, with identical permission for root account
- dynamic statement to add another statement to give `kms:Decrypt*` to new_auth_account_id root

AUT-3772 - auth encryption key policy allows cross account decrypt permission

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/dev.tfvars
ci/terraform/staging.tfvars

Double quoted aws account ids for `new_auth_account_id`
One of the account id starts with 0, double quote ensures terraform won't confuse this as an octal number

AUT-3772: Leading 0 in aws account id, double quoted

---

cloudformation/deploy/template.yaml

Basic auth rework on image URI and task definition:
- IP_ALLOW_LIST retrieved from Secrets manager, required and no default values set. 
- The sidecar image URI in EnvironmentConfiguration. 
- Sidecar is configured to deploy in dev (for testing purposes) and integration (live) environments. 
Issue: [AUT-3544]
Start a user journey from orchstub. If logged into GDS vpn, the redirect to frontend will not prompt for basic auth login credentials. For any other ip address, it will prompt

AUT-3544: Basic auth rework on image URI and task definition

---

cloudformation/deploy/template.yaml

Removed DesiredCount from the ECS service definition
Based on recommendation https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3410329629/ECS+AutoScaling+Services
Issue: [AUT-3546]
Run perf tests in staging, and concurrently run a deployment

AUT-3546: Removed DesiredCount from the ECS service definition

---

ci/terraform/integration.tfvars

Integration env cross-account redis sg group rules and auth kms share
Issue: [AUT-3544]
Env specific change for integration. Similar changes applied to lower envs recently, for [AUT-3768] and [AUT-3772]
[AUT-3768]: https://govukverify.atlassian.net/browse/AUT-3768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-3772]: https://govukverify.atlassian.net/browse/AUT-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3544 Integration env cross-account redis sg group rules and auth kms share

---

ci/terraform/variables.tf
cloudformation/deploy/template.yaml

Increasing the deregistration delay timeout of Target group from 30sec to 90sec so this is Greater than the Idle timeout on ALB (which is 60 sec)
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -a`
3. Check the Frontend Target group delay registration is changing from 30sec to 90sec

AUT-3757: Increasing target group deregistration delay

---

cloudformation/deploy/template.yaml

Phase 1 - deploy components while ECS service remains in control of deployment
Issue: [AUT-3494], [AUT-3546]
[AUT-3494]: https://govukverify.atlassian.net/browse/AUT-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Phase 1 PR to enable Canary deployments in SP staging

---

cloudformation/deploy/template.yaml

Phase 2 - Control of deployment shifts from ECS Service to CodeDeploy
Issue: [AUT-3494], [AUT-3546]
[AUT-3494]: https://govukverify.atlassian.net/browse/AUT-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Phase 2 PR Control of deployment shifts from ECS Service to CodeDeploy

---

cloudformation/deploy/template.yaml

Phase 2 - Control of deployment shifts from ECS Service to CodeDeploy
Issue: [AUT-3546]

Phase 2 Canary - Deployment control shifts from ECS Service to CodeDeploy

---

package.json
src/server.ts
yarn.lock

Add `vital-signs` package to get observability stats logged. For the most part we use default settings, except for static paths which are explicitally set for our `/assets/**/*` and `/public/**/*` paths.
This will enable us to see stats like event loop delay & utilization, average response time, max concurrent connections and requests per second in our logs.
The defaults at the time of commiting have it log every 10 seconds and log level at "info" with all available metrics.
Code review.
Note that this has been deployed to our dev environment and manually smoke tested to ensure it's not fundamentally broken our application.
Logs were also seen in CloudWatch, e.g. 
```
{
"level": 30,
"time": 1729076995468,
"pid": 28,
"hostname": "[REDACTED].compute.internal",
"name": …
```

AUT-3753: Implement `vital-signs` package

---

src/app.ts
src/components/healthcheck/healthcheck-controller.ts

Prior to this PR, the healthCheckRouter was being processed by express after other more resource-intensive middlewares. This meant that if the health check were to fail, resources had already been wasted on invoking resource-intensive middlewares like the session middleware. This commit resolves this by moving healthCheckRouter invocations before other middlewares.
This PR also adds logging when handling the health check, in line with guidance given [here](https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md#too-many-connections) under the heading 'HealthChecks'
1. Code Review

AUT-3755: Move health check router

---

cloudformation/deploy/template.yaml

Enable ECS canary in integration env frontend.
This is the phase2 change as per the [migration guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance) that removes LoadBalancers, NetworkConfiguration, TaskDefinition from ECS Service
Issue: [AUT-3544]

AUT-3544 - Enable ECS canary in integration env frontend

---

yarn.lock

Reverts govuk-one-login/authentication-frontend#2157 seeing small number of errors in production.

Revert "BAU: Bump express from 4.21.0 to 4.21.1"

---

src/components/common/layout/base.njk
src/components/common/layout/tests/base-integration.test.ts

Implemented conditional rendering of the beta banner in the base.njk file to ensure it is only visible in web view. Also, added integration tests to verify the functionality.
1. Code Review
2. Set DEFAULT_CHANNEL in a local frontend .env file to either 'web' or 'strategic_app' and start the application.
3. Verify if the beta banner correctly shows or hides based on the selected view.
[DFC-661](https://govukverify.atlassian.net/browse/DFC-661)
[DFC-661]: https://govukverify.atlassian.net/browse/DFC-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DFC-661]: Remove the Beta Banner from Strategic App view

---

cloudformation/deploy/template.yaml

Use transitional `-sp` domain for orch stub to auth audience
Issue: [AUT-3809]
[AUT-3809]: https://govukverify.atlassian.net/browse/AUT-3809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3809: Use transitional domain for orch stub to auth audience

---

src/assets/scss/application.scss
src/components/common/layout/base.njk
src/components/common/layout/tests/base-integration.test.ts

Implemented conditional rendering of the footer in the base.njk file to ensure it is only visible in web view. Also, added integration tests to verify the functionality.
1. Code Review
2. Set DEFAULT_CHANNEL in a local frontend .env file to either 'web' or 'strategic_app' and start the application.
3. Verify if the footer correctly shows or hides based on the selected view.## Checklist
[DFC-660](https://govukverify.atlassian.net/browse/DFC-660)
[DFC-660]: https://govukverify.atlassian.net/browse/DFC-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DFC-660 Remove footer from strategic app journey

---

.github/dependabot.yml

As patch bumps are the least likely to impact our use of a dependency, they should be a relatively safe initial grouping to attempt to lower the number of dependabot PRs we need to rebase/review/merge.
The current problem is we get daily PRs for patch bumps, and they end up being out of date with the `main` as a previous dependabot PR merges. This means it's currently a lengthy process of:
- Dep A: approve
- Dep B: approve
- Dep C: approve
- Dep A: merged
- Dep B: out of date
- Dep C: out of date
- Dep B: rebase
- Dep C: rebase
- Dep B: approve
- Dep B: merged
- Dep C: out of date
- Dep C: rebase
- Dep C: approve
- Dep C: merged
As these dependency groupings are closely related and interdependent this groups their dependabot update PRs for all semver bumps.
1. Code Review

BAU: Group some npm dependabot updates

---

ci/terraform/production.tfvars

Production env cross-account redis sg group rules and auth kms share
Issue: [AUT-3545]
Env specific change for production. Similar changes were made in integration recently [AUT-3544]

AUT-3545: Prod X-account redis sg group and auth kms share

---

src/app.ts
src/config/session.ts
src/server.ts
test/unit/app.test.ts
test/unit/session.test.ts

Before adding graceful shutdown, make the existing start server logic testable and add tests to assert the server starts on the expected port, with the expected timeouts and with the vital-signs package.
The redis client can be disconnected, but in order to do so the client needs to be available outside of the method that creates it.
A new `disconnectRedisClient()` method is added that will disconnect the client if there is a client set.
New calls to `getSessionStore` will reuse an existing redis client so long as the redisConfig matches. Otherwise an error is thrown.
This new `closeServer()` method will disconnect the redis client and stop vital-signs logging before shutting down the HTTP server.
Should the process receive a signal indicating it should shutdown, the `closeServer()` …

AUT-3762: Add graceful shutdown

---

cloudformation/cloudfront-waf/template.yaml
cloudformation/deploy/template.yaml
cloudformation/domains/template.yaml

1. New prod env transitional domains, certs and SSM params
2. Nginx sidecar temporarily deployed in prod to block public access
3. Disable CSLS log forwarding from WAF deployed to us-east-1
Issue: [AUT-3545]

AUT-3545 - New prod environment transitional '-sp' domains and basic auth sidecar

---

cloudformation/deploy/template.yaml

Added missing basic auth sidecar image URI in prod env mapping
Sidecar is temporarily deployed in prod to block public access
Issue: [AUT-3545]

AUT-3545: basic auth sidecar image URI in prod env mapping

---

.github/dependabot.yml

As they are closely related and previous attempts to upgrade required both `pino` and `pino-http` to be upgraded at the same time.
This should help organise these PRs a bit more.
1. Code Review

BAU: Grouping pino dependabot PRs

---

cloudformation/deploy/template.yaml

Enable ECS canary in prod (step 2). This change shifts control of deployment from ECS Service to CodeDeploy.
Issue: [AUT-3545], [AUT-3494]
[AUT-3494]: https://govukverify.atlassian.net/browse/AUT-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3545: enable ECS canary in prod (step 2)

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

##What
Take the `currentCredentialStrength` from the authorise request and pass it on to the start handler so it can be set in the auth session. The `currentCredentialStrength` might not exist in the authorise request and therefore wont pass the field through to the start handler.

Ato 975/send current credential strength claim to backed

---

src/locales/cy/translation.json
src/locales/en/translation.json

The personal data retention period is extending from 3 to 5 years. This PR updates the privacy notice to reflect this. There is a separate task to ensure users are prompted to accept the change. 
<details>
</details>
<details>
</details>
1. Code Review - it's a very small change to the translation files.

AUT-3828: Update privacy notice to reflect new retention period

---

yarn.lock

This caused problems when running locally - reverting to unblock that

BAU: Revert bump to cookie library

---

Dockerfile
docker-entrypoint.sh

Rather than running Node.js directly as PID 1, we use tini to ensure
that signals are properly forwarded to the app process.
Additionally, move the `yarn start` command to a separate script for
visibility. This part is not strictly necessary, but it makes me happier
to not have raw shell commands within the Dockerfile.
1. Ensure the container still builds locally:
```sh
docker build . --build-context oneagent_codemodules="$(mktemp -d)" -t  auth-frontend:aut-3756
```
1. Deploy to the `dev` environment, check it still runs and exits correctly.

AUT-3756: Use tini as PID 1

---

src/components/common/cookies/tests/cookies-controller-integration.test.ts

The test itself is very basic, just testing that we can successfully make a request to the post endpoint (without testing any of the expected functionality, which is already tested and much easier to test in the unit tests). This, among other breaking changes, prevents breaking updates to the cookies library. This has recently been seen in express dependency bumps, which bumps the cookie library to 0.7.x, which contains extra regex validation of the cookie values, which we don't currently meet as we use double quotes in the value.
This should prevent re-occurences of the incident that was caused by this cookie library bump.
For example:
1. Code Review
1. While on this branch, bump a dependency locally such that cookies is updated to 0.7.x (for example, by bumping express to 0.4.21 as done …

BAU: Add integration test for cookies post

---

.github/dependabot.yml

This pattern should still allow node version updates of v20 minor and patch versions, but v21 would be ignored etc.
This covers both Node and Docker ecosystems.
Doing this because our current configuration allows PRs for non-LTS Docker Node versions to be raised: https://github.com/govuk-one-login/authentication-frontend/pull/2248
1. Code Review

BAU: Dependabot ignore node versions more than v20.x.x

---

.github/dependabot.yml

Stop dependabot from PRing @types/node over v20.
We use LTS 20, so should not be suggesting types over that, like this PR: https://github.com/govuk-one-login/authentication-frontend/pull/2278

BAU: Stop dependabot from PRing @types/node over v20

---

package.json
yarn.lock

Setting 20.17.x will match node 20.17.0 we use. Only the major and minor number have to match. The patch number is for use by the type library.
1. Code Review

BAU: Set @types/node version to match node version in use

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
package.json
scripts/_create_env_file.py
src/components/common/layout/base.njk
src/config.ts
src/middleware/analytics-middleware.ts
yarn.lock

Updates `@govuk-one-login/frontend-analytics` from `2.0.1` to `3.0.1`
1. Code Review
This PR makes the upgrade proposed by Dependabot in https://github.com/govuk-one-login/authentication-frontend/pull/2093

BAU: Upgrade GOV.UK Frontend Analytics package to v3

---

.github/dependabot.yml

Work on #2235 revealed this version of the package does not include the CSS that's required. FEC are working on fixing this for a future release. This just ensures Dependabot doesn't try to get us to upgrade to this version
1. Code Review
#2235

BAU: Dependabot to ignore language toggle v 2.0.1

---

.github/dependabot.yml

There are two `@typescript-eslint/*` packages we use that should have the same version number when bumped.
This change will mean dependabot PRs are raised for these together, reducing the maintenance workload.
1. Code Review

BAU: Add `@typescript-eslint/*` dependabot groups

---

src/components/account-created/index.njk
src/components/sign-in-or-create/index.njk

- Add data nav and data link attribute to submit buttons to configure navigation tracking
- For the `/account-created` page, it has been confirmed by both Auth (Gwyn Jones) and Orch ( Ethan Mills) that finding out the url of the page which the user is navigated to it is not possible and so in this instance we will be returning `undefined` .
For reasonings from Auth as to why, click [here](https://govukverify.atlassian.net/browse/DAC-3581?focusedCommentId=180370)

[DAC-3581] - Navigation Tracker Not Firing on /sign-in-create and /account-created pages

---

cloudformation/deploy/template.yaml

SSM parameters for transitional DNS addresses get -sp suffix

AUT-3690: SSM parameters for transitional DNS addresses get -sp suffix

---

ci/terraform/dev.tfvars
ci/terraform/ecs.tf
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
src/app.constants.ts
src/app.ts
src/components/common/state-machine/state-machine.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/index.njk
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/components/mfa-reset-with-ipv/mfa-reset-authorize-service.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-routes.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-authorize-service.test.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts
src/components/mfa-reset-with-ipv/types.ts
src/config.ts

Created a service to call the MfaResetAuthorizeHandler API in the backend. If the request is successful, the API returns a URL to redirect the user to IPV Core's prove identity journey. This service is called when the user clicks the "change how you get security codes" link on the enter mfa pages.
1. Code review
2. Deploy this PR and relate auth API PR to dev environment
3. See that the JWT does a thing
https://github.com/govuk-one-login/authentication-api/pull/5535

AUT-3823: Implement call to MFA reset authorize API to redirect to IPV Core

---

src/app.constants.ts
src/app.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts

Adds a very basic controller and route, in the case that the mfa reset with IPV feature flag is on, that responds to a callback from the authorize endpoint in IPV, and for now just responds with a basic success status. This is to enable step by step implementation, so that we can see the callback successfully working.
1. Code Review

AUT-3834: add basic ipv callback endpoint

---

cloudformation/deploy/template.yaml

Deploy ECS canary components - phase1. At this phase ECS is still the DeploymentController

AUT-3690: Deploy ECS canary components - phase1

---

cloudformation/deploy/template.yaml

Deploy ECS canary phase 2
Revert "AUT-3690: Deploy ECS canary components - phase1" 
This reverts commit d243c643e5e8677c95d66b0b555926cc28fe0341. 
Activates CodeDeploy as the DeploymentController

AUT-3690: Re-enable canary in build and staging

---

.github/dependabot.yml

All dependabot PRs for eslint and related dependencies are grouped together.
This allows us to reduce the workload managing closely related dependencies.
A previous attempt grouped typescript-eslint packages, whereas this expands the group for all eslint packages we use.
For example, these PRs are open at the time of drafting this:
- https://github.com/govuk-one-login/authentication-frontend/pull/2318
- https://github.com/govuk-one-login/authentication-frontend/pull/2317
1. Code Review
- https://github.com/govuk-one-login/authentication-frontend/pull/2307

BAU: Group all eslint dependabot PRs

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars
src/locales/cy/translation.json
src/locales/en/translation.json

> [!CAUTION]  
> Do not merge before we have been given the go-ahead (initially anticipated early week commencing 11 November 2024 but has been delayed - See Jira)
1. Introduces contact form heading and label changes from _"...your identity document"_ to _"...your photo ID"_
2. Enables the no photo ID contact forms changes made in this PR and those linked below in integration and production
This is the label change from "You had a problem with your identity document" to "You had a problem with your photo ID"
<details>
</details>
<details>
</details>
This changes the heading from "A problem with your identity document" to "A problem with your photo ID" 
<details>
</details>
<details> …

AUT-2894: Release no photo ID contact forms

---

src/app.constants.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/reverification-result-service.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/components/ipv-callback/tests/reverification-result-service.test.ts
src/components/ipv-callback/types.ts

Adds to the existing dummy callback endpoint, to call the reverification result lambda. This is the next step in implementing the mfa reset with identity journey, and covers off step 10/11 in the flow diagram linked in the epic.
For example:
1. Code Review
1. Deploy to dev alongside [this api branch](https://github.com/govuk-one-login/authentication-api/tree/AUT-3824/temporarily-hardcode-success-in-reverification-result). 
1. Run through an mfa reset journey with the network tab open on dev tools. See that on callback from the stub to the frontend, we now make a further call to the backend's reverification endpoint, and that this is successful and successfully displays the "reverification result success" message added in this PR. Verify the reverification result lambda was called in the …

Aut 3824: Implement authentication callback

---

src/components/common/state-machine/state-machine.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts

Adds the ipv mfa reset and ipv callback routes to the state machine, to ensure that a user cannot arbitrarily transition to the ipv callback route e.g. by changing the url
1. Code Review
1. Deploy to dev 
1. Run through an mfa reset journey and see that the journey still works
1. Start a new journey and try to hit the ipv callback endpoint out of journey. See that this is not allowed by the state machine (user should be redirected back to the page they came from e.g. /signin-or-create)
1. Compare this e.g. to running main locally and hitting the endpoint out of journey (you'll need the mfa reset with ipv feature flag turned onto have the route available)

Aut 3824/add ipv callback to state machine

---

cloudformation/deploy/template.yaml

1. Add and maintain migrated zone old records. **Only activated in staging**, using feature flag `MaintainMigratedZoneRecords`
2. Use env mapping for transitional and migrated domains. Feature flag created `SwitchToMigratedZone` and currently switched off for all environments
If `MaintainMigratedZoneRecords` is set to true for a target environment, `FrontendDnsRecordA` and `ApplicationLoadBalancerDnsRecordA` resources will be created. The `EnvironmentConfiguration` mapping must have the old Cloudfront distribution and frontend ALB domain values. Rollback should remove the A record entries from the migrated route53 hosted zone. 
If `SwitchToMigratedZone` is set to true for a target environment, domain and certificate should toggle from `transitionalDomain` to …

AUT-3690: Add and maintain migrated zone old records

---

src/app.constants.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/enter-email-validation.ts
src/components/enter-email/index-re-enter-email-account.njk
src/components/enter-email/tests/__snapshots__/enter-email-integration.test.ts.snap
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/get-channel-specific-error-message.ts
test/unit/utils/get-channel-specific-error-message.test.ts

This PR does two things:
1. Updates the reauth email entry template to include content that is specific to the strategic app. This follows [approach 2](https://github.com/govuk-one-login/architecture/blob/main/adr/0193-embedding-web-frontends-in-mobile-apps.md#approach-2--shared-pages) described in the ADR which uses logic in the template. 
2. Introduces a channel specific error message for the strategic app. Because this is also the first PR to introduce different error messages for channels, I've separated the commit which introduces the relevant utility so the approach can be more easily be understood by future developers.
I found it quite challenging to reproduce the error state for this ticket in the frontend because it relies on the user being in a very specific combination of …

AUT-3840: Introduce app specific reauth content for email entry

---

.github/dependabot.yml
package.json
src/assets/scss/application.scss
src/components/common/layout/base.njk
src/config/nunchucks.ts
yarn.lock

> [!NOTE]
> Following the [instructions to update to version 2](https://www.npmjs.com/package/@govuk-one-login/frontend-language-toggle#user-content-upgrading-to-v2) had resulted in a `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]:` build error. Having contacted the package maintainers, they confirmed an additional change is needed (updating the path for `addLanguageParam`), which I've done.
Update `frontend-language-toggle` dependency and remove dependabot ignore rule for earlier version.
1. Code review
2. Run the branch locally to verify the language toggle works as expected. 
- Dependabot first raised a PR to update the language toggle in https://github.com/govuk-one-login/authentication-frontend/pull/2235 but it transpired that necessary CSS had not been included in version `2.0.1`. This PR …

BAU: Update frontend-language-toggle dependency

---

src/components/authorize/authorize-controller.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/tests/cookies-controller.test.ts

We had used `String()` to override the default encoding function used by the `cookie` library, but that meant we were saving raw JSON as cookie values. This is disallowed by [IETF RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1) as it contains, at a minimum, the double quote character.
While browsers tend to be lenient about this, it is a problem now as the `cookie` library has been updated to more closely follow the RFC, which means it will error if passed a disallowed character. We need to be compliant in order to upgrade our `express` version, which uses the updated `cookie` library.
Instead we switch to using the default `cookie` encode option, `encodeURIComponent()`, which will replace the disallowed characters with a different encoding.
The change does not …

AUT-3858: Use `encodeURIComponent()` to encode cookie values

---

src/assets/javascript/application.js

This PR does two things: 
1. Moves client-side JavaScript initialisation code that does not relate to analytics or cookie content out of the `appInit()` function and into a `load` event handler. 
2. Removes a redundant client-side function `initFeedbackRadioButtons` that acts on DOM elements not present in the codebase
To address a client-side bug identified in `DEV` where interacting with the "I do not have a UK mobile number" checkbox did not reveal / hide the component that allows users to enter an international phone number. Investigation revealed that this was because the relevant initialisation was tied to Google Analytics (specifically, the call to `window.DI.analyticsUa.init`)
1. Code Review, commit-by-commit
1. Deploy branch to Dev and run through an account creation journey. You …

AUT-3806: Move initialisation code to load handler

---

src/components/account-created/account-created-controller.ts
src/components/account-created/index.njk
src/components/account-created/tests/account-created-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Introduces app specific content for the account created screen. This follows [approach 2](https://github.com/govuk-one-login/architecture/blob/main/adr/0193-embedding-web-frontends-in-mobile-apps.md#approach-2--shared-pages) described in the ADR which uses logic in the template. 
<details>
</details>
<details>
</details>
1. Code Review

AUT-3841: Introduce app specific content for account created screen

---

dev-check-environment.js
package.json
src/components/account-recovery/check-your-email-security-codes/tests/send-email-otp-middleware.test.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/create-password/tests/create-password-controller.test.ts
src/components/doc-checking-app/tests/doc-checking-app-controller.test.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts
src/components/setup-authenticator-app/tests/setup-authenticator-app-controller.test.ts
test/utils/test-utils.ts
yarn.lock

This removes chai as promised as a dependency. This is because:
a) the latest version of chai-as-promised only works with ESM, which we're not using and would be a pain to convert.
b) chai-as-promised is somewhat deprecated since e.g. mocha introduced async support, and their documentation suggests to only use it in the case of not using a test framework with async support: [https://www.npmjs.com/package/chai-as-promised#working-with-non-promisefriendly-test-runners
](https://www.npmjs.com/package/chai-as-promised#working-with-non-promisefriendly-test-runners)
It has the added benefit of reducing our dependencies!
1. Code Review
1. See all the tests here are passing. You might want to break a few of them locally and see them still fail too - I did this as I was going but a spot check …

BAU: Remove Chai As Promised Dependency

---

src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts

When a user with identity initiates an account recovery to reset their MFA setup they will be redirected to IPV to prove they are the account holder.
They are sent to our `/mfa-reset-with-ipv` page which then redirects to IPV.
Here `isAccountRecoveryJourney` is set to `true` on the user session when is permitted to recover their account.
If not, we throw an error. This should be replaced with an appropriate rendered page to the user.
1. Code Review

AUT-3825: Ensure session reflects account recovery via IPV

---

package.json
yarn.lock

Update govuk-frontend to 4.9.0.
This is part of a co-ordinated update of the Crown Copyright logo.
Merge this PR only at the appropriate time.
Before
After
1. Code Review
1. Deploy to a dev environment with `./deploy-authdev.sh` or run the frontend application locally.
1. Compare the Crown Copyright logo in the footer of pages with the current live version to check that they are different.
1. Run regression tests as required.

DO NOT MERGE: AUT-3880: Update govuk-frontend to 4.9.0

---

.github/workflows/analyse-on-merge.yml
.github/workflows/pre-merge-checks.yml

`sonarsource/sonarcloud-github-action` has been deprecated [1].
> This action is deprecated and will be removed in a future release. Please use the sonarqube-scan-action action instead. The sonarqube-scan-action is a drop-in replacement for this action.
Instead the pre-existing `sonarsource/sonarqube-scan-action` [2] has replaced it.
As quoted above, this should be a "drop-in replacement". Version 4.1.0 is the latest at the this time [3].
[1] https://github.com/SonarSource/sonarcloud-github-action
[2] https://community.sonarsource.com/t/the-new-release-of-github-action-for-sonarqube-v-4-1-0-server-and-cloud/131399
[3] https://github.com/SonarSource/sonarqube-scan-action/releases/tag/v4.1.0
1. Code Review
2. After merging, ensure in follow on PRs that the check still works.

BAU: Switch SonarCloud GHA for SonarQube

---

ci/terraform/api.tf
ci/terraform/core.tf

Handle remote_state role_arn properly.
I missed this when upgrading terraform - this is the same fix as in api.

BAU: Handle remote state role arn properly

---

src/assets/scss/application.scss
src/components/enter-password/index-account-locked.njk
src/components/enter-password/index-sign-in-retry-blocked.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Introduces content specific to lockout scenarios encountered during sign in journeys in the strategic app channel. These include: 
Note: changes to achieve some of these were actually introduced in an earlier Pull Request [#2313](https://github.com/govuk-one-login/authentication-frontend/pull/2313) because templates are shared.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details> …

AUT-3857: Update strategic app content for password lockout

---

cloudformation/deploy/template.yaml

Integration environment old CloudFront distribution and old frontend ALB DNS names added to the EnvironmentConfiguration.
Prerequisite step before DNS migration
Issue: [AUT-3693]
[AUT-3693]: https://govukverify.atlassian.net/browse/AUT-3693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3693: Integration old cloudfront and frontend ALB DNS names

---

cloudformation/deploy/template.yaml

Build environment old CloudFront distribution and old frontend ALB DNS names added to the EnvironmentConfiguration. 
Prerequisite step before DNS migration
Issue: [AUT-3689]
[AUT-3689]: https://govukverify.atlassian.net/browse/AUT-3689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3689: Build old cloudfront and frontend ALB DNS names

---

cloudformation/deploy/template.yaml

Production environment old CloudFront distribution and old frontend ALB DNS names added to the EnvironmentConfiguration.
Prerequisite step before DNS migration
Issue: [AUT-3694]
Compare the values of `oldCloudFrontDistributionDomain` and `oldALBDNSName` in this template with
- CloudFront distribution domain as seen via AWS console
- EC2 -> load balancers -> production-frontend DNS name
- OR signin.account.gov.uk Route53 hosted zone entries
[AUT-3694]: https://govukverify.atlassian.net/browse/AUT-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3694: Prod old cloudfront and frontend ALB DNS names

---

src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/ipv-callback/index-cannot-change-how-get-security-codes.njk
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/components/ipv-callback/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Adds a new page for when a user cannot change their security codes in the new journey that goes via the IPV reverification route.
If IPV indicates that either the user has no stored identity, or that the check was incomplete, we render this page.
This page contains the relevant content and elements, but these don't currently do anything, so effectively for now it's a landing page. Subsequent tickets will cover off the behaviour of any of the options on this page being selected.
For now, in the other error cases we throw an exception. This will be updated in a subsequent ticket / PR, but for now we are just handling the above cases.
The route will only be deployed in environments where we have the new journey turned on.
| English | Welsh|
|----|---|
|<img width="1001" alt="Screenshot …

Aut 3826/create cannot change security codes page

---

src/components/ipv-callback/cannot-change-how-get-security-codes-validation.ts
src/components/ipv-callback/index-cannot-change-how-get-security-codes.njk
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Adds form validation for the radio buttons on this new page.
| English | Welsh |
| ----- |-----|
|<img width="567" alt="Screenshot 2024-12-19 at 15 27 10" src="https://github.com/user-attachments/assets/592dc69b-1e66-41cc-a47e-345950bfd9d9" />|<img width="587" alt="Screenshot 2024-12-19 at 15 27 20" src="https://github.com/user-attachments/assets/f9104773-fba3-4b96-a143-492dc769def2" />|
1. Code Review
1. Run locally and see the validation error when not choosing an option. To get to the page easily, you can temporarily comment out the session middleware and journey middleware for the ipv callback routes, and directly hit http://localhost:3000/cannot-change-security-codes

AUT-3951: Add validation for radio buttons on cannot change security codes page

---

cloudformation/deploy/template.yaml
deploy-authdevs.sh
scripts/dev_deploy_samconfig.toml
scripts/dev_deploy_tags.json
scripts/dev_sam_deploy.sh

SAM deploy frontend to new authdevs via command line. The UI hasn't changed, deployment functionality has been added for the new environments that use cloudformation template and sam deploy, instead of terraform.
Users will see two new environment options. "new" authdevX deployments switch to running `scripts/dev_sam_deploy.sh`. It builds the frontend docker image, runs `sam build` and `sam deploy` to deploy frontend. All existing usage options are supported
```
$ ./deploy-authdevs.sh 
1) authdev1
2) authdev2
3) authdev1-sp
4) authdev2-sp
```
Run `./deploy-authdevs.sh` as usual with desired options and test deployment to new authdev1 and 2
Example:
`./deploy-authdevs.sh -b -d -p` to build, deploy and prompt on deployment. `-t` option can also be used interchangeably with `-d` …

AUT-3939 - sam deploy frontend to new authdevs via command line

---

ci/terraform/authdev2.tfvars
ci/terraform/core.tf
ci/terraform/variables.tf

AUT-3907: Moving Authdev2 to Shared Dev VPC & Also run Authdev2 ECS service under dev cluster 
1. Code Review
2. Deploy to Authdev2  with `./deploy-authdev2.sh -t -p

AUT-3907: Moving Authdev2 to Shared Dev shared VPC

---

.github/workflows/pre-commit.yml
ci/terraform/authdev2.tfvars
ci/terraform/variables.tf
ci/terraform/waf.tf

Details in the individual commits.
TL;DR: rate limits now apply to endpoints individually, config format has changed
- Code Review
1. Deploy to an environment without making any changes to the tfvars: observe that the configuration is translated to the new format
2. Update the values of `{aps_session,ip}_endpoint_rate_limiting_configuration` tfvars, observe that your new values are used instead
3. I guess you could do some brute-forcing, to check whether the rules actually work. If the syntax is right, they will work, though.

BAU: Cloudfront WAF improvements

---

ci/terraform/variables.tf
ci/terraform/waf.tf

All the rate limiting config has now been migrated to the new format, so these old variables are no longer needed.
After this is merged, `/deploy/$env/{rate_limited_endpoints,rate_limited_endpoints_rate_limit_period,rate_limited_endpoints_requests_per_period}`
should be deleted.
1. Code review
2. Confirm `aps_session_endpoint_rate_limiting_configuration` and `ip_endpoint_rate_limiting_configuration` variables are present in all
environments' SecretsManager secrets

BAU: remove old rate limiting config variables

---

ci/terraform/cloudfront.tf
ci/terraform/production.tfvars
ci/terraform/variables.tf

Reverts govuk-one-login/authentication-frontend#2458
The new cloudformation introduces standard 500 pages, so we will need to do something different somewhere.
For now, not doing this is the right thing to do.

Revert "BAU: Send Cloudfront logs to Splunk"

---

src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/ipv-callback/cannot-change-how-get-security-codes-validation.ts
src/components/ipv-callback/index-cannot-change-how-get-security-codes.njk
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

This page can only be accessed by failing to complete an IPV re-verification journey which returns error codes `identity_check_failed` or `identity_did_not_match`.
It renders the existing failure page template and add the extra preamble required to explain the identity check failed.
| Welsh | English |
| --- | --- |
| ![Screenshot 2024-12-19 at 15 50 44](https://github.com/user-attachments/assets/020e83ed-411d-4ba9-acc7-8112e6ad206b) | ![Screenshot 2024-12-19 at 15 50 40](https://github.com/user-attachments/assets/12eb63ed-6968-4552-8423-c35f78d7833b) |

AUT-3930: Add `/cannot-change-security-codes-identity-fail` page

---

cloudformation/deploy/template.yaml

AUT-3943: switch signin.staging DNS to secure pipeline frontend
POC: migrate DNS while ECS blue/green is disabled
Issue: [AUT-3943]
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3943: switch signin.staging DNS to secure pipeline frontend

---

.gitignore
pyproject.toml
scripts/_create_env_file.py
scripts/create-env-file.sh
scripts/requirements.txt

Previously, only `authdev[0-9]+` and `build` environments were
supported. Now, we support `dev` and `staging` environments as well.
Additionally, switch dependency definition to `pyproject.toml` and use `click` for argument handling.
1. Code review
2. `scripts/create-env-file.sh dev`
3. `scripts/create-env-file.sh staging`

BAU: Allow env file creation for more environments

---

src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/enter-password/enter-password-controller.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/types.ts

- If a user selects "Try entering a security code again with the method you already have set up" in the cannot-change-how-get-security-codes page they will be redirected to the OTP challenge screen again. They are not sent another MFA code.
- Enter mfa attempt counts persist for both MFA types on the back end.
- Mfamethod type has been stored on a user's session from the enter password stage where it is retrieved from the db in order to know which OTP challenge screen they will be redirected to.
1. Code Review
2. Tail cloud watch logs for chosen MFA method handler (VerifyMfaCodeHandler for auth app, VerifyCodeHandler for SMS)
3. Run against dev and run through a sign in journey up to MFA challenge, enter an invalid code, then select 'Problems with the code?' -> 'change how you get …

AUT-3920: Redirect back to enter mfa pages

---

cloudformation/deploy/template.yaml

Disable frontend ECS Blue/green deployment
Issue: [AUT-3990]
Env level configuration. Can only be tested on the target env. 
Deploy pipeline changes from https://github.com/govuk-one-login/authentication-infrastructure/pull/35 to the target environment `./provision-<environment>.sh -p`
Delete frontend stack and redeploy. 
[AUT-3990]: https://govukverify.atlassian.net/browse/AUT-3990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3990: Disable frontend ECS Blue/green deployment

---

Dockerfile-stub
README.md
dev-app-orchstub.js
docker-compose.yml
package.json
scripts/_create_env_file.py
startup.sh

As part of splitting from orch, we can no longer rely on having the full set of orch infrastructure in our dev environments (dev, authdev1, authdev2). Therefore, rather than having an RP stub for running locally, we need an orch stub.
This introduces an orch stub that will run when running the startup script. Currently it runs on a different port to the local RP stub, so this will need to be remembered when testing locally. Eventually we should be able to remove the local RP stub entirely.
Note that currently, at the end of the journey when we hand back to the stub, you will hit an internal server error. The journey has successfully worked, but because the stub is trying to read cookies (and when running through a journey locally your cookies will be stored against a different domain) you …

AUT-3978: Add local orch stub

---

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/further-information/_proving-identity-further-information.njk
src/components/contact-us/questions/_proving-identity-problem-entering-address.njk
src/components/contact-us/questions/_proving-identity-something-else.njk
src/components/contact-us/questions/_user-location-question.njk
src/components/contact-us/questions/index.njk
src/components/contact-us/tests/__snapshots__/contact-us-controller-integration.test.ts.snap
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/components/contact-us/tests/contact-us-service.test.ts
src/components/contact-us/types.ts
src/components/enter-email/tests/__snapshots__/enter-email-integration.test.ts.snap
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

> [!WARNING]  
> Do not merge before given the go-ahead by Identity Pod (relevant contacts are in Jira ticket).
Updates to contact forms that will allow users to:
1. Describe a problem with entering their address
2. State their location when describing another problem they had proving their identity 
This change is hidden behind a feature flag which is enabled on build and lower envs.
In higher envs, the new form and "something else" question can be seen by knowing the right URLs:
- The `proving_identity_something_else` page requires a new query param to see the location question: `/contact-us-questions?theme=proving_identity&subtheme=proving_identity_something_else&referer=&supportContactFormProblemWithAddress=true`
- The `proving_identity_problem_with_address` page can just be opened as …

AUT-3937: Support form updates for international addresses

---

ci/terraform/cloudfront.tf

Adding lifecycle ignore for header var because Cloud-front Template has set NoEcho on these parameter so terraform continually detects changes though there is no change in value read via secret manager store
1. Code Review

BAU: Adding lifecycle ignore for header var

---

src/components/common/state-machine/state-machine.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts

Once a user has started the MFA reset with IPV, they are taken to IPV. Here we enable support for going back to the previous MFA entry page (be it SMS or App).
This is done by first making the `IPV_CALLBACK` path in response to `IPV_REVERIFICATION_INIT` optional. We don't actually use the output of the state machine to drive the redirect in a0bfb6478d86d7481ad9364f34980491bee9323f. This is because the actual URL to IPV goes to an external application, not something managed by the state machine.
Instead the internal path returned after `IPV_REVERIFICATION_INIT` are the MFA code entry page for the type the user has already. This is stored in the users session and if a user navigates back from IPV to auth this last page (MFA code entry) is allowed.
1. Code Review
1. Run locally against `dev` …

AUT-3962: Allow going back after starting MFA reset with IPV

---

src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Made content changes for MFA screens to reflect that MFA relies on approval from IPV.
SMS MFA:
AUTH APP MFA:
Changes to the acceptance tests have been made to reflect these changes. They are commented out currently, to be uncommented when MFA_RESET_WITH_IPV is turned on.
Happy for this to be merged in my absence if no changes need to be made.
1. Code Review
2. Go through sign in journey up to MFA page: 
- Check that for SMS you see: 'If you no longer have access to this phone number, check if you can change how you get security codes.'
- Check that for AUTH_APP you see: 'If you no longer have access to your authenticator app, check if you can change how you get security codes.'

AUT-3921: Change content for mfa reset with IPV

---

cloudformation/deploy/template.yaml

Deploy the frontend application with the MaintainMigratedZoneRecordsfeature switch enabled in the integration account. This will add the source (old) CloudFront and origin ALB alias records pointing to the old frontend to the newly created hosted zone in step 1.1
Migration guide https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan step 1.2

AUT-3693 - Feature switch on to maintain zone records in integration

---

src/components/account-recovery/change-security-codes-confirmation/change-security-codes-confirmation-controller.ts
src/components/account-recovery/change-security-codes-confirmation/index.njk
src/components/account-recovery/change-security-codes-confirmation/tests/change-security-codes-confirmation-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Minor content changes for the screen that confirms a user has changed their MFA method. These changes will be released alongside the updated mfa reset journey, so are behind a feature flag.
1. Code Review
**With IPV MFA reset journey on:**
| | English | Welsh |
|---|---|---|
|After changing to SMS |<img width="725" alt="Screenshot 2025-01-23 at 08 52 19" src="https://github.com/user-attachments/assets/60aacfc9-1914-4be7-9bba-115229fe6b71" />|<img width="755" alt="Screenshot 2025-01-23 at 08 52 26" src="https://github.com/user-attachments/assets/d19e588f-defc-4cf2-a3e2-29f839c549f6" />|
| After changing to Auth App |<img width="704" alt="Screenshot 2025-01-23 at 16 05 00" src="https://github.com/user-attachments/assets/1a957221-2dc6-4d19-848e-f2fd30c976e1" />|<img width="729" …

AUT-4004: Update confirmation screen for changing security codes

---

cloudformation/deploy/template.yaml

Frontend ECS rolling update speedup
MaximumPercent set to 200% for both frontend and service-down page. The scheduler may now start desiredCount number of new tasks before stopping the older tasks
Recommended setup in https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html

AUT-3693: Frontend ECS rolling update speedup

---

src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk

Mfa reset with IPV content was reverting to previous content upon page refresh. This is because the value for supportMfaResetWithIpv was not being cached. 
This PR implements the hidden input element to cache the supportMfaResetWithIpv value in MFA .njk files.
1. Code Review
2. Deploy to dev and run through journey to MFA page (the issue doesn't happen for me when running locally - I've no explanation for that)
3. See "check if you can change how you get security codes". Refresh page and make sure the content hasn't changed.

AUT-4037: Fix reversion to flag off content upon page refresh

---

cloudformation/deploy/template.yaml

Deploy the frontend application with the MaintainMigratedZoneRecordsfeature switch enabled in the production account. This will add the source (old) CloudFront and origin ALB alias records pointing to the old frontend to the newly created hosted zone in step 3.1 
Migration guide https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan step 3.2

AUT-3694 - maintain migrated zone records in prod

---

package.json
yarn.lock

Upgrade cheerio from the release candidate to the main 1.0.0 version, which as a side-effect resolved CVE-2025-22150 which depends on undici versions being updated, and in this case to 6.21.1.
1. Code Review

BAU: Upgrade cheerio

---

src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/reverification-result-service.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/components/ipv-callback/tests/reverification-result-service.test.ts
src/components/ipv-callback/types.ts

We need to forward the state received when a user returns from IPV during an MFA reset journey to our backend. This is so the backend can check the state received matches the state created by the backend for the session as a CSRF mitigation.
1. Code Review

AUT-3910: Send state to /reverification-result API

---

src/components/reset-password/reset-password-controller.ts
src/components/reset-password/reset-password-service.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/components/reset-password/tests/reset-password-service.test.ts
src/components/reset-password/types.ts

This makes use of the new optional flag ("allowMfaResetAfterPasswordReset") on the request to the reset password handler when the mfa reset via ipv journey is on.
This will mean that a user who has successfully reset their password does not have any account modifiers put on them, and can immediately reset their mfa on a subsequent journey after resetting their password (previously they would have had to complete one successful subsequent login journey before resetting mfa.
This behaviour was somewhat legacy anyway since we put the MFA challenge as part of password reset, but will be especially now that they have to go through a higher security journey as part of resetting their MFA.
We've made a decision here not to introduce a separate feature flag on the backend that reflects whether …

AUT-3993: Tell backend not to block user for mfa reset when mfa reset via ipv is on

---

src/app.constants.ts
src/components/ipv-callback/index-cannot-change-how-get-security-codes.njk
src/utils/taxonomy.test.ts
src/utils/taxonomy.ts

Add ga4 data for new cannot change security code pages (applicable to the new mfa reset journey).
1. Code review
1. Turn on ga4 for an environment where the ipv stub is working - either dev, or non strategic pipelines authdev1 or authdev2 (e.g. if in a tf environment `ga4_enabled = "true"`
1. Deploy this branch to that environment
1. Run through an mfa reset journey, and select one of the failure cases. Ensure you have accepted cookies
1. Verify the taxonomy data and content ids for that pages matches what is expected here, either via google tag assistant or the network tab

Aut 3998/add analytics for new mfa pages

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/further-information/_proving-identity-further-information.njk
src/components/contact-us/questions/_proving-identity-something-else.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/config.ts

Enable contact form changes to support international address questions.
1. Code Review
1. Run locally
1. See "You had a problem entering your address" option at http://localhost:3000/contact-us-further-information?theme=proving_identity&referer=
1. Select it and continue
1. Submit the form, see validation errors
1. Fill in form, submit and see expected error (SmartAgent won't be set up locally, but this is a success for release)
1. Go back to http://localhost:3000/contact-us-further-information?theme=proving_identity&referer=
1. Select option "Something else" and continue
1. See the "Do you live in the UK, Channel Islands or the Isle of Man?" question.
1. Submit the form, see validation errors
1. Fill in form, submit and see expected error (SmartAgent won't be set up locally, but this is …

AUT-4007: Release international address support

---

ci/terraform/ecs.tf
ci/terraform/variables.tf

This reverts commit 123bd847c1d8f30a240c88a2d5aaf46a07dee7b9.
Cloudformation makes this approach difficult to implement.
Keep the tfvars tidying in though.

Revert "AUT-4052: Add description for bypass CIDR blocks"

---

src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-integration.test.ts

These test that the middleware etc is all working correctly
We can ignore the taxonomy snapshots in these since the mfa reset via ipv page is not a rendered page.
Useful for if I do a bigger refactor of this stuff as part of adding the new guidance page for when someone is trying to do an mfa reset from a strategic app journey.

BAU: Add integration tests for mfa reset via ipv controller

---

src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/mfa-reset-with-ipv/index-open-in-browser-mfa-reset.njk
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-routes.ts
src/components/mfa-reset-with-ipv/tests/__snapshots__/mfa-reset-with-ipv-integration.test.ts.snap
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Introduces a new guidance page to be shown to app users who attempt to reset their mfa via the new journey.
There is an issue whereby if the user starts their journey in an app (for example the v2 one login app or the HMRC app), the user will not be able to complete an MFA reset journey in app. This is due to linking issues in the app portions of the journey. 
We therefore need to detect if a user is signing in via an app and, if so, show them a guidance page that instructs them to sign in via a web browser to complete an MFA reset.
Adding analytics data for the new page (awaiting from data analytics)
New guidance page:
| English | Welsh |
|----|----|
|<img width="1004" alt="Screenshot 2025-02-10 at 15 29 38" src="https://github.com/user-attachments/assets/465e399e-8f43-470e-ba54-6a1437c7d …

Aut 4051/prevent mfa reset for app journeys

---

src/components/authorize/authorize-controller.ts
src/components/authorize/tests/authorize-controller.test.ts

For strategic app journeys:
* We don't want to display the cookie banner
* We want to disable analytics cookies, regardless of the user's preferences (without affecting what happens if they go through a web journey)
This achieves this by setting analytics cookie preferences to false in the authorize controller (which is the start of a user's journey). This will mean that the banner will not appear for a user within this journey (as we only display when this cookie is not set) and also that no analytics data will be sent during this journey.
1. Code Review
1. Run locally
1. Clear cookies and go through a normal journey and make sure you can see the banner
1. Start a strategic app journey locally (I hack this by setting the res.locals.strategicAppChannel to true in channel middleware) and …

AUT-4050: Set analytics cookie preferences to off for strategic app journeys

---

src/components/common/constants.ts
src/components/enter-mfa/enter-mfa-routes.ts
src/middleware/allow-user-journey-middleware.ts
test/unit/middleware/allow-user-journey-middleware.test.ts

When a user is on the `/enter-code` page, starts the MFA reset journey and hits back they go back to the `/enter-code` page. The user is then unable to resend the code as the state machine is not in the right state to do so.
`allowAndPersistUserJourneyMiddleware` is introduced to solve this problem. It asserts the user is allowed to be on the page. It also updates the user session `journey` to reflect the path they are on (if the path is an optionalPath from a previous page). This ensures that when the users loads the page they can do any of the intended actions of that page.
This new middleware is only applied to the `GET /enter-code` route and we can consider if we want to roll this out to more, or all, routes.
1. Code Review
2. Deploy to an env
3. Start journey
4. On SMS MFA code …

AUT-4081: Check & persist allowed optional paths state for /enter-code

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/dev.tfvars
ci/terraform/ecs.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-authenticator-app-code/tests/__snapshots__/enter-authenticator-app-code-integration.test.ts.snap
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk
src/components/enter-mfa/tests/__snapshots__/enter-mfa-integration.test.ts.snap
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/config.ts

Introduces a new feature flag (routeUsersViaIpv) that will support a temporary testing phase of the new journey in production before we fully route users via the new journey. This is largely so that we can test prod connectivity.
During this testing phase, we will switch:
* the existing feature flag (supportMfaResetViaIpv) to on
* the new feature flag to off
The effect of this will be that users clicking through an mfa reset journey will still be routed via the existing mfa reset journey. But since the new routes for the new journey are deployed via the existing feature flag, they will be available to manually navigate to the new journey at the relevant point, meaning we can check the production journey without affecting users clicking through the normal journey.
Once we're happy, we will …

Aut 4088/update mfa feature switch for live testing

---

@types/express/index.d.ts
package.json
src/app.ts
src/middleware/set-local-vars-middleware.ts
src/utils/strings.ts
yarn.lock

Per https://github.com/govuk-one-login/architecture/blob/913c04af8b57e2cdce07c4b242a409690852d527/rfc/0083-express-on-ecs.md#too-many-connections, this makes some blocking calls async
- nonce generation
- session ID generation
Both "inspired" by changes in ipv-core-front.
This has been tested in sandpit

AUT-3754: Make blocking code async

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/dev.tfvars
ci/terraform/ecs.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-authenticator-app-code/tests/__snapshots__/enter-authenticator-app-code-integration.test.ts.snap
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk
src/components/enter-mfa/tests/__snapshots__/enter-mfa-integration.test.ts.snap
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/config.ts

Reinstating [this PR](https://github.com/govuk-one-login/authentication-frontend/pull/2592) which we [reverted](https://github.com/govuk-one-login/authentication-frontend/pull/2593) to prove it wasn't causing tests to fail in the new pipeline (now confirmed).
Introduces a new feature flag (routeUsersViaIpv) that will support a temporary testing phase of the new journey in production before we fully route users via the new journey. This is largely so that we can test prod connectivity.
During this testing phase, we will switch:
the existing feature flag (supportMfaResetViaIpv) to on
the new feature flag to off
The effect of this will be that users clicking through an mfa reset journey will still be routed via the existing mfa reset journey. But since the new routes for the new journey are …

Aut 4088/reinstate

---

.pre-commit-config.yaml

1.24 breaks compat
```
❯ go version
go version go1.24.0 darwin/arm64
❯ git commit
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/rhysd/actionlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
mixed line …
```

BAU: pin golang to 1.23.6 in pre-commit

---

cloudformation/deploy/template.yaml

A dress-rehearsal for what we'll do in integration / production for go live.
This should mean we can still go through the new mfa reset journey via IPV but the links the user clicks on will all be for the old journey.

BAU: Switch to live proofing of mfa journey in staging

---

cloudformation/deploy/template.yaml

Enable MFA reset in integration and production
- Makes MFA reset available for live proving
- Switch on 'UseMfaResetWithIpv' in the secure pipeline environments
See [implementation plan](https://govukverify.atlassian.net/wiki/spaces/LO/pages/5082808321/DCP-3200+Resetting+MFA+with+ID+re-verification+-+Implementation+Plan+27+Feb+2025)
1. Code Review

AUT-4047: PR-Silent-Enable - Enable MFA reset in integration and production

---

cloudformation/deploy/template.yaml

PR-Visible - Switch on MFA reset for end-users in integration and production
- Makes MFA reset available for live proving
- Switch on 'UseRouteUsersToNewIpvJourney' in the secure pipeline environments
See [implementation plan](https://govukverify.atlassian.net/wiki/spaces/LO/pages/5082808321/DCP-3200+Resetting+MFA+with+ID+re-verification+-+Implementation+Plan+27+Feb+2025)
To be merged after: https://github.com/govuk-one-login/authentication-frontend/pull/2615/
1. Code Review
#2615

AUT-4047: PR-Visible - Switch on MFA reset for end-users in integration and production

---

cloudformation/deploy/template.yaml

Refactor DNS migration feature switches
- Phase out MaintainMigratedZoneRecords as all environments are keeping this record
- Simplify SwitchToMigratedZone
- New feature flag MaintainSPZoneRecords to gradually remove -sp resources
Issue: [AUT-3942]
[AUT-3942]: https://govukverify.atlassian.net/browse/AUT-3942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3942: Refactor DNS migration feature switches

---

.github/workflows/deploy-frontend-sp-dev.yml

BAU: disable deploy-service-down-page for dev environments
To help speedup deployments to dev, authdev1 and authdev2

BAU: disable deploy-service-down-page for dev environments

---

src/components/setup-authenticator-app/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

By putting these items in an ordered list element in html, users accessing the service via assistive technologies (e.g. screen readers) should be able to better understand the structure of the page.
This necessitated removing the hard-coded numbers from the steps in the translation files, as these will be provided by the html elements.
This fixes a failure against this WCAG standard:
https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships
| | Current page | Page as rendered by this PR |
|---|----|-------|
| En |<img width="450" alt="Screenshot 2025-03-07 at 11 43 04" src="https://github.com/user-attachments/assets/94044ddc-7b53-4474-8a1a-d1f9ac3ee919" />|<img width="741" alt="Screenshot 2025-03-07 at 11 54 35" src="https://github.com/user-attachments/assets/c8af0ff8-8f99-4eb6-90 …

AUT-4103: Put numbered elements on setup auth app page in correct html

---

scripts/dev_sam_deploy.sh

Skip commitsha when deploying to dev envs via CLI scripts
This reduces the size of the changeset every deployment and thus speeds up the deployment
Issue: [AUT-4131]
Use `deploy-authdevs.sh`. Several test runs from the branch logged in the jira ticket
[AUT-4131]: https://govukverify.atlassian.net/browse/AUT-4131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4131: Skip commitsha when deploying to dev envs via CLI scripts

---

src/components/common/state-machine/state-machine.ts
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/prove-identity-callback-service.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/components/prove-identity-callback/tests/prove-identity-callback-service.test.ts
src/components/prove-identity-callback/types.ts

As part of a refactor to remove the RP auth code logic from /auth-code, reproduce this functionality here and no longer redirect to auth-code.
I've tested this in sandpit and dropped screenshots on the ticket
Code review. I've deliberately left auth-code alone as that needs cleaning up later. If you want to test this it will need deploying to sandpit as you'll need real orchestration for identity.

AUT-4110: Replicate auth code logic in prove-identity-callback

---

sandpit.Dockerfile

BAU: refactor to remove sandpit.Dockerfile build warning messages
Removes following warnings:
FromAsCasing - FROM and as casing do not match
LegacyKeyValueFormat - ENV key=value format should be used instead of legacy ENV key value
Compare the docker build output by running `./deploy-authdevs.sh -b` between main and this branch

BAU: refactor to remove sandpit.Dockerfile build warning messages

---

cloudformation/deploy/template.yaml

Auth frontend template maintains two A records (cloudfront and origin) in signin-sp hosted zone.
As part of post-migration cleanup, removing these records
Any resources managed by the feature flag `MaintainSPZoneRecords` and the flag itself is getting removed. No further changes.

AUT-4121: remove signin-sp zone A records from frontend template

---

src/components/common/cookies/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Added di-device-intelligence to list of cookies.
1. Code Review
2. Go to /cookies and see 'di-device-intelligence - When you close your web browser' added to cookies list
**English**
**Welsh**

AUT-4166: add device intelligence cookie to cookies list

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

Now we are passing new fields from orch to the auth frontend, we would like to pass these fields to the auth backend, to avoid having to use the client session authRequestParams field. 
1. Code Review

ATO-1435: Pass new claims to auth backend.

---

cloudformation/deploy/template.yaml

Bump and lockdown ecs canary nested stack to v2.1.2
**Phase 1 dependency**: pipelines are updated with the changes https://github.com/govuk-one-login/authentication-infrastructure/pull/59/files
[AUT-3991]
Verify that the changes are as prescribed in the [step 6 of the deployment guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-6%3A-Deploy-newly-added-resources)

AUT-3991: bump and lockdown ecs canary nested stack to v2.1.2

---

cloudformation/deploy/template.yaml

This change triggers the first canary deployment via CodeDeploy
This is dependent on https://github.com/govuk-one-login/authentication-frontend/pull/2681 released in the environment first
[AUT-3991]
Verify that the changes are as prescribed in the [step 8 of the deployment guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-8%3A-Trigger-first-Canary-deployment)

AUT-3991: switchover to ECS Canary CodeDeploy

---

cloudformation/deploy/template.yaml

This change triggers the first canary deployment via CodeDeploy in build and staging environments
This is dependent on
1. https://github.com/govuk-one-login/authentication-frontend/pull/2681 released in the environment first
2. build and staging frontend pipelines updated with changes in https://github.com/govuk-one-login/authentication-infrastructure/pull/59
[AUT-3991]
Verify that the changes are as prescribed in the [step 8 of the deployment guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-8%3A-Trigger-first-Canary-deployment)

AUT-3991: switchever to ECS canary in build and staging

---

package.json
yarn.lock

BAU: update es-lint to 3.3.1
This is really just to trigger a deployment for canary rollout.
1. Code Review
1. Test locally

BAU: update es-lint to 3.3.1

---

cloudformation/deploy/readme.md

Removed legacy frontend deployment instructions from readme.
Fixed hyperlinks with relative paths.
This is really just to trigger a deployment for canary rollout.
[AUT-3991]

BAU: remove legacy frontend deployment instructions from readme

---

cloudformation/deploy/template.yaml

This change triggers the first canary deployment via CodeDeploy in production
This is dependent on
1. https://github.com/govuk-one-login/authentication-frontend/pull/2681 released in the environment first
2. production frontend pipeline updated with changes in https://github.com/govuk-one-login/authentication-infrastructure/pull/59
[AUT-3991]
Verify that the changes are as prescribed in the [step 8 of the deployment guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance#Step-8%3A-Trigger-first-Canary-deployment)

AUT-3991: switchever to ECS canary in production

---

@types/express-session/index.d.ts
src/middleware/session-middleware.ts

Part I of a two part change.  This change needs to spend at least an hour in prod before the second part arrives.
Adds a new 'sessionRestored' flag and initialises it when /authenticate is called, which is the front door for all journeys in to Authentication. A subsequent change will use this flag to determine if the session has actually been restored from the Redis database.
See 9396e656b6d423ce4c4f66faad09a9294acf17e9
1. Code Review
1. Deploy to an environment and test a journey.
#2701 
https://onelogingovuk.service-now.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3D895e79cf83e4ea50510344547daad3c9%26sysparm_stack%3D%26sysparm_view%3D

AUT-4178: PART I - Add new sessionRestored flag and initialise

---

src/components/ipv-callback/tests/cross-browser-middleware.test.ts
src/middleware/session-middleware.ts
src/middleware/tests/session-middleware.test.ts

Use the new 'sessionRestored' flag in the session and set this to 'true when the session is first initialised. Check that this field exists for the session to be vaild in 'sessionIsValid' If the database ttl expires (despite the aps cookie still being available) then this field will be undefined, indicating that the session has not been restored from the database.  In this case the session expired page is displayed to users as the session has actually expired.
Temporary fix for an issue where the aps cookie expiry time is extended in a rolling manner, whereas the corresponding ttl for the Redis session item is not, which results in errors.
The reason this works (given that in theory every journey that goes through /authenticate will have the flag set to true) is because on any subsequent …

AUT-4178: PART II - Detect when session not restored from the database

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-email/index-create-account.njk
src/components/enter-email/tests/enter-email-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

We are going to enable app users to create accounts. This is a small tweak in preparation for that, since for app users these links will not open on a new tab
1. Code Review
1. This is harder to see locally since we haven't yet enabled strategic app create journeys, so I've been manually setting the res.locals.strategicAppChannel to true in the `enterEmailCreateGet` function as a way to check the text that appears in a strategic app journey.
| | English | Welsh |
|---|---|---|
| How the create account screen appears for web users (no change to current) |<img width="732" alt="Screenshot 2025-04-04 at 15 47 19" src="https://github.com/user-attachments/assets/a3cd4e64-7053-4744-9731-9d0c6c5d96de" />|<img width="731" alt="Screenshot 2025-04-04 at 15 47 30" …

AUT-4203: Remove opens in new tab text on enter email create screen for app users

---

src/components/auth-code/auth-code-routes.ts
src/middleware/session-middleware.ts
src/middleware/tests/session-middleware.test.ts

Check that the 'email' field is present on the session before handing over to the 'auth-code' route.  If the email is not present then route to the standard session error page.
Fixes a second issue where the frontend session in the Redis datastore expires after 1hr, whereas the frontend session cookie (aps) is rolling and can last longer after being extended on each silent login.
The issue manifests in the logs as
`TypeError: Cannot read properties of undefined (reading 'toLowerCase')
at /app/dist/middleware/account-interventions-middleware.js:13:50`
The first issue was resolved by #2705, but that change did not resolve this second issue.
- The frontend session in the Redis datastore will always expire after 1hr regardless of any silent logins (issue to be resolved later)
- The frontend …

AUT-4178: Check required session field 'email' when calling auth-code

---

src/components/account-not-found/index-mobile.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Users will now be allowed to create accounts via the strategic app, so this exposes the account creation flow when a user tries to sign in with an account that does not yet exist.
Content is updated to match latest requirements and a form and button is introduced to initiate the existing account creation journey.
| Welsh | English |
| --- | --- |
| ![localhost_3000_account-not-found_lng=cy(iPhone 12 Pro)](https://github.com/user-attachments/assets/96d58e3c-deb9-4614-811c-539333e04e23) | ![localhost_3000_account-not-found_lng=en(iPhone 12 Pro)](https://github.com/user-attachments/assets/5adc9f64-2dcb-491b-ab5c-80451b26d309) |
1. Code Review

AUT-4179: Update `/account-not-found` strategic app page

---

src/app.ts
test/unit/static.test.ts

Do not send the `x-powered-by: express` header.This can help to prevent low-effort fingerprinting
1. Code Review

AUT-4250: Do not send x-powered-by header on static assets

---

scripts/_create_env_file.py
src/app.ts
src/config.ts
test/unit/app.test.ts

Currently the server vital signs are logged in accordance with the defaults (every 10 seconds) in all environments.
This can obscure important logs when developing the frontend locally.
Here this 10 seconds default is overridden by 360 seconds when run locally.
1. Code Review
1. Run locally, but first run `./scripts/create-env-file.sh` to get the new setting.
2. See the logs are less frequent

BAU: Vital signs log less frequently locally

---

cloudformation/deploy/template.yaml

AUT-4251: Add FMS ignore tags cloaking Header WAF
AUTh is using regional Cloaking WAF to protect the load balancer however since this WAF is not maintained by FMS it gets flagged as false positives in Security Hub for resources that may appear unprotected by Firewall Manager (FMS)
1. Code Review
1. Deploy to any  Authdevs and see the new tags key with value is created on frontend ALB

AUT-4251: Add FMS ignore tags cloaking Header WAF

---

dev-app-orchstub.js
scripts/_create_env_file.py

Since the authdev environments have moved AWS accounts and the old `*.sandpit.*` domains have been deactivated we've been unable to run the frontend locally targeting the authdev environments.
This updates the env build script to statically create the audience values needed for all environments.
This is needed because the state file needed for the authdev envs reference the incorrect values, which are still required at the moment.
1. Code Review

BAU: Correct authdev signin URLs in env script

---

src/components/authorize/authorize-controller.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/test-data.ts
src/middleware/session-middleware.ts
src/middleware/tests/session-middleware.test.ts
src/types.ts
src/utils/logger.ts

Adds facility to track frontend response status by RP
- Log RP client id in response logger.
- Reads the mandatory rp_client_id claim from orchestration and makes this available as a local:
https://github.com/govuk-one-login/authentication-api/blob/72fdbb879debf7f547bf4e564e94ed3386397db9/oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java#L944
1. Code Review
1. Deploy to an environment for testing
1. Run a journey and check that the clientId appears in the response logs

Alert0010950: Log RP client id in response logger

---

ci/terraform/cloudfront.tf
scripts/dev_deploy_common.sh

BAU: enable FMS WAF on sandpit legacy CloudFront Frontend
Note : terraform in frontend is only used in sandpit, other env are migrated to secure pipeline 
For example:
code review

BAU: enable FMS WAF on sandpit legacy CloudFront Frontend

---

src/middleware/overload-protection-middleware.ts
src/middleware/tests/overload-protection-middleware.test.ts

Increase overloadProtection maxEventLoopDelay to 700ms in staging.
Protection triggering is currently too sensitive and has been triggered by low volume acceptance test runs in staging
This applies to staging only as overload protection is not enabled in any other environment.
1. Code Review

BAU: increase overloadProtection maxEventLoopDelay to 700ms in staging

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

Reintroducing this PR after fixing the smoke tests
We have defined some new claims which will replace the need for auth client session. This PR passes these new claims from orch to the auth backend.
Note that we would like to get rid of the `confidence` claim we get from orch. In the backend changes, we added another  claim called `requested_credential_strength` which we can update the frontend to use. Both of these claims are set to the same value in orch. Once we've swapped to using the new claim with the better name, we can remove the old claim in orch.
Deployed to sandpit with the backend changes
- Tested with VTR with level of confidence
- Tested with VTR without level of confidence
- Tested without providing a VTR
All journeys completed successfully and no fields were logged as …

ATO-1435: Pass new claims to auth backend

---

src/components/authorize/authorize-controller.ts

We send a clientSessionId from orch to auth frontend (as govuk_signin_journey_id). This adds logging to check if this clientSessionId matches the one set in the gs cookie.
1. Code Review
Just logging changes

ATO-1435: Log whether clientSessionIds are in sync

---

src/components/authorize/tests/__snapshots__/authorize-integration.test.ts.snap
src/components/how-do-you-want-security-codes/index.njk
src/components/how-do-you-want-security-codes/tests/__snapshots__/how-do-you-want-security-codes-integration.test.ts.snap
src/components/how-do-you-want-security-codes/tests/how-do-you-want-security-codes-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- Adds logic for auth app to the how do you want to get security codes page.
- If auth app is in present in req.session.user.mfaMethods, auth app radio button
is shown.
- This PR covers both scenarios where auth app is either default or back up
1. Code Review
2. Run against environment where you have two MFA methods set up
3. See radio buttons on 'How do you want to get a security code?' page

AUT 4246: How do you want to get sec codes for AUTH APP user

---

src/components/authorize/authorize-service.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/types.ts

Previously the value of Current credential strength was sent from Orchestration -> Authentication  and back again at userinfo. This was to compensate for the fact that the value was not set in all cases. We have now migrated to using Achieved Credential Strength instead, which has allowed this to be a solely Authentication owned value. We therefore no longer need to forward this to the backend as it doesn't use it anymore.
Deploy to authdev2:
- Ran through a journey
- Ran through an uplift journey
- All as expected
- https://github.com/govuk-one-login/authentication-api/pull/6538 PR which removed the backend usage of this field

ATO-1621: Stop forwarding current_credential_strength to backend

---

src/components/common/state-machine/state-machine.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-controller.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-validation.ts
src/components/how-do-you-want-security-codes/index.njk
src/components/how-do-you-want-security-codes/tests/how-do-you-want-security-codes-controller.test.ts
src/components/reset-password-2fa-auth-app/index.njk
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-controller.test.ts
src/components/reset-password-2fa-sms/index.njk
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/types.ts
src/locales/cy/translation.json
src/locales/en/translation.json

At present, we only allow the user to use a single MFA method (`mfaMethodType` in the session) to authenticate themselves. We want to allow the user to choose which MFA method they use, if they have multiple MFA methods set up.
This ticket covers adding the prompt to the auth app / SMS screens to allow the user to choose their method, if they have multiple MFA methods set up. This link should take them to the "how do you want security codes" page which provides them with a set of radio inputs for their MFA methods.
This ticket does not cover selecting the backup MFA method - see AUT-4183 for this.
[Backend work ~~is being~~ has been completed under a separate PR to update the resetPasswordRequest response to return the mfaMethods …

AUT-4256: present backup mfa method to user during password reset journey

---

src/components/authorize/authorize-service.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/types.ts

We would like to send the client name to the auth backend, so auth does not need to rely on the client registry to get this value. We are already sending the claim from orch to auth frontend, this PR is passing this claim onto the backend.
Deployed to authdev and tested a few journeys. All were successful

ATO-1669: Pass client_name claim to backend

---

src/components/authorize/authorize-service.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/types.ts

We would like to send the service type to the auth backend, so auth does not need to rely on the client registry to get this value. We are already sending the claim from orch to auth frontend, this PR is passing this claim onto the backend.
Deployed to authdev and tested. Journeys went fine.

ATO-1673: Pass service_type claim to auth backend

---

src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

We would like to send the subject type to the auth backend, so auth does not need to rely on the client registry to get this value. We are already sending the claim from orch to auth frontend, this PR is passing this claim onto the backend.
Tested on authdev2 for a couple of journeys and all works

ATO-1605: pass subject_type to backend

---

src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/tests/contact-us-questions-validation.test.ts

Significantly boosts testing coverage on questions validation.
Also removes an unnecessary statement.
I am of the view that this way of doing CC is super fiddly and not ideal. This testing was quick to implement and gives us some protection on something that's easy to mess up, but I don't think it's the end solution. 
1. Code Review

BAU: improve test coverage on questions validation

---

src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

We would like to move authentication away from using the ClientRegistry. To do this we need to pass information about the client from orch to auth, and store them on the auth session. A few fields we need have already been added as part of the client session migration.
This PR sends is_identity_verification_required to the backend.

ATO-1710: send is_identity_verification_required to auth backend

---

cloudformation/deploy/template.yaml

Temporarily increase ECS scaling configuration to support higher load.
In case of higher expected load merge this PR to increase the default task count and decrease the % cpu where ECS starts to scale.  This results in a higher initial base load before scaling starts and faster scaling.
1. Code Review
#2859

BAU: temporarily increase ECS scaling configuration to support higher load

---

src/components/common/journey/journey.ts
src/components/common/journey/tests/journey.test.ts
src/components/common/mfa/send-mfa-controller.ts
src/components/common/mfa/tests/send-mfa-controller.test.ts
src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-controller.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-2fa-sms/tests/__snapshots__/reset-password-2fa-sms-integration.test.ts.snap
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-integration.test.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/tests/__snapshots__/reset-password-check-email-integration.test.ts.snap
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts

We have a bug on password reset journeys where when a user triggers resending an SMS OTP it was being misattributed to the SIGN_IN journey, not PASSWORD_RESET_MFA. This meant that the count was also assigned to SIGN_IN incorrectly.
Here this is corrected by ensuring when requesting an SMS OTP via the /mfa API we send the correct journey.
This bug was also apparent when an SMS was sent after a user chooses their backup SMS MFA method.
We have a bug where a user will trigger two SMS OTP sends when attempting to try a resend on the password reset journey.
This happened as we were triggering an SMS OTP send on both the loading GET /reset-password-2fa-sms and POST /resend-code, and the "POST" was followed by a redirect to the "GET", thus triggering a second SMS send.
Now instead of sending an …

AUT-4452: Method management password reset MFA lockout fixes

---

src/components/select-mfa-options/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Reverts govuk-one-login/authentication-frontend#2867
Rdeploys https://github.com/govuk-one-login/authentication-frontend/pull/2847 following a rollback of the implementation on Thu 3 July 2025.

Redeploy "AUT-4255: mfa reset content changes"

---

src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts

- Adds uplift journey to journeys where 2hr lockout shown in the security-code-controller
- 15 minute lockouts should only be shown on account creation journeys as a measure to prevent spamming.
- See: https://govukverify.atlassian.net/wiki/spaces/LO/pages/3957162012/Business+Rules+Logic+for+Lockouts
1. Code Review
2. Go through uplift journey, enter SMS MFA 6 times and see 2 hour lockout

AUT-4189: add uplift journey to journeys where 2hr lockout shown

---

src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-controller.ts
src/components/how-do-you-want-security-codes/tests/how-do-you-want-security-codes-controller.test.ts
src/types.ts

- Previously, a user would be sent an OTP each time they selected an SMS MFA on the how do you want security codes screen, as long as it was not the last MFA selected.
- This commit fixes that issue by listing the MFA ID an OTP was sent to on the sentOtpMfaMethodIds array on a user's session if it has had an OTP sent to it in a given session.
- An MFA code will only be sent if the ID is not on this list and it is not the most recently selected MFA (mfaMethodId !== activeMfaMethodId).

AUT-4467: Fix resending SMS MFA OTP to number already sent OTP

---

src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-routes.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-validation.ts
src/components/reset-password-2fa-auth-app/tests/__snapshots__/reset-password-2fa-auth-app-integration.test.ts.snap
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-integration.test.ts

Add validation to the `reset-password-2fa-auth-app` routes to ensure that we can't send an empty code or a code with letters
1. Code Review
2. Deploy to a dev environment and follow the ACs on the [ticket here ](https://govukverify.atlassian.net/browse/AUT-4558) to ensure that you get the correct errors
https://github.com/user-attachments/assets/c303282f-dc35-4c30-b184-cc2c072ba98d

AUT-4558: Reset password 2fa auth app missing validation

---

src/components/common/mfa/send-mfa-controller.ts
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/components/resend-mfa-code/tests/resend-mfa-code-controller.test.ts

Show the 2 hour lockout screen when `isLocked(req.session.user.wrongCodeEnteredLock)` is true
1. Code Review
2. Deploy to dev env and test the fix works (follow [steps on ticket](https://govukverify.atlassian.net/browse/AUT-4473) and check that the 2 hour lockout screen is shown instead of 15 minute) 
https://github.com/user-attachments/assets/ea097be9-8581-41a3-92a2-a769f2c0b132

AUT-4473: Incorrect SMS MFA lockout screen when requesting new code sign in journey

---

src/components/contact-us/tests/contact-us-controller-integration.test.ts

Use a string instead of relying on the env variables for the `smartAgentApiUrl` inside `contact-us-controller-integration.test.ts` to prevent failing tests locally if you don't have correct env variables
1. Code Review

BAU: Use string instead of env variable in smart agent api url for integration tests

---

.github/dependabot.yml

Ignore @govuk-one-login/frontend-analytics versions >= 4.0.1
This version caused acceptance tests to fail in staging.  Different tests failed on different test runs.
Can be removed when the issue has been resolved.
See:
Test-frontend-pipeline:0b1303b3-0043-4927-b3d5-f6a7cb981dc0
Test-frontend-pipeline:1f75db58-a043-40ca-a177-b8ba99375064
1. Code Review
#2938 
#2940 
#2941

BAU: Ignore @govuk-one-login/frontend-analytics versions >= 4.0.1

---

journey-map/package.json
journey-map/src/index.ts
journey-map/src/mermaid.ts
package.json
src/app.ts
src/assets/scss/application.scss
src/components/templates/index.njk
src/components/templates/pages.ts
src/components/templates/templates-controller.ts
src/components/templates/templates-routes.ts

Add template viewer to auth frontend in non-prod environments. Currently only includes main (non optional) journey states, but can be easily extended.
This allows you to see a list of pages in the app:
Selecting one allows you to preview that page outside of a journey:
The journey map is also updated so that double-clicking on a page state (in green) opens up a preview of that page:
1. Code Review
1. Test locally with `yarn dev` and visiting both https://localhost:3000/templates and https://localhost:3000/journey-map
1. [Optional] Deploy to a dev environment and test there

Aut 4440/template viewer

---

journey-map/public/style.css
journey-map/src/index.ts
journey-map/src/mermaid.ts
src/components/common/state-machine/state-machine.ts

- Added common state for 'sign-in end', abstracting away the need to distinguish T&Cs accepted in each final auth step
- Added common state for 'password verified', ensuring both variants map the same paths
- Some styling tweaks to highlighted states and labels
Although this adds more states to the map, it reduces the total number of elements as it eliminates a bunch of parallel state transitions.
A more sophisticated approach here could instead use a 'sub-journey', completely abstracting the common states.
1. Code Review
1. Marvel at journey map locally
1. Ensure integration tests pass

AUT-4686: Common journey states

---

custom-lint-rules/no-res-locals-write.js
src/components/account-created/account-created-controller.ts
src/components/account-not-found/account-not-found-controller.ts
src/components/account-recovery/change-security-codes-confirmation/change-security-codes-confirmation-controller.ts
src/components/authorize/authorize-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/common/account-recovery/tests/account-recovery-helper.test.ts
src/components/common/constants.ts
src/components/common/mfa/send-mfa-controller.ts
src/components/common/state-machine/state-machine-executor.ts
src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/create-password/create-password-controller.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-phone-number/enter-phone-number-controller.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-controller.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/resend-email-code/resend-email-code-controller.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password/reset-password-controller.ts
src/components/select-mfa-options/select-mfa-options-controller.ts
src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
src/components/sign-in-or-create/sign-in-or-create-controller.ts
src/components/updated-terms-conditions/updated-terms-conditions-controller.ts
src/middleware/account-interventions-middleware.ts

- Removed `path` argument - using `req.path` simplifies logic and avoids 'hidden' transitions
- Added `res` argument - mirrors `req`, and provides access to locals
- Removed `sessionId` argument - can read from locals
- Extracted state machine executor from misleadingly named `constants.ts`
Largely these are innocuous changes. There is one case where we were passing a path that didn't match the request (see comment).
The aim of these changes is to give us more flexibility in the state machine execution without needing to update all the call-sites. A couple of examples:
- Automatically generating the `ctx` argument based on the session/locals, rather than needing to know what context to pass in to each step
- Executing additional actions when passing through states (e.g. sending an MFA …

BAU: Revise state machine interface

---

cloudformation/deploy/template.yaml

Increase minimum number of ECS tasks in staging from 9 to 12
During the last performance test the event loop was satured during ramp up, so adding more initial capacity to deal with the required load for the next test.
1. Code Review

BAU: Increase minimum number of ECS tasks in staging from 9 to 12

---

src/components/authorize/authorize-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/common/mfa/send-mfa-controller.ts
src/components/common/state-machine/state-machine-executor.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/create-password/create-password-controller.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-integration.test.ts
src/components/enter-password/tests/enter-password-reauth-integration.test.ts
src/components/how-do-you-want-security-codes/how-do-you-want-security-codes-controller.ts
src/components/resend-email-code/resend-email-code-controller.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-auth-app/tests/reset-password-2fa-auth-app-controller.test.ts
src/components/reset-password-2fa-sms/tests/reset-password-2fa-sms-controller.test.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/tests/reset-password-check-email-auth-app-2fa-integration.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-integration.test.ts
src/components/reset-password/tests/reset-password-required-integration.test.ts
src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
src/components/updated-terms-conditions/updated-terms-conditions-controller.ts
src/types.ts

Compute state machine context from current session instead of passing in bespoke parameters at each call-site. This should make it easier to reason about the state machine and use existing conditions elsewhere.
Also:
- Refine logging to make it easier to analyse journeys
- Remove some impossible transitions
New journey map:
1. Code Review
1. Ensure all acceptance tests still pass
https://github.com/govuk-one-login/authentication-frontend/pull/2962

BAU: State machine auto context

---

src/components/common/state-machine/state-machine-executor.ts
src/components/enter-email/enter-email-controller.ts
src/types.ts

This reverts commit cc290ca790781e5bf4693288339709f7d1c18aa3.
Remove `enterEmailMfaType`, superseded by `mfaMethodType`.
See also https://github.com/govuk-one-login/authentication-frontend/pull/2969

Revert "BAU: Keep enterEmailMfaType for ZDD"

---

src/app.ts
src/components/authorize/authorize-controller.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/templates/templates-controller.ts
src/middleware/account-interventions-middleware.ts
src/middleware/session-middleware.ts
src/utils/http.ts
src/utils/logger.test.ts
src/utils/logger.ts

- Add useful log context to request logger
- Use request logger where possible
- Redact sensitive/large query params (i.e. JAR payloads and auth codes)
```
{
"level": 30,
"time": 1757954030841,
"pid": 6,
"hostname": "<ECS task>",
"name": "di-auth",
"req": {
"id": 12345,
"method": "GET",
"url": "/enter-password",
"from": "/enter-email"
},
"res": {
"status": 200,
"sessionId": "<session id>",
"clientSessionId": "<journey id>",
"persistentSessionId": "<persistent session id>",
"languageFromCookie": "EN",
"clientId": "<client id>"
},
"timeTaken": 5,
"msg": "request completed with status code of: 200"
}
```
Standard properties are lifted to top level and client session id => journey id:
```
{
"level": 30,
"time": 1757954030841,
"pid": 6,
"hostname": "<ECS task>",
"name": "di-auth",
"req": { …
```

BAU: Improve logging context
