govuk-one-login/authentication-frontend

locales/en/translation.json
src/controllers/create-account.ts
src/controllers/enter-phone-number-controller.ts
src/routes.ts
src/views/enter-phone-number.html

Add Enter Phone Number screen.

LTG-35: add enter-phone-number screen

---

.env.sample
README.md
docker-compose.yml
src/app.constants.ts
src/config.ts
src/config/logging/winston.ts
src/controllers/create-account.ts
src/controllers/enter-email-controller.ts
src/error-handler.ts
src/middleware/form-validation-middleware.ts
src/services/authentication-service.interface.ts
src/services/authentication-service.ts
src/services/dynamo-user-service.ts
src/services/service-injection.ts
src/services/types/user.ts
src/services/user-service.ts
src/utils/http.ts
src/views/enter-phone-number.html
startup.sh
tests/unit/routes/enter-email.test.ts
tests/unit/utils/string-utils.test.ts

Call /userexists api resource with the email address provided by the user.
Add HTTP client, update tests for enter-email and clean up codebase.
See if the user already has an account.
Create a reusable http client with common services.

LTG-17: call userexists api resource with reusable http client

---

.eslintignore
@types/cookie-session/index.d.ts
@types/express/index.d.ts
locales/en/translation.json
package.json
src/app.constants.ts
src/app.ts
src/config.ts
src/controllers/enter-email-controller.ts
src/error-handler.ts
src/middleware/session-middleware.ts
src/routes.ts
src/services/authentication-service.interface.ts
src/services/authentication-service.ts
src/services/types/user-signup-credentials.ts
src/types/user-session.ts
src/utils/http.ts
src/utils/session.ts
src/views/create-account.html
src/views/enter-password.html
src/views/errors/session-expired.html
tests/unit/middleware/session-middleware.ts
tests/unit/utils/session.test.ts
yarn.lock

Add a client session using cookie-session.
Call the /signup api after user enters a password.

LTG-35: add client session and call to /signup api

---

package.json
src/config/logging/winston.ts
src/controllers/enter-email-controller.ts
src/controllers/enter-password-controller.ts
src/controllers/register-create-password-controller.ts
src/controllers/register-enter-phone-number-controller.ts
src/error-handler.ts
src/routes.ts
src/services/authentication-service.ts
src/services/types/user-signup-credentials.ts
src/types/user-session.ts
src/utils/http.ts
src/utils/session.ts

Add Prettier config.
Reformat all source to conform with the standard.
Need the same formatting rules for everyone to avoid conflicts.

BAU: add Prettier config

---

ci/pipeline.yaml
manifest.yml
src/controllers/enter-email-controller.ts
src/routes.ts

Added in secrets for config values and fixed issues with build

Add concourse secrets and fixed issues with codebase

---

locales/en/translation.json
src/controllers/register-create-password-controller.ts
src/views/create-account.html

Add max password length and validation message.
Style tweaks to make the page look like the prototype.
Need a max password length for security reasons.

LTG-35: max password length and style tweaks to Create Password

---

src/app.constants.ts
src/controllers/check-your-email-controller.ts
src/controllers/enter-email-controller.ts
src/routes.ts
src/services/authentication-service.interface.ts
src/services/authentication-service.ts
src/services/types/send-notification-request.ts
src/views/check-your-email.html

Call email notification service and redirect to 'check your email' page.
Page is a skeleton pending full content.
Only developers in our test Notify account are able to received email notifications.
Need user to enter the code sent to their email address.

LTG-311: Call email notification service and redirect to 'check your email' page

---

locales/en/translation.json
src/components/register-verify-email/index.njk
src/components/register-verify-email/register-verify-email-routes.ts

- Add the basic content to the verify email address page
- The rest of the functionality and validation messages will be added in LTG-34

LTG-360 - Add content to verify email address

---

src/services/authentication-service.ts
src/services/notification-service.interface.ts
src/services/notification-service.ts
src/utils/http.ts

The session id was being set incorrectly on the http client so this has been fixed

LTG-17 updated http client to take in session explicitly

---

.github/PULL_REQUEST_TEMPLATE.md
CODEOWNERS

- Add a PR template 
- Add GitHub CODEOWNERS, so reviews are prompted automatically

BAU - Add github template and CODEOWNERS

---

startup.sh

Add local startup option to startup.sh.
Can be quicker to run locally rather than use Docker.

BAU: add local startup option to startup.sh

---

README.md
package.json
src/components/enter-email/tests/enter-email-integration.test.ts
yarn.lock

Update running of mocha tests
So the unit tests and integration tests can be run by a separate command.

Separated running of tests and added mocha config to package.json

---

.github/workflows/pre-merge-checks.yml

We'll run `yarn test:unit` for PRs and passing is now a pre-requisite for merge

LTG-355: Pre-merge checks

---

src/components/enter-email/tests/enter-email-controller.test.ts
src/components/register-create-password/tests/register-create-password-controller.test.ts

- Write unit test for when a user creates password
- So it is well tested

LTG-35 - Write unit test for when a user creates password

---

src/config/i18next.ts

The translation files are not rendering so this is to fix that.
So users can see different text for en or cy

Update path for translations

---

src/app.ts
src/config/i18next.ts

Should fix translation issue see other commits for more detail PR messages

update translation path to passed to config

---

src/config/i18next.ts

Enabled logging for translation

---

src/components/register-verify-email/tests/register-verify-email-controller.test.ts

Unit test for 'check your email' GET.
Provide test coverage for this controller method.

LTG-371: Unit test for 'check your email' GET

---

session-start-local.sh

Update session-start-local script.
Due to changed /authorize parameters.

BAU: update session-start-local script

---

src/components/verify-email/tests/verify-email-integration.test.ts
src/locales/en/translation.json

Update validation message for when incorrect code entered.
The content has been updated so this needs reflecting in the code base.

Update validation message when incorrect code

---

ci/pipeline.yaml

Change git branch for app to fix issue with redirect

Update branch for pipeline

---

ci/pipeline.yaml

Update pipeline to main.
So the code deployed is from the main branch

Update pipeline back to main

---

src/app.ts
src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/cookies-routes.ts
src/components/common/cookies/index.njk
src/components/common/footer/accessibility-statement.njk
src/components/common/footer/footer-pages-controller.ts
src/components/common/footer/footer-pages-routes.ts
src/components/common/footer/privacy-statement.njk
src/components/common/footer/terms-conditions.njk
src/components/common/layout/base.njk
src/locales/en/translation.json

Add footer links to app.
So users can navigate to the necessary pages.

Add footer links to base layout

---

src/components/security-code-expired/index.njk
src/locales/en/translation.json

Updated content for security-code-expired existing user, phone mode.
Use correct page title.
Content has been updated.

GOVSI-429: updated content for security-code-expired existing user, phone mode.

---

src/components/common/footer/accessibility-statement.njk
src/locales/en/translation.json

Add accessibility statement page content.
As a user 
I want to view the accessibility statement  
So that I know how accessible the service is for me

GOVSI-110: add accessibility statement page content

---

src/app.constants.ts
src/app.ts
src/components/signed-out/index.njk
src/components/signed-out/signed-out-controller.ts
src/components/signed-out/signed-out-routes.ts
src/components/signed-out/tests/signed-out-controller.test.ts
src/locales/en/translation.json

Create signed out page.
As a user
I want confirmation that I have signed out of my account 
So that I am confident my information is safe

GOVSI-153: create signed out page

---

src/assets/javascript/cookies.js

Update cookies.js file to work in internet explorer.
The application needs to work in IE11.

Update cookies.js to work in IE

---

.eslintignore
dev-app.js
package.json

Implement an app to get a proper session from the authorize endpoint.
This is needed to test the flow locally.

Create app to allow local session

---

src/components/check-your-phone/tests/check-your-phone-integration.test.ts
src/components/common/layout/banner.njk
src/components/create-password/tests/create-password-integration.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts
src/components/verify-email/tests/verify-email-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Align figma errors with front end.
Figma is ahead of the front end app so they need to be aligned.

Align error messages with figma

---

docker-compose.yml
nodemon.json
package.json
startup.sh
yarn.lock

Minify and compress css and js.
This improves performance of the app and also is part of productionizing the front end.

Bau minify assets

---

src/locales/en/translation.json

Update page titles according to the latest Figma
.
Figma content has been updated since these pages were created.

GOVSI-520: Update page titles according to the latest figma

---

src/assets/scss/application.scss
src/components/account-created/account-created-controller.ts
src/components/account-created/index.njk
src/components/sign-in-or-create/sign-in-or-create-controller.ts
src/components/updated-terms-conds/tests/updated-terms-conds.test.ts
src/components/updated-terms-conds/updated-terms-conds-controller.ts
src/locales/en/translation.json

Content changes for govis-692 and govsi-693

Content changes for 692 & 693

---

manifest.yml
src/config.ts
src/utils/http.ts

- Configure the frontend app with the API key
- Include the api key in all requests to the backend api so it can be authenticated

GOVSI-790 - Configure the frontend app with the API key

---

.github/workflows/pre-merge-checks.yml
src/app.constants.ts
src/components/account-created/account-created-controller.ts
src/components/account-not-found/account-not-found-controller.ts
src/components/account-not-found/account-not-found-routes.ts
src/components/account-not-found/tests/account-not-found-controller.test.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/enter-password-routes.ts
src/components/enter-password/enter-password-validation.ts
src/components/enter-password/tests/enter-password-controller.test.ts
src/components/share-info/tests/share-info-integration.test.ts
src/components/sign-in-or-create/sign-in-or-create-controller.ts
src/components/sign-in-or-create/sign-in-or-create-service.ts
src/components/sign-in-or-create/sign-in-or-create-validation.ts
src/components/sign-in-or-create/tests/sign-in-or-create-controller.test.ts
src/components/updated-terms-conds/tests/updated-terms-cond-integration.test.ts
src/components/updated-terms-conds/tests/updated-terms-conds.test.ts
src/components/updated-terms-conds/updated-terms-conds-controller.ts
src/components/updated-terms-conds/updated-terms-conds-routes.ts
src/locales/en/translation.json
src/utils/http.ts

GOVSI-790 - Re-add http.interceptors.request as it is needed

---

manifest.yml
src/app.ts
src/assets/javascript/application.js
src/assets/javascript/cookies.js
src/components/common/layout/base.njk
src/config.ts
src/config/helmet.ts
src/middleware/set-local-vars-middleware.ts
src/utils/strings.ts

Add Google Tag Manager scripts to the header in all pages, along with a hidden iframe at the top of the page body, via the base template.
The Performance Team will be using Google Tag Manager for analytics.  I'm told the hidden iframe is part of the GTM magic.  See the JIRA ticket for more details.

GOVSI-128: Add Google Tag Manager scripts

---

src/assets/javascript/cookies.js

Remove data layer for GTM.
Asked by performance analyst to do so.

Remove GTM datalayer as requested

---

src/app.constants.ts
src/components/reset-password-check-email/index.njk
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/reset-password-check-email-routes.ts
src/components/reset-password-check-email/reset-password-check-email-service.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/reset-password-check-email/types.ts

Call 'reset password request' service when user clicks on the 'I've forgotten my password link'
Clicking on the link should send a password reset email, need to call the backend to send this.
#205

GOVSI-485: call 'reset password request' service

---

src/assets/javascript/cookies.js

Fix GTM.
Link tracking is not working

Add fix in for GTM

---

src/components/security-code-expired/index.njk

Fix template as it has incorrect elements.

Fix issue with security code template

---

docker-compose.yml
src/locales/en/translation.json

Currently, the session duration is set to 1800sec (30mins). We need to change it to 3600sec (60mins).

Session time from 30 mins to 60 mins

---

src/components/account-not-found/account-not-found-controller.ts
src/components/check-your-email/index.njk
src/components/enter-password/index-account-exists.njk
src/locales/en/translation.json

- Update check your email content 
- Fix enter-email link when registering
- Fix reset password link 
The UX doesn't match figma.

Update page content and fix broken links

---

src/components/check-your-phone/index.njk
src/components/common/layout/base.njk
src/components/enter-mfa/index.njk

Removing unneeded back transitions

Removing unneeded back transitions

---

src/components/updated-terms-conditions/index-mandatory.njk
src/components/updated-terms-conditions/index-optional.njk
src/components/updated-terms-conditions/updated-terms-conditions-controller.ts

Fix client name display issue with terms and conditions

Fix client name display issue

---

src/components/account-created/index.njk
src/components/check-your-phone/index.njk
src/components/enter-mfa/index.njk
src/components/reset-password/index-confirmation.njk
src/components/sign-in-or-create/index.njk
src/components/updated-terms-conditions/index-mandatory.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update content to match figma final designs.

Update content to match figma

---

src/components/account-created/account-created-controller.ts
src/components/account-created/index.njk

Update link for account created CTA.
Goes to wrong place.

Fix CTA for account created

---

src/components/enter-email/enter-email-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- Update reset password labels to align with figma
- Fix user journey via back buttons when creating an account
To fix a bug and align the screens with figmas final design.

Govsi 892 fix login journey back button

---

package.json
src/utils/http.ts
yarn.lock

- Dependabot updates
- Remove copying of robots.txt

Govsi 1050

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-service.ts
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/types.ts

Include contextual information when submitting the support form, for example:
session id
user agent
Some support tickets have no information which would enable us to understand what the user was doing when they encountered an issue, or to see the error they received in the logs.

Update contact form to add in session id and user agent

---

src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts

Remove not needed unit test

---

dev-app.js
src/components/auth-code/auth-code-controller.ts
src/components/auth-code/tests/auth-code-controller.test.ts
src/components/landing/landing-controller.ts
src/components/landing/tests/landing-controller.test.ts

Add support for _ga query param to be passed on redirects.
For perfomance team.

Add support for _ga parameter to be passed to RP

---

src/components/common/footer/privacy-statement.njk

Remove duplicate line from privacy statement.

Remove duplicate line

---

src/assets/scss/application.scss

Fix padding on terms and conditions page.

Fix padding on terms and conditions page

---

src/app.constants.ts
src/components/common/footer/terms-conditions.njk
src/components/common/layout/base.njk
src/components/create-password/index.njk
src/components/updated-terms-conditions/index-mandatory.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Change privacy statement url to privacy notice

Change privacy statement links

---

.github/workflows/pre-merge-checks.yml
src/app.constants.ts
src/assets/javascript/application.js
src/assets/javascript/cookies.js
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-routes.ts
src/components/contact-us/contact-us-validation.ts
src/components/contact-us/index-gov-service-contact-us.njk
src/components/contact-us/index-public-contact-us.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Update feedback form to be aligned with DFA figma.
To help improve UX/UJ.

Update feedback form

---

src/components/account-created/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update content for account created page.
As brexit checker is being retired.

Update content for account created page 

---

package.json
src/assets/javascript/application.js
src/assets/javascript/showPassword.js
src/assets/scss/application.scss
src/components/common/layout/base.njk
src/components/enter-password/_show-password.njk
src/components/enter-password/index-account-exists.njk
src/components/enter-password/index.njk

Add show password functionality. 
To allow users to check their password is correct.

Add show password functionality

---

src/assets/javascript/application.js

Fix module issue with show password feature.

Fix js issue with show password

---

src/assets/javascript/application.js
src/components/common/layout/base.njk
src/components/common/show-password/macro.njk
src/components/create-password/index.njk
src/components/enter-password/index-account-exists.njk
src/components/enter-password/index.njk
src/components/reset-password/index.njk

For consistency add the show password feature on all password inputs.

Add show password functionality to all password fields

---

src/components/common/layout/base.njk

Govsi 1232

---

src/components/sign-in-or-create/index.njk

Fix missing html block

---

src/components/sign-in-or-create/index.njk

Add missing class

---

src/components/sign-in-or-create/index.njk

Fix full stop in link

---

src/app.ts
src/assets/javascript/cookies.js
src/components/auth-code/auth-code-controller.ts
src/components/auth-code/tests/auth-code-controller.test.ts
src/components/enter-mfa/index.njk
src/components/enter-password/index-account-exists.njk
src/components/enter-password/index.njk
src/components/landing/landing-controller.ts
src/components/uplift-journey/uplift-journey-controller.ts
src/middleware/cross-domain-tracking-middleware.ts

Add in cross domain tracking middleware.
To fix cross domain tracking where the _ga parameter has expired.

Add in GA link generator to fix cross domain tracking

---

src/assets/javascript/cookies.js
src/components/account-created/index.njk
src/components/reset-password/index-expired.njk
src/components/reset-password/index-invalid.njk
src/components/updated-terms-conditions/index-mandatory.njk
src/components/updated-terms-conditions/index-optional.njk
src/components/updated-terms-conditions/index.njk

Add tracking to more pages.
To fix any missing links when moving between domains.

Add GA tracking to missing pages

---

package.json
yarn.lock

Upgrade axios to 0.25.0
Keep versions current.

BAU: upgrade axios to 0.25.0

---

src/components/reset-password-check-email/index-exceeded-request-count.njk
src/components/reset-password-check-email/index-request-attempt-blocked.njk
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Update content shown when the user requests too many password resets.
Content was not as expected so needed updating.

AUTH-1355: content for user password resets exceeded

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-service.ts
src/components/contact-us/questions/_account-creation-problem-questions.njk
src/components/contact-us/questions/_account-not-found-questions.njk
src/components/contact-us/questions/_another-problem-questions.njk
src/components/contact-us/questions/_email-subscriptions-questions.njk
src/components/contact-us/questions/_forgotten-password-questions.njk
src/components/contact-us/questions/_invalid-security-code-questions.njk
src/components/contact-us/questions/_no-phone-number-access-questions.njk
src/components/contact-us/questions/_no-security-code-questions.njk
src/components/contact-us/questions/_no-uk-mobile-questions.njk
src/components/contact-us/questions/_signing-in-problem-questions.njk
src/components/contact-us/questions/_suggestion-feedback-questions.njk
src/components/contact-us/questions/_technical-error-questions.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/components/contact-us/types.ts

- Send the questions and radio buttons selected to Zendesk.
- So it is clear what questions the user has answered.

AUTH-1393 - Add questions to Zendesk form 

---

src/assets/javascript/cookies.js
src/assets/scss/application.scss
src/components/account-not-found/index-optional.njk
src/components/sign-in-or-create/index.njk

Add id on to sign button for AC tests.

Add id to button on sign and create for AC tests

---

src/components/create-password/create-password-controller.ts
src/components/create-password/create-password-service.ts
src/components/create-password/types.ts

Add missing client session id for sign up call.

Add clientsessionid to signup call

---

src/components/account-created/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update content on account created page to match figma.

Update content on account created page

---

src/assets/javascript/application.js
src/assets/scss/application.scss
src/components/enter-phone-number/enter-phone-number-controller.ts
src/components/enter-phone-number/enter-phone-number-validation.ts
src/components/enter-phone-number/index.njk
src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts
src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/phone-number.ts
src/utils/strings.ts
test/unit/utils/phone-number.test.ts
test/unit/utils/strings.test.ts

Reverts alphagov/di-authentication-frontend#533

Revert "AUTH-1360: support international phone numbers"

---

src/components/contact-us/contact-us-controller.ts
src/components/contact-us/further-information/_account-creation-further-information.njk
src/components/contact-us/further-information/_signing-in-further-information.njk
src/components/contact-us/index-public-contact-us.njk
src/components/contact-us/questions/_account-creation-problem-questions.njk
src/components/contact-us/questions/_account-not-found-questions.njk
src/components/contact-us/questions/_another-problem-questions.njk
src/components/contact-us/questions/_email-subscriptions-questions.njk
src/components/contact-us/questions/_forgotten-password-questions.njk
src/components/contact-us/questions/_invalid-security-code-questions.njk
src/components/contact-us/questions/_no-phone-number-access-questions.njk
src/components/contact-us/questions/_no-security-code-questions.njk
src/components/contact-us/questions/_no-uk-mobile-questions.njk
src/components/contact-us/questions/_signing-in-problem-questions.njk
src/components/contact-us/questions/_suggestion-feedback-questions.njk
src/components/contact-us/questions/_technical-error-questions.njk
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts

- Change fromPage to referer
- Change the name of the fromPage parameter to referer to make it clear what it is and to make it more subtle

AUTH-1442 - Change fromPage to referer

---

src/assets/javascript/cookies.js

Check if ga and its plugins in exist before trying to add the _ga to links.
To support ad blockers.

Check if ga present to stop issues with ad blockers

---

.github/workflows/pre-merge-checks.yml
ci/tasks/deploy-frontend.yml
ci/terraform/ecs.tf
ci/terraform/variables.tf
src/assets/javascript/application.js
src/assets/scss/application.scss
src/components/enter-phone-number/enter-phone-number-controller.ts
src/components/enter-phone-number/enter-phone-number-validation.ts
src/components/enter-phone-number/index.njk
src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts
src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/utils/phone-number.ts
src/utils/strings.ts
test/unit/utils/phone-number.test.ts
test/unit/utils/strings.test.ts

Reverts alphagov/di-authentication-frontend#536

Revert "Revert "AUTH-1360: support international phone numbers""

---

ci/tasks/deploy-frontend.yml

AUTH-1360 - Remove unused var

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Update content to match figma.

Update sign in and create content

---

src/components/enter-password/index-account-exists.njk
src/components/enter-password/index-account-locked.njk
src/components/enter-password/index.njk

Reverts alphagov/di-authentication-frontend#570

Revert "AUT-57: drain in-flight password resets"

---

src/components/common/state-machine/state-machine.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/reset-password-check-email-routes.ts
src/components/reset-password-check-email/reset-password-check-email-service.ts
src/components/reset-password-check-email/reset-password-check-email-validation.ts
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/reset-password-service.ts
src/components/reset-password/tests/reset-password-controller.test.ts

Clean up unformatted code.
Running this on reset password with code was formatting unrelated files so left it until after.
#569

BAU: run yarn pretty

---

src/app.constants.ts
src/app.ts
src/components/common/state-machine/state-machine.ts
src/components/landing/landing-controller.ts
src/components/landing/tests/landing-controller.test.ts
src/components/landing/types.ts
src/components/prove-identity-welcome/index-existing-session.njk
src/components/prove-identity-welcome/index.njk
src/components/prove-identity-welcome/prove-identity-welcome-controller.ts
src/components/prove-identity-welcome/prove-identity-welcome-routes.ts
src/components/prove-identity-welcome/prove-identity-welcome-validation.ts
src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/types.ts

Add interstitial page for prove your identity.

Add in prove identity welcome page

---

src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/prove-identity-callback/prove-identity-callback-controller.ts
src/components/prove-identity-callback/prove-identity-callback-routes.ts
src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts
src/components/prove-identity/prove-identity-controller.ts
src/components/prove-identity/tests/prove-identity-controller.test.ts

Fix IPV core callback so it state machine can handle it.

Add in handling of IPV core callback

---

.github/workflows/pre-merge-checks.yml
.prettierignore
package.json

Run prettier as PR check
PR checks will fail if prettier has not been run and the code is not correctly formatted.

BAU: run prettier as PR check

---

src/app.ts

- Register IPV callback route
- Currently seeing an error because this is not registered

BAU - Register IPV callback route

---

src/components/enter-password/enter-password-validation.ts

Update template name to fix bug as existing file name no longer exists.

Update template name to correct one

---

src/components/doc-checking-app/doc-checking-app-service.ts

Add empty POST body so calls correct axios method.

Add empty body for POST doc checking app

---

src/components/check-your-phone/index.njk
src/components/enter-mfa/index.njk
src/components/reset-password-check-email/index.njk

Disable autocomplete on mfa inputs.

disable autocomplete on mfa number inputs

---

src/components/common/footer/accessibility-statement.njk
src/components/common/footer/privacy-statement.njk
src/components/common/footer/terms-conditions.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Fix hyperlink issues on various pages in footer.

Update content to remove incorrect formatting

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/variables.tf

ECS rollout config tweaks to all environments.
Rollout to build and integration was successful.
#585

AUT-212: ecs rollout config tweaks to all environments

---

ci/terraform/build.tfvars

Switch on frontend auto scaling in build.
Gradual rollout of auto scaling, testing in build.
#591

AUT-213: switch on frontend auto scaling in build

---

src/app.constants.ts
src/components/prove-identity-welcome/prove-identity-welcome-controller.ts
src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts

Update error code when redirecting back to RP to use a standard OIDC error code.

Update error back to RP to be standard OIDC code

---

src/components/common/layout/banner.njk

Update formatting for cookie banner text

Update formatting for cookie banner text

---

src/middleware/process-identity-rate-limit-middleware.ts
src/types.ts
src/utils/date.ts
test/unit/middleware/process-identity-rate-limit-middleware.test.ts

Store epoch instead of date object to simplify comparison.

Store epoch instead of date object

---

Dockerfile
Dockerfile-stub
local.Dockerfile
package.json

Optimise docker images.
- Do not deploy dev dependencies
- Change file ownership to node in target image
- Run as node user
- Add image digests

AUT-354: Optimise docker images

---

src/locales/cy/translation.json
src/locales/en/translation.json

- Update hint text for user not receiving a security code

AUT-259 - Update hint text for user not receiving a security code

---

src/components/create-password/create-password-validation.ts
src/components/reset-password/reset-password-validation.ts
src/utils/strings.ts
test/unit/utils/strings.test.ts

- Remove check to see if string contains letter
- We already do this by checking whether the string contains a number so we can remove this redundant validation

AUT-302 - Remove check to see if string contains letter

---

src/components/create-password/index.njk
src/components/reset-password/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Ensure the user knows the restrictions on passwords before they create or reset one.
- It is important to provide users with information prior to error handling, to help them clearly understand what the specific requirements are for entering data.

AUT-461 - Update password quality text

---

src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/setup-authenticator-app/setup-authenticator-app-service.ts

Update params for verify mfa code api call as they were incorrect and missing 2 extra values.

Update verify mfa code to have correct api call

---

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/index-public-contact-us.njk
src/components/contact-us/questions/_proving-identity-problem-questions.njk
src/components/contact-us/questions/index.njk
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Reverts alphagov/di-authentication-frontend#622

Revert "Revert "AUT-424 - Update user support form with new page""

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

New Privacy statement tweaks post review.
Some small content changes required.
#643

BAU: New Privacy statement tweaks post review

---

src/locales/en/translation.json

Update the content of the "About GOV.UK accounts" dropdown for MVP.
~Don't merge this yet, due to go out next week.~
So that the content of the dropdown is more representative of the current state of the account.

GUA-222: Update account blurb for MVP

---

ci/tasks/deploy-frontend.yml
ci/terraform/ecs.tf
ci/terraform/variables.tf

- Pass env var through terraform
- So application can read it

BAU - Pass env var through terraform

---

src/components/common/cookies/index.njk
src/locales/en/translation.json

- Add 5 new cookies to the `strictly necessary cookies`
- Add 1 new cookie to the `cookies that remember your settings`
- To reflect the cookies which are in use in the service

AUT-552 - Update cookie policy

---

src/app.ts

- Enable Doc App routes in production
-

BAU - Enable Doc App routes in production

---

src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
src/locales/en/translation.json

International number content updates.
Change some text on the 'enter your mobile phone number' screen for international numbers only.
To reflect the latest designs.

AUT-510: International number content updates

---

src/components/contact-us/contact-us-questions-validation.ts
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/locales/en/translation.json

- Fix validation error on the feedback form
- There is currently a non-sensical error message being shown to users when they enter their email address in an invalid format. Correct this to show the right error message.

AUT-558 - Fix validation error on the feedback form

---

src/components/contact-us/contact-us-controller.ts

Update form information when submitting a support ticket.
Field no longer required.

BAU: Update form information when submitting a support ticket

---

src/components/check-your-email/index.njk
src/components/common/state-machine/state-machine.ts
src/components/reset-password-check-email/index.njk
src/locales/en/translation.json

Adds details element to two components (`check-your-email` and `reset-password-check-email`) and removes replaced content. Updates the `translation.json` file to reflect these changes. 
Reflects change requested in the Jira ticket

AUT-599: Introduce details component via Nunjucks and translation

---

src/components/sign-in-or-create/index.njk
src/components/sign-in-or-create/sign-in-or-create-controller.ts
src/config.ts

Conditional inset text to switch to Welsh language, based on a feature switch.
The text will only display when we switch Welsh language support on.
The switching functionality itself will be implemented in another PR.
To show the user that Welsh language is available and how to switch to using it.

AUT-618: Conditional inset text to switch to Welsh language

---

ci/tasks/deploy-frontend.yml
ci/terraform/ecs.tf
ci/terraform/variables.tf
docker-compose.yml
src/locales/cy/translation.json

Upload welsh translation file.
- Correct syntax in order to make the json well-formed (otherwise the file does not load and the app falls-back to English).
- Add back the link to switch from Welsh to English (as this was added after the file was sent).
- Add infrstructure to support the Welsh language feature switch.
A further PR is required in the pipeline to switch on in Staging.
A Welsh language version of the application is required.
Enable first view testing of the translation.

AUT-200: Upload welsh translation file

---

ci/tasks/deploy-frontend.yml
ci/terraform/build.tfvars
ci/terraform/cloudwatch.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf

BAU: Publish CSLS logs to new endpoint

---

src/components/security-code-error/security-code-error-controller.ts

Reverts alphagov/di-authentication-frontend#784

Revert "ACI-7: Don't ask for email again after max verify code retries"

---

src/components/common/send-notification/send-notification-service.ts
src/components/common/send-notification/types.ts
src/components/resend-email-code/index.njk
src/components/resend-email-code/resend-email-code-controller.ts
src/components/security-code-error/index.njk
src/components/security-code-error/security-code-error-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Do not ask a new user to re-enter email when they request another code having exceeded the maximum number of retries when entering an email validation code.
To be deployed in conjunction with a server side change that does not block the email when the maximum number of retries has been reached, and which allows a brand new code to be sent to the email address.
Before:
1. User enters incorrect six digit email security code 6 times during account creation
2. User sees screen telling them they need to wait 15 mins to get a new code.
3. User clicks 'get a new code'
4. User enters same email address (again)
5. User sees screen telling them they need to wait 15 mins to get a new code.
6. User waits 15 mins (30s in build).
7. User clicks 'get a new code' (or abandons and starts again)
8. User …

ACI-7: Don't ask for email again after max verify code retries

---

src/components/prove-identity-welcome/index-existing-session.njk
src/locales/cy/translation.json

Fixed language inset content for the welcome page when user has an existing session

BAU: fixed language inset content

---

src/locales/cy/translation.json
src/locales/en/translation.json

Content change to bullet point in the Accessibility Statement
Content changes as requested in associated Jira ticket

AUT-778: Update Accessibility Statement

---

src/components/prove-identity-welcome/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

This PR modifies the 2 content `.json` files and the nunjucks `index-existing-session.njk` file.
The new content added adjacent to the link to change the language for the service tells users the document checking app is currently not available in multiple languages.

PYIC-2074 inform users about app translation status

---

ci/terraform/build.tfvars
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars

Does exactly what it says on the tin

BAU: Remove old logging endpoint as it's being turned off

---

src/app.constants.ts

Reverts alphagov/di-authentication-frontend#840

Revert "AUT-898 - The prompt param should be lower case"

---

ci/tasks/deploy-frontend.yml
ci/terraform/build.tfvars

Switch on password reset required for common passwords in all environments.
Initial testing in build is complete.
#848 
#854

ACI-19: Switch on password reset required for common passwords in all environments

---

src/components/common/constants.ts
src/components/security-code-error/index-security-code-entered-exceeded.njk
src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/security-code-error-routes.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Reverts alphagov/di-authentication-frontend#886

Revert "ACI-138 - Show the correct screen when user exceeds auth app code attempts and clicks try again"

---

src/components/contact-us/contact-us-service.ts

Changes a heading in Zendesk submission.
Following demo we have been asked to amend the heading that is submitted to Zendesk.
The PR which introduced the 'Subtheme' heading was #869

AUT-921: Change 'Subtheme' to 'Issue' in Zendesk submission

---

.github/PULL_REQUEST_TEMPLATE.md

Add section to PR template to confirm UI changes have been demonstrated to Content Design and Interaction Design.
Content and Interaction Design have asked for any changes to the user interface to be demonstrated to them so that all necessary changes to Figma can be made. This change seeks to support the process by adding a related section to the Pull Request template.

BAU: Add a section to the PR template to confirm demonstration of UI changes

---

src/locales/cy/translation.json
src/locales/en/translation.json

Replays the work in #906 but with the merge target being the branch to be merged under #921 so that this PR can be merged now and deployed to an environment for preview. 
Significant changes introduced under #921 have made the rebase / merge required for #906 complex and fiddly. It's easier to be confident of the change by replaying the changes on a new branch. 
This duplicates #906 which can be closed if this is merged.

Replay PYIC 2249

---

src/components/contact-us/contact-us-service.ts
src/locales/en/translation.json

- Change from "Text message to a phone number from a different country" to "Text message to a phone number from another country"
- So it reads clearer

BAU - Update text in contact form

---

ci/terraform/production.tfvars

- Enable International Phone Numbers in Production

AUT-70 - Enable International Phone Numbers in Production

---

.github/workflows/build-and-push-frontend.yml
basic-auth-sidecar/Dockerfile
basic-auth-sidecar/entrypoint.sh
basic-auth-sidecar/nginx.conf

GitHub Actions to build and push modules:
- builds, tags and pushes frontend and basic-auth-sidecar to ECR
Supporting efforts to move off Concourse
Depends on https://github.com/alphagov/di-infrastructure/pull/471

GitHub Actions to build and push modules

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Add Ofqual and Modern slavery statement to sign in page
- These services have onboarded are should be on our list of services
- [] Changes to the user interface have been demonstrated
- [] Performance Analysis have been informed of the change

AUT-1096/1095 - Add Ofqual and Modern slavery statement to sign in page

---

src/app.constants.ts
src/components/contact-us/contact-us-controller.ts
src/components/contact-us/tests/contact-us-controller-integration.test.ts
src/components/contact-us/tests/contact-us-controller.test.ts
src/components/contact-us/tests/contact-us-further-information-controller.test.ts
src/components/contact-us/tests/contact-us-questions-controller.test.ts
src/config.ts

Additional validation for contact us referer
The referer value must either be on an allowlist or a url on our domain.

BAU: Additional validation for contact us referer

---

src/components/account-not-found/index-mandatory.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Change content on 'No GOV.UK One Login found' screen

AUT-1159 - Change content on 'No GOV.UK One Login found' screen

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

- Remove list of RPs from sign in screen
- To prevent the list getting too long as more services join One Login

AUT-1149 - Remove list of RPs from sign in screen

---

ci/tasks/deploy-frontend.yml
ci/terraform/dns.tf

Remove unused variables from concourse

---

src/assets/scss/application.scss
src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Significant update to privacy notice (content changes are too long to include screenshot images, but Content and Interaction design have been provided with PDF screenshots).
Changes are due to go live on 11 April, to coincide with a scheduled release for the app. **Do not merge before 11 April**
Brings content from two separate notices into one.

AUT-1090: Update privacy notice

---

package.json
yarn.lock

Upgrade aws-sdk to 2.1356.0.
It's the latest version.

BAU: Upgrade aws-sdk to 2.1356.0

---

src/components/enter-authenticator-app-code/index.njk
src/components/enter-mfa/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Reverts alphagov/di-authentication-frontend#990

Revert "AUT-995: Content change on /enter-code and /enter-authenticationo-app-code page"

---

src/app.constants.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/common/verify-mfa-code/verify-mfa-code-service.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/types.ts
src/components/setup-authenticator-app/setup-authenticator-app-controller.ts

This reverts commit db24b7613001407a0009e295875ba04a03fa2392.

Revert "AUT-1242"

---

ci/terraform/ecs.tf

Fix oneagent-installer container not being added to list
Formatting of our terraform is hard to read. 😭

Fix oneagent-installer container not being added to list

---

src/components/resend-email-code/resend-email-code-controller.ts
src/components/security-code-error/security-code-error-controller.ts

Bug fix to ensure users are shown detailed content and reason why they have been blocked or cannot request a new OTP code after multiple invalid entries.
[Original PR](https://github.com/alphagov/di-authentication-frontend/pull/1047)

AUT-1281: Refactor redirection when user is blocked from entering otp code

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Expands privacy notice "Sharing your information to prove your identity" section and updates last updated date. 
To include information about DVLA and DVS as data processors who we share information with.
Rather than including full screenshots, I've tried to make the content review a bit easier by providing screenshots of the specific elements organised to reflect the task description provided in Jira (i.e. English and Welsh screenshots for Part 1 etc.)
Changes to the `terms_and_conditions` variable on the backend are made in https://github.com/alphagov/di-authentication-api/pull/3068

[Do not merge before 15/6] AUT-1217: Privacy notice updates to go live on 15 June

---

.github/workflows/deploy-frontend.yml

Point deployment actions to the build artifact bucket.
Hooking up the deployment to build now.

Point deployment actions to the build artifact bucket

---

ci/tasks/deploy-frontend.yml
ci/terraform/dev.tfvars

Remove hardcoded CSLS endpoint

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Updates Privacy Notice to reflect TTL changes for VCs
The TTL for VCs is changing.
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
Deletes the following sentence
> We currently store your proven identity information for 6 months.
> Ar hyn o bryd rydym yn storio'ch gwybodaeth hunaniaeth profedig am 6 mis.
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details> …

AUT-1351: Update Privacy Notice to TTL on VCs changes

---

src/components/common/footer/privacy-statement.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Updates to privacy notice.
I've made the screenshot backgrounds a light grey so it's a bit clearer within this PR where text is part of the screenshot. The actual privacy notice still has the normal white background.
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details>
<details>
<summary>English screenshot</summary>
</details>
<details>
<summary>Welsh screenshot</summary>
</details> …

[⚠️ Do not merge before go-live] AUT-1370: Update privacy notice for F2F

---

ci/terraform/waf.tf

- Increase rate limit for staging
- For performance testing

AUT-1401 - Increase rate limit for staging

---

src/locales/cy/translation.json
src/locales/en/translation.json

Updates updated at date - this was missed from the [PR to change the content](https://github.com/alphagov/di-authentication-frontend/pull/1130) although these changes will all go live at the same time since we've paused the push to production for frontend until this is all tested.

AUT-1632: Update terms and conditions updated at date

---

src/components/auth-code/auth-code-service.ts
src/components/auth-code/tests/auth-code-service.test.ts

Updated auth-code request "claim" to "claims"

AUT-1678: Updated claim to claims in request

---

.github/workflows/pre-merge-checks-shellscript.yaml
.shellcheckrc
basic-auth-sidecar/entrypoint.sh
ci/terraform/get_image.sh
ci/terraform/read_secrets.sh
deploy-sandpit.sh
startup.sh

1. rewrite `read-secrets.sh` to use `jq` for parsing the json, letting `bash` just deal with a TSV
2. Add a github action to run shellcheck on PRs
1. Ensure that all pre-existing errors are fixed
The commit message for updating `read-secrets.sh` explains the reasoning for the changes.
https://github.com/alphagov/di-authentication-api/pull/3366

[AUT-1720] `read-secrets.sh` breaks on any spaces in the secret description

---

src/locales/cy/translation.json
src/locales/en/translation.json

Modified radio buttons to reflect changes described in ticket 1734
## Screenshots
| Locale | Before | After |
|-----|-----|------|
| en |<img width="661" alt="Screenshot 2023-10-17 at 16 47 34" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/9ae2206a-0a83-4bde-852d-b79cd4c3ce4a">|<img width="612" alt="Screenshot 2023-10-17 at 16 46 16" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/27d9f620-deca-46a8-93c3-648786f98c40">|
| cy |<img width="608" alt="Screenshot 2023-10-17 at 16 50 23" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/9c2c3452-05dd-4f25-94a8-1ff8c866b497">|<img width="649" alt="Screenshot 2023-10-17 at 17 21 29" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/25ff848 …

AUT 1734 Updating radio button

---

ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf

Hotfix to fix acceptance tests
This reverts commit 7e35dddc3a0d35ff127ecffcb9b0902abaf05c15.

Revert "Sets the following environment variables across all environments

---

src/components/contact-us/questions/_email-subscriptions-questions.njk
src/components/contact-us/questions/_id-check-app-technical-problem.njk
src/components/contact-us/questions/_proving-identity-face-to-face-another-problem.njk
src/components/contact-us/questions/_proving-identity-face-to-face-problem-at-post-office.njk
src/components/contact-us/questions/_proving-identity-face-to-face-problem-continuing.njk
src/components/contact-us/questions/_proving-identity-face-to-face-problem-entering-details.njk
src/components/contact-us/questions/_proving-identity-face-to-face-problem-finding-result.njk
src/components/contact-us/questions/_proving-identity-face-to-face-problem-letter.njk
src/components/contact-us/questions/_proving-identity-face-to-face-technical-problem.njk
src/components/contact-us/questions/_proving-identity-problem-questions.njk
src/components/contact-us/questions/_signing-in-problem-questions.njk

Remove stray character.
It appears in the user interface.
* https://github.com/alphagov/di-authentication-frontend/pull/1169 Introduced the character

FIX: Remove character causing rendering issue

---

sonar-project.properties

Update Sonar organisation
The repository has been moved to a new organisation in Sonar

BAU: Update Sonar organisation

---

src/components/contact-us/contact-us-controller.ts

Add logging to smart agent contact form submission.
Enables 2nd and 3rd line to match a user session in the logs with a ticket using the ticket identifier.
The same facility already exists for Zendesk tickets.

BAU: Add logging to smart agent contact form submission

---

ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/sandpit.tfvars
ci/terraform/variables.tf
src/app.ts
src/config.ts
src/config/helmet.ts

Add CSP values for frame-ancestors, form-action, as their defaults don't fallback to 'self'.
The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined: frame-ancestors, form-action 
When changing these CSP directives, it is necessary to test the UI of the application to make sure any forms/ embedded frames are not broken.

AUT-1706: Review and fix CSP issues

---

ci/terraform/build.tfvars
ci/terraform/ecs.tf
ci/terraform/sandpit.tfvars
ci/terraform/variables.tf
src/app.ts
src/config.ts
src/config/helmet.ts

Reverts govuk-one-login/authentication-frontend#1203
Has applied "form-action 'none'" CSP by default.

Revert "AUT-1706: Review and fix CSP issues"

---

ci/terraform/integration.tfvars
ci/terraform/staging.tfvars

Reverts govuk-one-login/authentication-frontend#1208

Revert "AUT-1706: Turn on the frame_ancestors_form_actions_csp_headers flag"

---

ci/terraform/build.tfvars
ci/terraform/dev.tfvars
ci/terraform/dynatrace.tf
ci/terraform/ecs-roles.tf
ci/terraform/ecs.tf
ci/terraform/integration.tfvars
ci/terraform/production.tfvars
ci/terraform/sandpit.tfvars
ci/terraform/staging.tfvars
ci/terraform/variables.tf

Add environment variables to frontend container for Dynatrace agent.
This does _not_ yet add the Dynatrace agent, this will be done as another PR changing the Dockerfile
Dynatrace ECS integration for Authentication. :)

Add environment variables to frontend container for Dynatrace agent.

---

src/app.constants.ts
src/app.ts
src/components/account-intervention/password-reset-required/index.njk
src/components/account-intervention/password-reset-required/password-reset-required-controller.ts
src/components/account-intervention/password-reset-required/password-reset-required-router.ts
src/components/account-intervention/password-reset-required/tests/account-intervention-controller.test.ts
src/config.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Added template, route, unit test and translations for the Password Reset Required page.
The changes are necessary to be implemented as part of the account interventions user journey.
- [✅] Changes to the user interface have been demonstrated
- [✅] Performance Analysis have been informed of the change

AUT-1863: Added page and route for the Password Reset Required account interventions stage

---

ci/terraform/staging.tfvars

Enable the authorize controller in staging 
Step 3/7 in enabling split in staging: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

AUT-1762: enable authorize controller

---

ci/terraform/staging.tfvars

Provide missing env vars for staging split. Still to do for int and prod

AUT-1762: update staging vars for split

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars

Follow up to https://github.com/govuk-one-login/authentication-frontend/pull/1271 for integration and production

AUT-1762: update int and prod vars for split

---

ci/terraform/integration.tfvars

Step 3 of enabling the auth orch split

ATO-257: Enable authorize controller in integration

---

src/components/account-intervention/password-reset-required/index.njk
src/components/account-intervention/password-reset-required/password-reset-required-controller.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts

Made fixes to allow for password reset journey following password reset required screen.
Journey was stuck of password reset required screen

AUT-1841: Fixes to password reset journey following interventions

---

ci/terraform/auto-scaling.tf

correcting the typo in scale-out policy for Staging
AUT-1983

correcting the typo in scale-out policy for Staging

---

ci/terraform/auto-scaling.tf

[AUT-1983](https://govukverify.atlassian.net/browse/AUT-1983) Additional Step Adjustment in ecs scale up policy 
This change is to fine tune the performance testing on staging Environment 
Change is only made to staging at this point once we have the perf testing result & agreed will be release on Prod 
[AUT-1983]: https://govukverify.atlassian.net/browse/AUT-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Additional Step Adjustment in ecs scale up policy 

---

ci/terraform/production.tfvars
ci/terraform/variables.tf

AUT-2297 -Switching v1 scaling on prod
we need to revert  back to old scaling policy more context in Ticket

AUT-2297 Switching v1 scaling on prod

---

ci/terraform/auto-scaling.tf
ci/terraform/staging.tfvars

AUT-1983  Changing step scale no for staging 
updating Step scaling for Performance testing in staging ENV

AUT-1983 Changing Step scale no for staging perf test

---

src/components/common/state-machine/state-machine.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/types.ts
src/components/enter-password/enter-password-controller.ts
src/components/enter-password/tests/enter-password-support-2fa-before-password-reset-integration.test.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password/tests/reset-password-forced-2fa-before-integration.test.ts

Set up ‘Check your phone’ flow for Password Reset Required
Users can be forced to reset their password if they previously created a weak password.  This flow needs updating too to ask for a 2FA (SMS).

AUT-2032: Set up 2FA reset password flow for Password Reset Required

---

src/components/common/state-machine/state-machine.ts
src/components/reset-password-2fa-sms/index.njk
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts

Update content in check your phone page for the 2fa before password reset journey
Check you phone page in reset pw journey has wrong content under Problems with the code link
##Changes have been demonstrated
Changes have been demonstrated to @CraigRyder

AUT-2414: Update content in check your phone page for the 2fa before password reset journey

---

src/components/authorize/authorize-controller.ts

Add logging to verify reauth claim is populated

bau: Add logging to verify reauth claim is populated

---

dev-app.js
startup.sh

Fix local startup.
Remember to delete stub images before starting again.
Files added in error.

BAU: Fix local startup

---

ci/terraform/integration.tfvars

turn on 2fa_b4_password_reset feature flag in integration

Bau: turn on 2fa b4 password reset in integration

---

src/components/common/verify-code/verify-code-controller.ts

Fixed conditional AIS call depends on to correctly check the journey type against options.journeyType

AUT-2440: Fixed check against journey type in verify code controller

---

ci/terraform/auto-scaling.tf
ci/terraform/production.tfvars

AUT-2487-Switching on new ECS scaling policy in Prod
Enabling new Scaling Policy in prod which has been tested for performance testing

AUT-2487-Switching on new ECS scaling policy in Prod

---

startup.sh

Option to pass aws profile for backend on the command line in startup.sh.
Using 'source .env' to read environment variables was corrupting the orch to auth signing key.
'export_aws_creds.sh' needs the profile environment variable to be set directly.
#1429

BAU: Option to pass aws profile for backend on the command line in startup.sh

---

src/locales/cy/translation.json
src/locales/en/translation.json

Minor copy update for accessibility statement page. 
Also found a missing 'for' in the English translation when comparing the full latest copy to what we have, not mentioned in [ticket](https://govukverify.atlassian.net/browse/AUT-2500).
In the ‘Compliance status’ section
REPLACE 2.1 WITH 2.2
(Full sentence: “GOV.UK One Login is partially compliant with the [Web Content Accessibility Guidelines version 2.2](https://www.w3.org/TR/WCAG22/) AA standard,”)
In the first numbered bullet point under the ‘Non compliance with the accessibility regulations’ section
REPLACE 2.1 WITH 2.2
(Full sentence: “This fails WCAG 2.2 success criterion 2.2.1 (Timing Adjustable).”)
In the third numbered bullet point under the ‘Non compliance with the accessibility regulations’ section
ADD This fails WCAG 2.2 …

AUT-2500: content update for accessibility page

---

.github/PULL_REQUEST_TEMPLATE.md

Provides additional instructions and help for developers seeking a UCD review of screens. This is to:
1. help clarify what's needed, and why
2. describe and provide examples of how to it's been done before 
3. avoid the potential for implementation to not reflect expectations
Review the PR template changes.  
I have described the change I'm proposing to UCD colleagues.

BAU: Update PR template section for UCD review

---

.github/PULL_REQUEST_TEMPLATE.md

Builds upon recent work to improve our PR template by introducing two additional checklist items:
- the acceptance tests have been updated
- associated documentation (such as the README) has been updated
This change was discussed in the Authentication Developer Meeting on 21 March 2024, where we agreed this would be a good thing to do.
1. Review the content and approach

BAU: Update PR template to reference acceptance tests and documentation updates

---

README.md

Adds a troubleshooting section that's split into general steps and how to get past specific errors.
1. Review the new instructions
2. Review the way the instructions are presented to see if you think this works (for example, I've used a disclosure element for the steps relating to specific errors)

BAU: Add troubleshooting steps to README

---

src/components/prove-identity-welcome/prove-identity-welcome-controller.ts
src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts

Remove some old code related to Verify
This should have been removed as part of PYIC-2204 (#860)
Ensure removed code is no longer required

BAU: Remove unused code from prove-identity-welcome

---

ci/terraform/staging.tfvars

AUT-2596 increase ECS task size to 1cpu for Perf Test

AUT-2596 Change ECS task CPU to 1 for perf terst

---

ci/terraform/staging.tfvars

- Switch reauth in staging to enable testing

bau: Switch reauth in staging

---

ci/terraform/alb.tf

AUT-2645 --ALB access not enabled on staging 
we want to gather perf Test data for no of request hitting ALB

AUT-2645-Enabling ALB access logging on staging

---

src/components/security-code-error/security-code-error-controller.ts
src/components/security-code-error/tests/security-code-error-controller.test.ts

Refactors to the security error controller for readability
1. Code Review commit by commit - I have written my logic for the refactors in the commit message.

BAU: refactor security error controller

---

src/components/account-creation/resend-mfa-code/resend-mfa-code-controller.ts
src/components/check-your-email/check-your-email-controller.ts
src/components/check-your-phone/check-your-phone-controller.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/resend-email-code/resend-email-code-controller.ts
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/components/reset-password-2fa-auth-app/reset-password-2fa-auth-app-controller.ts
src/components/reset-password-2fa-sms/reset-password-2fa-sms-controller.ts
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/security-code-error/security-code-error-controller.ts
src/utils/lock-helper.ts
test/unit/utils/lock-helper.test.ts

Introduces shared helper methods for dealing with session locks to reduce duplication within the code, and make controllers more readable.
Code review commit by commit

Bau: Introduce lockout helpers

---

ci/terraform/cloudwatch.tf
ci/terraform/site.tf
ci/terraform/waf.tf

Driven by a request from security. Do not log in staging to reduce impact of performance tests on splunk load
I've tested this in sandpit, so just a code review

ATO-492: Enable logging of contact-us requests in WAF

---

ci/terraform/variables.tf

I had the logic reversed :facepalm:
- Code review

AUT-2697: Fix condition in rate_limited_endpoints

---

src/components/common/constants.ts
src/middleware/allow-user-journey-middleware.ts

Debugging state machine errors in smoke tests

AUT-2686: Add additional temporary logging

---

src/components/common/constants.ts
src/middleware/allow-user-journey-middleware.ts
test/unit/middleware/allow-user-journey-middleware.test.ts

Added session id to existing logs and some logging on the success case, to see why we're getting state machine errors in smoke tests.

AUT-2686: Add additional logging for debugging purposes

---

src/components/sign-in-or-create/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Reverts govuk-one-login/authentication-frontend#1564

Revert "BAU: Fix issue with landing page heading text wrap"

---

ci/terraform/waf-cf.tf

Fix for WAF rule only applicable for staging

AUTH-2655 auth cloud front fix waf

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars

integration + production terraform config for 2hr lockout go live
1. Code Review

AUT-2461: increase lockout duration in integration and prod

---

ci/terraform/build.tfvars

##What
Increasing build FE capacity to match Staging for Acceptance test improvement QA team PR 
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -t -p '

Increasing build FE capacity to match Staging for Acceptance test

---

ci/terraform/cloudfront.tf
ci/terraform/variables.tf
ci/terraform/waf.tf

Changes to Cloud front Template version  & WAF scope down for Zero WAF downtime when dns is  switched 
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -t -p'

changes to Cloud front Template & WAF scope down for Zero WAF downtime

---

src/components/check-reauth-users/check-reauth-users-service.ts
src/components/common/send-notification/send-notification-service.ts
src/components/enter-password/enter-password-service.ts
src/utils/http.ts
test/unit/utils/http.test.ts
test/unit/utils/mfa.test.ts

* Adds some missing tests for functionality (this will be useful as part of implementing AUT-2578)
* Renames a test file to ensure the tests are run (and updates the test expectation)
1. Code Review

Bau: Add tests for request config and fix existing test file

---

ci/terraform/build.tfvars
ci/terraform/staging.tfvars

AUT-2754 & AUT-2753
Switch DNS to cloud front build & staging
1. Code Review

AUT-2754 -Switch DNS to cloud front build & staging

---

ci/terraform/build.tfvars
ci/terraform/cloudfront.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf

Updating cloud front template to new version below two updates getting added 
1) csls logging for Cloaking WAF AcL 
2) Multiple origin option for Cloud front distribution
1. Code Review
2 Deploy to sandpit with `./deploy-sandpit.sh -t -p'

updating cloud front template to new version

---

.github/workflows/build-deploy-frontend-dev.yml
ci/terraform/dev.tfvars

Building DEV environment  in di-auth-devlopment account , Adding dev git workflow & dev variable 
1. Code Review

Adding Dev workflow & dev variable

---

scripts/trigger-gha-current-branch.sh

script to trigger manual workflow from Gh cli
Run  ./scripts/trigger-gha-current-branch.sh  , this should trigger the Workflow in git Action

script to trigger manual workflow from Gh cli

---

ci/terraform/get_image.sh

Updating the get-image script so for DEV frontend deployment it pull image from DEV tooling frontend Repo 
1. Code Review

get Dev image for Dev frontend deployment

---

ci/terraform/integration.tfvars

Switch on reauthentication in integration to support HMRC testing.
Reauth has been tested in staging.
1. Code review

BAU: Switch on reauthentication in integration

---

ci/terraform/variables.tf

Enable TICFFraudHeadersFunction on Cloud front distribution 
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -t -p '

Enable cloud front function

---

ci/terraform/dev.tfvars

Updating Minimum and Max health percentage for DEV env to run only 1 task
Code review

updating Minimum and Max health percentage for DEV to run only 1 task

---

ci/terraform/ecs.tf
ci/terraform/variables.tf
src/components/authorize/authorize-controller.ts
src/components/authorize/tests/authorize-controller.test.ts
src/components/common/state-machine/state-machine.ts
src/components/common/state-machine/tests/state-machine.test.ts
src/components/prove-identity-welcome/prove-identity-welcome-controller.ts
src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts
src/config.ts
yarn.lock

1. Code Review
2. Set a new constant in the env file to 1 to have the page skip, 0 to not have the page skip: PROVE_IDENTITY_WELCOME_SCREEN_DISABLED_FOR_ENVIRONMENT
3. Deploy to a production like env
4. Check to see if the page still appears in the scenarios where identityRequired is true, more details about this can be found in 2760

AUT-2760 adding functionality to skip "prove your identity welcome"

---

ci/terraform/staging.tfvars

Switch off prove identity welcome in staging.
So that the changes can be tested.
<!-- Describe the steps required to review this PR.
1. Code Review
#1643

AUT-2760: Switch off prove identity welcome in staging

---

ci/terraform/waf.tf

Creating low priority rule for Count the request which are not originating from cloudfront"
1. Code Review

Adding WAF count for request not from CloudFront

---

ci/terraform/integration.tfvars
ci/terraform/production.tfvars

https://govukverify.atlassian.net/browse/AUT-2660
https://govukverify.atlassian.net/browse/AUT-2661
**Deploy CloudFront in Prod & Int Env**
1. Code Review

Deploy CloudFront in Prod & Int Env

---

ci/terraform/integration.tfvars

AUT-2755 Switching CloudFront DNS in integration env
1. Code Review

Switching CloudFront DNS in int env

---

src/components/contact-us/contact-us-service-smart-agent.ts
src/components/contact-us/types.ts

Following Christopher Sly <[Christopher.Sly@teamhgs.com](mailto:Christopher.Sly@teamhgs.com)> request, we have to use another attribute for identity document value
https://govukverify.atlassian.net/browse/AUT-2881

AUT-2881: change identity document attribute

---

src/locales/cy/translation.json
src/locales/en/translation.json

Update /support page hours:
From:
Our office hours are 9:30am to 5:30pm, Monday to Friday. We’ll respond to you by email in 2 working days.
To:
Our office hours are 8:00am to 8:00pm, Monday to Friday. We’ll respond to you by email in 2 working days.
https://govukverify.atlassian.net/jira/software/c/projects/SSE/boards/222?selectedIssue=SSE-3440

ATO-698: Update support hours

---

ci/terraform/production.tfvars
ci/terraform/staging.tfvars

Sets analytics environment variables to reflect request from Frontend Capability Team.
1. Code Review
2. Verify that the values set match those requested (see related Jira ticket)
- https://github.com/govuk-one-login/authentication-frontend/pull/1633 set the GA4 and UA environment variables as initially requested
- https://github.com/govuk-one-login/authentication-frontend/pull/1522 introduced GA4

AUT-2889: Set analytics environment variables

---

src/components/signed-out/signed-out-controller.ts

Error 'Cannot destructure property ‘isAccountCreationJourney' of 'req.session.user' as it is undefined’ was triggered after the user signed out and in the case of he is refreshing the page. And user was redirected to the error page.
After investigation, I found the reason of it and I have seen it's related to an implementation asked in the ticket [DAC-2867](https://govukverify.atlassian.net/browse/DAC-2867)
But implementation was not what it's asked in the ticket, and value for the taxonomy level 2 needs to come from the previous page and not from req.session.user. FE capability team has already a ticket for this (DFC-505).
So I removed the condition and put "signed out" as a value (lot of chance that will be the value after the implementation of dfc-505).
1/ signed out
2/ refresh the …

Aut-2886: Fix error causing by ga4 taxonomy level 2 implementation into signed out function

---

src/locales/cy/translation.json
src/locales/en/translation.json

Updates content on the 'Choose how to get security codes' screen
<details>
</details>
<details>
</details>
1. Code Review

AUT-1485: Update 'Choose how to get security codes' content

---

.github/dependabot.yml

Set high dependabot PR limit
Default limit was set to 5 only.

BAU: Set high dependabot PR limit

---

ci/terraform/dev.tfvars

Deploy Cloud-front in DEV
1. Code Review

BAU: Enable Cloud-front in DEV

---

src/components/common/cookies/cookies-controller.ts
src/components/common/cookies/index.njk
src/components/common/cookies/tests/cookies-controller.test.ts

"Go back to the page you were looking at" link was not redirecting the visitor to their last visited page.
href attribute was not dynamic and form didn't intercept the value neither.
- Use a locals variable for filling href attribute.
- Add a new hidden field into the form to keep the value of the referer.
1/ Click on the "cookies" link (in the footer of the page)
2/ Select one of the radio buttons and submit the form
3/ Click on the link "Go back to the page you were looking at"

Aut-2923: Update go back href attribute with browser's referer page

---

.github/workflows/deploy-frontend-sp.yml
template.yaml

GitHub Actions to build and deploy the frontend using Secure Delivery Pipeline.
For now, the template is a placeholder until AUT-2930 adds the full template.
N/A
N/A

AUT-2929: Build GitHub Action to deploy dummy frontend template using Secure Delivery Pipeline.

---

package.json
src/components/common/layout/base.njk
yarn.lock

- Upgrade frontend analytics package to v2.0.1
- add new parameter to google analytics tracking code: isDataSensitive
Google Tag manager validation:

Aut-3028: upgrade analytics package v2.0.1

---

ci/terraform/integration.tfvars

AUT-2924: enable Service down page in Integration Env
1. Code Review

AUT-2924: enable Service down page in Integration Env

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/deploy-frontend.yml

`js` in `yaml` is hard. `#` isn't a comment in `js`.
- Code review

BAU: fix comment character

---

ci/terraform/auto-scaling.tf

Updating the performance autoscaling to match the values set for IPV.

LS-2142 Update auto-scaling.tf

---

src/components/authorize/authorize-controller.ts

Refactoring job to reduce the cognitive complexity of the controller job function. This was done to fix a Maintainability [SonarCloud issue](https://sonarcloud.io/project/issues?resolved=false&id=govuk-one-login_authentication-frontend&open=AYzUo9kaB6Jo2MZpSJhh).
1. Code Review
This was tested by deploying to authdev2

BAU:reduce the complexity of authorize-controller.ts

---

src/components/updated-terms-conditions/index.njk

- Change submit button styling and make it compliant with gov uk design system
- Log in
- go to updated terms and conditions page ( /updated-terms-and-conditions )
- [X ] A UCD review has been performed.

Auth-2714: change submit button classes into updated terms conditions page

---

.github/workflows/deploy-frontend-sp.yml
.pre-commit-config.yaml
template.yaml

Create initial template to deploy frontend

AUT-2930 - Create initial template to deploy frontend

---

ci/terraform/waf.tf

Fix for Staging frontend Deploy in pipeline 
1. Code Review

removed index key  since we are not using Flag Now

---

.github/workflows/deploy-frontend-sp.yml
cloudformation/readme.md
cloudformation/template.yaml

1. Build and push service down page container within the deploy-frontend-sp GHA
2. Service down page components in the auth frontend cloudformation template
1. Branch successfully deployed via GHA: https://github.com/govuk-one-login/authentication-frontend/actions/workflows/deploy-frontend-sp.yml ✅
2. Service down ECS service deploys within the frontend fargate cluster ✅
3. Can follow the guide to turn on/off service down page https://team-manual.account.gov.uk/supporting-govuk-one-login/managing-incidents/temporarily-shutter-govuk-sign-in/ ✅

AUT-3364 Service down page attached to SP Auth frontend

---

.github/workflows/deploy-frontend-sp.yml
cloudformation/template.yaml

Deploy ServiceDownPage in integration and production environments.
This replicates the terraform setup managed by `service_down_page` variable in *.tfvars.

AUT-3414 - Deploy ServiceDownPage in integration and production environments

---

src/components/enter-email/enter-email-controller.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-email/tests/enter-email-integration.test.ts

AUT-2790: Add logic to redirect to sign-out when introducing wrong email in re-auth journey
1. Code Review
2. Deploy to authdev1, with [this](https://github.com/govuk-one-login/authentication-api/pull/4899) as back-end and test that you are logged out, after 5 attempts with a wrong email in the re-auth journey
3. Try to log in and check that you are not locked
https://github.com/govuk-one-login/authentication-api/pull/4899

AUT-2790: Add logic to redirect to sign-out when introducing wrong email is introduced in reauth

---

.github/workflows/deploy-frontend-sp.yml
cloudformation/cloudfront-waf/template.yaml
cloudformation/deploy/template.yaml

Improvements on the auth secure pipeline templates:
1. Rate limited endpoints config params in waf template
2. Temporarily disable CSLS log forwarding from staging
3. Redis configs as environment parameters to ECS task definition
Deploy frontend using https://github.com/govuk-one-login/authentication-frontend/actions/workflows/deploy-frontend-sp.yml 
Successful deployment and promotion build -> staging should suffice

AUT-3492 - Improvements on the auth secure pipeline templates

---

src/components/common/mfa/send-mfa-controller.ts
src/components/common/mfa/tests/send-mfa-controller.test.ts
src/components/common/verify-code/tests/verify-code-controller.test.ts
src/components/common/verify-code/verify-code-controller.ts
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/enter-mfa/tests/enter-mfa-reauth-integration.test.ts
src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts

In the reauth journey, want to redirect the user to the client redirectUri when he enters six invalid otp codes, instead of locking them out for six hours..
1. Code Review

AUT-2788: implement logout instead of lockout for sms mfa in reauth

---

src/components/resend-mfa-code/index.njk
src/components/resend-mfa-code/resend-mfa-code-controller.ts
src/locales/cy/translation.json
src/locales/en/translation.json

- Re auth: update resend mfa code paragraph because user is now 
- Signin and ask to send the code again
- paragraph will tell you you will be signed out

Aut-3089: update resend mfa code paragraph content if reauth is activated

---

README.md

Fixes a tiny typo in the README
Code Review

BAU: Add missing angle bracket to README

---

.github/workflows/deploy-frontend-sp.yml
cloudformation/deploy/template.yaml

Changes to Frontend template:
- KMS encryption key for decrypting requests from Orchestration
- Deploy basic-auth sidecar only in integration environment
- Move frontend tasks to protected subnets
Jira ticket: [AUT-3491]
Deploy with GHA https://github.com/govuk-one-login/authentication-frontend/actions/workflows/deploy-frontend-sp.yml
Build account orch stub https://orchstub.signin.build.account.gov.uk/ submit form successfully redirects to https://signin-sp.build.account.gov.uk/sign-in-or-create
[AUT-3491]: https://govukverify.atlassian.net/browse/AUT-3491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3491 - Frontend config changes to integrate with orchestration

---

src/locales/en/translation.json

BAU: Fix typo in spot spinner text

---

.github/workflows/deploy-frontend-sp-dev.yml
.github/workflows/deploy-frontend-sp.yml

Workflow to deploy frontend to dev environments. 
Documentation: https://govukverify.atlassian.net/wiki/spaces/LO/pages/4462215197/How+to+deploy+frontend+to+dev+environments+using+secure+pipeline

AUT-3522 - Workflow to deploy frontend to dev environments

---

cloudformation/cloudfront-waf/template.yaml
cloudformation/domains/template.yaml

Refactored to use Fn::ForEach intrinsic loop function to create resources
Future authdevX environments can be added by expanding this list
```
- EnvName
- - authdev1
- authdev2
- authdev3
- ....
- ....
- authdevN
```
Documentation link: https://govukverify.atlassian.net/wiki/spaces/LO/pages/4462870544/Dev+domain+migration

AUT-3522 - Domains rework to support authdev environments

---

cloudformation/deploy/template.yaml

Issue: AUT-3522
Auth frontend template rework to allow sub-environments
SubEnvironment parameter is passed as a parameter from the pipeline
Initially supported authdev1 deployment into di-authentication-development account, https://signin.authdev1.dev.account.gov.uk/
Associated stack orchestration changes in https://github.com/govuk-one-login/authentication-infrastructure/pull/8

AUT-3522 - Auth frontend template rework to allow sub-environments

---

cloudformation/deploy/template.yaml

Staging orchToAuthSigningPublicKey set
Issue: [AUT-3539]
To integrate new orchestration-stub with frontend in secure pipeline staging account
[AUT-3539]: https://govukverify.atlassian.net/browse/AUT-3539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Integrate new orchestration-stub with frontend

---

.github/workflows/deploy-frontend-sp.yml

Comment out basic-auth-sidecar build in sp GHA. basic-auth sidecar not required until integration.
Issue: [AUT-3539]
[AUT-3539]: https://govukverify.atlassian.net/browse/AUT-3539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3539 - Comment out basic-auth-sidecar build in sp GHA

---

.git-blame-ignore-revs
src/components/common/password-guidance/_password-guidance-details.njk
src/components/create-password/index.njk
src/components/reset-password/index.njk
src/locales/cy/translation.json
src/locales/en/translation.json

Adds an additional paragraph to the "How to create a secure password" details component. Also:
1. Extracts duplicated code and content to a shared component
2. Reformats relevant templates and adds these changes to blame ignore
In addition to using these static screenshots for the UCD review, it is possible to review these changes in a production-like environment by using the GitHub Action to deploy this branch. I'd be happy to help with that, if needed. 
<details>
</details>
<details>
</details>
<h4>Reset your password</h4>
<details>
</details>
<details>
</details>
* Code review
* [Optionally] Run the branch to verify the "Create your password" and "Reset your password" pages reflect …

AUT-2141: Update secure password creation details component

---

cloudformation/deploy/template.yaml

For dev, authde1 and authdev2 environments
Issue: [AUT-3745]
Run e2e user journeys from orchstub instances
[AUT-3745]: https://govukverify.atlassian.net/browse/AUT-3745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3745: Orchstub integration configurations

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/dev.tfvars

Orchstub public keys for dev, authdev1 and authdev2 frontend
Integrates the new orchstub with frontend instances.
Existing rp-stubs still work 
Issue: [AUT-3763]
Run a sign-in journey via both existing rp-stub and new orch stub
[AUT-3763]: https://govukverify.atlassian.net/browse/AUT-3763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3763 - Orchstub public keys for dev, authdev1 and authdev2 frontend

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/build-deploy-frontend.yml
.github/workflows/test-sidecar.yml
basic-auth-sidecar/Dockerfile

Lockdown nginx:mainline-alpine base image to specific sha256 digest
Do not build and push the sidecar image.  Will keep integration on the existing image.  This is because the build and push sidecar tasks is currently failing.
Fix for recent build issues seen i.e. https://github.com/govuk-one-login/authentication-frontend/actions/runs/11161473976/job/31024511258
Caused by missing pkg-oss dependencies as nginx base image bumped version from 1.71.1 to 1.71.2
Relevant error lines:
```
3.067 + hg clone -r 1.27.2-1 https://hg.nginx.org/pkg-oss/
4.143 destination directory: pkg-oss
4.143 abort: unknown revision '1.27.2-1'
```
Issue: [AUT-3773]
[AUT-3773]: https://govukverify.atlassian.net/browse/AUT-3773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

AUT-3773 - Lockdown nginx:mainline-alpine base image to specific sha256 digest

---

ci/terraform/production.tfvars

Turn on reauth feature flag in production
1. Code Review
Make sure that a performance analyst colleague in your team has been informed of any changes to the user interfaces or user journeys.

BAU: switch on reauthentication in production DO NOT MERGE

---

ci/terraform/get_image.sh

Fixing Frontend failure by fixing Side car image version in Integration
code review

BAU: Fixing Frontend failure by fixing Side car image version

---

cloudformation/deploy/template.yaml

Frontend to access cross-account redis session cache
- Removed all redis components from the cloudformation template
- cross-account redis connection host, port, password provided from Secret manager `/deploy/$Environment/..` params

AUT-3768 - Frontend to access cross-account redis session cache

---

.github/workflows/build-deploy-frontend-dev.yml
.github/workflows/build-deploy-frontend.yml
.github/workflows/test-sidecar.yml
basic-auth-sidecar/Dockerfile
ci/terraform/get_image.sh
package.json
tsconfig.json
yarn.lock

The combination of the nodejs upgrade and `chai-http` 4.x -> 5.x meant that ts-node stopped working properly in the sidecar tests.
Downgrading `chai-http` has resolved the issue.
Also, nginx's modules repo had moved. Pulled in the latest version of the modules Dockerfile, and added comments for the future
Ensure the tests run in the workflow

BAU: Fix sidecar build

---

.github/workflows/deploy-frontend-sp.yml
cloudformation/deploy/template.yaml
cloudformation/domains/template.yaml

- Integration environment transitional domains and certs
- Nginx sidecar subenv rework and deploy to dev environments
Issue: [AUT-3544]

AUT-3544: Integration account bootstrap - DNS, certs and basic auth setup

---

cloudformation/deploy/template.yaml

Phase 1 - deploy components while ECS service remains in control of deployment
Issue: [AUT-3546]

Phase 1 - deploy components with ECS referencing Task definition

---

.github/dependabot.yml

Adding groups for github actions and docker to reduce the number of PRs generated by dependabot.
1. Code Review

BAU: Add dependabot groups for github actions and docker.

---

cloudformation/deploy/template.yaml

AUT-3808 : Enable Splunk Logs Subscription for new Frontend ECS log 
1. Code Review

BAU: Adding csls log subscription to new Frontend ECS logs

---

cloudformation/deploy/template.yaml

AUT-3546: Changing the Cooldown and threshold  for scale in & scale out on new Frontend 
1. Code Review

AUT-3546: Changing the Cooldown and threshold 

---

cloudformation/deploy/template.yaml

Prettifying the frontend cloudformation template
Orchstub to auth signing configurations, separated from main orchestration. Frontend supports both sets simultaneously
Issue: [AUT-3809]
[AUT-3809]: https://govukverify.atlassian.net/browse/AUT-3809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3809 - Orchstub to auth signing configurations

---

cloudformation/deploy/template.yaml

Add Cloudfront distribution cloaking WAF in front of Frontend ALB
Issue: [AUT-3545]

AUT-3545: Add CF WAF association to Frontend ALB

---

src/components/security-code-error/tests/security-code-error-controller.test.ts
src/components/security-code-error/tests/test-scenario-data.ts

Simple refactor. Extracts test scenario data out of test file so that:
1. the test file is a bit lighter and more easy to understand
2. the data can be reused for the tests that will be introduced for strategic app under AUT-3838 (which will need the same test scenario data).
Code review, there's just one commit.

BAU: Refactor security code error tests

---

ci/terraform/variables.tf

Setting default log retention to 30 days. 
See https://govukverify.atlassian.net/browse/SW-243 and associated epic https://govukverify.atlassian.net/browse/SW-241

SW-243 Set default log retention to 30 days

---

src/components/authorize/tests/authorize-integration.test.ts

The test itself is very basic, just testing that we can successfully make a request to the endpoint when the user has given cookie consent (without testing any of the expected functionality, which is already tested and much easier to test in the unit tests). This, among other breaking changes, prevents breaking updates to the cookies library, since in the case where this value is true, and the client has set cookie sharing to true, we set a cookie value and if this fails we can fail to let someone through authorize. This has recently been seen in express dependency bumps, which bumps the cookie library to 0.7.x, which contains extra regex validation of the cookie values, which we don't currently meet as we use double quotes in the value.
This should prevent re-occurences of this incident. …

BAU: Add regression test for authorize controller

---

cloudformation/domains/template.yaml

Domain hosted zone and certificates deployed in two stages
Deploy changes to target environment using the `provision-<environment>.sh` script from this PR https://github.com/govuk-one-login/authentication-infrastructure/pull/23

AUT-3690: Domain hosted zone and certificates deployed in two stages

---

ci/terraform/auto-scaling.tf

Small change to  Increase the scale down cooling period and scaling adjustment  observed in perf test 
1. Code Review

BAU: Increase the scale down cooling period

---

.github/dependabot.yml

These dependencies are closely releated and grouping their dependabot PRs will help quicken there updates.
For example, these PRs are open at the time of writing:
- https://github.com/govuk-one-login/authentication-frontend/pull/2354 introduces a breaking change
- https://github.com/govuk-one-login/authentication-frontend/pull/2353 adds support for the breaking change
- https://github.com/govuk-one-login/authentication-frontend/pull/2352
1. Code Review

BAU: Group i18next dependabot PRs

---

cloudformation/deploy/template.yaml

Remove unsupported nested if from FindInMap intrinsic function
Tested in authdev1 and authdev2
https://github.com/govuk-one-login/authentication-frontend/actions/runs/11977770607
https://github.com/govuk-one-login/authentication-frontend/actions/runs/11977774043

AUT-3690: Remove unsupported nested if from FindInMap intrinsic function

---

cloudformation/deploy/template.yaml

Switch staging signin DNS to secure pipeline frontend

AUT-3690: switch staging signin DNS to secure pipeline frontend

---

cloudformation/deploy/template.yaml

This reverts commit 762e846b35d307be2302c00b9fa732301d068319.
Testing rollback

Revert "AUT-3690: switch staging signin DNS to frontend"

---

cloudformation/deploy/template.yaml

AUT-3947: Adding http keep Alive flag for Staging in new frontend
1. Code Review
2. Deploy to authdevs with `./deploy-authdev1 -t -p `
3. Add observe the changes to task definition

AUT-3947: Adding http keep Alive flag for Staging in new frontend

---

cloudformation/deploy/template.yaml

switch signin.staging DNS to secure pipeline frontend
Issue: [AUT-3943]
Step 1.9 of https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3943: switch signin.staging DNS to secure pipeline frontend

---

cloudformation/deploy/template.yaml

This reverts commit e3580d41086c999e751876cecc64f8df822fc2ac.
Issue: [AUT-3943]
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "AUT-3943: switch signin.staging DNS to secure pipeline frontend"

---

ci/terraform/authdev1.tfvars

[AUT-3954] Move Authdev1 env to run on Shared VPC
1. Code Review
1. Deploy to  authdev1  
[AUT-3954]: https://govukverify.atlassian.net/browse/AUT-3954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3954: Move Authdev1 env to run on Shared VPC

---

cloudformation/deploy/template.yaml

Disable ECS blue/green deployment in staging
Issue: [AUT-3943]
[AUT-3943]: https://govukverify.atlassian.net/browse/AUT-3943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3943: Disable ECS blue/green deployment in staging

---

ci/terraform/cloudfront.tf
ci/terraform/production.tfvars
ci/terraform/variables.tf

Enable cloudfront log shipping to splunk
- Update the cloudfront cloudformation template
- Add a new variable to enable splunk log forwarding
- Update production.tfvars to enable splunk log forwarding in prod

BAU: Send Cloudfront logs to Splunk

---

src/utils/logger.ts

It's often useful to see the headers attached to a specific frontend request. So let's log them.
Code Review

BAU: Log request headers

---

cloudformation/deploy/template.yaml

We are dual running old and new pipelines so the new SAM template.yaml also needs updating to switch the feature on in staging.
1. Code Review

AUT-3834: Enable new MFA reset feature in Staging.

---

docs/diagrams/usecase/auth-use-case-overview.puml

Add overview use case diagram in PlantUML.
See [generated image](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4296867886/Diagrams)

BAU: Add overview use case diagram

---

src/app.constants.ts
src/components/ipv-callback/cross-browser-middleware.ts
src/components/ipv-callback/cross-browser-service.ts
src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/ipv-callback-routes.ts
src/components/ipv-callback/tests/cross-browser-middleware.test.ts
src/components/ipv-callback/tests/cross-browser-service.test.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts
src/components/ipv-callback/tests/ipv-callback-integration.test.ts
src/components/ipv-callback/types.ts
src/components/mfa-reset-with-ipv/mfa-reset-authorize-service.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-authorize-service.test.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts
src/components/mfa-reset-with-ipv/types.ts
src/middleware/allow-user-journey-middleware.ts
src/middleware/session-middleware.ts
src/middleware/tests/session-middleware.test.ts

- Send additional info with authorize request
- Identify returning cross browser users
- Fetch redirect URL from backend and redirect
Commit-wise

AUT-3924: cross browser

---

cloudformation/deploy/template.yaml

Enable IPV for authdevs in new frontend
1. Code Review

AUT-3982: Enable IPV for authdevs in new frontend

---

cloudformation/deploy/template.yaml

AUT-3982: Correct the Authdev environment ipv condition as Sub environment
1. Code Review

AUT-3982: Correct the Authdev environment ipv condition as Sub environment

---

src/components/common/state-machine/state-machine.ts
src/components/mfa-reset-with-ipv/mfa-reset-with-ipv-controller.ts
src/components/mfa-reset-with-ipv/tests/mfa-reset-with-ipv-controller.test.ts

Reverts govuk-one-login/authentication-frontend#2494

Revert "AUT-3962: Allow going back after starting MFA reset with IPV"

---

src/components/ipv-callback/ipv-callback-controller.ts
src/components/ipv-callback/tests/ipv-callback-controller.test.ts

The journey on the user's session was ACCOUNT_RECOVERY as a result of starting the MFA reset with IPV journey. This caused the VerifyMfaCodeHandler in the back end to get an invalid auth app secret, in turn causing valid auth app MFAs to fail. As this is in the case where the identity reproving with IPV has failed, the journey type should go back to what it was before initiating MFA reset with IPV (which can be reauthentication or sign_in). As a fix, I’ve set req.session.user.isAccountRecovery to false if IPV returns an error response.
1. Code Review
2. Run through MFA reset with IPV journey choosing an error response from the stub
3. See that a valid auth app code succeeds
I have checked the journey types by printing out to cloudwatch on the back end in the VerifyMfaCodeHandler. Can …

AUT-4005: Fix auth app OTP challenge after IPV error bug

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
cloudformation/deploy/template.yaml

Add config to enable MFA reset IPV reverification in authdevs.
1. Code Review
2. Deploy to authdev envs and attempt an MFA reset.

AUT-3982: Enable IPV stub in authdevs

---

cloudformation/deploy/template.yaml

AUT-3693: Set IPV Spinner  false in Int and  prod env also  no Orchstub in Int and Prod env
1. Code Review

AUT-3693: set IPV Spinner  false in Int and  prod 

---

cloudformation/deploy/template.yaml

Disable nginx-sidecar in production frontend
Part of migration steps https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan#Switch-traffic-to-the-new-frontend-ALB.1

AUT-3694: Disable nginx-sidecar in production frontend

---

cloudformation/deploy/template.yaml

Enable the new MFA reset feature in the new secure pipelines build environment.
1. Code Review

AUT-3822: Enable MFA reset in new sp-build env.

---

cloudformation/deploy/template.yaml

Use DynatraceNonProductionVariables for dynatrace layer in integration

AUT-3693: Use DynatraceNonProductionVariables for dynatrace layer in integration

---

deploy-authdevs.sh

BAU: Adding  a note for Authdev1 & Authdev2 Legacy frontend deployment
1. Code Review
2.  deploy ./deploy-authdevs.sh -p  select option 1 or 2

BAU: Added a note for Authdev1 & Authdev2 Legacy frontend deployment

---

ci/terraform/auto-scaling.tf
ci/terraform/production.tfvars
ci/terraform/staging.tfvars
cloudformation/deploy/template.yaml

AUT-4079: changing the ECS task size based on recommendation to fix the 504 error observed during perf test ,also adjusted the threshold for scaling 
1. Code Review

AUT-4079: changing the Ecs task size based on recommendation

---

.pre-commit-config.yaml
.tflint.hcl
ci/terraform/alb.tf
ci/terraform/auto-scaling.tf
ci/terraform/core.tf
ci/terraform/variables.tf
scripts/tflint.py

[AUT-4069] Add tflint configuration
Fix all pre-existing issues.
I've disabled `aws_elasticache_replication_group_default_parameter_group`, because I don't want to fix it and don't want it to throw errors for people.
Code Review
[AUT-4069]: https://govukverify.atlassian.net/browse/AUT-4069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4069: Add tflint and fix existing issues

---

src/components/contact-us/contact-us-controller.ts
src/config.ts

- Turn on mfa reset with ipv contact form changes
- This needs to be reverted after HGS does UAT testing
- Only in lower environments
1. Code Review

BAU: turn on mfa reset with ipv contact form changes

---

cloudformation/deploy/template.yaml
src/config.ts

Until we cut over to full SP, show the test banner in sp production.
Code review

AUT-3846: Show test banner in SP prod

---

ci/terraform/authdev1.tfvars
ci/terraform/authdev2.tfvars
ci/terraform/dev.tfvars
ci/terraform/ecs.tf
ci/terraform/staging.tfvars
ci/terraform/variables.tf
cloudformation/deploy/template.yaml
src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/index.njk
src/components/enter-authenticator-app-code/tests/__snapshots__/enter-authenticator-app-code-integration.test.ts.snap
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts
src/components/enter-mfa/enter-mfa-controller.ts
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/index.njk
src/components/enter-mfa/tests/__snapshots__/enter-mfa-integration.test.ts.snap
src/components/enter-mfa/tests/enter-mfa-controller.test.ts
src/components/enter-mfa/tests/enter-mfa-integration.test.ts
src/components/reset-password/reset-password-controller.ts
src/components/reset-password/tests/reset-password-controller.test.ts
src/config.ts

Reverts https://github.com/govuk-one-login/authentication-frontend/pull/2592 as we are seeing test failures in the SP pipeline.
We currently think this is unlikely to be related to this change, but reverting to rule out.

Aut 4088/revert

---

cloudformation/deploy/template.yaml

Switch sp to new alb in production
Step 3.11 in the deployment plan: https://govukverify.atlassian.net/wiki/spaces/LO/pages/4773052525/Auth+New+Frontend+Go-live+Release+Plan
1. Code Review

AUT-3694: switch sp to new alb in production

---

src/locales/cy/translation.json

The previous value was a google translate placeholder. This is the actual translation from DWP.
Confirm that the value in the json file is the same as the value in the spreadsheet

BAU: fix CY translation for test banner

---

src/components/contact-us/contact-us-controller.ts
src/config.ts

Reverts govuk-one-login/authentication-frontend#2586

Revert "BAU: turn on mfa reset with ipv contact form changes"

---

cloudformation/deploy/template.yaml

Deploy dev frontend with migrated zone
Cleanup transitional signin-sp configurations and feature flag
Issues: [AUT-3942], [AUT-4121]
Deploy to authdev1, authdev2, dev frontend
[AUT-3942]: https://govukverify.atlassian.net/browse/AUT-3942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4121]: https://govukverify.atlassian.net/browse/AUT-4121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-3942: Deploy dev frontend and transitional -sp domain cleanup

---

src/components/landing/landing-route.ts

This allows express to pick up async errors which occur in this controller.
See ticket for details

AUT-4149: wrap landing get

---

src/components/enter-email/enter-email-controller.ts
src/components/healthcheck/healthcheck-controller.ts
src/utils/logger.ts

- Update the logging middleware to exclude the healthcheck
- Remove the log from the healthcheck endpoint
Tested locally
Code review only
No relevant checklist items

AUT-4169: Do not log on healthcheck requests

---

src/utils/logger.ts

#2672 missed a healthcheck path. Add it to fully suppress healthcheck loggint

AUT-4169: Add missing healthcheck path

---

src/components/authorize/authorize-controller.ts
src/components/authorize/authorize-service.ts
src/components/authorize/claims-config.ts
src/components/authorize/tests/authorize-service.test.ts
src/components/authorize/tests/test-data.ts
src/components/authorize/types.ts

Reverts govuk-one-login/authentication-frontend#2666

Revert "ATO-1435: Pass new claims to auth backend."

---

src/app.ts
src/components/common/layout/tests/base-integration.test.ts
test/unit/static.test.ts

Add some more permissive cache control headers to the static assets. 
Ensure application pages remain uncached
No relevant items

AUT-4209: Cache static assets

---

dev-app-orchstub.js
src/app.constants.ts
src/components/common/state-machine/state-machine.ts
src/components/enter-email/enter-email-controller.ts
src/components/enter-email/enter-email-routes.ts
src/components/enter-email/tests/enter-email-controller.test.ts
src/components/enter-email/tests/enter-email-create-account-integration.test.ts
src/components/sign-in-or-create/index-mobile.njk
src/components/sign-in-or-create/sign-in-or-create-routes.ts
src/locales/cy/translation.json
src/locales/en/translation.json

Users of the strategic app will be able to create accounts. This link allows them to access this journey. The content on the `/sign-in-or-create` content is also updated and users are allowed to go back to the `/sign-in-or-create` screen after clicking create and start the sign in journey.
| English | Welsh |
| --- | --- |
| ![localhost_3000_sign-in-or-create(iPhone 12 Pro)](https://github.com/user-attachments/assets/76bd9711-37fb-4b0e-a68e-438606c4e27c) | ![localhost_3000_sign-in-or-create_lng=cy(iPhone 12 Pro)](https://github.com/user-attachments/assets/7b595917-c022-4c73-bbac-e0fe9425be20) |
1. Code Review

AUT-4173: Add create link for strategic app channel

---

package.json
yarn.lock

Reverts govuk-one-login/authentication-frontend#2733

Revert "BAU: Bump jsdom from 26.0.0 to 26.1.0"

---

ci/terraform/authdev1.tfvars

No changes this PR is to trigger new Build
1. Code Review

BAU: Dummy Commit to trigger build again from main

---

.github/workflows/call_build-push-docker-image.yml
.github/workflows/checkov.yml
.github/workflows/pre-commit.yml
.github/workflows/require-pinned-github-actions.yml

Reverts govuk-one-login/authentication-frontend#2761

Revert "BAU: Bump the gha-all-dependencies group across 1 directory with 4 updates"

---

src/locales/cy/translation.json
src/locales/en/translation.json

Privacy office email updates.
- update the email provided for the GDS Privacy office in the Privacy Notice
- correct a typo
1. Code Review
1. Deploy to an environment for testing.
#2756

AUT-4269: privacy office email updates

---

src/components/common/verify-code/verify-code-controller.ts
src/components/reset-password-check-email/index.njk
src/components/reset-password-check-email/reset-password-check-email-controller.ts
src/components/reset-password-check-email/reset-password-check-email-validation.ts
src/components/reset-password-check-email/tests/__snapshots__/reset-password-check-email-integration.test.ts.snap
src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts
src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts

We're currently dropping the isForcedPasswordResetJourney parameter when rendering a validation error, so the rendered screen changes when you enter an incorrect code. This introduces a more robust mechanism for passing unchanging template parameters through validation checks
Code review. I'd welcome comments on the approach, I'm planning to extend this to other places we do validation unless there are objections

AUT-4244: Fix validation for reset password check email

---

cloudformation/deploy/template.yaml

BAU: changing vcpu ecs task to 1cpu in staging for perf testing
1. Code Review

BAU: changing vcpu ecs task to 1cpu in staging for perf testing

---

src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk
src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts
src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk
src/components/enter-mfa/tests/enter-mfa-controller.test.ts

- Adds the 'try another way prompt' to uplift screens when a user has multiple MFAs, allowing them to go through the switch prioritised MFA journey.
1. Code Review
2. Go through uplift journey with multiple MFAs set up. See 'try another way' prompt and switch prioritised MFA.

AUT-4199: Uplift journey with multiple migrated MFAs

---

src/components/contact-us/contact-us-controller.ts

Pages are working, but missing this property for the new OL app sign in problem. It was failing with `TypeError: Cannot read properties of undefined (reading 'issueDescription')`
The form type of the new page is 
`<input type="hidden" name="formType" value="oneLoginAppSignInProblem"/>`
so this maps the formType to the correct set of data.
1. Code Review
This cannot be tested in dev, as our dev envs aren't hooked up to send forms.

AUT-4347: add missing form type to questions

---

cloudformation/deploy/template.yaml

FRONTEND_API_BASE_URL set from environment mappings.
Staging api base url is set to the new location (auth-internal-api running from the new strategic staging account)
Deploy to dev envs

AUT-4544: FRONTEND_API_BASE_URL set from environment mappings

---

cloudformation/deploy/template.yaml

AUT-4544: rollback staging FRONTEND_API_BASE_URL to auth pipeline deployed instance

AUT-4544: rollback staging FRONTEND_API_BASE_URL to auth pipeline deployed instance

---

cloudformation/deploy/template.yaml

[AUT-4700]: Hardcode Dynatrace layer ARN to fix bugs in Cloud-formation
1. Code Review
[AUT-4700]: https://govukverify.atlassian.net/browse/AUT-4700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4700: hardcode dynatrace layers to fix bugs in Cloud-formation

---

cloudformation/deploy/template.yaml

Post testing in staging revert PR Reverts govuk-one-login/authentication-frontend#2986

Revert "AUT-4710: Staging authExternalApiId & Auth Internal Api ID temporary …"

---

cloudformation/deploy/template.yaml

Reverts govuk-one-login/authentication-frontend#2997

Revert "Aut 4711 build testing iteration 1 auth ext api and auth internal api"

---

src/components/common/state-machine/state-machine-executor.ts
src/components/enter-email/enter-email-controller.ts
src/types.ts

This reverts commit 7f6e1142441fcac5996f3d00164a5ff3fa8e2177.
Follow up PR to https://github.com/govuk-one-login/authentication-frontend/pull/2998 which cleans up the `enterEmailMfaType`

BAU: Clean up enterEmailMfaType
