govuk-one-login/authentication-frontend

ci/pipeline.yaml
Inject API_BASE_URL env var from a pipeline secret into the frontend application on deployment.
Frontend now calls a real /userexists endpoint so needs to know where it is.
=> LTG-17: inject API_BASE_URL env var from a pipeline secret

locales/en/translation.json, src/app.constants.ts, src/controllers/register-account-created-controller.ts, src/controllers/register-create-password-controller.ts, src/routes.ts, src/views/register-account-created.html
Add 'account created successfully' page.
When 2FA not required navigate to this page after 'enter password', otherwise navigate to 'enter phone number'.
In order to test the flow include 'no2fa' in the email to simulate a client not requiring 2FA.
- Given that the user has successfully created their password AND the service that the user requires only Email and Password for to access their service, When they select “Continue”, Then an account must be created for the user AND they should be directed to “You have successfully created your GOV.UK account” UI.
=> LTG-35: add account created successfully page

session-start-local.sh
Add script to launch the app locally with a session id
If running a local node app against the remote API a session id is required from the API in order to run the flow.  This script retrieves the session id and passes it to the local app.
=> BAU: add script to launch the app locally with a session id

src/app.ts
The deployment of the app to paas can't find the path to where the views live so throws an error. This PR fixes that.
=> Fix path for views for deployment

.github/dependabot.yml
Initial dependabot config to update node and docker dependencies.
Keep repo up to date with dependency versions.
=> BAU: add dependabot

README.md, startup.sh
- Update README.MD with instructions on how to run the frontend application.
- Update the startup.sh, so it won't error if the script is run and there is a stopped container.
- So the startup.sh will restart the application whether the container is running or stopped
- So people know how to run the app locally.
=> BAU - Update README and amend startup.sh

src/config/i18next.ts
The path to the translation files is broken when deployed.
To allow pages to be translated properly.
=> Fix path to load translations

src/components/common/layout/base.njk, src/components/register-verify-email/index.njk, src/components/register-verify-email/register-verify-email-controller.ts, src/locales/en/translation.json
Tweak 'check your email' to look like prototype.
Make sure all text and fonts are correct.
Include the email address entered on the previous page.
Page must conform to the design.
=> LTG-371: tweak 'check your email' to look like prototype

src/config/helmet.ts
Add sha for inline script in helmet config.
In the base template for gov.uk frontend there is a inline script which is not allowed with the CSP policy the app has in place. This has been fixed by adding the sha value to the helmet config.
For more info refer to https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#if-your-javascript-is-not-working-properly
=> Fix for CSP issue in base layout for gov frontend

src/app.constants.ts, src/components/enter-email/tests/enter-email-integration.test.ts
Change 'userexists' endpoint to user-exists.
Keep API resource path names consistent.
https://github.com/alphagov/di-authentication-api/pull/109
=> BAU: Change 'userexists' endpoint to user-exists.

.github/workflows/pre-merge-checks.yml, src/app.constants.ts, src/app.ts, src/components/create-password/tests/create-password-integration.test.ts, src/components/enter-email/tests/enter-email-integration.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts, src/components/landing/landing-controller.ts, src/components/verify-email/tests/verify-email-integration.test.ts, src/config/cookie.ts, src/middleware/session-middleware.ts
Update cookie options for csurf, i18next and cookie session.
The cookies did not have the correct settings set for httponly and secure so this has been updated.
=> Update all cookies security options

src/handlers/internal-server-error-handler.ts
In the global handler for errors there is no need to call the next middleware
As this is the end of the middleware pipeline it doesn't need to call next.
=> remove next call in error handler

.eslintignore, package.json, src/assets/javascript/application.js, src/assets/javascript/cookies.js, src/components/common/layout/banner.njk, src/components/common/layout/base.njk, src/locales/en/translation.json
Add cookie banner and save cookie preferences.
User must be prompted to save their cookie preferences.
=> GOVSI-126: add cookie banner and save cookie preferences

src/locales/en/translation.json
Add missing spaces to cookie banner text.
Spaces are missing.
=> GOVSI-126: add missing spaces to cookie banner text

src/assets/javascript/cookies.js, src/components/common/cookies/index.njk, src/locales/en/translation.json
Update the cookie policy page with the latest content.
Add required UI components.
Save updated preferences when the user clicks the save button.
As a user 
I want to know how the cookies will be used on the authentication service 
So that I can make an informed decision as to whether I want the service to use cookies
=> GOVSI-104: add cookie policy page and save preferences

src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts
Only redact the phone number to be stored for the session.
A bug was introduced where the redacted phone number was failing on the backend validation.
=> Redact phonenumber only for session

ci/pipeline.yaml
Run acceptance tests in the pipeline.
Pipeline migrated from di-auth-oidc-provider.
Tests only currently triggered by changes to the frontend and/or the acceptance tests.
Step towards gating deployment to the next environment based on acceptance test success.
Identify breaking changes quickly and before they are deployed further.
https://github.com/alphagov/di-authentication-acceptance-tests
=> BAU: run acceptance tests in the pipeline

ci/pipeline.yaml, manifest.yml
Use the DNS route front.build.auth.ida.digital.cabinet-office.gov.uk to the front end.
Required to allow cookies to be shared between front and backend endpoints.
=> GOVSI-606: Add route to frontend

manifest.yml
We had included a badly formed `routes` section in the `manifest.yml` file.
Deployment is failing.
#133
=> GOVSI-606: Fix manifest error

ci/pipeline.yaml
Update signin frontend app url for acceptance tests
We now have a new domain name for the frontend which should be reflected in the tests.
=> BAU: update signin frontend app url for acceptance tests

package.json, yarn.lock
- BAU: Bump @types/pino from 6.3.8 to 6.3.11
- BAU: Bump @types/chai from 4.2.19 to 4.2.21
- BAU: Bump @types/pino-pretty from 4.7.0 to 4.7.1
- BAU: Bump @types/i18next-fs-backend from 1.0.0 to 1.0.1
- BAU: Bump @types/nunjucks from 3.1.4 to 3.1.5
- BAU: Bump @types/cheerio from 0.22.29 to 0.22.30
- BAU: Bump @types/csurf from 1.11.1 to 1.11.2
=> dependabot commits merge 20210804 172056

dev-app.js, src/app.constants.ts, src/app.ts, src/components/share-info/index.njk, src/components/share-info/share-info-controller.ts, src/components/share-info/share-info-routes.ts, src/components/share-info/share-info-service.ts, src/components/share-info/tests/share-info-controller.test.ts, src/components/share-info/types.ts, src/locales/en/translation.json, src/middleware/session-middleware.ts, src/utils/http.ts
Create share-info page and api calls to capture user consent.
- Add new page which calls 'client-info' on GET to retrieve the client name and list of supported scopes for displaying on the page.
- On submit (POST) call 'update-profile' to store the user consent against the client in the user profile.
Includes additional local node app by @sanisc that starts a session and run the flow locally.
The application must capture the user's consent to share data with the service.
https://github.com/alphagov/di-authentication-api/pull/261
https://github.com/alphagov/di-authentication-api/pull/265
https://github.com/alphagov/di-authentication-api/pull/267
=> GOVSI-281: create share-info page and api calls to capture user consent

src/components/common/errors/404.njk, src/components/common/errors/500.njk, src/components/common/errors/session-expired.njk, src/locales/en/translation.json, startup.sh
Update content and use translations for 404, 500 and session expired error pages.
Content has been refresh since the pages were first created.
Pages were not completely templated to read from translations.
=> GOVSI-611: update content and use translations for 404, 500 and session expired error pages

src/components/common/errors/404.njk, src/locales/en/translation.json
Content updates to error pages based on the latest Figma.
Pages were built against content documents linked in the ticket.  Content has since changed and is superseded by the Figma.
=> GOVSI-611: error page content updates to match the figma

src/components/share-info/index.njk, src/components/share-info/share-info-routes.ts, src/components/share-info/share-info-validation.ts, src/components/share-info/tests/share-info-integration.test.ts, src/locales/en/translation.json
By default no option will be selected.
On clicking continue an error message will be displayed if no option is selected.
Page content has been updated in the Figma and there is new default behaviour and an error message for when no option is selected by the user for sharing.
#155 
#267
#265
#261
=> GOVSI-281: updated content for 'share-info' page

src/app.constants.ts, src/app.ts, src/components/enter-password/index.njk, src/components/reset-password-check-email/index.njk, src/components/reset-password-check-email/reset-password-check-email-controller.ts, src/components/reset-password-check-email/reset-password-check-email-routes.ts, src/components/reset-password-check-email/tests/reset-password-check-email-controller.test.ts, src/locales/en/translation.json
Add new 'reset password check email' page
Update link from 'forgotten password' on 'enter password page.
This is only the new page, build of backend service to follow.
As part of Account Recovery, when an existing user is logging in, we need to have an option for them to reset their password, in case they have forgotten it.
=> GOVSI-641: add new 'reset password check email' page

src/components/create-password/create-password-controller.ts, src/components/create-password/tests/create-password-controller.test.ts, src/components/enter-password/enter-password-controller.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts
- Skip 2FA when the state of AUTHENTICATED is returned
- We can remove the check in the create-password-controller and MFA is required atm for users who are signing up
- When a user successfully logs in the service requires MFA then the LOGGED_IN is returned from the API and the user is required to confirm who they are using 2FA which is why they are then redirected to the check your phone page.
- For services that don't require MFA when a user logs in then the AUTHENTICATED state is returned from the API and we can redirect the user to auth-code, skipping the need for 2FA.
=> GOVSI-819 - Skip 2FA when the state of AUTHENTICATED is returned

src/components/enter-password/enter-password-controller.ts, src/components/enter-password/enter-password-service.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts, src/components/enter-password/types.ts
- Pass through the client session ID to the login endpoint
- It is required by the Login lambda so it can find out the relevant client details and calculate the state machine rule
=> GOVSI-818 - Pass through the client session ID to the login endpoint

src/components/common/mfa/mfa-service.ts, src/components/common/mfa/types.ts, src/components/resend-mfa-code/resend-mfa-code-controller.ts, src/components/resend-mfa-code/tests/resend-mfa-code-controller.test.ts, src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts
Add error handling when rate limit hit on enter-mfa endpoint
To prevent abuse of the system.
=> Add mfa rate limiting

src/components/enter-password/enter-password-controller.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts, src/components/enter-password/types.ts
- Change the login lambda to check if the REQUIRES_TWO_FACTOR state is returned from login and redirect them to the CREATE_ACCOUNT_ENTER_PHONE_NUMBER screen if so
- Make redacted phone number optional as it will not be returned if this state is returned
- When the REQUIRES_TWO_FACTOR state is returned from the login endpoint, we need to direct the user to the CREATE_ACCOUNT_ENTER_PHONE_NUMBER page so that they can register a phone number and verify it.
=> GOVSI-839 - Amend frontend for dropoffs

src/components/landing/landing-controller.ts, src/middleware/session-middleware.ts
Only create a new session if one doesn't exist
To allow SSO to work with consent, tc's and VTR. This will all be superseeded when the session is moved to redis.
=> Only create a new session if one doesn't exist

.github/workflows/pre-merge-checks.yml, docker-compose.yml, manifest.yml, src/components/check-your-email/tests/check-your-email-integration.test.ts, src/components/check-your-phone/tests/check-your-phone-integration.test.ts, src/components/create-password/tests/create-password-integration.test.ts, src/components/enter-email/tests/enter-email-integration.test.ts, src/components/enter-mfa/tests/enter-mfa-integration.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts, src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts, src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts, src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/components/share-info/tests/share-info-integration.test.ts, src/components/updated-terms-conditions/tests/updated-terms-conditions-integration.test.ts, src/config.ts, src/utils/http.ts
Repoint to frontend api.
The oidc and frontend endpoints have been split into two separate apis.  These changes repoint the frontend to use the new api.
New environment variable FRONTEND_API_BASE_URL with the new api url.
Ability to isolate the two APIs. They can then be deployed separately and have different configurations (such as access controls and rate limits).
https://github.com/alphagov/di-authentication-api/pull/642
=> GOVSI-748: repoint to frontend api

.github/workflows/analyse-on-merge.yml, .github/workflows/pre-merge-checks.yml, package.json, sonar-project.properties
- Ensure `nyc` outputs the coverage reports in LCOV format
- Add `sonar-project.properties` file
Sonar is analysing this repo but not producing coverage stats
=> GOVSI-1053: Add Coverage Reports for Sonar

sonar-project.properties
- The property to specify the coverage path is now plural
- Also, remove the deprecated `sonar.language` property
Coverage was not being correctly reported to SonarCloud
#372
=> GOVSI-1053: Fix invalid coverage property name

src/components/security-code-error/index-too-many-requests.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Remove spaces from OTP error page hyperlinks.
Use securityRequestsExceededExpired resources rather than securityCodeInvalid for 'too many requests'
'get a new code' links contained an extra hyperlinked space at the end.
=> GOVSI-1102: remove spaces from OTP error page hyperlinks

src/components/enter-email/enter-email-validation.ts, src/components/enter-email/tests/enter-email-integration.test.ts
- Use the Notify validation when validating emails in our frontend. https://github.com/alphagov/notifications-utils/blob/c264fa9facedf721c8dd9cf8ee2766591e750e0c/notifications_utils/__init__.py#L14
- Disable lint validation on regex
- There were email addresses that were passing our validation but then failing on Notify.
=> GOVSI-1111 - Bring email validation inline with Notify

src/components/common/layout/base.njk
Amend support link to point to contact form.
For go-live, since we are only going ahead with an end-user “Contact us” form, we need to amend the “Support” link on the Sign In footer to lead users directly to the “Contact us” form. Currently, it takes users to a “Support” page.
=> Amend support link to point to contact form

src/utils/logger.ts, test/unit/utils/logger.test.ts
Log referer path as 'from' for a request.
Use the 'referer' header for a request to log the page where the user came from.
Understand actual user journey more easily from the logs.
=> BAU: log referer path as 'from' for a request

.github/workflows/analyse-on-merge.yml
Add zendesk env var to on merge check.
Sonarqube checks now run on merge, which also runs the integration tests for coverage, so they env var is needed here too.
#396
=> BAU: add zendesk env var to on merge check

src/utils/logger.ts, test/unit/utils/logger.test.ts
Understand actual user journey more easily from the logs
Log referer path as 'from' for a request.
Use the 'referer' header for a request to log the page where the user came from.
Understand actual user journey more easily from the logs.
Take-two as there was an issue with post-merge checks:
#401 
#397
=> BAU: log referer path as from for a request

src/components/account-created/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Update account-created confirmation page to include email subscriptions.
There will be a corresponding email template change directly in Notify.
This service will soon be supported by GOV.UK.
The PR will only be merged when the service actually goes live.
=> GOVSI-1094: update account-created confirmation page for email subs

src/app.constants.ts, src/components/common/footer/footer-pages-routes.ts
Add redirect for 'privacy-statement' to the privacy policy.
Resolves https://govuk.zendesk.com/agent/tickets/4784737 until accounts can update the link.
=> BAU: add redirect for 'privacy-statement' to the privacy policy

.github/dependabot.yml
Remove dependabot open-pull-requests-limit.
Ability to choose from all available upgrades.
https://github.com/alphagov/di-authentication-account-management/pull/246
=> BAU: remove dependabot open-pull-requests-limit

dev-app.js, src/components/reset-password/reset-password-controller.ts, src/components/reset-password/tests/reset-password-controller.test.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/components/reset-password/types.ts
- Pull off the session-id and persistent-id from the reset password link and send them in the API request.
- If they can't be found then return the expired password link page to the user, the same as we do if the code has been tampered with
- Set the client-id correctly in the dev-app.js for when we run the frontend locally
- Add extra tests
- So the reset password has the session-id and persistent-session-id available to it
=> GOVSI-1154 - Send session and persistent id in request to reset-password

src/components/reset-password/reset-password-service.ts
- Send session-id as header to reset password
- The session-id wasn't being sent as it wasn't configured in the reset-password-service.ts
=> GOVSI-1154 - Send session-id as header to reset password

src/utils/logger.ts
- Only log 'res' fields supported by pino.
- Log persistentSessionId
pino 'res' supports 'statusCode' but not the other fields:
https://github.com/pinojs/pino-std-serializers
https://github.com/alphagov/di-authentication-account-management/pull/249
=> BAU: only log res fields supported by pino

.github/workflows/pre-merge-checks.yml
Dependabot can't access github repo secrets for PR's created by dependabot. PR removes sonar scans on dependabot PR's.
=> Only sonarscan when none dependabot PR

src/app.constants.ts, src/app.ts, src/components/check-your-email/index.njk, src/components/prove-identity/prove-identity-controller.ts, src/components/prove-identity/prove-identity-routes.ts, src/components/prove-identity/prove-identity-service.ts, src/components/prove-identity/tests/prove-identity-controller.test.ts, src/components/prove-identity/types.ts
Add new route to call ipv-authorize
- Provide a way to test redirecting to the IPV service by calling the ipv-api 'ipv-authorize' endpoint then redirecting to the uri provided.
- The route is not integrated into the flow and needs to be hit manually.
- A session with an email address is required, so make sure to get past 'enter-mail' before entering the 'prove-identity' url in the browser to test.
- The browser will then redirect to the IPV stub.
- The new route is only deployed to build and integration.
Test handoff integration with the IPV stub.
https://github.com/alphagov/di-authentication-api/pull/1165
=> GOVSI-1165: add new route to call ipv-authorize

Dockerfile, docker-compose.yml, local.Dockerfile, package.json
- Create a new docker image which will be used when running the frontend in Fargate.
- Use docker mult-stage builds to optimize our Dockerfile and reduce the size. This has brought the size down from 152.62 mb to 52.24 mb in ECR
- Carry on using the existing image when running locally and rename it to local.Dockerfile.
- When we are running in an env other than local, there's a lot of dependencies that we don't require. 
-  In our Dockerfile which will be used for all env other than local, we can specify `yarn install --production=true` which will ensure we exclude all dependencies under devDependencies in package.json. This has meant that some of these dependencies that we do require had to be copied up to the dependencies in package.json.
- We need the local.Dockerfile to carry on using …
=> AUTH-1306  - Make optimized docker image to run with Fargate

src/app.constants.ts, src/app.ts, src/components/healthcheck/healthcheck-controller.ts, src/components/healthcheck/healthcheck-routes.ts, src/components/healthcheck/tests/healthcheck-controller.test.ts, src/components/healthcheck/tests/healthcheck-integration.test.ts
Add healthcheck endpoint to frontend management application.
The endpoint returns a simple '200 OK'
ALB and Fargate requires a healthcheck endpoint to know whether the app has started.
https://github.com/alphagov/di-authentication-account-management/pull/304
=> AUTH-1277: add healthcheck endpoint to frontend application

ci/terraform/production.tfvars
- Use the correct value for `common_state_bucket` in the `production.tfvars`, this is incorrectly pointing at the non-production state bucket.
The deploy to production is failing as it can't read from the specified (incorrect) bucket.
#472
=> AUTH-1276: Fix incorrect bucket name in production.tfvars

README.md
Fix Concourse URL and deployment job name.
Because they are incorrect.
=> BAU: Fixed some outdated README info

package.json, src/app.ts, src/components/check-your-email/tests/check-your-email-integration.test.ts, src/components/check-your-phone/tests/check-your-phone-integration.test.ts, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/create-password/tests/create-password-integration.test.ts, src/components/enter-email/tests/enter-email-integration.test.ts, src/components/enter-mfa/tests/enter-mfa-integration.test.ts, src/components/enter-password/tests/enter-password-integration.test.ts, src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts, src/components/healthcheck/tests/healthcheck-integration.test.ts, src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts, src/components/reset-password-check-email/tests/reset-password-check-email-integration.test.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/components/share-info/tests/share-info-integration.test.ts, src/components/updated-terms-conditions/tests/updated-terms-conditions-integration.test.ts, src/config.ts, src/config/session.ts, src/server.ts, src/utils/ssm.ts, src/utils/types.ts, yarn.lock
Read Redis configuration from SSM for ECS Fargate.
- Update server startup to support async calls.
- Update integration tests to support async startup.
- Include aws-sdk in dependencies to make use of aws.ssm library.
- Add a flag to show when the app is running under Fargate.
- Retrieve the Redis config from SSM when on Fargate.
Frontend currently runs on PaaS and retrieves Redis connection details from PaaS services. This option is not available when running on ECS Fargate.
Some Redis connection details are secret so we decided to put them in AWS SSM Parameter store. This PR reads these parameters from SSM when running under Fargate so that the app can connect to Redis.
https://github.com/alphagov/di-authentication-account-management/pull/312
=> AUTH-1358: read redis configuration from ssm for ecs fargate

ci/tasks/deploy-frontend.yml, ci/terraform/build.tfvars, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/variables.tf
- Terraform requires a values for new variables that, mostly, come from Concourse secrets.
- Change default value of frontend_api_url (should be `null`)
To enable deployment in the pipeline.
#478
=> AUTH-1359: Update deploy task to inject new Terraform variables

ci/terraform/cloudwatch.tf, ci/terraform/waf.tf
- Add a WebACL to the frontend ALB (use same rules as we currently use on API)
- Add logging of blocked requests to a new log group
- Drain log groups to Splunk
To secure the ALB we will be using to host the frontend
=> AUTH-1321: Add a WAF to the frontend ALB

ci/terraform/cloudwatch.tf, ci/terraform/ecs.tf
- Rename the ECS service log group to be prefixed with `/ecs/`
This will group all the ECS related logs together (alphabetically) in Cloudwatch and make it easier to pick out the log groups in the Splunk processor.
https://github.com/alphagov/di-infrastructure/pull/158
https://github.com/alphagov/di-authentication-account-management/pull/333
https://github.com/alphagov/centralised-security-logging-service/pull/797
=> AUTH-1369: Rename ECS service log group

src/locales/cy/translation.json, src/locales/en/translation.json
Update inset text on 'no account found' screen.
Use consistent language about the relationship between this account and other accounts throughout the application.
=> AUTH-1337: update inset text on no account found screen

ci/terraform/variables.tf, ci/terraform/waf.tf
- Adjust WAF rate limiting rule to allow 5000 requests in 5 mins
- Adjust service deployment parameters to allow a max 150% 
Rate limit rule was being triggered while testing due to the fact that each page visit incurs circa 10 page requests.
The deployment rules ensure that ECS has enough scope to start up new tasks before shutting down old versions whilst still maintaining the desired number of running instances.
=> AUTH-1316: Tweak ZDD and rate limit

ci/terraform/route53.tf
- In preparation for the migration lets change the hostname on the ALB TLS certificate to that of the real DNS name of the service.
We will pointing the real DNS records at the ALBs in the near future, so let's get the certificates ready.
=> AUTH-1388: Change the hostname on the ALB certs

src/locales/cy/translation.json, src/locales/en/translation.json
Update 'mins' to 'minutes' on the 'You cannot reset your password at the moment' screen.
Was carried over from the previous text.
#495
=> AUTH-1355: 'mins' to 'minutes'

ci/terraform/alb.tf, ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/route53.tf, ci/terraform/sandpit.tfvars, ci/terraform/security-groups.tf, ci/terraform/variables.tf
- Remove the flag that controls the creation of the security group rule allowing ingress from anywhere.
- Switch the frontend DNS record (`signin.account.gov.uk`) to point at the Fargate ALB.
- Ensure the Fargate ALB is using the correct certificate.
We are ready to switchover hosting of the frontend.
=> AUTH-1388: Switchover

ci/tasks/deploy-frontend.yml
- We have the number of instances being overridden in both in the environment specific `.tfvars` file and in the pipeline deploy task, lets remove the variable from the task and rely on the `.tfvars`
Injected variables from the deploy task should be reserved for secrets only.
https://github.com/alphagov/di-authentication-account-management/pull/355
https://github.com/alphagov/di-infrastructure/pull/165
=> AUTH-1388: Use tfvars for number of instances

ci/tasks/deploy-frontend.yml, ci/terraform/alb.tf, ci/terraform/ecs.tf, ci/terraform/sandpit.tfvars, ci/terraform/security-groups.tf, ci/terraform/variables.tf
- If we provide a basic auth password to the Terraform then deploy a sidecar Nginx container as a proxy
- The sidecar should proxy requests through to the frontend app use the basic creds provided once its authenticated the user with basic auth creds
- Update security groups to work with this configuration
- Inject sidecar image details to the Terraform, these will be provided by the pipeline.
- Inject basic auth credentials which will be stored in Concourse secrets. As you can't have a blank secret, evaluate the special case of "none" to a blank string.
We wish to protect the integration environment from general use.
https://github.com/alphagov/di-infrastructure/pull/168
=> AUTH-1833: Integration basic auth sidecar

ci/tasks/deploy-frontend.yml
- Remove the trailing whitespace after the `\` in the deploy task. 
The whitespace is getting a interpretted as an empty string parameter and, as such, Terraform is failing.
#503
=> AUTH-1833: Remove troublesome whitespace in task file

src/components/create-password/create-password-controller.ts, src/components/create-password/create-password-service.ts, src/components/create-password/tests/create-password-controller.test.ts, src/components/create-password/tests/create-password-integration.test.ts, src/components/create-password/types.ts
Previously the backend used to return a state to say whether consent is required. This is the new way of doing that so when registering users can accept or reject consent.
=> Fix bug with consent not being populated when registering

src/middleware/cross-domain-tracking-middleware.ts
Fixes issue for public facing pages e.g privacy-policy which don't require a session id
=> Only add if session exists - fix for public facing pages

src/components/contact-us/contact-us-controller.ts
- Fix Zendesk form so it shows the correct question in the Zendesk body
- Currently the `What are you contacting us about` question on the Zendesk form always has `A problem creating an account` as the answer. This is because the text hasn't been changed for when a user selects a different answer.
=> BAU - Fix Zendesk form

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/further-information/_account-creation-further-information.njk, src/components/contact-us/further-information/_signing-in-further-information.njk, src/components/contact-us/index-public-contact-us.njk, src/components/contact-us/questions/_account-creation-problem-questions.njk, src/components/contact-us/questions/_account-not-found-questions.njk, src/components/contact-us/questions/_another-problem-questions.njk, src/components/contact-us/questions/_email-subscriptions-questions.njk, src/components/contact-us/questions/_forgotten-password-questions.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-phone-number-access-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_no-uk-mobile-questions.njk, src/components/contact-us/questions/_signing-in-problem-questions.njk, src/components/contact-us/questions/_suggestion-feedback-questions.njk, src/components/contact-us/questions/_technical-error-questions.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/contact-us/tests/contact-us-controller.test.ts, src/components/contact-us/tests/contact-us-further-information-controller.test.ts, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/components/contact-us/types.ts
- Add the referer to the Zendesk body when it is present 
- Make the back button dynamic on the contact-us page so it can return the user to where they previously were 
- When theme isn't present in the requests to contact-us-further-information or contact-us-questions then redirect to contact-us.
- So we can have a better idea of where users are facing issues 
- So user can return to the previous page if they were stuck 
- Because if a user goes to them 2 pages without a theme they can't do anything so we should redirect them to the contact-us page
=> AUTH-1385 - Add referer to Zendesk api 

ci/terraform/redis.tf
- Remove the Redis instance from PaaS
We are no longer running Frontend in PaaS so we do not need the Redis instance
*N.B. the CloudFoundry Terraform provider will be removed in a follow-up PR, once this PR has been merged and Terraform has destroyed the Redis resource. The follow up PR will also remove any, now, defunct variables and update the deployment task appropriately*
=> AUTH-1389: Remove PaaS Redis resource

ci/tasks/deploy-frontend.yml, ci/terraform/.terraform.lock.hcl, ci/terraform/build.tfvars, ci/terraform/cf-data.tf, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/sandpit.tfvars, ci/terraform/site.tf, ci/terraform/variables.tf
- Remove the `cf-data.tf` file containing CloudFoundry data sources
- Remove the cloudfoundry provider configuration
- Manually remove cloudfoundry provider version info from HCL lock file
- Remove Terraform variables used for CloudFoundry authentication
- Remove Terraform variable used for Redis service plan
- Update deployment task to no longer pass above variables
We are no longer managing any CloudFoundry (PaaS) resources using Terraform as we have moved the frontend to ECS. This PR removes all, now defunct, CloudFoundry related configuration from Terraform.
=> AUTH-1389: Remove CloudFoundry Provider and related variables

src/middleware/cross-domain-tracking-middleware.ts
There has been an issue in the logs that has manifested when users are trying to go to pages without a valid session where ga crossdomain tracking is required.
=> Check client on session so doesn't throw error

ci/terraform/alb.tf, ci/terraform/route53.tf
- Remove the route53 resource `signin-fg.<domain>`
- Remove the ACM resources for generating a certificate for the above domain name
The `signin-fg.<domain>` DNS name was a testing hostname during the migration from PaaS to ECS, it is no longer required.
=> AUTH-1839: Remove the generation of the signin-fg DNS and cert

src/assets/javascript/application.js, src/assets/scss/application.scss, src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/enter-phone-number/enter-phone-number-validation.ts, src/components/enter-phone-number/index.njk, src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts, src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/utils/phone-number.ts, src/utils/strings.ts, test/unit/utils/phone-number.test.ts, test/unit/utils/strings.test.ts
Support international phone numbers.
- Add option for the user to add an international phone number instead of a UK number.
- A checkbox shows and hides a new international phone number input as required.
- Validation rules are slightly different for international numbers.  International numbers are entered in E164 format with or without the leading '+'.
Users without a UK mobile number have been unable to create accounts thus far.
=> AUTH-1360: support international phone numbers

ci/terraform/ecs.tf
- Add a NGINX_HOST environment variable injecting the frontend domain name into the NGINX basic auth sidecar.
We're getting some unusual re-writing of requests that redirect to localhost.
https://github.com/alphagov/di-infrastructure/pull/204
=> BAU: Add a new environment variable to inject a hostname to NGINX

src/components/signed-out/index.njk, src/components/signed-out/signed-out-controller.ts, src/config.ts, src/locales/cy/translation.json, src/locales/en/translation.json, yarn.lock
Update content for the signed-out page in frontend.
Content is not appropriate for some user scenarios.
- Not all users will come via the GOV.UK homepage.
- Include a 'sign in' option for when this makes more sense.
=> AUTH-1376: update content for the signed-out page

src/components/landing/landing-controller.ts, src/components/landing/tests/landing-controller.test.ts, src/components/landing/types.ts
Move ga tracking logic to /start endpoint so it is no longer called in /authorize.
=> Move ga tracking logic to /start endpoint

src/components/contact-us/contact-us-controller.ts
- Use query referer as referer if present
- So we are able to use the referer present on the contact-us link in the emails
=> AUTH-1366 - Use query referer as referer if present

src/components/account-created/account-created-controller.ts, src/components/account-created/account-created-routes.ts, src/components/account-created/index.njk, src/components/account-created/tests/account-created-controller.test.ts
Change account created page to be a form post.
This is to stop issues with users clicking the link more than once which causes error's downstream.
=> Change to post form on account created page

src/locales/cy/translation.json, src/locales/en/translation.json
- Remove norefer from feedback link
- We want to pass the referer on so we know what page the user clicked the feedback link from
=> BAU - Remove norefer from feedback link

src/components/account-not-found/account-not-found-controller.ts, src/components/common/state-machine/state-machine.ts
Add missing error handling to account not found so works as expected when errors come back from the send notification handler.
=> Add error handling to account not found

src/app.constants.ts, src/middleware/log-error-middleware.ts, src/middleware/session-middleware.ts, src/utils/error.ts, test/unit/middleware/log-error-middleware.test.ts
Log invalid session as 'info' not 'error'.
- Extend Error class to add a level field.
- When level is info do not log 'Error' or the stacktrace.
Invalid sessions are not errors and occur because users leave their browsers open for longer than 60 min.  
This change removes error noise from the logs, so people are less likely to think there is an actual problem.
=> AUTH-1473: log invalid session as 'info' not 'error'

src/locales/cy/translation.json, src/locales/en/translation.json
Fix typo on privacy notice
Incorrect address.
=> AUTH-1494: fix typo on privacy notice

src/app.constants.ts, src/components/landing/landing-controller.ts, src/components/landing/tests/landing-controller.test.ts, src/utils/error.ts, test/unit/middleware/log-error-middleware.test.ts
Log backend Error 1000 Session Id missing or invalid as info.
'log-error-middleware.test.ts' changes are just formatting.
All backend 4xx errors are being logged as info so gradually extending this to the frontend to reduce noise in the logs.
#550
=> AUTH-1473: Log backend Error 1000 Session Id missing or invalid as info

package.json, yarn.lock
Force minimist to 1.2.6.
Minimist is a dev-only dependency.
Fix advisory on 1.2.5
https://github.com/advisories/GHSA-xvch-5gv4-984h
=> BAU: force minimist to 1.2.6

ci/terraform/build.tfvars, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/sandpit.tfvars, ci/terraform/staging.tfvars, ci/terraform/variables.tf
- Add a new tfvars file containing valid values for the staging environment.
- Remove the now defunct `paas_frontend_cdn_route_destination` variable.
We are adding a staging environment to integration test with the other components of GOV.UK Sign in
https://github.com/alphagov/di-authentication-api/pull/1581
https://github.com/alphagov/di-authentication-account-management/pull/400
https://github.com/alphagov/di-infrastructure/pull/216
=> AUTH-1427: Add staging environment overrides

ci/tasks/deploy-frontend.yml, ci/terraform/security-groups.tf, ci/terraform/variables.tf
- Make the CIDR block used for to match incoming traffic to the ALB parameterised. The default should be anywhere (`["0.0.0.0/0"]`)
This will allow us to override in the pipeline for staging and other environments.
=> AUTH-1427: Parameterise ALB allowlist

ci/terraform/cloudwatch.tf
- Add the `kms:ReEncrypt*` and `kms:GenerateDataKey*` actions to the cloudwatch policy.
It seems these are now required to create encrypted log groups.
https://github.com/alphagov/di-authentication-account-management/pull/407
=> AUTH-1427: Add missing permissions for Cloudwatch

src/components/enter-password/index-account-exists.njk, src/components/enter-password/index-account-locked.njk, src/components/enter-password/index.njk
Removes the password reset option to allow time for in-flight resets to expire.
The option will be put back again when password reset using an OTP is released straight after.
When password resets using an OTP replace resets using a link there could be a short window where valid links have been sent, but the screens needed to action them have been removed.  In order to avoid this scenario the option to reset passwords will be removed just for long enough for all in-flight reset links to expire.  This means that all users having requested a link will be able to use them before the option disappears.
After 15 mins password resets with an OTP will be deployed, see related PR below.
#562
=> AUTH-1477: drain in-flight password resets

src/components/common/state-machine/state-machine.ts, src/components/landing/landing-controller.ts, src/components/landing/tests/landing-controller.test.ts, src/components/landing/types.ts, src/types.ts
Update landing component to add new state for doc checking app.
To allow the skipping of authentication as this is not required for the document checking app journey.
=> Update landing component to support skipping authentication

ci/terraform/alb.tf, ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/integration.tfvars, ci/terraform/variables.tf
ECS rollout configuration tweaks in build and integration only.
Set health_check_grace_period_seconds to 15s. Current default is 0.
Set ALB deregistration_delay to 30s. Current default is 300s.
Changes to be extended to staging and prod after checks in build and integration.
We currently have these two configuration values set to their defaults.
Currently waiting 300s for the apps to drain during a rollout as the deregistration delay is set to the default. Frontend transactions complete in a matter of seconds so there is no reason to wait for 5 mins. This will reduce rollout timeout.
See the ECS service event log when a rollout happens, it takes 5 mins between deregistration (when the ALB stops sending traffice to the app) and finally stopping the app. Nothing happens during this time. …
=> AUT-212: ECS rollout configuration tweaks in build and integration only

src/components/contact-us/further-information/_account-creation-further-information.njk
Move 'You do not have a UK mobile phone number' to top of list on support form to try improve the user experience.
=> Make no UK phone priority on support form

ci/terraform/auto-scaling.tf, ci/terraform/ecs.tf, ci/terraform/sandpit.tfvars, ci/terraform/variables.tf
Add auto scaling config for frontend.
Variables created to override min and max counts, cpu and memory trigger thresholds, and cpu and memory for the app.
Includes scale out and scale in cooldown periods too.
Applies only in sandpit, switched off in all other environments.
The frontend apps should be able to scale according to demand.
https://github.com/alphagov/di-authentication-account-management/pull/461
=> AUT-213: add auto scaling config for frontend

ci/terraform/build.tfvars, ci/terraform/integration.tfvars, ci/terraform/staging.tfvars
Rollout auto scaling to int and staging.
Reduce memory in build, int and staging to 1GB as a first step.  
We should be able to reduce both CPU and memory down further later on and scale out instead given the existing headroom.
Reduce memory to 1GB as memory is constant regardless of load and is only running at about 7%.
Scaling up and down has been proven in build using the performance tests.
#591 
#592
=> AUT-213: rollout auto scaling to int and staging

src/locales/cy/translation.json, src/locales/en/translation.json
Update content for session timeout to 2hrs
Session timeout is being increased to 2hrs to cater for long-running identity flows.
https://github.com/alphagov/di-authentication-api/pull/1919
https://github.com/alphagov/di-authentication-account-management/pull/475
=> AUT-401: update content for session timeout to 2hrs

ci/terraform/build.tfvars, ci/terraform/integration.tfvars, ci/terraform/staging.tfvars
Scale down Fargate in Pre Prod environments.
CPU currently maxes at 7% and Memory is always static at 7% in build so there is lot's of headroom, more so in int and staging.
Let the environments scale out if needed as an optimisation.
Container size to be moved to prod after some time, aligning other environments first.
#592 
#593 
#594
=> BAU: Scale down Fargate in Pre Prod environments

src/app.constants.ts, src/assets/scss/application.scss, src/components/common/layout/base.njk, src/components/prove-identity-callback/index.njk, src/components/prove-identity-callback/prove-identity-callback-controller.ts, src/components/prove-identity-callback/prove-identity-callback-routes.ts, src/components/prove-identity-callback/prove-identity-callback-service.ts, src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts, src/components/prove-identity-callback/types.ts, src/components/prove-identity-welcome/prove-identity-welcome-controller.ts, src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts, src/locales/en/translation.json, src/middleware/process-identity-rate-limit-middleware.ts, src/types.ts, src/utils/date.ts, src/utils/error.ts, test/unit/middleware/process-identity-rate-limit-middleware.test.ts
Add spinner to IPV journey
Due to the nature of SPOT and performance issues a spinner has been added to IPV journey to allow the response from SPOT to be processed before begin redirected back to the RP.
=> Add spinner to IPV journey

src/components/landing/landing-controller.ts, src/components/landing/types.ts, src/components/prove-identity-callback/prove-identity-callback-controller.ts, src/components/prove-identity-callback/tests/prove-identity-callback-controller.test.ts, src/components/prove-identity-welcome/prove-identity-welcome-controller.ts, src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts, src/middleware/process-identity-rate-limit-middleware.ts, src/types.ts, src/utils/error.ts
Add state param to RP error redirects
As state is mandatory it needs to be returned on errors that redirect back to the RP.
=> Add state param to RP error redirects

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_no-uk-mobile-questions.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/contact-us/types.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Add a new question `How was the security code sent?` which can either be answered Email or Text Message. 
This will change the following forms -
**Account creation routes only**
1. You did not receive a security code 
2. The security code did not work 
- Change the hint text 
- Make the `Anything else you want to us` question mandatory. If the question has been left blank then an error message 'Enter more detail' will be displayed.
This will change the following forms -
**Account creation and Sign in routes**
1. You did not receive a security code
2. The security code did not work 
**Account creation routes only**
4. You do not have a UK mobile phone number
- We are trying to get more information from users to identify the cause of their issues.
=> AUT-259 - Update the Zendesk form

src/app.constants.ts, src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/prove-identity-welcome-routes.ts, src/components/prove-identity-welcome/prove-identity-welcome-validation.ts
Update prove your identity welcome page for an existing session so the continue button works.
The continue button failed because there was a separate post route which is not in the state machine which wouldn't allow a user to continue. The page has been changed to point to the same post route as an non logged in user.
=> Update ipv welcome page to use same route for all users

src/components/common/footer/terms-conditions.njk
Update contact-us link on terms and conditions page.
The link currently goes to the 'Support' page when it should go to 'Contact Us' instead.
=> AUT-301: Update contact-us link on terms and conditions page

deploy-sandpit.sh
- Remove hardcoded image name
- Don't wait for ECS if infra has been destroyed
If image name changes, we only need to change the variable value now.
When destroying Terraform infrastructure there is no need to have the "wait for ECS" step as the ECS tasks will no longer exist.
=> AUT-434: Sandpit deploy tweaks

src/components/create-password/create-password-validation.ts, src/components/create-password/tests/create-password-integration.test.ts, src/components/reset-password/reset-password-validation.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/utils/strings.ts, test/unit/utils/strings.test.ts
- Show the error message `Your password must be at least 8 characters long and must include letters and numbers` in the following scenarios for when a user creates or resets their password.
1. only contains numbers
2. only contains letters
3. is fewer than 8 characters long
4. has a combination of 2 or more of those things
- Update hint text for both create and reset password screens
- This change is required to help the user to understand how to enter valid passwords.
=> AUT-302 - Create generic error message for some invalid password scenarios

src/app.constants.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/index-public-contact-us.njk, src/components/contact-us/questions/_proving-identity-problem-questions.njk, src/components/contact-us/questions/index.njk, src/components/contact-us/tests/contact-us-controller.test.ts, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Add new radio button on the first page of the support form names 'A problem proving your identity'
- Create a new page which the user is redirected too when they select that radio button.
- This page will contain 2 new mandatory text boxes, along with the generic `Can we reply to you by email?` question
- Update opening text on support form
- Update submit success text
- So users have a clear path if they experience any issues when trying to prove their identity
- Compare with content doc - https://docs.google.com/document/d/1DWfN09H17vyk-7H7tzKmDQ7NhSQxtpBtZDqdy8Vy5Tg/edit?pli=1#
=> AUT-424 - Update user support form with new page

src/config/helmet.ts
add preload directive to HSTS
So we can add *.account.gov.uk to the preload list
https://github.com/alphagov/di-authentication-api/pull/2049
=> DCP-147 add preload directive to HSTS

.github/workflows/analyse-on-merge.yml
Add SUPPORT_MFA_OPTIONS switch to analyse on merge checks.
Unit tests are failing because they test the scenario in which this is switched on.
#615
=> BAU: Add SUPPORT_MFA_OPTIONS switch to analyse on merge checks

ci/terraform/alb.tf
Ensure TLS >=1.2 and disallow CBC ciphers
Currently we allow TLS 1.0 and 1.1. We should not allow that.
We also allow CBC-mode ciphers.  We should not allow that, preferring
GCM (or ChaCha20, but I don't think ELBs support that).
Amazon load balancer security policies are documented here:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
This configuration is (roughly) equivalent to mozilla's "intermediate"
recommendation here:
https://wiki.mozilla.org/Security/Server_Side_TLS
It should support Firefox 27, Android 4.4.2, Chrome 31, Edge 12, IE 11
(on Win7), Java 8u31, OpenSSL 1.0.1, Opera 20 and Safari 9.
=> DCP-157: Ensure TLS >=1.2 and disallow CBC ciphers

local.Dockerfile, package.json, yarn.lock
Use node-dev instead of nodemon.
There is a vulnerability in a nodemon transitive dependency, though this is dev only and is not deployed in any environment so cannot be exploited.
https://github.com/advisories/GHSA-pfrx-2q88-qq97
=> BAU: Use node-dev instead of nodemon

src/components/common/layout/banner.njk
- Update arial label to be consistent with screen
- The visual label is not the same as the source code which can cause issues with a screen reader. Update the source code so it is consistent and will work with screen readers
=> AUT-460 - Update arial label to be consistent with screen

src/locales/cy/translation.json, src/locales/en/translation.json
- Update feedback link
- Make it clear that this link opens in a new tab as users of screen reading assistive technologies need to be provided with this information prior to activating the link.
=> AUT-462 - Update feedback link

src/app.constants.ts, src/app.ts, src/components/common/constants.ts, src/components/common/state-machine/state-machine.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-routes.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-service.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-validation.ts, src/components/enter-authenticator-app-code/index.njk, src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts, src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts, src/components/enter-authenticator-app-code/types.ts, src/components/enter-password/enter-password-controller.ts, src/components/enter-password/types.ts, src/components/security-code-error/index.njk, src/components/security-code-error/security-code-error-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json, yarn.lock
Add 'Enter the security code shown in your authenticator app' screen for sign in journey.
The option will only be displayed if SUPPORT_MFA_OPTIONS is turned on, and if the user has auth app credentials in the database, otherwise it will default to SMS.
Allows the user to sign in with an authenticator app if they have set one up, rather than using SMS as a second factor.
=> AUT 440: Add 'Enter the security code shown in your authenticator app' screen for sign in journey

src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/utils/mfa.ts
Environment specific text for authenticator app
For production just display 'GOV.UK SignIn', for all test environments add an environment name too.
Allows people who test in multiple environments to have several entries in the same app.
=> AUT-418: Environment specific text for authenticator app

src/components/common/state-machine/state-machine.ts, src/components/enter-password/enter-password-controller.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-password/types.ts, src/components/reset-password/reset-password-controller.ts, src/components/reset-password/tests/reset-password-controller.test.ts
Remove isPhoneNumberVerified flag everywhere
This value is super seeded by isMfaMethodVerified and allows the code base to simplified to support auth apps as a feature toggle easier.
=> Remove isPhoneNumberVerified flag

src/components/common/footer/privacy-statement.njk, src/locales/cy/translation.json, src/locales/en/translation.json
I've updated the content on a couple of pages ahead of our private beta launch next week. **Please do not push these changes until Thursday 30 June.** I can let you know when they're good to go. 
**Accessibility statement for GOV.UK accounts** 
I've changed the dates when:
- the accessibility statement was last reviewed
- GOV.UK accounts were last tested
- the last accessibility audit report was produced
**GOV.UK accounts privacy notice**
I've made several changes to this to reflect the users will now be able to prove their identity with their GOV.UK account. 
If it's useful, the changes are all highlighted in green in [this draft version of the privacy notice](https://docs.google.com/document/d/1s1xj1imh53rnYHjUyT47y5V6RPxIXw8z57f7mKNGs_o/edit#).
=> Privacy and Accessibility statements: updating content in time for 30 June

ci/tasks/deploy-frontend.yml, ci/terraform/ecs.tf, ci/terraform/variables.tf
- Inject a list of IP addresses into the basic auth side car that are allowed to bypass basic auth.
We need to disable to basic auth for the automated end to end tests to run, however, we need to keep it on for external IP addresses. The allow list will be injected at deploy time by Concourse.
https://github.com/alphagov/di-infrastructure/pull/302
https://github.com/alphagov/di-infrastructure/pull/303
=> AUT-495: Inject basic auth bypass IP addresses

ci/terraform/core.tf, ci/terraform/ecs.tf
- Set the `TRUSTED_PROXIES` environment variable on the sidecar to be the list of CIDR blocks for the public subnet (where the ALB lives).
The ability to bypass basic auth, based on IP address (i.e. GDS addresses only), is not working due to the NGinx reporting the ALB IP as the client IP. We're now using the RealIP module in NGinx to determine the actual client address and we need to tell it which IPs are our known proxies.
https://github.com/alphagov/di-infrastructure/pull/305
=> AUT-495: Inject trusted proxies into basic auth side car

ci/terraform/site.tf
- Update tag application name for frontend
- It was tagged as account-management previously. This should be the authentication frontend.
=> BAU - Update tag application name for frontend

src/components/common/layout/base.njk, src/locales/en/translation.json
Do not open all footer links in a new tab.
Will now open in the same tab:
- Accessibility statement
- Cookies
- Terms and conditions
- Privacy notice
Will keep opening in a new tab
- Support
If a link opens in a new tab users of screen reading assistive technologies need to be provided with this information prior to activating the link.  Either we update the link text to say that a new tab will open, or stop opening links in a new tab.
Four links will now open in the same tab as they lead to simple, more or less static pages, so using the back button will not cause any issues.  The 'Support' link leads to a more complex page with more steps so it's best to keep this opening in a new tab, in this case the link text has been updated.
=> AUT-473: Do not open all footer links in a new tab

src/components/common/state-machine/state-machine.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/reset-password/reset-password-controller.ts, src/components/reset-password/tests/reset-password-controller.test.ts, src/components/select-mfa-options/index.njk, src/components/select-mfa-options/select-mfa-options-controller.ts, src/locales/en/translation.json
When a user drops off in the sign up process there needs to be a change to support multiple 2fa options when the user comes back. The following has been added.
- A temp change to the state machine to enable the testing of this in parallel of what is currently live
- Get security codes screen update content to support drop out user
- Added functionality to reset password to support the new mfa methods as-well as drop offs.
=> Support 2fa drop out with new screen

ci/tasks/deploy-frontend.yml
- Pass in SUPPORT_MFA_OPTIONS in the deploy-frontend task
- By default set this to false
=> BAU - Pass in SUPPORT_MFA_OPTIONS in the deploy-frontend task

src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/locales/en/translation.json
- Change content on the 'Prove your identity with a GOV.UK account page
- To make it clearer to the user that they require a UK passport to prove their identity with us.
=> AUT-544 - Change content on the 'Prove your identity with a GOV.UK account page

src/app.constants.ts, src/app.ts, src/assets/javascript/application.js, src/assets/javascript/cookies.js, src/components/common/cookie-consent/cookie-consent-service.ts, src/components/common/cookies/cookies-controller.ts, src/components/common/cookies/cookies-routes.ts, src/components/common/cookies/index.njk, src/components/common/layout/base.njk, src/locales/en/translation.json, src/types.ts
Restore Sign In cookies policy and update content.
- Stop linking to the GOV.UK Cookies Policy, link instead to the custom Sign In policy which will apply across DI.
- Restore the cookies policy page and the ability to save analytics cookie preferences within the page.
- Update the page content to cover all cookies.
The GOV.UK Cookies Policy did not support transferring analytics behaviour from the GOV.UK Account to Sign In.
=> AUT-497: Restore Sign In cookies policy and update content

src/components/common/layout/banner.njk
Update link in cookie banner.
To point to the new sign in cookie policy page.
#670
=> AUT-497: Update link in cookie banner

.gitignore, local.Dockerfile, package.json, yarn.lock
Revert node-dev for nodemon.
git ignore .env files
Nodemon had a vulnerability in 2.0.15 but this has now been fixed.
Switching back from node-dev.
#636
=> BAU: Revert node-dev for nodemon

package.json, src/components/common/cookies/tests/cookies-controller.test.ts
Add unit tests for di cookies policy page.
Catching up with the unit tests as the page was needed asap.
#671 
#670
=> AUT-497: Add unit tests for di cookies policy page

docker-compose.yml
Add missing switches to docker-compose.
- SUPPORT_INTERNATIONAL_NUMBERS
- SUPPORT_MFA_OPTIONS
Able to test locally with the switches on and off.
=> BAU: Add missing switches to docker-compose

src/components/common/cookies/cookies-controller.ts, src/components/common/cookies/index.njk, src/components/common/cookies/tests/cookies-controller.test.ts
Remove cookies update referer from session.  Add as a hidden form parameter instead to remove reliance on the session.
Stops users without a session from seeing an error.
The cookies policy page shows a banner when the cookies preferences are updated with a link to go back to the page the user was looking at.  Given that the user can submit their preferences multiple times this could not be based on the original 'referer' as the referer could then be the cookies page, so this information was stored in the session.
A few users appear to be landing directly on the accessiblity statement or privacy statement, meaning they don't have a session.  If they clicked on the cookies page they then saw an error.  These users may be bots, but it's possible they are arriving directly from a search …
=> AUT-497: Remove cookies update referer from session

src/components/setup-authenticator-app/index.njk, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/components/setup-authenticator-app/setup-authenticator-app-validation.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts, src/middleware/form-validation-middleware.ts, src/types.ts, src/utils/validation.ts
Redisplay auth app QR code and secret after validation error.
Add an additional optional parameter to 'validateBodyMiddleware' and 'renderBadRequest' to allow for locals to be passed back to the page after a validation error.
When the user entered an invalid or incorrect code the page was being redisplayed without the QR code and secret.
=> AUT-534: Redisplay auth app qr code and secret after validation error

src/components/common/state-machine/state-machine.ts, src/locales/en/translation.json
Make "Get a security code by text message instead" link redirect to /enter-phone-number.
Update the state machine to allow the redirect.
Update product name text used to show codes in authenticator apps
The link was not redirecting correctly.
=> AUT-538: Make "Get a security code by text message instead" link redirect to /enter-phone-number

.github/workflows/analyse-on-merge.yml, .github/workflows/pre-merge-checks.yml
Remove github actions coverage task
The unit test and integration test tasks already produce coverage reports so this is duplication.
As these tasks also clear coverage before running the output only represents integration test coverage and not combined coverage.
=> BAU: remove github actions coverage task

src/components/common/cookies/cookies-controller.ts
Sanitize cookie referrer.
Add extra sanitization to the referrer to the cookie page.
Additional security just in case Nunjucks fails to do the sanitization.
=> BAU: Sanitize cookie referrer

src/app.constants.ts, src/app.ts, src/components/common/errors/error-controller.ts, src/components/common/errors/error-routes.ts, src/components/common/errors/tests/error-controller.test.ts
Add an external route to the http 500 error page (for the doc-app-callback api).
So that the doc-app-callback lambda can redirect to this error page in the event of an internal server error.
At the moment the 500 error page is only displayed in response to an internal error, such as when an error is returned by api call, and there is no way to route to this page externally.
The doc-app-callback lambda returns a 500 directly in case of error, which is displayed in the browser in a rather unfriendly way.  When this route is deployed the api will be able to route to the more user friendly error page when something goes wrong, where links to contact support etc are available.
=> AUT-582: Add an external route to the http 500 error page (for the doc-app-callback api)

src/assets/javascript/cookies.js, src/components/common/cookies/index.njk
Use cookie to track history when setting analytics cookies.
Uses a new cookie 'chl' to store the referring place in the browser history when landing on the cookies page.  This can then be used to calculate how far to go back in history to get to the referring page when the user clicks on the 'Go back to the page you were looking at' link after changing analytics cookie preferences.
Removes reliance on the 'referrer' header which is not guaranteed to be correct across domains with a referrer policy.
Javascript is guaranteed to be available in this scenario as the user cannot switch on analytics cookies with javascript being on.
#670
=> AUT-576: Use cookie to track history when setting analytics cookies

src/components/check-your-phone/index.njk, src/components/common/mfa/mfa-service.ts, src/components/common/mfa/send-mfa-controller.ts, src/components/common/mfa/types.ts, src/components/common/state-machine/state-machine.ts, src/components/enter-mfa/index.njk, src/components/enter-password/enter-password-controller.ts, src/components/resend-mfa-code/index.njk, src/components/resend-mfa-code/resend-mfa-code-controller.ts, src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts, src/components/reset-password/reset-password-controller.ts, src/components/security-code-error/index-too-many-requests.njk, src/components/security-code-error/index-wait.njk, src/components/security-code-error/security-code-error-controller.ts, src/locales/en/translation.json
NOTE: Booked in separately with Kim Clayden for content aspect run through and sign-off (before which this PR will not be merged regardless of tech review progress).
NOTE: Also covers AUT-391 (remind user why they cannot get a new code within 15 minute lockout window) as this is so closely related to AUT-393 that it does not make sense to release either first without the other: https://govukverify.atlassian.net/jira/software/c/projects/AUT/boards/193?modal=detail&selectedIssue=AUT-391
- Add resend phone OTP code screen to account creation journey
- Amend some content of resend phone OTP code screen in sign in journey to match current Figma
- Differentiate between calls to MFA Lambda when they are `isResendCodeRequest` (resending a code in the account creation journey) vs when it's …
=> AUT-393: Add resend phone OTP code screen to account creation journey

src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/index.njk, src/components/common/state-machine/state-machine.ts, src/components/setup-authenticator-app/index.njk, src/locales/en/translation.json
- For both phone and auth app journey branches, ensure there is a link back to the MFA method selection page (`/get-security-codes`)
- For auth app, amend content to match Figma - particularly 'access code' => 'security code'
- For SMS MFA, make additional text to go back to the MFA method selection page conditional on supporting MFA env var - as this page will only become live when auth apps are live
- To allow user to change their mind about which MFA option to select (SMS or Auth App at the moment) up to the point that they have validated their choice by inputting a correct code.
=> AUT-535: Make MFA choice reversible until method validated

src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/index.njk, src/components/common/state-machine/state-machine.ts, src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/enter-phone-number/index.njk, src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts, src/components/setup-authenticator-app/index.njk
- Enable back button on auth app setup screen
- Enable back button on input phone number screen (ahead of SMS MFA setup)
- Make both 'point at' MFA method choice page
- Make phone back button conditional on MFA options being supported
- To give a further mechanism for users to navigate account creation journey
- Extension of https://github.com/alphagov/di-authentication-frontend/pull/690 - which allowed much the same, except via text hyperlinks within the main content
=> AUT-535: Add back buttons to auth app and sms code setup screens

src/components/create-password/index.njk, src/locales/en/translation.json
- Make it clear which links opens in a new tab by adding '(opens in a new tab)' to the link
- Update the text to remove any potential contradiction between this screen and our privacy policy.
- Improve accessibility for screen readers 
-  To remove any potential contradiction between this screen and our privacy policy.
=> AUT-571 - Update terms of use content on create password screen

src/components/enter-phone-number/index.njk, src/locales/en/translation.json
- Make changes to drop off screen when auth apps are enabled
- Add missing line `You must use a UK mobile phone number` to the enter phone number screen and ensure it is not displayed if international phone numbers are enabled 
- The current drop of screen when auth apps are enabled correctly reads 'Finish creating your account' when asking for a phone number. However when auth apps are enabled, the previous screen already reads 'Finish creating your account'. 2 consecutive screens should not have the same H1 so it needs to be changed to improve usability and accessibility.
=> AUT-610 - Make changes to drop off screen when auth apps are enabled

src/app.constants.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/further-information/_account-creation-further-information.njk, src/components/contact-us/questions/_authenticator-app-problem.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/index.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/contact-us/tests/contact-us-further-information-controller.test.ts, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/locales/en/translation.json
- Change the text on the radio button for "did not receive code" on the feedback form for account creation journey.
- Add a new radio button to the list of code receive methods on no security code and invalid code pages
- Add new subtheme for "problem with authenticator app"
- Hide authenticator app specific changes behind feature flag
- Remove unused entries from `translations.json`
We are going introduce authenticator apps and the feedback form needs to provide a way of reporting issues with this journey.
=> AUT-598: Authenticator app feedback form

src/assets/javascript/cookies.js
- Add datalayers for auth apps
- These are used for google anayltics for user tracking
=> AUT-606 - Add datalayers for auth apps

src/components/common/show-password/macro.njk, src/components/enter-authenticator-app-code/index.njk, src/components/enter-email/index-create-account.njk, src/components/enter-email/index-existing-account.njk, src/components/enter-password/index.njk, src/locales/en/translation.json
- Resolve accessibility and usability issues in journey
- Note the security code text is slightly different from the ticket. This is intentional following the text that already existed. 
- Use the H1 heading as the label for the input field as per the GOV.UK design system method for question pages. This will present users of screen reading assistive technologies with less content to navigate through and have audibly feedback before reaching the input field.
**AUT-550** 
**AUT-464**
=> AUT-550 & AUT-464 - Resolve accessibility issues

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/further-information/_signing-in-further-information.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-phone-number-access-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_security_send_method.njk, src/components/contact-us/types.ts, src/locales/en/translation.json
- Change "did not receive" to "did not get" a security code
- Change "do not have access to phone number" to "changed phone number
- Add radios for to be displayed if auth apps are enabled
- Amend validation to validatte under correct circumstances
- Show the radio buttons on the noPhoneNumberAcces feedback questions if auth apps are enabled.
- Replace hard-coded question passed to Zendesk with actual question asked to user.
- Re-order radios on problem signing in form
- Change hint on `invalidSecurityCode` form
We are going live with authenticator apps and need the feedback form to reflect this
=> AUT-603: Feedback form amendments for auth apps on sign-in journey

src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/components/setup-authenticator-app/setup-authenticator-app-service.ts, src/components/setup-authenticator-app/types.ts
- Send the clientSessionId in the request to the verify-mfa-code endpoint for account-creation
- So we can attach the clientSessionId in the lambda logs
=> AUT-619 - Send clientSessionId in request for account creation for auth apps 

src/components/contact-us/contact-us-controller.ts
- The `optionalDescription` is now `section2` on the form, update the question map appropriately to map the correct header.
As a result of a recent change we were incorrectly mapping the question text to the Zendesk ticket.
#702
=> BAU: Fix question text passed to Zendesk on noPhoneNumberAccess form

README.md, docker-compose.yml
This change does two things: 
- Add `container_name` to docker compose file
- Update README to reflect this container name
When following the README I found that the [Running the tests](https://github.com/alphagov/di-authentication-frontend/blob/main/README.md#running-the-tests) section did not work. I got some advice on how this might be fixed and have included those changes in this PR.  
Fixes issue with instructions in README not working.
=> Update test running instructions in README

src/locales/en/translation.json
Add also available in Welsh to the 'en' resource file before translation.
Get as much text in as possible before the files are sent.
=> AUT-618: Add also available in Welsh to the 'en' resource file before translation

src/components/prove-identity-welcome/index-existing-session.njk, src/locales/en/translation.json
- Amend text to match Figma
- Change button and hyperlink to radio buttons to improve user experience
- Controller should still work, as POST controller is based on session isAuthenticated status rather than on the value of the radion button
- Exception is when radio button value is 'redirect' but logic again applies to this case
These are all user experience improvements
=> AUT-628: Amend prove identity welcome page content

src/locales/en/translation.json
- Preload text for offering Welsh language via 'prove your identity' screen
- No immediate function - purely to allow this text to be sent to translators
=> AUT-629: Preload translation text

src/components/common/state-machine/state-machine.ts, src/components/reset-password-check-email/index.njk, src/locales/en/translation.json
Removes link, content and state from the details element in this state. 
New request received via comment on Jira Ticket
Changes what was implemented in #715
=> AUT-599: Remove link from reset password change email

src/components/common/state-machine/state-machine.ts, src/components/reset-password-check-email/index.njk, src/locales/en/translation.json
- Route resend code hyperlink to `/reset-password-resend-code` on forgotten password 'check your email' screen
- This was already the case before #715
- However, it was erroneously changed to point at `/resend-code`
- For this reason no new screens needed
- State machine also removes option to go back to the enter code screen once a correct OTP has been entered, as otherwise the resend code hyperlink routes straight to the reset password screen (bottom screenshot below) as it does not need to resend a code when a correct one has already been input. This creates a strange user experience.
Starting screen (unchanged apart from hyperlink destination):
Resend code screen:
If resend code clicked too many times:
If reset password hyperlink clicked whilst still within 15 minute window:
Reset …
=> AUT-599: Amend resend code href in forgotten password screen

src/components/reset-password-check-email/index-reset-password-resend-code.njk
Updates content for the forgotten password resend code page (See "Accessing the page" below) to reflect what is in the image (also below)
I've also created a [new Jira ticket](https://govukverify.atlassian.net/browse/AUT-668) to capture the need for the page to have its own entries within `translation.json` (See "Borrowing translations" below)
This page is accessed by: visiting `/sign-in-or-create` and clicking "Sign in"; then entering an existing email address and clicking "Continue"; then clicking "I've forgotten my password"; then expanding "Problems with the code" and clicking "Send the code again"
This PR is being raised during a freeze to the content of `translation.json` (while the team awaits the translators to provide a Welsh version). For this reason the template has borrowed …
=> AUT-599: Update content for get security code resend code

src/locales/cy/translation.json, src/locales/en/translation.json
Add link hrefs allowing users to switch between English and Welsh, and from Welsh to English, on the Sign In or Create page.
This is only visible when Welsh is switched-on, otherwise the inset containing the explanation and link will not be visible.
As this needs a different link for each language I have also broken the symlink between the cy -> en files and have added a separate cy file again (which contains a different link).  This also means that language switching can now be tested.
Setting an lng query param automatically updates the cookie with the same value.
Users need a way to switch between languages, currently this is done using these links on the Sign In or Create page.
#711 
#714
=> AUT-618:  Add link href to switch between en and cy, and vice-versa

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/types.ts
Add Ticket Identifier to support form.
A unique id is generated whenever a user submits a support ticket.  This id is then logged alongside the session id.
Replaces Session Id in the form.
Enables support teams to trace errors in the logs corresponding to the ticket.
=> AUT-670: Add Ticket Identifier to support form

src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/components/prove-identity-welcome/prove-identity-welcome-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Add Welsh language toggle to prove identity welcome screen
- This works by redirecting to the same page with `lng=cy` as a query param (note: it does get rid of any existing params e.g. google analytics).
- I18Next does the work of changing cookie off the back of this (cookie also called `lng`)
- Add same change in the opposite direction (`lng=en`) to switch back
When `supportLanguageCY` environment variable is turned off/absent:
When  `supportLanguageCY` environment variable is turned on:
To provide a mechanism for users to switch languages between English and Welsh.
Some text was preloaded in translation.json so that the file could be shared earlier with translators: https://github.com/alphagov/di-authentication-frontend/pull/716
=> AUT-629: Add Welsh language toggle to prove identity welcome screen

src/utils/phone-number.ts
- Add all numbers, and the +44 variants, to the allow list
For smoke and acceptance purposes we need to ensure all Notify numbers are accepted.
=> BAU: Add all known Notify numbers to allow list

src/config/i18next.ts
Use the language switch in i18n config.
Means that switched-off languages are not loaded by i18n, makes it impossible to switch to the language.
=> AUT-200: Use the language switch in i18n config

src/components/check-your-email/index.njk, src/components/check-your-phone/index.njk, src/components/enter-authenticator-app-code/index.njk, src/components/enter-mfa/index.njk, src/components/reset-password-check-email/index.njk, src/components/setup-authenticator-app/index.njk
Removes `pattern: "[0-9]*"` from all number inputs. 
This update reflects a recent change to GOV.UK Design System recommendations for using pattern attributes on number inputs. The Design System update is described at: https://github.com/alphagov/govuk-design-system/pull/2323
Similar PR raised in `di-authentication-account-management` here: https://github.com/alphagov/di-authentication-account-management/pull/582
=> AUT-669: Remove pattern attribute from numeric inputs

src/components/auth-code/auth-code-routes.ts
- Use existing asyncHandler wrapper to wrap the GET function for `/auth-code` route
- This allows `next()` to be called in case of a failure e.g. API returns error code
- It is functionally equivalent to try/catch in the GET function, where `catch(error){...}` calls `next(error)`
- Previously an API side error such as 502 would result in the browser displaying page not found (nothing visual) - something like this:
- Now, due to the `/auth-code` handler being hooked up to global error handling, an API failure redirects to this screen:
=> AUT-512: Wrap authCodeGet controller/handler in async handler wrapper

ci/terraform/build.tfvars, ci/terraform/staging.tfvars
Switch on Welsh in build (and staging).
Make Welsh available so that accpetance tests can be built against it.
Flag had been omitted for staging.
=> BAU: Switch on Welsh in build (and staging)

src/components/check-your-email/index.njk, src/components/check-your-phone/index.njk, src/components/reset-password-check-email/index.njk
We need to ensure that an incorrect OTP entered during Create account OR Sign in for both email address and phone number clears when the screen ‘refreshes’ with errors following the POST request
So as to reduce the likelihood of a user trying to continue the journey using the same incorrect code
[AUT-678](https://github.com/alphagov/di-authentication-account-management/pull/589)
=> AUT-682: Clear Incorrect OTP

src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-controller.test.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts
Send account created mail when account created with auth app.
The api call to send an email was missing from when an account is created with an auth app, so the email was not being sent.
=> AUT-706: Send account created mail when account created with auth app

src/components/check-your-email/index.njk, src/components/common/layout/base.njk, src/components/create-password/index.njk, src/components/enter-email/index-create-account.njk, src/components/enter-email/index-existing-account.njk, src/components/reset-password-check-email/index.njk, src/components/reset-password/index.njk
Replaces hardcoded "Continue" and "Back" within templates with translations. See Jira ticket for detail of changes made and screenshots. 
Render of page in Welsh was showing English text.
=> AUT-690: Fix localisation for continue and back

src/components/account-not-found/account-not-found-controller.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/common/send-notification/send-notification-service.ts, src/components/common/send-notification/types.ts, src/components/enter-email/enter-email-controller.ts, src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/resend-email-code/resend-email-code-controller.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/utils/http.ts
Pass user language as header to sendNotification to enable sending Notify messages in both English and Welsh
Makes use of existing dormant changes to the oidc api.
Updates for the remaining frontend services that trigger notifications will follow.
Enable the backend to choose Notify template by language.
https://github.com/alphagov/di-authentication-api/pull/2304
https://github.com/alphagov/di-authentication-api/pull/2318
=> AUT-639: Pass user language as header to sendNotification

src/components/common/mfa/mfa-service.ts, src/components/common/mfa/send-mfa-controller.ts, src/components/common/mfa/types.ts, src/components/enter-password/enter-password-controller.ts, src/components/reset-password/reset-password-controller.ts
Send User-Language to 'mfa' service.
Completes the changes required to Fronted to send language specific Notify templates according to the user's language.
#749
=> AUT-639: Send User-Language to 'mfa' service.

src/locales/cy/translation.json
Adds "English" to language switch when page is in Welsh (mirroring the inclusion of "Welsh" in the link when the page is in English). 
Noticed this while working on other translations and sought advice from Content Design who asked if I could change it.
=> BAU: Add "English" to language switch

src/locales/cy/translation.json
Replaces "Text message" string in Welsh translation file with "Neges destun" (a translation for text message which appears in several other places within this file). 
Provides users who have selected Welsh language with the Welsh translation.
=> BAU: Replace "Text message" in Welsh translation with Welsh

src/components/sign-in-or-create/index.njk, src/components/sign-in-or-create/sign-in-or-create-controller.ts
- Change sign-in HTML element from `button` to `a` on landing page meaning text stays in line with sentence rather than being centred when 640px screen size breakpoint is reached. Also means that the 'focus' highlight highlights only text and not a button (see screenshot):
After ('sign-in' link in focus):
- Change controller to allow it to apply the same logic as when the request was a POST
- This text was previously a button (albeit styled as a link) to allow request to be POST request
- However, this 'broke' certain styling, such as making the text be centred on the screen at screen width under 640px
- Changing to a 'normal' link means that the request is now GET
- As a result, I added a query parameter, which allows the GET controller to apply the POST logic in this circumstance
- …
=> AUT-684: Change sign-in button to link on landing page

src/components/sign-in-or-create/index.njk
- Add ID to anchor tag for sign-in link
- Matches ID previously given to the button this replaces, so that Acceptance Tests can recognise it
Amends: https://github.com/alphagov/di-authentication-frontend/pull/753
=> AUT-684: Add ID to anchor tag for sign-in link

src/components/check-your-email/index.njk
- Decrease width of email OTP code input field
- Use govuk-input--width-10 class, just like elsewhere
- Width was inconsistent stylistically with rest of user experience
=> AUT-696: Decrease width of email OTP code input field

src/components/common/state-machine/state-machine.ts
- Fix password reset flow for auth app users
- State machine previously always redirected to enter phone code, making password reset impossible for auth app users
- Now additional condition is checked, which redirects to enter auth app code if auth app is enabled
Additional note: As currently written in state machine, the condition (`requiresMFAAuthAppCode`) that is being checked to decide to route to auth app flow is:
```
requiresMFAAuthAppCode: (context) =>
context.mfaMethodType === MFA_METHOD_TYPE.AUTH_APP &&
context.isMfaMethodVerified === true,
```
Both of these fields are being returned via the `loginResponse` in the `reset-password-controller` file.
- Status quo results in auth app users being unable to recover from a forgotten password
=> AUT-730: Fix password reset flow for auth app users

ci/terraform/ecs.tf, ci/terraform/sandpit.tfvars, src/config.ts, src/config/i18next.ts
Configure cookie domain for lng cookie.
As the lng cookie is currently set to the default domain for each app it is not visible across different apps, such as Frontend and Account Management.  This means that when the user chooses a language in Frontend it is not reflected in Account Management as AM sets its own cookie.
Instead, set it to the service domain so that the cookie can be seen across the service.
=> AUT-691: Configure cookie domain for lng cookie

src/components/enter-email/enter-email-controller.ts, src/components/enter-email/enter-email-service.ts, src/components/enter-email/types.ts, src/components/reset-password-check-email/reset-password-check-email-controller.ts, src/components/reset-password-check-email/reset-password-check-email-service.ts, src/components/reset-password-check-email/types.ts, src/components/reset-password/reset-password-controller.ts, src/components/reset-password/reset-password-service.ts, src/components/reset-password/types.ts
- Add header to `userExists` backend call
- Add header to `resetPasswordRequest` backend call
- Add header to `resetPassword` backend call
We need this header to identify the user journey so we can pass through to the audit service.
=> AUT-708: Pass `clientSessionId` header to backend where missing

src/locales/cy/translation.json
Changes value for link destination in Welsh translation file to match value in English translation
Fixes bug identified this afternoon where Welsh users clicking request new security code were not progressing to the page. This made it seem that the page didn't exist.
=> FIX: Make link destinations for resend email codes consistent

src/locales/cy/translation.json
Fix Welsh resource typo on enter authenticator app code.
The validation message for invalid code was being displayed in English rather than Welsh.
=> BAU: Fix Welsh resource typo on enter authenticator app code

src/components/common/cookies/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Update notification banner to use a translation value and introduces the relevant value.
To ensure the "Success" message is translated for users viewing the page in Welsh
=> AUT-739/fix success title in success panel

src/components/contact-us/questions/_account-creation-problem-questions.njk, src/components/contact-us/questions/_account-not-found-questions.njk, src/components/contact-us/questions/_another-problem-questions.njk, src/components/contact-us/questions/_authenticator-app-problem.njk, src/components/contact-us/questions/_email-subscriptions-questions.njk, src/components/contact-us/questions/_forgotten-password-questions.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-phone-number-access-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_no-uk-mobile-questions.njk, src/components/contact-us/questions/_proving-identity-problem-questions.njk, src/components/contact-us/questions/_signing-in-problem-questions.njk, src/components/contact-us/questions/_suggestion-feedback-questions.njk, src/components/contact-us/questions/_technical-error-questions.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Moves "Send message" text to translation file and update all references
To ensure the message is translated for users viewing the page in Welsh.
=> AUT-738/move send message to translation file

src/assets/scss/application.scss, src/components/common/show-password/macro.njk, src/components/create-password/index.njk, src/components/enter-password/index-account-exists.njk, src/components/enter-password/index.njk, src/components/reset-password/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
This commit updates the two show password macros and all their implementations to:
1. Remove the unused 'hint' parameter that was causing an unnecessary element to be included in the HTML payload
2. Support translations via a new `showSettings` config object
So that users viewing the page in Welsh have the component translated correctly.
=> AUT-714: Update "show password" component to support translations

src/components/common/cookies/index.njk, src/components/common/footer/support.njk, src/components/contact-us/further-information/_account-creation-further-information.njk, src/components/contact-us/further-information/_signing-in-further-information.njk, src/components/contact-us/questions/_reply_by_email.njk, src/components/contact-us/questions/_security_send_method.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/components/select-mfa-options/index.njk, src/components/select-mfa-options/tests/select-mfa-options-integration.test.ts, src/components/share-info/index.njk, src/components/share-info/tests/share-info-integration.test.ts
- Fix radio button focus behaviour from error summary link
- Before commit, error summary href does not target anything
- After commit, error href targets first radio button of set with error
- Mirrors change in commit 6654c47/PR #756 - but now with broader scope
Note: Some integration tests needed to be tweaked because they were targetting by `id` and this change affects the `id` names
- The failure to focus when clicking the link in error summary is a WCAG 2.1 accessibility failure.
This was originally reported and fixed for a single contact-us page (same fix now, but just in more places): https://github.com/alphagov/di-authentication-frontend/pull/756
=> AUT-731: Fix radio button focus behaviour from error summary link

src/app.ts, src/middleware/cookie-lang-middleware.ts, src/utils/logger.ts
- Add language information to logs
- Middleware sets this as single-request-response-cycle local variable
- Pino logger picks this up and adds it as an extra dimension to logs
- To allow performance analysts to analyse degree to which English vs Welsh languages versions are viewed on a per-page basis
=> AUT-707: Add language information to logs

README.md
- Suggest we add some information about `dev-app.js` to aid new users in configuring their local environment. 
- These kinds of change are required to see some pages at all e.g. the Prove Your Identity Welcome screen.
=> BAU: Update README with information about dev-app.js

src/app.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/index.njk, src/components/common/state-machine/state-machine.ts, src/components/common/state-machine/tests/state-machine.test.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/further-information/_account-creation-further-information.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-phone-number-access-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_security_send_method.njk, src/components/contact-us/tests/contact-us-further-information-controller.test.ts, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/components/create-password/create-password-controller.ts, src/components/enter-password/enter-password-controller.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/enter-phone-number/index.njk, src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts, src/components/reset-password/reset-password-controller.ts, src/components/reset-password/tests/reset-password-controller.test.ts, src/components/sign-in-or-create/index.njk, src/components/sign-in-or-create/sign-in-or-create-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- This required a few minor tweaks to the state-machine.ts to ensure that the users who dropped off would go to the GET_SECURITY_CODES screen instead of the CREATE_ACCOUNT_ENTER_PHONE_NUMBER screen.
- Remove content that is no longer required
- There will be further changes to remove the SUPPORT_MFA_OPTIONS from terraform and other files.
- Auth Apps has now been deployed in every environment so now the feature flag can be removed.
=> AUT-627 - Remove supportMFAOptions flag from frontend code base

src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/components/sign-in-or-create/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Introduces `lang` attributes where the page switches between Welsh and English
This is necessary to meet WCAG 2.1 Success Criterion 3.1.2 Language of Parts (AA)
=> AUT-751: Add additional lang attributes where necessary

src/components/common/layout/base.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Provides translated text and updates OGL link destination to reflect the language preference.
So that these parts of the footer and links to the OGL reflect user language preferences
=> AUT-672: Add translations for OGL and Crown Copyright

ci/terraform/redis.tf
- Change elasticcache maitenance window
- Make the maintenance window earlier so that it still avoids high periods of traffic but so that it is not in the middle of the night should elasticcache maintenance caus e an incident.
=> BAU - Change elasticcache maitenance window

src/app.constants.ts, src/app.ts, src/components/common/state-machine/state-machine.ts, src/components/photo-id/index-no-photo-id.njk, src/components/photo-id/index.njk, src/components/photo-id/photo-id-controller.ts, src/components/photo-id/photo-id-routes.ts, src/components/photo-id/photo-id-validation.ts, src/components/photo-id/tests/photo-id-controller.test.ts, src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/components/prove-identity-welcome/prove-identity-welcome-controller.ts, src/components/prove-identity-welcome/tests/prove-identity-welcome-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
Content changes to the ‘Prove your identity with a [GOV.UK](http://gov.uk/) account page’ to mention app functionality 
Modified proveIdentityWelcomePost and state-machine to redirect to photo-id if the user is not already authenticated
Added routes and controller for the two new pages
- photo-id
- no-photo-id 
[PYIC-1980](https://govukverify.atlassian.net/browse/PYIC-1980)
Now that users will be able to prove their identity using the app, we need to set users' expectations about this early on in the journey to make sure they are prepared.
Both Core & App teams made the collective decision that we do not want users to be creating an account if they do not have a Photo ID, as they will not be able to prove their identity with us and would then be returned to Verify to create another …
=> PYIC-1980 Build content & design changes to pre-auth pages

src/components/security-code-error/security-code-error-controller.ts
Do not ask a new user to re-enter email when they request another code having exceeded the maximum number of retries when entering an email validation code.
To be deployed in conjunction with a server side change that does not block the email when the maximum number of retries has been reached.
**Before**:
1. User enters incorrect six digit email security code 6 times during account creation
2. User sees screen telling them they need to wait 15 mins to get a new code.
4. User clicks 'get a new code'
5. User enters same email address (again)
6. User sees screen telling them they need to wait 15 mins to get a new code.
7.  User waits 15 mins (30s in build).
8. User clicks 'get a new code' (or abandons and starts again)
9. User enters same email address (again)
10. User user selects …
=> ACI-7: Don't ask for email again after max verify code retries

src/components/common/show-password/macro.njk, src/components/enter-password/index-account-exists.njk
This PR:
* Updates the `govukInputWithShowPassword` and `govukInputWithShowPasswordWithLabelAsPageHeading` Nunjucks macros to permit the inclusion of an `autocomplete` attribute
* Passes "current-password" to the call in `index-account-exists.njk`
Note: I have tested that the macro update does not impact calls where no `autocomplete` argument is passed. These simply ignore it.
This addresses a WCAG 2.1 Level AA failure relating to the password field on "You have a GOV.UK account".
=> AUT-780: Add autocomplete attribute for password on account exists

src/locales/cy/translation.json
We need to consider an approach NOT to translate/show the user support form in Welsh when we go live with Welsh content for the rest of the journey.
So as to avoid an issue where the support team are unable to respond to user submissions as a result of submissions received in Welsh rather than English.
=> AUT-765: Replace Welsh content with English in contact-us page 

ci/terraform/production.tfvars
Switch on frontend auto scaling in production.
Scale down but scale out.
CPU is peaking at 7.5%.
Memory is static under 7%.
This leaves ample headroom to scale down even without scaling out. Keep minimum 4 instances so at least one per AZ.  Can look to reduce this to 3.
Auto scaling is already enabled in the test environments, and proven in build by running the performance tests to make it scale.
=> BAU: Switch on frontend auto scaling in production

ci/terraform/production.tfvars
BAU: Set ecs desired count to equal auto scaling min count.
1 of 2, next PR will tell Terraform to ignore external changes, but need to update the value first otherwise it will be ignored.
Terraform has reset the service to the default as it had been changed by Fargate and did not match the Terraform state.
This happend during a deployment at 11.54
```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
aws_ecs_service.frontend_ecs_service has been changed
~ resource "aws_ecs_service" "frontend_ecs_service" {
~ desired_count                      = 2 -> 4
id                                 = "arn:aws:ecs:eu-west-2:172348255554:service/production-app-cluster/production-frontend-ecs-service"
name                               = …
```
=> BAU: Set ecs desired count to equal auto scaling min count

ci/terraform/ecs.tf
Tell Terraform to ignore external changes to ecs desired count.
So that it won't overwrite changes made by the autoscaler.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#ignoring-changes-to-desired-count
PR 2 / 2
#793 
#789
=> BAU: Tell Terraform to ignore external changes to ecs desired count

src/components/check-your-email/index.njk
Adds the "one-time-code" `autocomplete` attribute to the field users enter their OTP.
Fixes a WCAG 2.1 failure of Success Criterion 1.3.5
=> AUT-779: Add autocomplete attribute to OTP input

src/components/create-password/index.njk
Adds "new-password" to the Nunjucks call which results in `autocomplete="new-password"` attribute being included in the HTML for password and password confirmation fields presented during account creation.
Fixes a failure of WCAG Success Criterion 1.3.5 Identify Input Purpose.
=> AUT-782: Add autocomplete attribute to fix WCAG failure

src/components/setup-authenticator-app/index.njk
Update `autocomplete` attribute to indicate input purpose as "one-time-code".
Fixes a failure of Success Criterion 1.3.5 by identifying the input purpose
=> AUT-787: Update autocomplete to fix WCAG issue on auth app setup page

src/components/check-your-phone/index.njk
Changes `autocomplete` attribute from `"off"` to `"one-time-code"`.
Fixes a WCAG 2.1 Level AA failure by identifying the input purpose. It's not clear why we would have set this to be `"off"` as I can't find a reference to this in Jira and have asked on the Slack channel.
=> AUT-788: Set OTP field autocomplete attribute to use "one-time-code"

src/components/enter-email/index-existing-account.njk
This change:
* introduces `autocomplete="email"` to fix a WCAG 1.3.5 failure
* introduces the correct type and spellcheck attributes (as set out in the Design System)
Fixes a WCAG failure and brings the component in line with the GOV.UK Design System.
=> AUT-791: Update email field to use GOV.UK pattern

src/components/enter-password/enter-password-controller.ts
Passes the email from the session through as a `postValidationLocal` so that it is available to the view at the time of render. This is more 'backend' than I'm used to so grateful for any feedback on how I've achieved this. 
Fixes a bug where the address is not shown.
=> ACI-88: Display email following validation error

src/components/enter-authenticator-app-code/index.njk
Adds an autocomplete attribute to the OTP field presented in the Sign In journey. It's not clear why we would have set this to be "off" as I can't find a reference to this in Jira and have asked on the Slack channel.
Fixes a WCAG 2.1 Level AA failure by indicating the input purpose to user agents and assistive technology.
=> AUT-795: Add autocomplete attribute to OTP field

src/components/enter-password/index.njk
Adds `autocomplete="current-password"` to password field in Sign In journey.
Fixes a WCAG 2.1 Level AA failure by identifying the input purpose (Success Criterion 1.3.5)
=> AUT-793: Add autocomplete to current password field

src/components/common/cookies/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Remove the `lang` row from cookie description
This reflects the cookies available for clients
=> AUT-689: Remove lang from cookie description to reflect cookies available

src/components/common/state-machine/state-machine.ts
-  Fix Auth App uplift scenario
- When a user has auth apps as their 2FA method and logs into a low level service and then goes to uplift to a medium low level service the user gets a 500.
- This happens because the frontend attempts to call the MfaHandler which attempts to send the user an sms text. What should actually happen is the user should be displayed with a screen to enter their auth app code. Change the state machine to show the user the correct page in this scenario by adding a new condition.
=> BAU - Fix Auth App uplift scenario

src/components/landing/landing-controller.ts, src/components/landing/tests/landing-controller.test.ts, src/components/landing/types.ts
- Receive MfaMethodType from the /start endpoint
- Add additional tests.
- We were currently using the MfaMethodType in the state machine but this was not being returned from the start handler. Now that it is we need to ensure it is populated in the context.
=> AUT-802 - Receive MfaMethodType from the /start endpoint

README.md, dev-app.js, docker-compose.yml
- Add a second stub for local testing that requests no MFA
- Ensure new nonce and state values each time
Eases local testing allowing you to have different stub launchers with different VTRs without needing to restart
=> BAU: Add a second stub launcher for no MFA

src/locales/cy/translation.json
Update `translation.json` file.
Welsh translation file included untranslated English content.
=> BAU: Add Welsh version of untranslated paragraph

src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts, src/utils/phone-number.ts, test/unit/utils/phone-number.test.ts
- Regex had previously accepted any phone number where first two numbers were 0 or 7.
- This includes many common international phone number formats e.h. 0033 for France.
- We are now relying on functions from our supporting library instead of regex to determine if a phone number is a UK one
- Note that we use country code rather than specifying country as GB, so as not to exclude Isle of Man and similar.
- Whilst support international phone numbers feature flag is toggled to off ("0"), we do not wish to allow users to register with international phone numbers.
=> AUT-824: Fix international phone number validation rule

ci/terraform/cloudwatch.tf
- Cloudwatch metric filter for language logs
- 2 separate filters so that Grafana can graph language change events separately to 'normal' language tracking
- Prerequisite to get Cloudwatch data in a form that will be accessible in Grafana
=> AUT-707: Cloudwatch metric filter for language logs

ci/terraform/cloudwatch.tf
Remove url dimension from all-get-requests-with-language-dimension metric
Grafana + Cloudwatch restrictions mean it's difficult to report or chart when there are so many values in a dimension.  This will simplify the metric so we can show some meaningful numbers.
#822
=> AUT-707: Remove url dimension from all-get-requests-with-language-dimension metric

src/locales/en/translation.json
One value in `en/translation.json` has been updated.
This change removes misleading content for the user.
=> PYIC-2135 Update content on no-photo-id unhappy path

ci/terraform/cloudwatch.tf
Tweak metric filter query tracking language changes.
Current query is picking /contact-us-questions submits where the language change page is the referrer, for example:
contact-us-questions?theme=proving_identity&referer=https%3A%2F%2Fsignin.account.gov.uk%2Fsign-in-or-create%3Flng%3Den
=> AUT-707: Tweak metric filter query tracking language changes

src/components/enter-password/index-account-exists.njk, src/components/enter-password/index.njk
Set autocomplete for current password entry fields from `"current-password"` to `"off"`
Following the passwords meeting on 8/11 we're exploring how different browsers respond to autocomplete attributes to validate that implementations are consistently "opt-in" and the extent to which modern browsers do not support `"off"` as an autocomplete value for login fields. 
Further information is provided in the ticket.
=> Set current password autocomplete to off

src/components/account-not-found/account-not-found-controller.ts, src/components/account-not-found/index-one-login.njk, src/components/account-not-found/tests/account-not-found-controller.test.ts, src/components/landing/landing-controller.ts, src/components/landing/types.ts, src/config.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts
- If the service that sent the auth request is an internal One Login service (such as GOV.UK Accounts or Account Management) do no give the option to create an account.
If a user has come from these accounts and does not have an account, the chances are that they have ended up there in error.
TBC - there will be an accompanying API change that sets the `isOneLoginService` flag in the start response.
=> ACI-11: Display different "Account Not Found" page for internal services

src/locales/cy/translation.json, src/locales/en/translation.json
- Update validity text for email OTP
- Applies only to email not SMS
- Applies only to account creation, not password reset
- Applies only to this repo, not the account management repo
- This scope was agreed as part of backend ticket ACI-76
- The backend has already been changed to issue the same code for up to 2 hours in this scenario.
=> ACI-82: Update validity text for email OTP

src/locales/cy/translation.json, src/locales/en/translation.json
- Add translation.json for new error screen
- Screen will display when a user attempts to view a page that requires a session directly via the URL
- Note: CY text is English placeholder for now. Will replace with translation at earliest opportunity.
- Needed for a new screen (PR for that to follow later)
=> ACI-23: Add translation.json for new error screen

src/locales/cy/translation.json
- Add the Welsh translations for the new account not found page that is displayed for other One Login internal services (e.g. Account Management)
The Welsh translations are required for the page to go live.
#832 
https://github.com/alphagov/di-authentication-api/pull/2509
=> ACI-11: Add Welsh translations for account not found (one login)

src/app.constants.ts
- Make the prompts in our app.constants file lower case
- As per the OIDC spec https://openid.net/specs/openid-connect-core-1_0.html. The prompt param consists of a list of " Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent"
=> AUT-898 - The prompt param should be lower case

package.json, yarn.lock
Upgrade mocha to 10.0.1
Remove dependency on vulnerable minimatch version.
https://security.snyk.io/package/npm/minimatch/3.0.4
=> BAU: Upgrade mocha to 10.0.1

src/components/sign-in-or-create/index.njk
Removes newline between closing`</span>` and the closing `</a>` that follows it
The newline is being interpreted as a space and rendered as a blank space at the end of the link.
=> ACI-133 Remove stray space from link

src/components/common/footer/accessibility-statement.njk, src/locales/en/translation.json
Adds issue arising from use of `meta refresh` to the Accessibility Statement.
As a WCAG non-compliance this should be listed in the Accessibility Statement under the Public Sector Bodies Accessibility Regulations.
=> ACI-120: Update accessibility statement

ci/tasks/deploy-frontend.yml
Set a default value for the SUPPORT_PASSWORD_RESET_REQUIRED variable in the pipeline.
Deploy frontend build is failing as this is unset.
#848
=> ACI-19: Set a default value for the SUPPORT_PASSWORD_RESET_REQUIRED variable in the pipeline

src/components/common/show-password/macro.njk, src/components/create-password/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Updates content to extract messaging that was previously within bullet points to new hint text for one of the password fields.
The change in content and presentation is intended to help users avoid issues. The impact of this change will be monitored to determine next steps.
=> ACI-124: Change content on create password screen

src/components/setup-authenticator-app/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Content and design change to the ‘Set up an authenticator app’ page advising users they can enter the secret key manually in to their authenticator app rather than scan the QR code.
Change is to help users avoid issues relating to the interplay of the secret key and QR code.
=> ACI-121: Add cannot scan QR code to auth app page

src/components/account-created/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
- Introduce a dynamic element on the ‘you’ve created your account’ screen, to show the user the name of the service the user came from.
- To assist the user to understand what has happened, what will happen next and what they need to do.
=> AUT-12: Add service name to account created page

src/components/photo-id/index.njk, src/components/photo-id/photo-id-validation.ts, src/locales/cy/translation.json, src/locales/en/translation.json
This PR changes the content on the `photo-id` page to inform users chipped passports can be used to prove their identity.
The app journey supports this form of identity proofing.
* [PYIC-2203](https://govukverify.atlassian.net/browse/PYIC-2203)
=> PYIC-2203 Update wording on photo-id page

src/assets/javascript/cookies.js
Change to structure of page language data pushed to Google Analytics and bring the push earlier in the lifecycle. 
The analytics core team have requested a change to the timing and structure of data pushed to Google Analytics via `dataLayer`.
The first implementation based on initial requirements was merged via #839
=> AUT 881: Update dataLayer push to reflect new requirements

src/components/account-not-found/index-mandatory.njk
- Show the 'Create a GOV.UK account' button
- When a user comes from a service, clicks sign in but doesn't have an account they are given the option to create an account. This button needs to display 'Create a GOV.UK account' instead of 'Sign in to a service'
=> BAU - Show the 'Create a GOV.UK account' button

src/components/security-code-error/index-security-code-entered-exceeded.njk, src/locales/en/translation.json
- Clarify that the issue is the *wrong* code being submitted
- Remove the word 'then' from one of the sentences (this was in fact a bug where the view was referencing the wrong part of the translation JSON)
Before:
After:
- At request of content designer - locally-run screenshot has been checked and approved by her
=> AUT-929: Fix wording on 'wrong security code entered too many times'

src/components/account-created/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Revert changes to display service name 
Service name returned does not appear user-friendly. i.e. for account management, it returns:
[ACI-12](https://github.com/alphagov/di-authentication-frontend/pull/846)
=> aci-12: Revert changes to display service name on account created page

src/locales/en/translation.json
Fix quotes for account created page.
Stop acc tests from failing
#875
=> BAU: Fix quotes for account created page

src/locales/cy/translation.json
- Add Welsh translation of content change
- Change applies to 'you have entered wrong code too many times'
- Now says 'wrong code' rather than simply 'code'
Before:
After:
- At request of content designer
- English language change was merged under this PR: https://github.com/alphagov/di-authentication-frontend/pull/874/files#diff-f42562c98e440b987ac05f6dd6a75797b81b5d6a090db09faaee014f0478aff6L1657
=> AUT-929: Update Welsh translation for wrong OTP entered 15 min block period

src/assets/javascript/cookies.js, src/components/create-password/ab-tests/index-variant.njk, src/components/create-password/create-password-controller.ts, src/components/create-password/index.njk, src/components/create-password/tests/create-password-controller.test.ts, src/components/landing/landing-controller.ts, src/components/landing/types.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts
Enables front-end aspects of an A/B testing proof of concept that works as follows: 
1. Where `landing-controller.ts` encounters `startAuthResponse.data.featureFlags` they are added to the session
2. The presence or absence of these `featureFlags` on the session will determine which template is rendered by `create-password-controller.ts`
3. Each template is rendered with a `data-ab-test` attribute that has a value of either "variant-a" or "variant-b"
4. A new section is added to `translation.json` files for content that is included in A/B tests (the intention here is to allow it to be identified quickly and removed when no longer needed)
5. Where the user has consented to analytics cookies a JavaScript function will run that captures the `path` and variant information and pushes this to …
=> FIREBREAK: Enable frontend of A/B Testing proof of concept

src/components/sign-in-or-create/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
~**DO NOT MERGE** for now as  this has to go out roughly at the same time as the equivalent changes on `di-authentication-account-management` land.~ Have now been cleared to merge this in.
-------
The accounts team are going live with some updates to the account management area including a content update on the account blurb which now lists the services the account can currently be used with.
Implement the same update on the authentication frontend side so that the entire journey is congruent.
The equivalent content update on the account management side of things lives on [this branch](https://github.com/alphagov/di-authentication-account-management/pull/668).
=> GUA-574: Update account blurb on sign-in-or-create

src/server.ts
- Set the default keep alive to be greater than that of the ALB
- The default keep alive of an express app is 5seconds. The default keep alive of the Frontend ALB is 60 seconds. This can cause 5xx errors from the ALB, as the ALB will occasionally believe it has an open connection it can use however as the ECS keep alive timeout is only 5 seconds the socket has since closed and a 502 is sent back to the ALB.
- By keeping the keep alive timeout of the ECS container slightly longer than the ELB keep alive timeout, we can reduce these errors from happening.
=> BAU - Set the default keep alive to be greater than that of the ALB

.github/workflows/analyse-on-merge.yml, .github/workflows/pre-merge-checks-terraform.yml, .github/workflows/pre-merge-checks.yml
- Upgrade GH actions to not use Node.js 12
- We are currently seeing deprecation warnings. For example - https://github.com/alphagov/di-authentication-frontend/actions/runs/3649503508
- Node12 is out of support and any github versions running on Node will need to be upgrade - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> ACI-123 - Upgrade GH actions to not use Node.js 12

ci/terraform/ecs.tf, ci/terraform/staging.tfvars, ci/terraform/variables.tf, src/app.constants.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/contact-us-validation.ts, src/components/contact-us/further-information/_id-check-app-further-information.njk, src/components/contact-us/further-information/index.njk, src/components/contact-us/index-public-contact-us.njk, src/components/contact-us/questions/_id-check-app-face-scanning-problem.njk, src/components/contact-us/questions/_id-check-app-linking-problem.njk, src/components/contact-us/questions/_id-check-app-something-else.njk, src/components/contact-us/questions/_id-check-app-taking-photo-of-id-problem.njk, src/components/contact-us/questions/_id-check-app-technical-problem.njk, src/components/contact-us/questions/_service_trying_to_use.njk, src/components/contact-us/questions/_what_happened.njk, src/components/contact-us/questions/index.njk, src/components/contact-us/types.ts, src/config.ts, src/locales/cy/translation.json, src/locales/en/translation.json
Add GOV.UK ID Check app specific options to support pages. 
The initial option to access ID Check App forms will be displayed only where the `support_id_check_app_forms=1` environment variable is present. The feature flag was introduced in a secondary commit that can be reverted when the feature has been confirmed by user support as working as expected. I've also set this variable to default to "0" but have a value of "1" in `staging.tfvars`.
So that users experiencing issues with the GOV.UK ID Check app are presented with suitable options on the support pages.
In addition to adding the new entries in the Welsh and English`translation.json` files, the steps to achieve this were: 
[AUT-923]: https://govukverify.atlassian.net/browse/AUT-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> AUT-921: Update support pages to include GOV.UK ID Check app options

src/components/common/constants.ts, src/components/security-code-error/index-security-code-entered-exceeded.njk, src/components/security-code-error/security-code-error-controller.ts, src/components/security-code-error/security-code-error-routes.ts, src/components/security-code-error/tests/security-code-error-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Correct error scenario for auth app incorrect code
- When a user enters 6 invalid codes on the auth app enter otp they are taken to the 'You entered the wrong security code too many times', when they select try again they are taken to the Enter the 6 digit security code shown in your authenticator app' Fix that so the try again link takes them to the 'You cannot enter a security code at the moment' screen
=> ACI-138 - Show the correct screen when user exceeds auth app code attempts and clicks try again

src/components/updated-terms-conditions/index-optional.njk, src/components/updated-terms-conditions/updated-terms-conditions-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Change the content for optional services on T&Cs reject page
- User should be able to continue without saving, via `redirect_uri`
- So as to align the current page with the page on [Figma](https://www.figma.com/file/aVqNC4pKaebZchIU691f31/DI-Authentication?node-id=14739%3A60383&t=cWhR2MNCoQvxKw43-0)
=> ACI-15: Change the content for optional services on T&Cs reject page

ci/terraform/build.tfvars
Adds `support_id_check_app_forms = "1"` feature flag to Build
The forms need to be available on Build for automated testing. 
The PR that introduced the support forms is #869. A subsequent PR amended the Zendesk submission slightly #895
=> AUT-921: Add support form feature flag to build

src/app.constants.ts, src/components/common/constants.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/resend-mfa-code/resend-mfa-code-controller.ts, src/components/security-code-error/index-security-code-entered-exceeded.njk, src/components/security-code-error/security-code-error-controller.ts, src/components/security-code-error/security-code-error-routes.ts, src/components/security-code-error/tests/security-code-error-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts
- Allow user to request a new MFA OTP when the 15 minute period has elapsed
- Enforce a 15 minute block period when a user enters the auth app OTP incorrectly a max number of times 
- Add additonal test coverage
- When a user enters 6 invalid codes on the auth app enter otp they are taken to the 'You entered the wrong security code too many times', when they select try again they are taken to the Enter the 6 digit security code shown in your authenticator app' Fix that so the try again link takes them to the 'You cannot enter a security code at the moment' screen
- Remove the cookie and set the invalid expiry on the session. This will stop impacting users logging into a different GOV.UK account within the same session.
=> ACI-138/AUT-292 -  Show correct error pages when user is forced to wait 15 mins due to OTP block 

src/components/photo-id/index-no-photo-id.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Unhappy path content for the `no-photo-id` page (in English and Welsh) has been updated, and the `.njk` file has a single edit to use the correct json file key for the `h1` content on this page.
Content designers are standardising the format of unhappy path pages throughout the journey
[PYIC-2185](https://govukverify.atlassian.net/jira/software/c/projects/PYIC/boards/187?modal=detail&selectedIssue=PYIC-2185&assignee=6228bdb48a4bb60068f5b1d8)
[PYIC-2185]: https://govukverify.atlassian.net/browse/PYIC-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-2185 Update unhappy path content

src/components/contact-us/contact-us-service.ts, src/components/contact-us/tests/contact-us-service.test.ts
Add new `sign_in_app` Zendesk tag that will be sent in place of`govuk_sign_in` where support requests relate to the ID Check app. 
This tag was requested by the Support Team during the demo of new ID Check app support forms. It will allow them to differentiate and change the routing of requests that relate to the GOV.UK ID Check app.
* #869 Introduced the ID Check app support forms
* #895 Tweaked the Zendesk submission in response to a feedback from the Support Team
* #896 Added the feature flag to build
=> AUT-921: Add new Zendesk identifier tag

src/app.constants.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-questions-validation.ts, src/components/contact-us/further-information/index.njk, src/components/contact-us/index-public-contact-us.njk, src/components/contact-us/questions/_account-creation-problem-questions.njk, src/components/contact-us/questions/_account-not-found-questions.njk, src/components/contact-us/questions/_another-problem-questions.njk, src/components/contact-us/questions/_authenticator-app-problem.njk, src/components/contact-us/questions/_email-subscriptions-questions.njk, src/components/contact-us/questions/_forgotten-password-questions.njk, src/components/contact-us/questions/_id-check-app-something-else.njk, src/components/contact-us/questions/_id-check-app-technical-problem.njk, src/components/contact-us/questions/_invalid-security-code-questions.njk, src/components/contact-us/questions/_no-phone-number-access-questions.njk, src/components/contact-us/questions/_no-security-code-questions.njk, src/components/contact-us/questions/_no-uk-mobile-questions.njk, src/components/contact-us/questions/_proving-identity-problem-questions.njk, src/components/contact-us/questions/_signing-in-problem-questions.njk, src/components/contact-us/questions/_suggestion-feedback-questions.njk, src/components/contact-us/questions/_technical-error-questions.njk, src/components/contact-us/questions/_what_happened.njk, src/components/contact-us/questions/index.njk, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts, src/utils/validation.ts, test/unit/utils/validation.test.ts, yarn.lock
Introduces the `govukCharacterCount` to the following user support forms: 
Analysis has revealed the need to communicate and ensure a limit of 1200 characters on text areas within user support forms. See the Jira ticket for a full description.
The approach to achieve this has been: 
1. To add a `ZENDESK_FIELD_MAX_LENGTH` constant that represents the maximum length of fields submitted to Zendesk. This introduces more complexity than simply having the value hard-coded in several places but a single source of truth ensures changes to the constant will immediately cascade to the controller, validation logic and messages, and for number localisation.
2. Adds a new validation rules to prevent submissions that exceed this length.
3. Introduces a new object constant `PLACEHOLDER_REPLACEMENTS` to …
=> ACI-139: Add character limit to user support forms

src/components/updated-terms-conditions/index-mandatory.njk, src/components/updated-terms-conditions/index-non-service-rejected.njk, src/components/updated-terms-conditions/tests/updated-terms-conditions.test.ts, src/components/updated-terms-conditions/updated-terms-conditions-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json
Create new T&Cs rejected page for non-service scenarios and refactor content for mandatory services T&Cs page
- Three possible outcomes to determin which view is displayed:
- `index-mandatory.njk` for Mandatory services
- `index-optional.njk` for optional services
- `index-non-service-rejected.njk` for non service scenarios
- The view is determined by the client service type via `req.session.client.serviceType`
So as to align the current page with the page on [Figma](https://www.figma.com/file/aVqNC4pKaebZchIU691f31/DI-Authentication?node-id=14739%3A60383&t=cWhR2MNCoQvxKw43-0)
[Change for optional services](https://github.com/alphagov/di-authentication-frontend/pull/891)
=> ACI-16-18: Create new T&Cs rejected page for non-service and refactor mandatory services page

src/components/common/footer/terms-conditions.njk, src/components/common/layout/banner.njk, src/components/updated-terms-conditions/index-mandatory.njk, src/components/updated-terms-conditions/index-non-service-rejected.njk, src/components/updated-terms-conditions/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
- Link to Accounts cookie policy rather than the GOV.UK cookie policy from the rejected terms and conditions screens
-  Update the cookie policy link and text in the terms and conditions
- Update cookie banner to link to correct cookie's policy
- We have a different cookie policy to GOV.UK and it is the GOV.UK accounts cookie policy that we should be linking to in these scenarios
=> ACI-144 - Update cookie links to point to GOV.UK accounts cookie policy 

ci/terraform/staging.tfvars
Align frontend staging sizing with production.
Staging will be used for performance testing so should match production sizing.
=> AUT-955: Align frontend staging sizing with production.

ci/terraform/staging.tfvars
Align staging frontend redis sizing with production for performance testing.
Staging will be used for performance testing so should match production sizing.
#903
=> AUT-955: Align staging frontend redis sizing with production for performance testing

src/components/resend-mfa-code/resend-mfa-code-controller.ts, src/components/security-code-error/security-code-error-controller.ts, src/components/security-code-error/tests/security-code-error-controller.test.ts
Block user from accessing enter-code page before the 15 mins code lock as elapsed
- Refactor `newCodeLink` to redirect the user to `render-mfa-code` page instead of `enter-phone-number` page via `SecurityCodeErrorType.OtpMaxRetries`
To fix Phone OTP bug when a user is creating their One Login account and they enter their OTP more than 5+ times incorrectly
=> ACI-140: Redirect user to correct screen after OTP has been entered 5+times

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/questions/_id-check-app-face-scanning-problem.njk, src/components/contact-us/questions/_id-check-app-linking-problem.njk, src/components/contact-us/questions/_id-check-app-something-else.njk, src/components/contact-us/questions/_id-check-app-taking-photo-of-id-problem.njk, src/components/contact-us/questions/_id-check-app-technical-problem.njk, src/components/contact-us/questions/_proving-identity-problem-questions.njk
This PR does two things: 
1. Adds a new "What service were you trying to use?" field to the "Problem proving your identity" support form 
2. Changes the placement of existing "What service were you trying to use?" fields within other support forms so that they appear above the warning text (as requested by Interaction Design). 
The existing forms that have been rearranged in this way are:
- "You had a technical problem" (under the ID Check App)
- "You had a problem scanning your face using the GOV.UK ID Check app"
- "You had a problem linking the app to your web browser" (under the ID Check App)
- "Something else" (under the ID Check App)
- "You had a problem taking a photo of your identity document" (under the ID Check App)
The additional field added in (1) is needed by the support team. …
=> AUT-956: Addition of and amendments to existing "What service were you trying to use?" fields

ci/tasks/deploy-frontend.yml, ci/terraform/build.tfvars, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/sandpit.tfvars, ci/terraform/staging.tfvars
- Set the support_international_numbers terraform variable for all environments. This will be set to "0" apart from staging where it will be set to "1"
- This will allow us to test out international phone numbers in staging before we roll out to other environments
- Stop setting this variable via the deploy-frontend.yml. This file picks up the environment variable via the concourse pipeline which is overkill when it can be set as a terraform variable in the relevant <environment>.tfvars file.
=> AUT-969 - Enable internal phone numbers for staging

src/locales/cy/translation.json, src/locales/en/translation.json, src/locales/tests/locale.test.ts
This PR does two things: 
Typographical change approved by Content Design and Interaction Design. Previous PRs (#847) have removed dumb quotes and we need a way to ensure they don't come back. 
This page shows the mix of "smart quotes" and "dumb quotes" that were present
This page shows the page with "smart quotes" only
=> AUT-1042: Remove dumb quotes

src/locales/tests/locale.test.ts
Update locale file tests to refer to "typographically incorrect quotes".
This is a more accurate way of referring to them.
#910
=> AUT-1042: Refer to typographically incorrect quotes in tests

src/components/enter-phone-number/enter-phone-number-validation.ts
- Increase the international phone number limit to 25
- Some international dialing codes range from having 2 to 7 numbers. Therefore our current 15 number limit might disclude some international numbers.
=> AUT-969 - Increase the international phone number limit to 25

src/components/common/footer/privacy-statement.njk, src/locales/cy/translation.json, src/locales/en/translation.json
-  Update cookie links and text in privacy policy. There has been changes made to 2 parts of the privacy policy here. 
- We were either not including a reference to the GOV.UK accounts cookie policy or including a reference but linking to the GOV.UK cookie policy.
- Below shows screenshots of the changes for Scenario 1. There are no screenshots for Scenario 2 as that is just a change of the link href.
**Scenario 1 before**
**Scenario 1 after**
=> AUT-992 -  Update cookie links in privacy policy 

src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Hint text for international mobile number field to become: Include the country code, for example +33 for France
- Validation error message for ‘invalid format’ on international mobile number field to become: Enter a mobile phone number in the correct format, including the country code
- Validation error message for ‘no user input’ on international mobile number field to become: Enter a mobile phone number
- Validation error message for ‘no user input’ on Uk mobile number field to become: Enter a UK mobile phone number
- Validation error message for ‘Characters other than digits + or - used’ on international mobile number field to become: Enter a mobile phone number using only numbers or the + symbol
- So the messaging we give to the users is clearer
=> AUT-969 - Update hint and validation content for enter phone number

src/components/sign-in-or-create/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
- Add SWE content to `Create a GOV.UK account of sign in` page
- To reflect the services that have onboarded
=> AUT-974 - Add SWE content to `Create a GOV.UK account of sign in` page

src/locales/tests/locale.test.ts
Introduce tests to ensure that the English and Welsh translation files have the same shape (i.e. the same property keys all the way down through nesting).
To ensure there is no potential for drift between the files
=> AUT-1062: Ensure translation file keys are the same

src/components/common/footer/privacy-statement.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
⚠️ Do not merge before 10:30am on 9 February
Replace all references to "account(s)" with content and translations provided by Content Design.
To reflect name change to GOV.UK One Login
=> AUT-1058/AUT-1059 GOV.UK One Login name change

src/locales/cy/translation.json
Replaces an English sentence that was found in the Accessibility Statement with the Welsh language equivalent.
There should not be English text in the Welsh language page.
=> Fix: Replace English text in Welsh Accessibility Statement

src/app.ts, src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/questions/_security_send_method.njk, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/middleware/set-international-phone-number-support-middleware.ts, test/unit/middleware/set-international-phone-number-support-middleware.test.ts
Introduces additional option for "How did you expect to get the security code?" to differentiate between UK phone numbers and IPNs on four forms: 
|                                 | A problem creating a GOV.UK account | A problem signing in to your GOV.UK account |  
|---------------------------------|-------------------------------------|---------------------------------------------|
| Did not receive a security code | Form updated to include new option | Form updated to include new option  | 
| Security code didn't work       | Form updated to include new option |  Form updated to include new option | 
These changes are behind the international phone numbers feature flag.
Allows users to indicate whether they have used a UK or international phone number when submitting a support …
=> AUT-971: Update support forms to include IPNs

ci/terraform/build.tfvars
Enables IPNs via the feature flag in build.
To enable testing.
=> Enable IPNs in build

ci/terraform/integration.tfvars
- Enable International Numbers in Integration
- We are close to going live and need to enable them in all non prod environments first
=> BAU - Enable International Numbers in Integration

src/locales/cy/translation.json, src/locales/en/translation.json
A content change to reassure users they can still continue their journey, but will need to prove their identity in a different way.
This change was proposed by the content designer on the core team because the current `title` and `H1` makes this sound like more of a dead end for users than it actually is.
* [Related change in core-front repository](https://github.com/alphagov/di-ipv-core-front/pull/690)
=> PYIC-2431 Update unhappy path page title

src/components/common/errors/404.njk, src/components/common/errors/session-expired.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Revise error message for the following pages:
- 404/page not found
- Session timeout 
- 500/Internal service error
So that users have a better understanding of why there's an error
[Service Unavailable](https://github.com/alphagov/di-infrastructure/pull/468)
=> AUT-1061: Revise messages on error pages, for 400, 500 error codes

src/components/sign-in-or-create/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Adds 'Sign your mortgage deed' to accounts list
So that HM Land Registry users are aware they can use the service. The Accounts team have confirmed that the corresponding changes are already live. 
=> AUT-1067: Add 'Sign your mortgage deed' to accounts list

src/components/common/errors/404.njk
Response to bug raised to fix styling on `Page not found` error screen 
To ensure the paragraphs run the full width of the page
From:
To:
[Origial PR](939)
=> AUT-1061: Remove wrapping around paragraphs on the Page not found screen

src/components/sign-in-or-create/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Change current ‘Sign in’ link on the ‘Create a [GOV.UK](http://gov.uk/) One Login or sign in’ page to a secondary button.
After seeing an increase in the number of users landing on the `You already have an account` page which was a sign of users mistakenly choosing to create account rather than sign in. To avoid confusion, a secondary button is used as supposed to a text with a link attached.
=> AUT-1116: Change One Login Sign In link to secondary button

src/app.constants.ts, src/components/common/errors/mid-journey-direct-navigation-without-session.njk, src/handlers/internal-server-error-handler.ts, src/handlers/tests/internal-server-error-handler.test.ts, src/locales/cy/translation.json, src/middleware/session-middleware.ts, src/middleware/tests/session-middleware.test.ts
- Add no session middleware
- This will distinguish vs situations where a session is lacking because it has timed out (currently after 2 hours)
- It applies when there is no session because the user has e.g. bookmarked a session-required page and is trying to navigate directly
For example, `/enter-email` is a session-required route. Now, if we try to navigate to it directly, we will see (English):
or the equivalent page in Welsh:
- To improve accuracy of error messages for users
=> AUT-1051: Add no session middleware

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-service.ts, src/components/contact-us/further-information/_id-check-app-further-information.njk, src/components/contact-us/questions/_id-check-app-face-scanning-problem.njk, src/components/contact-us/questions/_id-check-app-hidden-fields.njk, src/components/contact-us/questions/_id-check-app-linking-problem.njk, src/components/contact-us/questions/_id-check-app-something-else.njk, src/components/contact-us/questions/_id-check-app-taking-photo-of-id-problem.njk, src/components/contact-us/questions/_id-check-app-technical-problem.njk, src/components/contact-us/tests/contact-us-controller.test.ts, src/components/contact-us/tests/contact-us-questions-controller.test.ts, src/components/contact-us/types.ts
Allows for two new query string parameters to be provided to the `/contact-us-further-information` route representing an `appSessionId` and `appErrorCode`. These will be included in GET requests coming from the ID Check App. 
An example request URL would be: 
`https://signin.account.gov.uk/contact-us-further-information?theme=id_check_app&appErrorCode=aed1&appSessionId=1234abcd-12ab-11aa-90aa-04938abc12ab`
Where these parameters are included and meet expectations, they will persist through to ID Check App forms (as hidden fields where possible, or query strings where not) and be sent to Zendesk as:
* The `appSessionId` will be the "Ticket identifier" (replacing the Base64 string)
* The `appErrorCode` will be a new field called "ID Check App error code"
The inclusion of an error code and …
=> AUT-1119: Support form changes for ID Check App

src/app.constants.ts, src/components/check-your-email-security-codes/check-your-email-security-codes-controller.ts, src/components/check-your-email-security-codes/index.njk, src/locales/cy/translation.json, tsconfig.json
'check-email-change-security-codes' navigation changes, Welsh translation
- Make the back url dynamic so it can go back to either 'check-your-phone' or 'enter-authenticator-app-code' as required.
- POST form to 'check-email-change-security-codes'.
The back url needs to be dynamic as this page is the target for two different previous pages.
The form POST url was incorrect.
Changes are dormant and not visible to users.  To be demonstrated when the account recovery flow is in place.
#960
=> AUT-1080: check-email-change-security-codes navigation changes, Welsh translation

src/components/reset-password-check-email/reset-password-check-email-service.ts
- Remove useCodeFlow boolean from reset password request
- The boolean is never used so we can stop sending it to the api
=> BAU - Remove useCodeFlow boolean from reset password request

ci/tasks/deploy-frontend.yml, ci/terraform/core.tf, ci/terraform/dns.tf, ci/terraform/route53.tf, ci/terraform/variables.tf
Adds a new hosted zone so that di-authentication-frontend is entirely responsible for its DNS configuration.
This decouples from the dns configuration in di-infrastructure, eliminating the need for remote state.
=> Decouple usage of DNS

src/components/account-created/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Refactor account-created content for optional services (CICS save and resume).
- When the user has created their account, they will see this page:
When CICS service users create their account via GOV.UK One login through their application, they are provided with an option to save their progress
=> AUT-1158: Refactor account-created content for optional services

src/components/enter-mfa/enter-mfa-auth-app.njk, src/components/enter-mfa/enter-mfa-controller.ts, src/components/enter-mfa/enter-mfa-mobile.njk, src/components/enter-mfa/index.njk, src/components/enter-mfa/tests/enter-mfa-controller.test.ts, src/components/enter-password/enter-password-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts
When a user signs in with 1FA and tries to access another service like account management, they are required to go through 2FA regardless of their authentication level and redirected to `/enter-code` screen.
- Create new field `mfaMethodType` in `UserSession` during sign in journey
- Display new content for users with `MFA_METHOD_TYPE` of `AUTH_APP`
- Display new content for users with `MFA_METHOD_TYPE` of `SMS`
So that a user signed in with 1FA understands why they are required to go through 2FA process in order to access the RP's service.
=> AUT-995: Change content on the /enter-mfa screen accordingly to mfa method type

ci/terraform/route53.tf
Terraform will error instead of destroy zones
This will ensure hosted zones don't accidentally get deleted, as the name server values will be hardcoded in the root zone.
=> Terraform will error instead of destroy zone

src/components/check-your-phone/index.njk, src/components/contact-us/tests/contact-us-controller-integration.test.ts, src/components/enter-mfa/tests/enter-mfa-integration.test.ts, src/components/enter-password/tests/enter-password-controller.test.ts, src/components/enter-phone-number/tests/enter-phone-number-controller.test.ts, src/components/enter-phone-number/tests/enter-phone-number-integration.test.ts, src/components/resend-email-code/tests/resend-email-code-integration.test.ts, src/components/resend-mfa-code/index.njk, src/components/resend-mfa-code/tests/resend-mfa-code-integration.test.ts, src/components/reset-password/tests/reset-password-controller.test.ts, src/components/reset-password/tests/reset-password-integration.test.ts, src/components/updated-terms-conditions/tests/updated-terms-conditions-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/utils/strings.ts, test/unit/utils/strings.test.ts
Simple change to the way hidden telephone numbers are described/presented on two screens: 
The new presentation uses words to convey that the presented digits are the end of the user's telephone number and, in doing so, addresses an issue where screen readers were reading "Star star star 0 4 0 6" that may have been confusing for some users. 
=> AUT-1094: Change hidden telephone number presentation

src/components/contact-us/contact-us-service.ts, src/utils/types.ts, src/utils/zendesk.ts
Log information about the contents of the support form without logging any user entered text.  Able to see which fields are empty and which ones have content. 
Log the error code and status text from the zendesk api on error.
Provide more information to help with diagnosis when dealing with zendesk api errors.
=> AUT-1050: Additional logging for support form

src/components/contact-us/contact-us-service.ts
On the support form users have an option to provide a contact email and contact name.  The contact name is not mandatory.  If a user does not already have a Zendesk account then the requester name field is mandatory and the ticket creation request will be rejected by the api.
If a user does not supply a contact name then the email address will be used by default instead.  In Zendesk the account will be created with the first part of the email address before the '@'.  Users can change their account name if they so wish by logging into their Zendesk account.
For users who do have an existing account this change makes no difference, and the requester name will not be updated.
Resolves an issue where support form submissions were unsuccessful, returning an HTTP 422 error for users not having …
=> AUT-1050: Send email as contact name when contact name not provided

src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/tests/check-your-phone-controller.test.ts, src/components/check-your-phone/tests/check-your-phone-integration.test.ts, src/components/common/verify-mfa-code/verify-mfa-code-post.ts, src/components/common/verify-mfa-code/verify-mfa-code-service.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts
- Call `/verify-mfa-code` from the check-your-phone-controller instead of `/verify-code` 
- Create a common component for calling the VerifyMfaCodeHandler
- Call the common component from the enter-authenticator-app-code-controller to avoid code duplication
- The logic to validate registration SMS OTPs has moved to the VerifyMfaCodeHandler
https://github.com/alphagov/di-authentication-api/pull/2901
=> AUT-1208 - Call VerifyMfaCodeHandler from the check-your-phone-controller

ci/terraform/route53.tf
create_before_destroy on certificate resource
Certificates can't be destroyed while in used
=> create_before_destroy on certificate

src/components/enter-authenticator-app-code/index.njk, src/components/enter-mfa/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
This PR is a result of a reverted [PR](https://github.com/alphagov/di-authentication-frontend/pull/978) where issues were discovered regarding incorrect content were being displayed.
When a user signs in with 1FA and tries to access another service like account management, they are required to go through 2FA regardless of their authentication level 
- Content change for users with MFA method type SMS, `/enter-code`
- Content change for users with MFA method type AUTH_APP, '/enter-authenticator-app-code`
So that a user signed in with 1FA understands why they are required to go through 2FA process in order to access the RP's service.
Changes to the user interface or content should be demonstrated to Content Design and Interaction Design before being merged. This is to ensure they can make …
=> AUT-995: Content change on /enter-code and /enter-authenticationo-app-code paGE

src/components/enter-mfa/index.njk
Moves the details component below the "Continue" button on the 2FA journey for users signing into the service. 
Design change described in related Jira ticket
The screen is shown below, with the details component expanded. 
The same changes were introduced for other pages in https://github.com/alphagov/di-authentication-frontend/pull/940
=> AUT-1075: Move details component below "Continue" button

src/locales/cy/translation.json, src/locales/en/translation.json
Updates hint text for all support forms that use the "What service were you trying to use?" question to be 
> If you cannot remember the name of the service, tell us what you were trying to do, for example get a DBS check. Or you can tell us the name of the government department you’ve been dealing with.
This includes forms for:
=> AUT-1123: Update hint text for service trying to use

src/assets/scss/application.scss
Small CSS change to fix overflow bug affecting on smaller screen sizes. 
Change has been tested across in [browsers to test (from June 2022)](browsers-to-test-in-from-june-2022), including: 
OS | Browser | Result
-- | -- | --
Windows | Edge (latest two versions) | ✅ ✅
  | Google Chrome (latest two versions) | ✅ ✅
  | Mozilla Firefox (latest two versions) | ✅ ✅
macOS | Safari 12, 13, 14, 15, 16 | ✅ ✅ ✅ ✅ ✅
  | Google Chrome (latest two versions) | ✅ ✅
  | Mozilla Firefox (latest two versions) | ✅ ✅
iOS | Safari for iOS 12, 13, 14, 15, 16 and later | 16, 15, 13,  tested. Browserstack remote devices running 14 could not access the page (seemingly as a result of the way they handle redirects). It seems very low risk that the bug will be present there.
  | Google Chrome (latest two versions) | …
=> AUT-1228: Fix overflow on interrupt screen

src/components/create-password/create-password-validation.ts
Fixes issue where the error message link was giving focus to the second input rather than the first. Having considered the issue it seemed most sensible to simply switch the order of validation rules (so that the `password` field is evaluated after `confirm-password`, and is therefore the input linked to). 
The screenshot below shows the fix with focus state after a user has clicked on the validation message. 
While this bug might appear minor, it could be especially confusing for screenreader users (or those using other technologies where content is encountered sequentially) because presenting a single error message that moves focus to the last error in the DOM could likely result in the additional errored field being missed.
=> AUT-1223: Fix error message link anchoring

src/app.constants.ts
Add 'changeCodesConfirmEmail' to the 'CONTACT_US_REFERER_ALLOWLIST'.
To capture the referer when a user clicks 'contact us' in this new email template.
The entire account recovery flow will be demonstrated when complete.
Will be informed when the entire flow is complete.
https://github.com/alphagov/di-authentication-api/pull/2925
https://github.com/alphagov/di-authentication-api/pull/2959
=> AUT-1089: Add 'changeHowGetSecurityCodesConfirmationEmail' to the 'CONTACT_US_REFERER_ALLOWLIST'

src/app.constants.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/common/verify-mfa-code/verify-mfa-code-service.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/enter-authenticator-app-code/types.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
Introduce `JOURNEY_TYPE` parameter for the `VerifyMfaCodeInterface`
- Registration
- Account Recovery
- Sign In
In order to redirect to the corresponding feature in the `VerifyMfaCode` lambda.
[Changes in the Auth API](https://github.com/alphagov/di-authentication-api/pull/2962)
=> AUT-1242: Refactor VerifyMfaCode interface to use Journey Type parameter

src/locales/cy/translation.json, src/locales/en/translation.json
Changes 'another' to 'a' in the page heading for 'Another problem using your GOV.UK One Login'. This does not change the previous page (as shown below). Note that while the contact forms are currently only available in English, this PR also updates the Welsh version so that translations are consistent.
Change requested by Content Design
=> AUT-1206: Change 'another' to 'a' in form heading

src/app.constants.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/common/verify-mfa-code/verify-mfa-code-service.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/enter-authenticator-app-code/types.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
Introduce optional `JOURNEY_TYPE` parameter for the `VerifyMfaCodeInterface`
- Registration
- Account Recovery
- Sign In
In order to redirect to the corresponding feature in the `VerifyMfaCode` lambda.
=> AUT-1242: Add optional journey type parameter to VerifyMfaCode interface

tsconfig.json
- Add all .ts files within `src` directory to TS project
- The include property specifies the files to be included in the TypeScript project
- By default, this should have included all files within the directory where the tsconfig.json file is stored except those specified in exclude
- In reality, however, it seemed to miss the server file intermittently
- This change ensures that all TS files in src will be picked up
N/A
=> Add 'include' line to tsconfig.json

src/components/check-your-email-security-codes/check-account-recovery-middleware.ts, src/components/select-mfa-options/index.njk, src/components/select-mfa-options/select-mfa-options-controller.ts, src/components/select-mfa-options/select-mfa-options-validation.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts, src/utils/validation.ts
- Add variant to MFA selection screen, to be used in Account Recovery journeys
- Note: this introduces an extra boolean to the User Session, which may cause bugs if we lose track of it. At the moment, I think it is safe, because it has no effect outside of this single page, and once an account recovery journey starts, neither of the other two variants should apply i.e. account creation or account part creation; by definition account (i.e. MFA) recovery would have to happen _after_ either/both of those
The new variant looks like this:
Notes:
- Whilst testing, I noticed a bug: all req.body fields were being passed to the render function as a string
- This meant that any hidden inputs (in the end not the approach used here) with value "false" were being interpreted by Nunjucks as truthy so …
=> AUT-1082: Add variant to MFA selection screen

src/components/check-your-phone/check-your-phone-controller.ts, src/components/common/verify-mfa-code/verify-mfa-code-service.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/enter-authenticator-app-code/types.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
- `isRegistration` from the VerifyMfaCode request
- 
`isRegistration` is no longer required as the interface in the backend has changes to generic journey type which includes registration journey.
[Backend change](https://github.com/alphagov/di-authentication-api/pull/2978)
=> AUT-1242: Remove isRegistration param from VerifyMfaCode request

src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/enter-phone-number/enter-phone-number-validation.ts, src/utils/phone-number.ts, test/unit/utils/phone-number.test.ts
- Loosen international phone number validation to include 00 prefix format
- For example 0034608453322 would be rejected prior to the change
- After the change it would be transformed into a '+' format number, but accepted in validation
The field in question is the bottom one below:
I considered also validating that this field was a non-UK number by changing the following function to:
```
export function containsInternationalMobileNumber(value: string): boolean {
const formattedNumber = convertInternationalPhoneNumberToE164Format(value);
return (
isValidPhoneNumber(formattedNumber) &&
parsePhoneNumberWithError(formattedNumber).countryCallingCode !== "44"
);
}
```
This would have eliminated UK-format values like `0044 7777 777 777`. The reason that I did not add this extra check is that I …
=> AUT-1275: Loosen international phone number validation to include 00 format

package.json, src/assets/scss/application.scss
Import only those GOV.UK Frontend components we use and tidy import paths through use of `--load-path` [CLI option](https://sass-lang.com/documentation/cli/dart-sass#load-path).
I've tested the create and sign in journeys locally to ensure there is no visual change to pages. 
Avoids users loading CSS which isn't used and reduces page weight by 20kB
This reflects changes made by the Accounts Team in [#818](https://github.com/alphagov/di-account-management-frontend/pull/818)
=> AUT-1143: Sass optimisation

package.json, yarn.lock
Uses `--quiet-deps` CLI option to suppress Sass deprecation warnings arising from `govuk-frontend` use of slash for division. The Design System [team are aware of these issues](https://github.com/alphagov/govuk-frontend/issues/2238) but cannot use the `math.div` method recommended by Dart Sass without breaking support for other compilers. In light of this, Design System [guidance recommends using `--quiet-deps`](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#silence-deprecation-warnings-from-dependencies-in-dart-sass)
Prior to the Sass upgrade introduced in this PR, the `--quiet-deps` argument wasn't doing what it should (an issue that has been faced by [other teams](https://github.com/alphagov/di-solid-prototype/pull/97)). Having created a test app, …
=> BAU: Quiet SASS deprecation dependencies

src/components/check-your-phone/check-your-phone-controller.ts, src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
Include `ACCOUNT_RECOVERY` journey type in verify MFA code request when user session is in account recovery journey
To ensure the `VerifyMfaCode` lambda is aware of what journey is motion
[Part 2](https://github.com/alphagov/di-authentication-frontend/pull/1018)
[Bug Fix](https://github.com/alphagov/di-authentication-frontend/pull/1017)
[Part 1](https://github.com/alphagov/di-authentication-frontend/pull/1012)
=> AUT-1242: Include ACCOUNT_RECOVERY journey type in VerifyMFACode request

ci/terraform/build.tfvars
- Enable account recovery in build
- So we can test the account recovery journey in a non prod environment
=> BAU - Enable account recovery in build

src/components/common/constants.ts, src/components/enter-email/tests/enter-email-create-account-integration.test.ts, src/components/resend-email-code/resend-email-code-controller.ts, src/components/resend-email-code/tests/resend-email-code-controller.test.ts, src/components/resend-email-code/tests/resend-email-code-integration.test.ts
- When a user has requested more than 5 email OTPs during account creation, they are blocked for 15 minutes from requesting anymore codes. After the block had expired and they asked to resend the code, previously 2 codes were being sent at once when only 1 has been requested
- To fix this we will stop relying on the send-notification lambda to tell us when the user is blocked or not and instead set an attribute in the user session which will be a timestamp telling us when the user is no longer blocked. Update the logic in the resend-email-controller to check this attribute in the session rather than send a request to the send-notification lambda
- Update the ERROR_CODE_MAPPING in constants.ts to ensure that routes are called in the correct order and the block is put on the session when …
=> AUT-1273 - Stop email OTP being sent twice after 15 minute block

src/components/security-code-error/security-code-error-controller.ts, src/config.ts
- Parameterise the OTP locked duration
- To allow it to be configured locally for testing. Default value is 15 minutes.
=> AUT-1273 - Parameterise the OTP locked duration

src/components/enter-authenticator-app-code/enter-authenticator-app-code-controller.ts, src/components/resend-email-code/resend-email-code-controller.ts, src/components/resend-mfa-code/resend-mfa-code-controller.ts
- Compare time rather than UTC string
- Comparing UTC string isn't reliable and instead we should convert them to Date and compare the time for a more accurate comparison
=> AUT-1273 - Compare time rather than UTC string

ci/terraform/dynatrace.tf, ci/terraform/ecs-roles.tf, ci/terraform/ecs.tf
Adds the OneAgent installer sidecar to the frontend deployment.
This will instrument the frontend within Dynatrace.
=> Add OneAgent to frontend

ci/terraform/ecs.tf
Use ECR image rather than Docker Hub for alpine
We can pull the image from a private endpoint.
=> Use ECR image rather than Docker Hub for alpine

src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/tests/check-your-phone-controller.test.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-controller.test.ts
Send change security codes confirmation email in account recovery journey.
The account recovery journey reuses the 'enter-phone-number' and 'setup-authenticator-app' screens so that users can switch their mfa method.  A flag in the session indicates whether the account recovery journey is in effect.  In this case a different confirmation email is sent when the journey completes: 'You’ve changed how you get security codes when you sign in to GOV.​UK One Login'.
This PR chooses the correct email template depending on the user journey, and adds tests to test each case.
A further PR will follow to route to the correct confirmation page.
The user should receive the correct confirmation email depending on their journey.
To be demonstrated when the complete flow is ready.
#998 …
=> AUT-1089: Send change security codes confirmation email in account recovery journey

src/utils/mfa.ts, test/unit/utils/mfa.ts
Reduces the number of characters in the secret key shown to users when setting up an authenticator app from 52 characters to 32 characters. 
While working on AUT-1149 it came to light that the secret key we present to users setting up an auth app is 52 rather than 32 characters long. When this was queried by Content and Interaction Design, a technical conversation concluded that the initial implementation of the auth app secret set it to be longer than is recommended by [RFC4226](https://www.ietf.org/rfc/rfc4226.txt).
=> AUT-1197: Reduce number of characters in secret key presented to users

src/components/enter-mfa/index.njk, src/components/enter-mfa/tests/enter-mfa-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
Add last three digits of a user's phone-number in `/enter-code` screen
Required so that user's are reassured of the number they'll be receiving the OTP code
=> AUT-1196: Add last three phone-number digits during sign in journey

ci/terraform/ecs.tf
- Remove the OneAgent installer container from the task definition.
OneAgent is causing DNS firewall issues (related to IPV6), let temporarily remove until the correct configuration can be determined.
N/A
#1035 
#1031
=> BAU: Stop the DynaTrace oneagent loading

src/app.constants.ts, src/components/account-recovery/change-security-codes-confirmation/change-security-codes-confirmation-controller.ts, src/components/account-recovery/change-security-codes-confirmation/index.njk, src/components/account-recovery/change-security-codes-confirmation/tests/change-security-codes-confirmation-controller.test.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/tests/check-your-phone-controller.test.ts, src/components/common/state-machine/state-machine.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-controller.test.ts
Show security codes changed confirmation page.
When a user has completed updating how they get security codes the 'You've changed how you get security codes' screen is displayed.  The screen has two modes with different text, one for SMS and one for Auth Apps.  Each mode is selected with a query parameter.
- Update the state machine to go to the correct version of the screen depending on the mfa method chosen by the user.
- Update tests to check for the correct navigation.
- Remove sending the confirmation email from the controller as the mail is already sent by 'check your phone' and 'enter authenticator app code'.
A user should see confirmation when the how they get security codes has been updated.
To be demonstrated when the complete flow is available.
#1001 
#1032
=> AUT-1083: Show security codes changed confirmation page

ci/terraform/staging.tfvars
- Enable Account Recovery in the Staging environment
- So the Account Recovery journey can be testing in Staging
=> BAU - Enable Account Recovery in the Staging environment

src/components/enter-password/enter-password-validation.ts
Use post validation locals to access email param from session when validating enter password form
When form validation fails, i.e. user does not enter a password and proceeds to continue `/enter-password-account-exists` page, the user's email disappears from the content on the page.
=> AUT-1229: Bug fix to use post validation local in enter password form to access email from session

src/components/common/constants.ts, src/components/common/state-machine/state-machine.ts, src/components/enter-email/enter-email-controller.ts, src/components/enter-email/tests/enter-email-controller.test.ts
Fixes a user-facing issue where users who had entered an incorrect passwords enough times to be presented with "You entered the wrong password too many times" were presented with "Sorry, there is a problem" at the point of submitting their email in a new journey.
This has been achieved by: 
* adding a condition to `enter-email-controller.ts` so responses from the `userExists()` service which have both `result.success` as falsy and `result.data.code` for `ACCOUNT_LOCKED` are redirected to the route for that error code
* updating the state machine to permit progress from `ENTER_EMAIL_SIGN_IN` to `ACCOUNT_LOCKED` as an optional path
* adding an error code mapping between the `ACCOUNT_LOCKED` error code and path
* introducing a unit test to confirm that `res.redirect` is called once and with …
=> AUT-1296: Fix new journey after multiple incorrect passwords

src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk, src/components/enter-authenticator-app-code/index.njk, src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-controller.test.ts, src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk, src/components/enter-mfa/index.njk
- Ensure the link to perform account recovery persists when either the wrong OTP is entered or no OTP is entered and the user clicks continue 
- Add more unit tests to the enter-authenticator-app-code-controller.ts
- When the page re-renders due to no OTP being entered, we need to ensure that the fields supportAccountRecovery and checkEmailLink persist otherwise the link to change how you get security codes disappears
- We can achieve this by passing supportAccountRecovery and checkEmailLink as hidden fields
=> AUT-1304 - Ensure Account Recovery links persist 

src/components/common/footer/privacy-statement.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Text and HTML semantics changes to the "Using the GOV.UK ID Check app to prove your identity" section of the privacy notice (i.e. some items that were previously lists are now paragraphs etc.). This also changes the last published date to 30 May 2023. 
To reflect the fact that the ID journey will start using data from biometric residence permits (BRPs).
Another change to the privacy notice is scheduled to go live on the same day (30 May). The PR for this is https://github.com/alphagov/di-authentication-frontend/pull/1010
=> [DO NOT MERGE until Wed 31 May 2023] AUT-1287: Updates to privacy notice

src/components/account-recovery/check-your-email-security-codes/check-your-email-security-codes-validation.ts
- When the account recovery enter email OTP causes an error either by no OTP entered or an incorrect OTP entered, then make sure that the current template is persisted by passing in the correct template name in `check-your-email-security-codes-validation.ts`
- The template was incorrectly displaying the `check-your-email/index.njk` when the template failed validation
=> AUT-1306 - Ensure correct template is rendered when validation error is thrown

src/locales/cy/translation.json, src/locales/en/translation.json
- Update content of account recovery email OTP to state it is only valid for 15 mins.
- Email OTP validity for account recovery is 15 mins instead of 2 hours. Update content to reflect this.
=> AUT-1311 - Change OTP validity time for account recovery

src/components/resend-email-code/resend-email-code-controller.ts, src/components/security-code-error/security-code-error-controller.ts, src/config.ts, src/types.ts
Ensure user cannot request new code when the user has entered invalid email verification code too many times before the 15 minute blocked period.
- A new lock `wrongCodeEnteredAccountRecoveryLock` is stored in the user session when user is blocked from entering invalid verification code too many times. The API returns error code `1046`
To block users from requesting a new code multiple times.
[Backend change](https://github.com/alphagov/di-authentication-api/pull/3017)
=> AUT:1281: OTP Block for Account Recovery journey

src/components/account-not-found/account-not-found-controller.ts, src/components/account-recovery/check-your-email-security-codes/send-email-otp-middleware.ts, src/components/common/send-notification/send-notification-service.ts, src/components/common/send-notification/types.ts, src/components/enter-email/enter-email-controller.ts, src/components/enter-phone-number/enter-phone-number-controller.ts, src/components/resend-email-code/resend-email-code-controller.ts
- Add journeyType to send notification requests
- To allow the API to be able to differentiate between requests that use the same notification type but are from different journeys.
=> BAU - Add journeyType to send notification requests

src/app.constants.ts, src/app.ts, src/components/account-creation/resend-mfa-code/index.njk, src/components/account-creation/resend-mfa-code/resend-mfa-code-controller.ts, src/components/account-creation/resend-mfa-code/resend-mfa-code-routes.ts, src/components/account-creation/resend-mfa-code/tests/resend-mfa-code-controller.test.ts, src/components/account-creation/resend-mfa-code/tests/resend-mfa-code-integration.test.ts, src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/index.njk, src/components/common/state-machine/state-machine.ts, src/components/landing/landing-controller.ts, src/components/select-mfa-options/select-mfa-options-controller.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/types.ts
- Split code for the resend SMS code screen between sign in and account creation journeys
- Note: This should make no visual difference
- The single variant that already exists calls the MFA Handler on the back end. That handler 'assumes' that a phone number will have been stored in the user profile database. However, this is no longer true since the steps of adding and verifying a phone number were combined into a single transaction (e.g.: https://github.com/alphagov/di-authentication-api/pull/2944)
- That in turn was done to make the system work better for account recovery needs
- In the account creation journey, the user will not have a phone number stored against their profile when the code is resent
- To get around this, we will hit the send notification lambda directly (providing …
=> AUT-1276: Split resend code account creation vs sign-in

src/app.constants.ts, src/app.ts, src/components/authorize/authorize-controller.ts, src/components/authorize/authorize-routes.ts, src/components/authorize/authorize-service.ts, src/components/authorize/tests/authorize-controller.test.ts, src/components/authorize/tests/authorize-integration.test.ts, src/components/authorize/types.ts, src/components/common/state-machine/state-machine.ts, src/config.ts, src/middleware/session-middleware.ts
- Create `/authorize` route and initial logic
- Create new router/controller/service
- Apply feature flag so that `/authorize` is only registered when `SUPPORT_AUTH_ORCH_SPLIT` is true ("1")
- Update state machine to allow same transitions from new `/authorize` route to other routes as is currently allowed for `/` (landing/start)
- This will allow the back end (OIDC API) to redirect to `/authorize` rather than landing in due course
- `/authorize` will eventually validate and parse a JWT from OIDC API to receive some information that is currently reliant on Client Registry DB access on the frontend API
=> AUT-1248: Create /authorize route and initial logic

src/components/common/footer/privacy-statement.njk
paragraph_ten was used here when it should have been paragraph_sixteen.
It looks like it was mistyped on the original change.
=> Privacy statement was using the wrong locale key

src/components/check-your-phone/check-your-phone-controller.ts, src/components/setup-authenticator-app/setup-authenticator-app-controller.ts
Include journey type in sendNotification calls.
Journey type will become a mandatory parameter.
https://github.com/alphagov/di-authentication-api/pull/3076
=> AUT-1347: Include journey type in sendNotification calls

src/components/contact-us/contact-us-controller.ts
Specify `{ lng: 'en' }` options parameter for `req.t()` calls used to prepare Zendesk submissions. I considered a couple of ways to approach this (such as creating a proxy for `req` that would override `.t()`) but these all seemed to introduce an unnecessary abstraction and would be difficult to test. 
Ensures translations obtained for the purpose preparing Zendesk submissions are returned in English even if the service itself is being presented in Welsh.
Note that, despite the contact forms being presented to users in English, several field identifiers are passed to Zendesk in Welsh. 
Having applied these changes the fields are passed to Zendesk in Welsh.
=> AUT-1340: Force 'en' locale for Zendesk submissions

src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
The two translation files have been slightly updated for `prove-identity-welcome` to match the content already in `sign-in-or-create`. 
The `src/components/prove-identity-welcome/index.njk` page has had the `insetAlternativeLanguageAppWarning` content nunjucks tag removed as the app is now available in Welsh, as requested in [PYIC-2948](https://govukverify.atlassian.net/browse/PYIC-2948).
The old version of the content was not understandable in isolation for screen reader users or other users navigating links on the page out of context.
Please …
=> PYIC-2949 Change Welsh link in pre-auth

src/locales/cy/translation.json
Adds a missing Welsh translation "Check your phone" page
Before this change, some English text was included within the "Problems with the code" disclosure element
So that all content on the page is presented in Welsh when the user has selected Welsh as their language preference. 
=> AUT-1357: Add missing Welsh translation

src/locales/cy/translation.json, src/locales/en/translation.json
Changes relate to the reduced session duration from 2 hours to 1.
Session duration is being reduced from 2 hours to 1 hour.
Several PRs combine to introduce this change in functionality and content
* https://github.com/alphagov/di-authentication-frontend/pull/1078
* https://github.com/alphagov/di-authentication-frontend/pull/1077
* https://github.com/alphagov/di-authentication-frontend/pull/1076
* https://github.com/alphagov/di-authentication-api/pull/3109
=> AUT-1368: Update Cookie Policy and Accessibility Statement

src/locales/cy/translation.json, src/locales/en/translation.json
Updates content on "Sorry, the page has expired" page to reflect change in session duration from 2 hours to 1 hour.
Session duration is being reduced from 2 hours to 1 hour.
Several PRs combine to introduce this change in functionality and content
* https://github.com/alphagov/di-authentication-frontend/pull/1078
* https://github.com/alphagov/di-authentication-frontend/pull/1077
* https://github.com/alphagov/di-authentication-frontend/pull/1076
* https://github.com/alphagov/di-authentication-api/pull/3109
=> AUT-1367: Change duration on "Sorry, the page has expired"

src/locales/cy/translation.json, src/locales/en/translation.json
This is to reflect the change in session duration from 2 hour to 1
Several PRs combine to introduce this change in functionality and content
* https://github.com/alphagov/di-authentication-frontend/pull/1078
* https://github.com/alphagov/di-authentication-frontend/pull/1077
* https://github.com/alphagov/di-authentication-frontend/pull/1076
* https://github.com/alphagov/di-authentication-api/pull/3109
=> AUT-1369: Change code expiry content on "Check your email"

src/middleware/session-middleware.ts
Adds `return` statements to lines that call `next()` in `session-middleware.ts`
During a group debugging session we identified that the absence of a `return` statement was introducing a bug resulting in a 401 being returned where the `gs` cookie had been manually deleted.
=> FIX: Add return statement to next calls in middleware

src/components/enter-email/enter-email-validation.ts
- The validation library we use, `express-validator`, wraps `validator.js`.
- This enforces a length limit of 64 characters on the user (part before @ sign) (see source code here: https://github.com/validatorjs/validator.js/blob/63b1e4dc16ad77489745d2b2309431bce16dab60/src/lib/isEmail.js#L136)
- We don't need this as we already validate length, so I turned this library default off
- We also assume that `!isEmail()` means the format is fundamentally invalid, so the error message we currently display is misleading in this scenario, where it's more of a length problem
Before:
After:
- To avoid 'hidden' validation rules that conflict with rules we have set explicitly, and to give more accurate error messages
=> BAU: Disable library email length validation

src/app.constants.ts, src/components/prove-identity-callback/prove-identity-callback-controller.ts, src/components/prove-identity-callback/prove-identity-callback-routes.ts, src/components/prove-identity-callback/session-expiry-error.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Creates a "Sorry, there is a problem" screen specifically for users whose auth session has expired during their IPV journey.
This is part of the work to reduce the session timeout from 2 hours to 1 hour. 
=> AUT-1371: Create problem screen for timed out IPV sessions

ci/terraform/integration.tfvars
- Enable account recovery in integration
- So that the account recovery journey can be performed in the integration environment
=> AUT-1222 - Enable account recovery in Integration

src/components/reset-password-check-email/reset-password-check-email-controller.ts
Currently in prod, when a user is blocked from requesting OTP during password reset journey, that is they have clicked on the 'Send the code again' CTA they are redirected to the pages below which the makes references to password reset and not OTP timeout request. 
The change is to redirect the user to the following pages instead:
Ensure the right content is displayed to user, in order to give a better understanding of why they are blocked from progressing through the password reset journey
=> AUT-1274: Replace Password Reset error pages with security-code-error page when user is blocked from requesting OTP

src/components/common/constants.ts, src/components/resend-email-code/resend-email-code-controller.ts, src/components/reset-password-check-email/reset-password-check-email-controller.ts, src/components/security-code-error/security-code-error-controller.ts, src/config.ts, src/types.ts
Initiate a 15 mins block when a user attempts to request a new code whilst 15 mins blocked period has not elapsed
- When user clicks on the 'get new code' CTA, they are redirected to 'You cannot get a new security code at the moment' page when 15 mins blocked period is still active
- Create a separate lock session specifically for Password Reset `wrongCodeEnteredPasswordResetLock`
To stop users from requesting multiple Password Reset OTP too many times
=> AUT-1283: Initiate a 15 minutes block in password-reset journey from requesting a new OTP code whilst user is blocked

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/variables.tf
- Set `PASSWORD_RESET_CODE_ENTERED_WRONG_BLOCKED_MINUTES` env variable in build to 3000 (30 seconds)
- In order to be consistent with the frontend API
Currently in build, when a user is blocked is blocked from entering code, the default elapsed time is set to 15 minutes in build environment. It should rather be set to 30 seconds to be consistent with the Frontend API.
=> AUT-1412: Override Password Reset code blocked minutes env in build

ci/terraform/build.tfvars, ci/terraform/variables.tf
Fixes the error below:
`│ Error: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal number into Go struct field KeyValuePair.Environment.Value of type string`
- redefine the variable to string value
=> AUT-1412: Fix unmarshal number terraform error by redefining the variable to string value

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/variables.tf
Instead of setting the default elapsed time to 15 minutes when a user is blocked from entering code during the account recovery journey in the build environment, it should be set to 30 seconds.
=> AUT-1282: Override code blocked minutes in build from 15 mins to 30 secs

src/assets/javascript/cookies.js
- Add account recovery URLs to GA tracking
- We have added 2 new pages for the account recovery journey. We need to add the data layers so that they are present for the GA (Universal Analytics)
=> BAU - Add account recovery URLs to GA tracking

ci/terraform/variables.tf
Set default value for orch_to_auth_signing_public_key
Mandatory tf var is causing the build to fail.
#1096
=> AUT-1096: Set default value for orch_to_auth_signing_public_key

src/components/setup-authenticator-app/setup-authenticator-app-validation.ts, src/components/setup-authenticator-app/tests/setup-authenticator-app-integration.test.ts, src/locales/cy/translation.json, src/locales/en/translation.json
- Bugfix validation on enter auth app code screen (account creation/recovery)
- Handle scenario where user enters non-digit characters
This is already the expected behaviour
=> AUT-1427: Validation on enter auth app code screen (account creation or recovery)

src/components/check-your-phone/check-your-phone-controller.ts, src/components/check-your-phone/check-your-phone-validation.ts
- When a user submitted an incorrect or invalid code in account recovery, choosing SMS as their new MFA type, they would lose a 'local' in the validation process (this happens because the [renderBadRequest function](https://github.com/alphagov/di-authentication-frontend/blob/1c4dd395ef450977837ce31bd0222e6ba20b6921/src/utils/validation.ts#L82) doesn't pass through the controller and can only access local variables that have been passed explicitly)
- The loss of this 'local' meant that the resend code URL was no longer available to the template, so the `href` would default to the current page i.e. looping the user back to the same place if they tried to click "send the code again"
- This happened through 2 different mechanisms depending on the type of validation error: one mechanism for an …
=> AUT-1426: Fix code resend link SMS account recovery

src/components/common/footer/privacy-statement.njk
Adds `govuk-link` class to links in the privacy notice
So they reflect the link focus states (for hover, focus, visited etc.) set out in the Design System.
=> AUT-1435: Add govuk-link class to Privacy notice links

src/components/enter-authenticator-app-code/index-2fa-service-uplift-auth-app.njk, src/components/enter-authenticator-app-code/index.njk, src/components/enter-authenticator-app-code/tests/enter-authenticator-app-code-integration.test.ts, src/components/enter-mfa/index-2fa-service-uplift-mobile-phone.njk, src/components/enter-mfa/index.njk, src/components/enter-mfa/tests/enter-mfa-integration.test.ts
Amends Nunjucks templates for entering Auth App and SMS codes during sign in. The change strengthens conditional to require strict equality. Also introduces some associated integration tests.
Bug identified where the a non-functional "You can securely change how you get security codes" link is presented to users (if users click on this link they are presented with the "Sorry, there is a problem" page).
=> FIX: Prevent account recovery link display where not permitted

ci/terraform/dns.tf
- Update account management URL
- It should now be home.account.gov.uk instead of account.gov.uk to ensure we take users to account management
=> BAU - Update account management URL

src/components/reset-password-check-email/reset-password-check-email-controller.ts
This is a change to supplement API change which will return `1039` error code when a user has entered too many invalid Email OTPs.
This update rectifies a bug regarding inconsistency where a blocked user could initiate a new session and, incorrectly, be given another chance to enter an OTP.
API Change (https://github.com/alphagov/di-authentication-api/pull/3161)
=> AUT-1421: Implement redirection to error page for excessive invalid Email OTP attempts

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/variables.tf
- By default, the lock duration is 15 mins. Override this for 30 seconds in the build environment. 
- So functionality can be tested easier
=> BAU - Override lock duration for the build environment

src/components/prove-identity-welcome/index-existing-session.njk, src/components/prove-identity-welcome/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Updates both variants of the pre-auth page to reflect changes requested for the F2F journey.
<details open>
<summary>Pre-auth page (English)</summary>
</details>
<details open>
<summary>Pre-auth page (Welsh)</summary>
</details>
<details open>
<summary>Pre-auth page for existing session (English)</summary>
</details>
<details open>
<summary>Pre-auth page for existing session (Welsh)</summary>
</details>
=> [⚠️ Do not merge before go-live] AUT-1424: Update pre-auth pages for F2F journey

src/utils/logger.ts
- Log only path of requests, and not query parameters
- We are currently logging full query strings; this is not really required, and means that if a user were to include PII in a query string (deliberately or otherwise) we risk logging it in normal application logs (note: we should never be accepting PII in a query string anyway, so this is 'belt and braces')
- To mitigate this risk, we can log only the path i.e. without query params
- Note also relevant discussion here: https://govukverify.atlassian.net/browse/INCIDENT-373
=> Log only path, without query parameters

ci/terraform/production.tfvars
- Enable account recovery block in all environments (all except prod were already enabled)
- This is part of putting account recovery journeys live in production
- Corresponding PR for back end must be merged first: https://github.com/alphagov/di-authentication-api/pull/3218
=> AUT-1223: Enable account recovery in production

src/components/contact-us/questions/_proving-identity-problem-questions.njk, src/components/contact-us/questions/_service-trying-to-use.njk, src/components/contact-us/questions/_technical-error-questions.njk
Updates all instances of `govukInput` that have a 'checkable' type as defined by [the HTML specification](https://html.spec.whatwg.org/multipage/interaction.html#attr-spellcheck) to include a `spellcheck=false` attribute. These types are `text`, `search`, URL and `email`. It does not include inputs with a type of `tel`, because `tel` is not a checkable type under the spec.
User agents can also conduct spellchecking on other fields, such as `<textarea>` which is rendered extensively throughout the support forms through the use of `govukCharacterCount`. Having searched the code I can see that all rendered `<textarea>` components are shown with a warning to:
> Do not include personal or financial information, for example your passport or credit card details
Because the application of …
=> AUT-1547: Apply spellcheck attribute consistently

src/components/create-password/ab-tests/index-variant.njk, src/components/create-password/index.njk, src/components/reset-password/index.njk, src/locales/cy/translation.json, src/locales/en/translation.json
This uses the same approach as has been implemented by Accounts Home in OLH-869 updating the programmatically associated label (as implemented with `aria-label`) and text that is announced to assistive technology (via a `<span>` with `aria-live="polite"`). There are no changes to the visual presentation. 
The Accounts Home PR is https://github.com/alphagov/di-account-management-frontend/pull/930
=> AUT-1299: Differentiate show and hide labels on password component

src/locales/en/translation.json
Adds missing semi-colon to the English version of the privacy notice
<details open>
<summary>English screenshot (with semi-colon added to sentence before list)</summary>
</details>
While reviewing the content for AUT-1493, colleagues noticed that a semi-colon was missing from the English version of the privacy notice.
=> BAU: Add missing semi-colon

package.json, src/components/authorize/authorize-controller.ts, src/components/authorize/claims-config.ts, src/components/authorize/jwt-service.ts, src/components/authorize/tests/authorize-controller.test.ts, src/components/authorize/tests/authorize-integration.test.ts, src/components/authorize/tests/jwt-service.test.ts, src/components/authorize/tests/test-data.ts, src/components/authorize/types.ts, src/utils/error.ts
Add jwt-service tests.
Add AuthorizeRequestPayload interface.
- Added basic validation of JWE and claims if contained in the query request.
- This will remove the dependency of the start API endpoint in the frontend API on client registry (DB) access
- This is a pre-requisite for splitting the orchestration and authentication APIs
Builds on backend changes - Pass client registry fields to auth front end via JWE: https://github.com/alphagov/di-authentication-api/pull/3159
=> AUTH1248: Add claim validation to jwt-service.

src/utils/logger.ts, test/unit/utils/logger.test.ts
Update path logging expression and stop logging query params for 'from' field.
The existing expression used to log paths was always empty so nothing was being logged.  'req.path' does not contain query parameters: https://expressjs.com/en/api.html#req.path
URL pathname (used for logging the 'from' field) also does not contain query parameters: https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname
#1120
=> BAU: Update path logging expression and stop logging query params for 'from' field

src/components/authorize/authorize-controller.ts, src/components/landing/landing-controller.ts, src/components/landing/tests/landing-integration.test.ts, src/utils/url.ts
- Pass through an additional query parameter called `result` through the redirect from the landing page (i.e. the route that is redirected to by the OIDC API on receipt of an authorize request)
- This query param will always have the key 'result'
- It is expected that it will always have the value 'sign-in' although the code does not assume this
- Note: this is done in two handlers. Landing (`/`) is currently the active path for landing, but Authorize (`/authorize`) will play the same role when authentication and orchestration are split. So effectively the Authorize handler does nothing at the moment in production, but this is future proofing for this particular change.
- The `result` parameter originates in an email sent to end users as part of the face to face journey
- When the user …
=> AUT-1622: Add query param passthrough from landing to sign in

src/components/authorize/authorize-controller.ts, src/components/authorize/claims-config.ts, src/components/authorize/jwt-service.ts, src/components/authorize/tests/authorize-controller.test.ts, src/components/authorize/tests/authorize-integration.test.ts, src/components/authorize/tests/jwt-service.test.ts, src/components/authorize/tests/test-data.ts, src/types.ts
Orchestration currently passes scopes and claims to authentication. We decided to simplify this, by only passing claims when the auth/orch split feature flag is on.  There, we need to parse this claims object and set it in the session, in order to forward the request on (this will be done in a subsequent PR).
This should not affect current behaviour, so we still parse scopes.
[PR](https://github.com/alphagov/di-authentication-api/pull/3313) to pass only claims through on the backend
=> AUT-1648: validate the jwt claim object and set in the session

src/components/common/footer/privacy-statement.njk, src/locales/cy/translation.json, src/locales/en/translation.json
Content changes for privacy notice version 1.9
- GOV.UK One Login to be deleted after three years rather than two.
- Addition of statment on fraud check 'soft search' added in four places.
Target deployment date: Wed 13 Sep 2023
Account retention period changes to be published in line with planned timelines for bulk email campaign notifying users of the changes.
To publish required privacy notice changes.
Deploy before:
https://github.com/alphagov/di-authentication-api/pull/3328
=> AUT-1634: DO NOT MERGE UNTIL WED 13 SEP 23: Content changes for privacy notice version 1.9

src/app.constants.ts, src/components/auth-code/auth-code-controller.ts, src/components/auth-code/auth-code-service.ts, src/components/auth-code/tests/auth-code-service.test.ts, src/components/auth-code/types.ts
We have a new Lambda for generating Auth codes for Authentication. This is the AuthenticationAuthCodeHandler which sits in di-authentication-api. 
In the Authentication frontend, we call the AuthCodeHandler from the auth-code-controller.ts . When the Auth Orch feature flag is enabled, we need to call the new AuthenticationAuthCodeHandler which lives on the endpoint /orch-auth-code on the Authentication internal API
When the Authentication frontend receives the response it will be able to redirect back to Authentication.
This is part of enabling the split of authentication and orchestration.
=> Aut 1646/call new authcode lambda

src/app.constants.ts, src/components/auth-code/auth-code-controller.ts, src/components/auth-code/auth-code-service.ts, src/components/auth-code/tests/auth-code-service.test.ts, src/components/auth-code/types.ts
This re-instates a previous commit that we reverted while working out why there were acceptance test failures. These were because of the feature flag for the auth/orch split being on in build - this has now been [turned off](https://github.com/alphagov/di-authentication-frontend/pull/1142).
=> AUT-1646 Call new authcode lambda if auth orch split is on

src/components/auth-code/auth-code-controller.ts, src/components/auth-code/auth-code-service.ts, src/components/auth-code/tests/auth-code-service.test.ts, src/components/auth-code/types.ts, src/components/authorize/authorize-controller.ts, src/components/authorize/claims-config.ts, src/components/authorize/tests/test-data.ts, src/types.ts
- Add `is-new-account` and `rp-sector-uri` to auth code lambda call (new lambda that will only be used once auth-orch split is enabled)
- These fields relate only to post-orch auth split
- This is because the lamdba that receives these fields is not currently used
- It will only get used once the auth-orch split flag is turned on
- The fields are needed ultimately so that the auth userinfo lambda can populate all of the required information
- There is a backend change to consume these fields here: https://github.com/alphagov/di-authentication-api/pull/3348
=> AUT-1688: Add 2 fields to auth code lambda call

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/staging.tfvars, ci/terraform/variables.tf
Introduces the variables to support SmartAgent. Values will be picked up from Secrets Manager.
To enable SmartAgent support in lower environments.
Code to introduce SmartAgent support was introduced in https://github.com/alphagov/di-authentication-frontend/pull/1140
=> AUT-1635: Add variables to support SmartAgent

src/components/contact-us/contact-us-service-smart-agent.ts, src/components/contact-us/types.ts
Adds `sa-tag-identifier`, `sa-tag-theme` and `sa-tag-subtheme` to SmartAgent payload.
Contact Centre team have requested this additional information to be sent through to the SmartAgent API via a [comment on the Jira ticket](https://govukverify.atlassian.net/browse/AUT-1653?focusedCommentId=89945).
This PR: 
* Adds to SmartAgent payload introduced in https://github.com/alphagov/di-authentication-frontend/pull/1140
* Will require https://github.com/alphagov/di-authentication-frontend/pull/1144 to be merged for testing in a deployed environment
=> AUT-1653: Add additional tags requested

ci/terraform/build.tfvars
- Add signing public key to build tfvars
- This is the public counterpart to the private signing key used to sign the JWT sent from OIDC API to Auth frontend
- The JWT is encrypted and signed as part of the `/authorize` endpoint
- Extends work to get the auth orch split journey working in build:
- https://github.com/alphagov/di-authentication-frontend/pull/1148
=> AUT-1678: Add signing public key to build tfvars

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/variables.tf, src/components/authorize/authorize-controller.ts, src/components/authorize/claims-config.ts, src/components/authorize/tests/authorize-controller.test.ts, src/components/authorize/tests/authorize-integration.test.ts, src/components/authorize/tests/test-data.ts, src/config.ts
- Parameterize aud and client_id in config
- Applies to /authorize route
- Used as part of redirect from /authorize endpoint in OIDC API
- These values must match those set in the OIDC API config
- They are part of the validation rules which ensure the JWT received is 'legitimate'
- Extends work to get the auth orch split journey working in build:
- https://github.com/alphagov/di-authentication-frontend/pull/1148
- https://github.com/alphagov/di-authentication-frontend/pull/1149
=> AUT-1678: Parameterize aud and client_id in config

src/utils/logger.ts
- Re-enable logging of full URLs (not only paths)
- Discussion of relative merits can be found in INCIDEN-96
- This has been requested by security colleagues: https://govukverify.atlassian.net/browse/INCIDEN-96?focusedCommentId=90986
- Reverses: https://github.com/alphagov/di-authentication-frontend/pull/1120
=> BAU: Reenable full URL logging

src/app.ts, src/components/common/footer/footer-pages-controller.ts, src/components/common/footer/privacy-statement.njk, src/components/common/footer/terms-conditions.njk, src/components/common/layout/base.njk, src/components/contact-us/common-english-only/layout/base.njk, src/config.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/middleware/outbound-contact-us-links-middleware.ts, src/middleware/tests/outbound-contact-us-links-middleware.test.ts
All pages currently provide direct links to the Contact Forms (at `/contact-us`) via a "feedback" link in the phase banner and a "support" link in the footer of all page. There are also _indirect_ routes to the Contact Forms through Privacy notice, Terms & Conditions and Accessibility statement links (to `/support`) which present a form asking users if they are members of the public or working for a government service (when a user selects the public option on this page they are routed to the contact forms).
1. Allows the URL for contact forms to be set through a new `URL_FOR_SUPPORT_LINKS` environment variable so links can be go to the new Triage Page (and this can be tested in lower environments)
2. Retains `/contact-us` as a default where the environment variable is not provided
3. Adds …
=> AUT-1650: Support triage page

.pre-commit-config.yaml
- The `di-pre-commit-hooks` repo has now been migrated to the `govuk-one-login` org, update `.pre-commit-config.yaml` to reflect the change.
The `di-pre-commit-hooks` repo has now been migrated to the `govuk-one-login` org.
N/A
=> SPT-473: Update pre-commit reference to programme hooks

src/components/sign-in-or-create/index.njk
Align Sign in or create page content for both MANDATORY and OPTIONAL clients.
OPTIONAL clients (where the user is not required to create an account before starting the service journey) had slightly different content on the sign in or create screen, to cover the scenario where the user was to create an account to save their progress.  As this content was not thought to be help it has been removed, so that OPTIONAL clients now see exactly the same content as MANDATORY clients.
=> AUT-1715: Align Sign in or create page content for both MANDATORY and OPTIONAL clients

src/utils/smartAgent.ts
Uses optional chaining when constructing string passed to `throw new Error()` and log values used in SmartAgent configuration. 
Since the integration PR has been merged we've found that form submissions on Build are resulting in a "Sorry, there is a problem" being presented to users.
Looking into this, it seems there's a call to undefined properties of `error`, so I've changes the syntax to optional chaining.
The hypothesis is that this is a result of the shape of values that are being provided via Secrets Manager so I'm also logging the values of those.
The PRs that integrated SmartAgent were:
* #1140 
* #1144 
* #1146
=> AUT-1653: Change SmartAgent logging approach to debug Build

ci/terraform/ecs.tf
Fix casing issue in Terraform variable name
What was a lowercase `u` should have been uppercase `U`.
This variable was introduced in https://github.com/alphagov/di-authentication-frontend/pull/1161
=> AUT-1668: Fix single letter casing issue in Terraform variable

src/components/contact-us/contact-us-service-smart-agent.ts, src/components/contact-us/types.ts
Sends the `appErrorCode` through to a new `sa-app-error-code` property in the SmartAgent payload.
The `sa-app-error-code` property was added to the SmartAgent API mappings after the previous integration was put in place.
* https://github.com/alphagov/di-authentication-frontend/pull/1140
=> AUT-1766: Add app error code to SmartAgent payload

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/further-information/index.njk
Changes the "Back" link `href` on `/contact-us-further-information` from being a hard-coded value to either: 
1. the `referer` where the referer passes the checks in `validateReferer`, or
2. `/contact-us` where it does not
When testing inbound links from the triage page that was deployed to Integration today, we found the links that include the `theme=id_check_app` parameter are redirected to `/contact-us-further-information` as expected but always use `/contact-us` as the back link `href`  (see the description in #1160 of how the presence of `theme=id_check_app` results in the user being passed directly to `/contact-us-further-information). This is problematic for two reasons: 
1. The user had not come from `/contact-us`
2. It resulted in the user getting stuck in a loop between …
=> AUT-1831: Fix back links from Triage Page

src/components/contact-us/questions/_account-creation-problem-questions.njk, src/components/contact-us/questions/_account-not-found-questions.njk, src/components/contact-us/questions/_another-problem-questions.njk, src/components/contact-us/questions/_authenticator-app-problem.njk, src/components/contact-us/questions/_forgotten-password-questions.njk, src/components/contact-us/questions/_id-check-app-face-scanning-problem.njk, src/components/contact-us/questions/_id-check-app-linking-problem.njk, src/components/contact-us/questions/_id-check-app-something-else.njk, src/components/contact-us/questions/_id-check-app-taking-photo-of-id-problem.njk, src/components/contact-us/questions/_no-uk-mobile-questions.njk, src/components/contact-us/questions/_suggestion-feedback-questions.njk, src/components/contact-us/questions/_technical-error-questions.njk
This apostrophe actually renders on the page and is accidental
Removes an accidental character from the support form question pages.
This renders on the page - you can see this live e.g. [here](https://signin.account.gov.uk/contact-us-questions?theme=account_creation&subtheme=no_uk_mobile_number&referer=)
| Before this fix (see live e.g at  | After this fix |
|----|----|
|<img width="629" alt="Screenshot 2023-10-18 at 14 53 29" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/be95db14-48fa-4f46-9eb9-a31b15000ccf">|<img width="588" alt="Screenshot 2023-10-18 at 14 54 17" src="https://github.com/alphagov/di-authentication-frontend/assets/25515510/f8722e69-1972-456e-bd7e-0178d65359e5">|
=> BAU: Fix accidental character in support form questions

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/sandpit.tfvars, ci/terraform/staging.tfvars, ci/terraform/variables.tf
Sets the following environment variables consistently across all environments. After this change, all `.tfvars` files should reflect the values shown in the table below.
|  | Support SmartAgent  |  Support Welsh in Contact Forms | URL for support links  |
|---|---|---|---|
| Sandpit  | 1  | 1  | `https://home.build.account.gov.uk/contact-gov-uk-one-login`  |
| Build  | 1  | 1  | `https://home.build.account.gov.uk/contact-gov-uk-one-login`  |
| Integration  | 1  | 1  | `https://home.integration.account.gov.uk/contact-gov-uk-one-login`  |
| Staging  | 1  | 1  | `https://home.staging.account.gov.uk/contact-gov-uk-one-login`  |
| Live | 0  | 0  | `/contact-us`  |
Prepares the environments for go-live later this month. After this PR, the only change necessary to release to production will be …
=> AUT-1650: Set environment variables for new Contact Centre

src/locales/cy/translation.json
Change to Welsh version of message presented to users who have entered exactly the number of characters permitted in a character count textarea.
Message translate to "You have 0 characters left"
Message translates to "You have 0 characters remaining" 
* https://github.com/alphagov/di-authentication-frontend/pull/1161 Introduced the Welsh translation of Contact Forms
=> AUT-1688: Minor content change

ci/terraform/build.tfvars, ci/terraform/ecs.tf, ci/terraform/integration.tfvars, ci/terraform/production.tfvars, ci/terraform/sandpit.tfvars, ci/terraform/staging.tfvars, ci/terraform/variables.tf
🆕 This is a reverted PR that had been approved and merged on 19 October. The reason for it being reverted is there were some failing acceptance tests relating to content on the Triage Page. These tests have been temporarily removed until the Triage Page is available in Welsh.
Sets the following environment variables consistently across all environments. After this change, all `.tfvars` files should reflect the values shown in the table below.
|  | Support SmartAgent  |  Support Welsh in Contact Forms | URL for support links  |
|---|---|---|---|
| Sandpit  | 1  | 1  | `https://home.build.account.gov.uk/contact-gov-uk-one-login`  |
| Build  | 1  | 1  | `https://home.build.account.gov.uk/contact-gov-uk-one-login`  |
| Integration  | 1  | 1  | …
=> AUT-1650 - Set environment variables across all environments

src/components/contact-us/contact-us-controller.ts, src/components/contact-us/contact-us-service-smart-agent.ts, src/components/contact-us/tests/contact-us-controller.test.ts, src/components/contact-us/tests/contact-us-service.test.ts
This PR does three things: 
* Refactor `validateReferer` to receive the service domain as an argument and add unit tests (implemented in commit https://github.com/alphagov/di-authentication-frontend/pull/1184/commits/82d137814d340ffc87f91f8791d2ebbc77eb4e8a)
* Extend `validateReferer` to handle URLs that have been encoded as URI components (implemented in commit https://github.com/alphagov/di-authentication-frontend/pull/1184/commits/e211a0147b91a61748d8f7be8b0ac0ac553383ae)
* Decodes the referer before it is passed to SmartAgent (implemented in commit https://github.com/alphagov/di-authentication-frontend/pull/1184/commits/e0fcd72b19a6551d45e4d339962b424c9023d494)
Because `validateReferer` is used to validate the `fromURL` query parameters we receive from the Triage Page. These are …
=> AUT-1736: Extend validateReferer to handle encoded URLs and decode referers before sending to SmartAgent
